### ISSUE TITLE
fritz!dect 301 hkrmode nicht mehr setzbar

### ISSUE THREAD

**Issue by vdi-cloud** [foxthefox/ioBroker.fritzdect#100]
Das Attribut hkrmode (früher mode - musste meine Skripte entsprechend anpassen) ist in V2.0.0  - nicht mehr setzbar. Es gibt keine Fehlermeldung. Früher konnte der Operation Mode mit 0=auto, 1=closed, 2=open gesetzt werden.  Ich habe das genutzt, um das Thermostat zu steuern, wenn das Fenster offen oder geschlossen ist, weil soweit ich erinnere, windowopenactiv, nicht gesetzt werden konnte. windowopenactiv wiederum scheint jetzt über den Adapter möglich, denn in der Fritzbox wird der Zustand signalisiert, nicht aber auf dem Thermostat-Display. 
Hinweis: Ich habe mal mit FHEM verglichen, dort ist hkrmode so nicht existent - sondern wird über eigene Schalter u.a. für CLOSED, OPEN und BOOST umgesetzt.

**Comment by foxthefox** [comment]
richtig, der hkrmode ist ein eigener Datenpunkt, den hab ich wohl vergessen umzubenennen (bei der CMD Bearbeitung).
Habs ertüchtigt.

Danke für die Rückmeldung, sollte jetzt gehen.

Ich kannauch zusätzlich noch 1 button für AUTO einbauen, und einen für permanent OFF. ON sollte über  BOOST abgedeckt sein?

**Comment by vdi-cloud** [comment]
OK, probiere ich mal aus. Denke,  extra buttons für die Modi wären nicht schlecht. BOOST ist m.E. bei Thermostaten oft nicht Dauer-ON, sondern ON für eine bestimmte Zeit, dann erfolgt ein Rückfall auf AUTO. Wie das bei AVM gedacht ist, weiß ich nicht.

**Comment by foxthefox** [comment]
ich baue mal 3 buttons ein, OFF/ON/AUTO.
Boost/Window sind switches um ein und auszuschalten

**Comment by foxthefox** [comment]
leider geht 2.1.0 mit den neuen buttons noch nicht

**Comment by foxthefox** [comment]
jetzt sollte Version 2.1.0 gehen :-)

**Comment by vdi-cloud** [comment]
ich habe mal mit der letzten version 2.1.6 herumgespielt... zunächst konnte ich nur bei einem Thermostat vom ON- oder OFF-Modus nicht mehr auf Auto umstellen. Eine Umstellung auf ON oder OFF funktionierte aber.  Mit der Fritz Smart Home App klappte das Setzen vom Auto-Modus und wurde auch im Adapter signalisiert. Erst danach konnte ich die Modi wieder über den Adapter umschalten - über die Buttons als auch über den Operationmode. Allerdings ist der Adapter in der Instanzen-Ansicht gelb. Das ist merkwürdig.

**Comment by foxthefox** [comment]
irgendwas ist noch übrig von einer vorigen Installation, es gibt keinen Datenpunkt info.connection mehr! Dieser ist die Ursache für den gelben Status.
wenn etwas nicht zu bedienen geht, bitte in den debug modus wechseln und dort beobachten, was dort geloggt wird.
aus Sicht des Adapters macht es kein Unterschied, ob vorher etwas außerhalb bedient wurde, oder nicht.
bitte dann den Teil posten, wo es um das Kommando geht.

**Comment by andreaskoerber** [comment]
Hallo,
danke. Ich habe eine grundsätzliche Frage zum hkrmode - oder auch sonst: Was gibt der Datenpunkt konkret an? Was bewirkt er, wenn ich ihn setze? Etwa:
ON = Heizungsventil offen - unabhängig vom Ergebnis tsoll-tist?
OFF = Heizungsventil geschlossen -       -"-
AUTO = automatische Steuerung gem. tsoll-tist?


Ich hätte gerne einen Datenpunkt, der mir ausgibt, ob bzw. wie weit das Ventil offen ist - egal ob automatisch oder per Hand geschaltet - etwa um zu sehen, ob und wie die Automatik auch reagiert. Gibt es das überhaupt?

**Comment by foxthefox** [comment]
Einen Datenpunkt für den Öffnungsgrad des Ventils gibt es leider nicht, wenn dann wäre er schon im Adapter.

ON ist voll Offen, "Saunamodus"
OFF ist Ventil zu
AUTO ist Temperaturregelung

**Comment by TCRW** [comment]
Moin,

auch ich habe das Problem, dass ich über ein script (iobroker) die Werte der Datenpunkte verändere, um das Ventil komplett auszuschalten. In meinem Fall über den button - setmodeoff. Dieser wird auch als true und bestätigt angezeigt, der hkrmode geht kurz auf 1 und springt dann automatisch wieder auf 0. Dasselbe passiert, wenn ich den hkrmode direkt auf 0 setze.

**Comment by foxthefox** [comment]
Das kann ich so nicht nachvollziehen. Wenn ich mit dem button im Datenpunkt bediene "setemodeoff" bleibt hkrmode auf 1 stehen.
Nach welcher Zeit ändert es sich denn spontan wieder auf auto/0 zurück?
Um das näher untersuchen zu können, benötige ich das log im debug modus und Hinweise welche Aktion zum scriptBefehl zuzuordnen sind.

Befehle sind immer mit ack=false abzusetzen, mit ack=true wird nur der Wert geschrieben, aber kein Befehl bearbeitet.

**Comment by TCRW** [comment]
Hi,

wie im Forum beschrieben liegt der Fehler bei mir daran, dass ich die Datenpunkte über "aktualisieren" , statt "steuere" geschrieben hatte, Durch das ändern auf "steuere" Datenpunkt "Thermostat operation mode " ist das nicht mehr aufgetreten.

**Comment by foxthefox** [comment]
dann schließe ich das mal
