### ISSUE TITLE
No response...

### ISSUE THREAD

**Issue by Dragon0501** [foxthefox/ioBroker.fritzdect#105]
Der Adapter funktioniert eine ganze Zeit lang ohne Probleme. Iwann ist dann der Zeitpunkt, da gibt er das hier von sich:

`

fritzdect.0 | 2021-01-08 11:47:37.249 | error | (9329) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-01-08 11:47:37.249 | error | (9329) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}
fritzdect.0 | 2021-01-08 11:47:37.065 | error | (9329) no response part in returned message
fritzdect.0 | 2021-01-08 11:47:37.065 | error | (9329) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}
fritzdect.0 | 2021-01-08 11:47:36.908 | error | (9329) no response part in returned message
fritzdect.0 | 2021-01-08 11:47:36.908 | error | (9329) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}

`
7590 und 2.1.7
![Screenshot 2021-01-08 at 11 59 14](https://user-images.githubusercontent.com/59663011/104007983-121ac800-51a9-11eb-81af-7ed96d254975.png)

**Comment by Dragon0501** [comment]
Im Log der Box steht falsches Passwort eingegeben.

**Comment by xdaamg** [comment]
Der Fehler tritt bei mir auch auf, Benutzer/Passwort stimmen (eigener Fritzbox-Benutzer mit Rechten entsprechend der Doku), Intervall auf 120 Sek. Verwende zusätzlich noch den tr064-Adapter (Intervall 150 Sek.). Hatte zuvor die Version 2.0, dort habe ich den Fehler nicht beobachtet.

**Comment by Ilovegym66** [comment]
Seit 2.1.7 hier auch, lief ein paar Stunden ohne Probleme, auf einmal der Fehler.. 
Aktualisierung ist auf 300 gesetzt.  Fritzbox OS 7.24 Beta.
Stoppe ich den Adapter, warte einen Moment, starte erneut, läuft er wieder ohne Probleme. 
Kann es sein, wenn zuviele changes an die FB gesendet werden innerhalb einer kurzen Zeit, dass dann der Fehler auftritt?

**Comment by Dragon0501** [comment]
Kann ja eigentlich nicht sein, da der Fehler ja mit 2.0.0 und 1. Sowieso nicht auftrat und sich der Skriptunterbau nicht geändert hat.

**Comment by xdaamg** [comment]
Prüfe mal in der Fritzbox die "System/Ereignisse". Gibt es dort gehäuft Einträge "Anmeldung gescheitert"?
Bei mir waren dort Einträge vorhanden, verursacht durch veraltete Login-Daten von einer Home-Assistant-Testinstanz. Möglicherweise wurde das der Fritzbox dann zu viel (obwohl die Instanz auf einer anderen IP läuft). Ich bin noch am Testen, ob der Fehler immer noch auftritt.

**Comment by Dragon0501** [comment]
Ja gibt es. Der einzige Adapter der Fehler ausgibt und nicht funktioniert ist aber der fritzdect. Alle anderen funktionieren.

**Comment by Dragon0501** [comment]
Back to 1.1.4
Problem solved...

**Comment by Ilovegym66** [comment]
...ist aber so, nachweisbar und nachvollziehbar. Das Testsystem mit 1.1.4 läuft einwandfrei, die 2.1.7 zickt irgendwann rum.
Gleicher Fehler gabs auch schon mit der 0.4.2 oder was das damals war.. :-)
Abgesehen davon, hast du die Changes gelesen? Da steht ausdrücklich drin, dass am Login procedure einiges wegen FritzOS 7.24 geändert wurde.. 
Mein Intervall im Adapter steht auf 300.
Wie beschrieben, der Fehler tritt dann auf, wenn mehrere Commandos kurz hintereinander gesendet werden, evtl. wird jedesmal ein Login versucht, ich konnte noch nicht auf debug stellen, bin noch unterwegs.

**Comment by Ilovegym66** [comment]
Hi,
der Fehler tritt bei mir seit gestern abend nicht mehr auf. Geändert habe ich bis heute Nacht um 2 nix, dann wurde FritzOS geupdated auf 7.24.xx irgendwas.. heute betreibe ich den Adapter mit dem js-controller 3.2.3, keine Probleme mehr.
Kann so bleiben. :-)
Dankeschön!

**Comment by foxthefox** [comment]
Es ist in der Tat so, daß nicht nur ein schnelles Intervall zum Abfragen, sondern auch viele Kommandos zur gleichen Zeit die Fritzbox mit vielen Logins belasten, wie schon woanders auch beschrieben, da gibt es scheinbar eine undokumentierte Anzahl und dann blockiert die FB.

**Comment by Ilovegym66** [comment]
Wie kann ich denn verhindern, dass z.bsp. wenn ein Script bei Fenster auf - die Heizung auf off schaltet, und danach gleich eine Tuer auf geht, und die nächste Heizung wieder off geschaltet wird.. ? 
Könnte man da im Adapter evtl. das Polling zur Fritzbox sammeln und nur alle 30 sek senden, oder so? 
Damit es, egal was man für Scripte hat, erst gar nicht so weit kommt..?

**Comment by foxthefox** [comment]
Ich glaube nicht, daß dein beschriebenes Szenario schon das Problem darstellt. Laut AVM Doku ist eine begrenzte Zahl von Sessions zur gleichen Zeit gültig. Und diese würden 20min gelten. Das bringt mir aber nichts, da ich keinen Vermittlungsschicht habe, die die Verbindung immer offen hält.

**Comment by Ilovegym66** [comment]
stimmt! ok. Haken dran. :-)

**Comment by foxthefox** [comment]
> Im Log der Box steht falsches Passwort eingegeben. Sowohl Benutzername als auch Passwort stimmen zu 100%. Es hat damit ja bereits funktioniert.

die Rückantwort 0000000 kann mehrere Ursachen haben, einmal ist es die Blockierung des Zugriffs mangels Rechte oder Überschreitung von Anzahl der Sessions oder eben login/pw ist nicht passend oder login nicht bekannt oder so.

Wenn login/pw ausgeschlossen werden kann, weil z.B. der Adapter richtig startete und auch schon lief, dann ist es das erstere.
Es gab Nutzer, die ein Fehler im Skript hatten und deswegen unentwegt das gleiche Kommando rausjagen, das quittiert die FB dann mit 0000000 irgendwann.

Andere haben Abfrageintervalle von 5s eingestellt und bringen so die FB in Überlast, daß sie nicht einmal mit 000000 antwortet, sondern mit 503.

**Comment by foxthefox** [comment]
> Kann ja eigentlich nicht sein, da der Fehler ja mit 2.0.0 und 1. Sowieso nicht auftrat und sich der Skriptunterbau nicht geändert hat.

Die API zur Fritzbox ist schon seit 2.0.0 drin, in 2.1.x wurde lediglich auf einen anderen Stil des Adapteraufrufs umgestellt.

**Comment by Dragon0501** [comment]
Mein Problem damit ist aber, ich bin etwas updatefaul und suche nicht regelmäßig. Das erste Update nach 1. sowieso welches mir vorgeschlagen würde war die 2.1.7. habe erstmal auf 1. und zurückgestellt und werde es in ein paar Tagen erneut versuchen...

**Comment by xdaamg** [comment]
> 
> 
> Es ist in der Tat so, daß nicht nur ein schnelles Intervall zum Abfragen, sondern auch viele Kommandos zur gleichen Zeit die Fritzbox mit vielen Logins belasten, wie schon woanders auch beschrieben, da gibt es scheinbar eine undokumentierte Anzahl und dann blockiert die FB.

Die Fehlermeldungen des Adapters (No response, "00000000") wurden bei mir durch zu viele Anfragen an die Fritzbox, teils auch noch mit ungültigen Anmeldedaten, ausgelöst. Seitdem die Anmeldedaten für alle zugreifenden Geräte/Apps wieder stimmen (eigener Account pro Gerät) gibt auch der Fritzdect-Adapter keine Fehler mehr aus.

**Comment by Dragon0501** [comment]
Problem solved! Nachts hat sich eines meiner Steuerungsskripts aufgehängt, hat unendlich viele Anfragen an den Adapter geschickt, dieser hat sich aufgehängt und auch weitere Adapter ohne Rückmeldung gekillt. Skript gefixt und funktionierte wieder. komisch, obwohl nichts geändert wurde... Naja Hauptsache ist es funktioniert wieder.
