### ISSUE TITLE
Version 2.1.7 Objektnamen wurden geändert ... muss das sein?

### ISSUE THREAD

**Issue by lcars79** [foxthefox/ioBroker.fritzdect#106]
Ich habe von der Version 1.1.x geupdatet auf die 2.1.7 und musste nun feststellen, dass die Temperaturwerte sowie andere Werte wie z.B. Stromverbrauch nicht mehr aktualisiert werden, dachte ich erst bis ich gesehen hatte, dass die Objekt IDs plötzlich alle anders sind.

Statt DECT200... nun nur DECT.... Das  ist sehr schlecht wenn man diese Namen in Skripten verwendet und nun der Name plötzlich ein anderer ist.

Die IDs sollten bitte nicht ohne Grund geändert werden sonst gehen die ganzen Skripte nicht mehr die da was auslesen!

**Comment by foxthefox** [comment]
leider musste es sein, denn der Adapter hat mal ganz einfach mit einem DECT200_ und Comet_ angefangen. Mit der zunehmenden Gerätevielfalt und der bisherigen Codebasis war dies nicht mehr zu managen. Mit der Verwendung der übermittelten Namen und eine Vereinheitlichung zu DECT_ ergab sich eine Halbierung des Codes und es ist wesentlich einfacher neue Dinge einzubringen.
Ist auch als Breaking change ausgewiesen.

**Comment by lcars79** [comment]
Danke für die Antwort da weiß man wenigstens Bescheid. Leider fällt einen das UI seitig in ioBroker nicht sofort auf, dass ein Update ggf. was ändert. Der wichtigste Punkt wäre da gewesen (neben allen anderen Feature die du implementiert hast) "ACHTUNG OBJECT IDs ÄNDERN SICH". Weil das ist im Grunde genommen die entscheidende Info gewesen. Aber alles gut vielleicht war ich ja der einzige der das nicht richtig nachgelesen hat ;-)

Trotzdem super Projekt und ich habe das hier voll im Einsatz :-)

**Comment by fs-plugins** [comment]
ich habe wg Neuinstall unbeabsichtigt ein Update gefahren
die obigen Erklärungen sind ja verständlich
jedoch sind auch massiv states geändert - actualtemp,targettemp, mode usw.
das hat mir endgültig unwahrscheinlich viel Arbeit beschert, in vielen scripten und obendrein an bestimmt 200 Stellen in den VIS-Projekten ebenso (leider hilft bei so etwas auch kein alias mehr)

**Comment by lcars79** [comment]
Genau so erging es mir auch. Aber die Skripte sind nun angepasst bei mir. Man sollte es imho aber in Zukunft am Besten lassen solche Namen zu ändern da diese Sachen bei den Nutzern nur zu unnötigen Problemen führen. Leider zeigt das ioBroker auch nicht schön an wenn z.B. solche großen Änderungen bei einem Plugin anstehen und so etwas zu erwarten ist.

**Comment by Ilovegym66** [comment]
siehe oben Kommentar vom Entwickler. 
Ich kann allen nur raten, die Changes zu lesen, bevor man das Update macht. Das ist nur ein  oder zwei Mausklick im Admin mehr, steht ja dick und fett drin.

**Comment by darkman242** [comment]
und für die Skripte empfiehlt es sich mit Aliasen zu arbeiten und diese bei so einem Problem gleich mal zu implementieren

**Comment by fs-plugins** [comment]
wo möglich und machbar kann ich das ebenso nur empfehlen, vereinfacht ähnlich auftretende Dinge erheblich - klar zustimm

allerdings muss man die Zeit für die Sache bei ein paar tausend states dann auch erstmal zur Verfügung haben (von den ungezählten VIS-Objekten gar nicht zu sprechen), das sind viele Stunden
eine umfangreiche, hauptsächlich mit geschriebenen Scripten gesteuerte und über Jahre gewachsene Hausautmation ist nicht mal eben komplett umzumodeln...

**Comment by foxthefox** [comment]
breaking changes sind nicht ohne, die gibt es an vielen Stellen auch under the hood (admin 2/3, compact mode, js-controller...) die sind auch für die Adapterentwicklung unschön und irgendwann ist ein refactoring nötig. Was heute mit einer Fritzbox geht war damals nicht absehbar von einer schaltbaren Steckdose ist es nun ein größeres EcoSystem geworden und die FB-API ist auch nicht so straight forward wie man es evtl denkt.
UND so eine Adapterentwicklung findet in der Freizeit statt und diese Update hat mich auch sehr viele Stunden gekostet und das mache ich nicht weil ich alle ärgern will, sondern die Zukunftsfähigkeit des Adapters zu sichern

**Comment by fs-plugins** [comment]
ich denke für die meisten gilt: wir können uns bedanken dass sich da jemand die Arbeit macht und wir es nutzen dürfen - und das will ich mal ausdrücklich tun!
aus eigener Erfahrung weiß ich sehr gut, wie man sich selber etwas eigentlich optimales vorstellt und umsetzt - das ganze ist ja eine abstrakte Sache wo sich die meisten nicht reindenken können (und mir ist auch klar welcher Aufwand dahinter steckt)
wer weiß welche Gründe es waren zB die tsoll/tist jetzt so zu benennen (das wird ja sicher im Adapter umgesetzt wie es letztlich dann in den states auftaucht), kann ja auch sein das es so von der API kommt und der einfacheren Pflege wegen übernommen wird
wir müssen jetzt damit leben und hoffen halt, das es nicht so bald wieder notwendig erscheint
evtl veranlassen unsere Kommentare allerdings auch, künftig nach Möglichkeit solche ID-Änderungen nur bei Unumgänglichkeit vorzunehmen :)

ist eigentlich ausführlich ausdiskutiert und sollte geschlossen werden, ist jetzt so wie es ist ;-)
