### ISSUE TITLE
ioBroker Log: (4294) unknown functionbitmask, please open issue on github 40960

### ISSUE THREAD

**Issue by kBrausew** [foxthefox/ioBroker.fritzdect#107]
After installing Fritzdect adapter 2.1.7 and start it, show a log entry:

(4294) unknown functionbitmask, please open issue on github 40960
=> mobil plug "telekom plug with energy-usage

(4294) unknown functionbitmask, please open issue on github 36864
=> Group (of plug's)

Türkontakt wird mit "functionbitmask" 8208 erkannt.

[JSON.zip](https://github.com/foxthefox/ioBroker.fritzdect/files/5802552/JSON.zip)

**Comment by foxthefox** [comment]
Super, daß hilft ungemein zur Verbesserung des Adapters.
Wurden irgendwelche Anteile denn schon angelegt?

Auf jeden Fall helfen die Daten und ich werde mir sie ansehen und in die nächste Version einbauen.

**Comment by kBrausew** [comment]
Mit V0.2.4 wurde nur der AVM-Thermostat angelegt sonst nix.
Mit V2.1.7 ... siehe JSON
[fritzdect.0.json.zip](https://github.com/foxthefox/ioBroker.fritzdect/files/5804915/fritzdect.0.json.zip)
Setzen von STATE am Plug & Group nach TRUE/FALSE hatte bislang keinen Erfolg...
Template/Vorlagen wurden nicht angelegt...

BTW: Am Wochenende kommt noch "Telekom Fensterkontakt" von der Qivicon auf die Fritz.Box...
?Neues Ticket oder hier erweitern?

**Comment by foxthefox** [comment]
wenn er noch nicht erkannt werden sollte, dann neues Ticket

**Comment by foxthefox** [comment]
> Setzen von STATE am Plug & Group nach TRUE/FALSE hatte bislang keinen Erfolg...
> Template/Vorlagen wurden nicht angelegt...
> 

Danke.
Genau der STATE ist noch ein zusätzliches Problem. Dieser Plug ist das erste Gerät (was ich sehe) welches nur den simpleonoff hat und kein state.
Das muß ich mir ansehen und anders gestalten.

**Comment by kBrausew** [comment]
BTW: Mein ioBroker ist noch nicht Produktiv (nutze NOCH QIVICON :-( )...
Falls du etwas brauchst (nur so zur Info: Habe JS Kenntnisse, zwar angestaubt aber vorhanden :-)

**Comment by kBrausew** [comment]
> wenn er noch nicht erkannt werden sollte, dann neues Ticket

... dann melde ich in ab ;-)


Welche Chancen habe ich dass ich mit Thermostat von HM-IP auf CCU3 und Tür/Fenster-Kontakt auf FritzBox ein funktionierendes Heizprofil auf ioBroker hinbekomme... habe mitbekommen das Fritze keine RPC-Events in Richtung ioBroker unterstützt, bedeutet der Status für "Fenster-offen" muss gepollt werden???

Na zur not fliegen die Kontakte raus und ich hole ZigBee oder HM Kontakte

**Comment by foxthefox** [comment]
> > wenn er noch nicht erkannt werden sollte, dann neues Ticket
> 
> ... dann melde ich ihn ab ;-)
> 
> Welche Chancen habe ich dass ich mit Thermostat von HM-IP auf CCU3 und Tür/Fenster-Kontakt auf FritzBox ein funktionierendes Heizprofil auf ioBroker hinbekomme... habe mitbekommen das Fritze keine RPC-Events in Richtung ioBroker unterstützt, bedeutet der Status für "Fenster-offen" muss gepollt werden???
> 
> Na zur not fliegen die Kontakte raus und ich hole ZigBee oder HM Kontakte

Die Frage solltest du mal im Form stellen. Das Thermostat könnte einen externen windowopen ggf. entgegennehmen. Die älteren HM Thermostate boten da eine Direktverknüpfung.  Eher problematisch sehe ich das notwendige Polling von Zuständen aus der FB, und darüberhinaus scheint es auch noch unbekannten Updatecycle der Geräte mit der FB zu geben.
Geräte die nicht im Batteriebetrieb sind, kommunizieren scheinbar öfter, aber die Batteriebetriebenen scheinen batterieschonend zu arbeiten. Es ist vorstellbar, daß ein Kontakt schnell weitengemeldet wird, aber beim Thermostat DECT3xx ist bekannt, daß um ca. 15min eine Kommunikation mit der FB stattfindet.

**Comment by kBrausew** [comment]
ne, schon klar...
es ging mir nur um die Kommunikation Fritz <=> ioBroker: Hier gibt es also kein RPC; es wird immer via Adapter gepollt ausgehend vom Adapter.
Standard sind ja 5 Minuten für den gesamten Adapter eingestellt, das ist ja dann nicht pro Device änderbar?

**Comment by foxthefox** [comment]
die 5min sind mal willkürlich angesetzt, aber es gilt immer nur für den gesamten Adapter. Einzelne Geräte machen nicht wirklich einen Unterschied im Telegrammverkehr. Es gibt Möglichkeiten DECT300/DECT200 einzeln abzufragen, den Rest aber nicht. Und so übermäßig groß ist dann die Gesamtantwort auch nicht.

**Comment by kBrausew** [comment]
OK, dann ausführlicher ;-)
Ich spreche ja AUSSCHLIESSLICH von dem Teil auf dass du Einfluss hast: Kommunikation zwischen ioBroker und FritzBox via Adapter!
Hier wird gepollt (Adapter pollt in Richtung Fritz) und es gibt keinen "Rückkanal" ala RPC-Events die eine Zustandsänderung zurückmelden.
D.h.: Egal wie schnell ein Device mit der Fritz seinen Zustand abgleicht, der Zustand kommt erst im ioB an wenn die Pollt-Zeit abgelaufen.
5 Minuten ist dann bei "Smart" viel zulange...

Jetzt gibt es zwei Möglichkeiten:
1) Ich stelle den Wert auf eine Sekunde (was mir immer noch zulange erscheint) und es funktioniert "fast" OnTime so wie es soll

2) Der Wert bleibt bei 5Min und man kann an einem Value (hier z.B. State) einzeln der Pollwert ändern.
Dies würde allerdings Entwicklung deinerseits voraussetzen damit dies möglich wird.
Jetzt bleibt nur die Frage: Wenn dem möglich wäre, bringt das überhaupt einen Vorteil zur Variante 1)

Oder sind gar Variante 1) und 2) nicht möglich weil "ich-hab-keine-Ahnung-warum-auch-immer"

**Comment by kBrausew** [comment]
Nachtrag Türkontakt:
Wird mit funktionbitmask 8208 erkannt, keine Warning im Log...

Devices:
[json-2.zip](https://github.com/foxthefox/ioBroker.fritzdect/files/5820305/json-2.zip)

**Comment by foxthefox** [comment]
> Jetzt gibt es zwei Möglichkeiten:
> 
> 1. Ich stelle den Wert auf eine Sekunde (was mir immer noch zulange erscheint) und es funktioniert "fast" OnTime so wie es soll
> 2. Der Wert bleibt bei 5Min und man kann an einem Value (hier z.B. State) einzeln den Pollwert ändern.
>    Dies würde allerdings Entwicklung deinerseits voraussetzen damit dies möglich wird.
>    Jetzt bleibt nur die Frage: Wenn dem möglich wäre, bringt das überhaupt einen Vorteil zur Variante 1)
> 
> Oder sind gar Variante 1) und 2) nicht möglich weil "ich-hab-keine-Ahnung-warum-auch-immer"

Variante 1 geht nicht mit diesem Zeitbereich. schon bei 10s gibt es Probleme. Das sind zu viele logins an der FB. exakte Werte kenne ich da nicht, aber zu viel Kommunikation endet mit '0000000' Antwort der FB. Was meist fehlinterpretiert wird, da meine message login error, pw falsch heißt.

Variante 2 ist nur eine Untervariante von 1. Würde man jedem Geräte ein eigenes polling geben, läuft das dennoch auf logins in Richtung FB hinaus. also das schnellste polling eines Gerätes sieht genauso aus wie, die 5min auf den schnellsten wert gesetzt. Und wie oben schon versucht zu erklären, ob ich alle Geräte abfrage oder nur eines, die Menge an Daten sind gleich, da ich auf die gesamten Geräteinfos gehe. 

und ja, die FB meldet sich nicht zurück, es geht nur aktives polling.

**Comment by foxthefox** [comment]
die Version 2.1.8 auf GitHub sollte Abhilfe schaffen, bitte testen

**Comment by kBrausew** [comment]
Test abgeschlossen:
- Erkennung der neuen Komponenten: Positiv abgeschlossen
- Zustands-Abfrage und Änderung der Object-Properties: Steuerung "Simple-On/Off" erfolgreich
- Energiemessung: Ok (Nicht gefordert und nicht getestet) :: Seitens FritzOS auch nicht möglich

Super Arbeit: Danke!!!

**Comment by kBrausew** [comment]
Nur als Hinweis für dich: Da die Verbindungsabbrüch vom Plug zur Fritz immer häufiger und auch länger werden, werde ich wohl meine Plugs & und Fensterkontakte gegen ZigBee oder HM/HmIP austauschen.

Wenn ich vollständig umgezogen bin könnte ich dir für deine super Unterstützung ein paar übrige Teile zusenden... Interesse?

**Comment by foxthefox** [comment]
Ich habe auf eve umgestellt. Danke für dein Angebot. 
Aber dennoch Fragen zu " Verbindungsabbrüch vom Plug zur Fritz immer häufiger und auch länger werden"
- was heißt das, Abbrüche zwischen Stecker und FB?, Abbrüche zwischen iobroker und FB?
- wie stellst du den ersteren Abbruch fest?
- da Stecker direkt an ihrer Spannungsversorgung hängen, sollten diese keine nennenswerten Abbrüche haben, außer die DECT Reichweite ist ein Problem.
- wenn es Abbrüche zwischen iobroker und FB ist, dann stimmt ggf. etwas nicht mit dem polling Intervall und ggf. Apps und andere Adapter die darauf gleichzeitig zugreifen wollen
-

**Comment by kBrausew** [comment]
Fehler:
In der Fritz-UI wurde der Plug mit "Gerätestatus": Nicht Verbunden dargestellt. Bedienung On/Off konnte nicht geändert werden.
Manuelles betätigen des Ein/Aus-Button am Plug änderte den On/Offzustand am Plug direkt und in der UI nach gefühlt einer Sekunde in seltenen Fälle auch erst nachdem der GS auf "Verbunden" zurück wechselte.
An dem verbundenen ioBroker war der Offlinezustand ersichtlich ("present") und verständlicherweise war auch keine On/Off Änderung möglich.

Vorab: Die Verbindungsabbrüche hatte ich bereits bevor ich Fritz und ioBroker koppelte!

- Der Abbruch ist zwischen Fritz und Stecker
- DECT: Da ich den Fenster-Kontakt zum Testen immer direkt neben einen Plug lege, glaube ich nicht an eine DECT-Unterversorgung, TF-Kontakt war immer erreichbar.
- Da die Qivicon eine Interne DECT-ULE hat gehe ich von einer Beeinflussung zwischen Fritz und Qivicon aus. Leider kann ich 
- diese derzeit nicht einfach abschalten. QIVICON war bei DECT-ULE immer zuverlässig obwohl die Fritz auch im DECT-Sektor sendete.
- Verbindungsabbrüche habe ich per eMail eingestellt
- Jeder Plug hat am Tag auf verschiedene Uhrzeiten verteil Unterbrechungen von bis zu 2 Stunden
- Hierbei wird weder der Aufstellungsort noch die einzelne HW bevorzugt. Habe jeden Plug mit jedem Ort bereits einmal getauscht: Kein Muster erkennbar.

Reine Vermutung ohne Beweise:
Mit diesem Fehler-Bild würde ich jetzt auf die Plug tippen, da der FT-Kontakt keine Aussetzer hatte.
Man kann ihm jetzt nicht vollständig die "Schuld" zuweisen da er an der Qivicon ja funktionierte.
Ich gehe davon aus das Fritz & Plug's KNAPP über der Tolleranzgrenze betrieben werden und der FT-Kontakt deutlich mehr Reserven mitbringt im DECT Band.

Aufgrund der Tatsache dass die TF-Kontakte zwar verlässlich arbeiten aber ich in ioBroker durch die schlechte Polling-Rate nicht verwenden kann, werde ich das Projekt DECT-ULE HAN-FUN vollständig beerdigen.

Fakt ist: Mit mehr als einer Sekunde polling ist weder eine Alarmanlage noch ein Heizprofil für mich in ioBrocker vernünftig zu realisieren.

Ohne Fritz steht mir sogar HASS.IO zur Verfügung: Anbindung Fritz<->HASS ist wirklich um längen schlechter als deine hier
Ganz ehrlich gefällt mir ioBroker zwar besser aber die Android-App's sind halt ne nette Spielerei die ich gerne hätte und in ioBroker schmerzlich vermisse (als den Komfort, nicht die App an sich)


Einziger Punkt mich an ioBroker zu binden wäre selber einen Adapter für https://github.com/uhppoted/uhppoted zu realisieren: Denn JS kann ich, zwar angestaubt... 
Aber Phyton für HASS.IO ist absolutes Neuland...

**Comment by kBrausew** [comment]
So: Es ist soweit!
USB 3.0 an der Fritz abgeschaltet (auf 2.1 geändert für beide Ports), qivicon abgeschaltet ==> keine bekannten Störquellen im DECT-ULE Band

- TF-Kontakter stabil :-)
- Plug's haben immer noch Verbindungsabbrüche...

Die Abbrüche sind zwar von 20 - 30 auf 3 - 5 pro Tag und Plug zurückgegangen aber es ist immer noch untragbar :-(
Auffällig ist das je näher sie am Repeater sind desto mehr Abbrüche haben sie.

Ich stell den Krempel am diesem oder nächstes Wochenende mal in eBay ein.
