### ISSUE TITLE
Adapter Version 2.1.7

### ISSUE THREAD

**Issue by MELDB345** [foxthefox/ioBroker.fritzdect#108]
Die Version steuert meine Comet DECT Heizkörper Ventile nicht an.

**Comment by foxthefox** [comment]
danke für die Rückmeldung, falls Hilfe benötigt wird, wären mehr Angaben wünschenswert.
Ansonsten empfehle ich den adapter in den debug modus zu versetzen und im log zu schauen was da passiert.

**Comment by MELDB345** [comment]
Hallo,

 

was brauch sie noch für Angaben.

 

Iobroker läuft auf einem Beelink mit Debian als Betriebssystem.



 

Von: foxthefox [mailto:notifications@github.com] 
Gesendet: Dienstag, 12. Januar 2021 20:58
An: foxthefox/ioBroker.fritzdect
Cc: MELDB345; Author
Betreff: Re: [foxthefox/ioBroker.fritzdect] Adapter Version 2.1.7 (#108)

 

danke für die Rückmeldung, falls Hilfe benötigt wird, wären mehr Angaben wünschenswert.
Ansonsten empfehle ich den adapter in den debug modus zu versetzen und im log zu schauen was da passiert.

**Comment by MELDB345** [comment]
Hallo,

 

hier den Log vom Adapter auf Version 2.1.7



 

Von: foxthefox [mailto:notifications@github.com] 
Gesendet: Dienstag, 12. Januar 2021 20:58
An: foxthefox/ioBroker.fritzdect
Cc: MELDB345; Author
Betreff: Re: [foxthefox/ioBroker.fritzdect] Adapter Version 2.1.7 (#108)

 

danke für die Rückmeldung, falls Hilfe benötigt wird, wären mehr Angaben wünschenswert.
Ansonsten empfehle ich den adapter in den debug modus zu versetzen und im log zu schauen was da passiert.

**Comment by foxthefox** [comment]
> Hallo, hier den Log vom Adapter auf Version 2.1.7 

war leider kein log in der mail drin.

Welche Nodejs Version, welche js-controller Version?
Welche Geräte wurden angelegt?
Sind alle Geräte angelegt?
Startet der Adapter mit Meldungen "create ....."
Im debug Modus des Adapters, gibt es beim steuern des Thermostat Meldungen "command ... detected..." Danach Fehlermeldungen?
Was bringt die Rückmeldung vom AdapterConfig wenn man die Taste  "Meine Geräte" drückt.
Wie ist das Polling Intervall eingestellt?

**Comment by MELDB345** [comment]
Hallo,


node  v10.23.0

npm v6.14.8




Holen Sie sich Outlook für Android

**Comment by foxthefox** [comment]
Hab kein Android :-)

die 2 Angaben allein bringen die Hilfe nicht wirklich vorwärts.
wenn es hier zu umständlich ist, dann evtl. im Forum

https://forum.iobroker.net/topic/40485/test-adapter-adapter-fritzdect-v2-1-x-github?_=1610804005767

**Comment by MELDB345** [comment]
Ich denke ich habe jetzt mein Problem gefunden.
Nachdem ich jetzt über den link ins Forum gegangen bin und etwas gelesen habe.
Bei mir hat es den Objektbaum nicht angelegt, weil als User admin rein muss .
Das war mein Problem jetzt hat es den Objektbaum angelegt.
Ich denke jetzt geht alles.

Danke für die Hilfe.


Gesendet von Mail für Windows 10

Von: foxthefox
Gesendet: Samstag, 16. Januar 2021 18:54
An: foxthefox/ioBroker.fritzdect
Cc: MELDB345; Author
Betreff: Re: [foxthefox/ioBroker.fritzdect] Adapter Version 2.1.7 (#108)

Hab kein Android :-)
die 2 Angaben allein bringen die Hilfe nicht wirklich vorwärts.
wenn es hier zu umständlich ist, dann evtl. im Forum
https://forum.iobroker.net/topic/40485/test-adapter-adapter-fritzdect-v2-1-x-github?_=1610804005767
