### ISSUE TITLE
Important: Change to FRITZ!Box login process

### ISSUE THREAD

**Issue by sky-it** [foxthefox/ioBroker.fritzdect#110]
https://avm.de/service/schnittstellen/

With the upcoming release of FRITZ!OS 7.25, there will be a change when logging in with the FRITZ!Box password, which developers for FRITZ!Box will need to take into account. The change is expected to take effect at the end of 2020, as well in version 7.24, available in advance in the FRITZ! Lab.

The document below describes the changes and provides recommendations for user guidance for logging into a FRITZ!Box. The document is intended for developers who program third-party applications for FRITZ!Box. From a usability point of view, developers of third-party applications are strongly recommended to adapt their user interface and terms to the behavior of the FRITZ!Box interface, which is familiar to the user.

-----------------------------------------------------------------------

Wichtige Information: Änderung des Anmeldeverfahrens an einer FRITZ!Box

Ab dem kommenden Release FRITZ!OS 7.25 kommt es bei der Anmeldung mit dem FRITZ!Box-Kennwort zu einer Änderung, die von Entwicklern für FRITZ!Box berücksichtigt werden muss. Die Änderung wird absehbar Ende 2020 wirksam und vorab im FRITZ!Labor in der Version 7.24 bereit gestellt werden.

Das folgende Dokument beschreibt die Änderungen und gibt Empfehlungen zur Benutzerführung bei der Anmeldung an einer FRITZ!Box. Das Dokument richtet sich an Entwickler, die Drittanwendungen für die FRITZ!Box programmieren. Aus Usability-Gesichtspunkten wird Entwicklern von Drittanwendungen stark empfohlen, die Benutzerführung und die Begriffe an das für den Anwender gewohnte Verhalten der FRITZ!Box-Oberfläche
anzugleichen.

**Comment by foxthefox** [comment]
ist schon in Version 2.1.x berücksichtigt
