### ISSUE TITLE
Schaltzustand Fritz Dect 200 wird nicht angezeigt

### ISSUE THREAD

**Issue by c1olli** [foxthefox/ioBroker.fritzdect#117]
Das Modul selbst tut was es soll, und gefällt mir wirklich sehr gut.
Das einzige was mir fehlt, ist eine Anzeige für den Schaltzustand, wenn ich über den Taster an der DECT 200 schalte.
Denn die Änderung wird dann bei mir im ioBroker nicht angezeigt.
Kann man das noch einbauen? 
MFG
c1olli

**Comment by foxthefox** [comment]
das verstehe ich nicht.
Wenn sich die Steckdose schalten lässt, dann ändert sich auch deren Zustand.
Also mit dem Datenpunkt "state" wird geschaltet und danach steht "state" auf dem Zustand den man gewählt hat.
Dieser Zustand ist die Anzeige.

Intern sendet der Adapter ein Telegram an die Fritzbox und wenn die Kommunikation erfolgreich war, setzt der Adapter den Datenpunkt "state" nochmal mit dem Wert und ACK=true.

**Comment by c1olli** [comment]
Ja, wenn ich über ioBroker schalte, dann funktioniert das auch, Schalte ich aber über den Taster an der Steckdose kommt keine Rückmeldung. Starte ich dann den Adapter neu, dann aktualisiert sich der Staus.
Wo es da klemmt weiß ich auch nicht.
Edit:
Nun macht er es - aber die Aktualisierung dauert ca. 2-3 Minuten

**Comment by foxthefox** [comment]
das ist ein normales Verhalten. Im Adapterconfig gibt es die Einstellung Pollintervall, mit der wird die Zeit zwischen Aktualisierungen eingestellt (default 300s=5min). In diesem Zyklus meldet sich iobroker bei der fritzbox an um den aktuellen status abzuholen.
Die FB meldet sich nicht selbständig und pusht neue Werte an iobroker, leider!
Wenn man in den DEBUG Modus des Log schaltet sieht man dieses Intervall sehr gut.
Einstellungen unterhalb oder im Bereich 10s sind kritisch, weil dann zu viele Logins an der FB passieren und die FB nicht mehr mag.
