### ISSUE TITLE
Dect 500 nicht implementiert

### ISSUE THREAD

**Issue by AchtungWild** [foxthefox/ioBroker.fritzdect#118]
Leider lässt sich die dect 500led Lampe nicht implementieren.
Kann das eventuell jemand  anpassen?

Vielen Dank

**Comment by foxthefox** [comment]
Für den Entwickler ist es immer sehr hilfreich wenn man mehr Info zum Problem bekommt.
Die DECT500 ist per se im Adapter realisiert und wurde schon von anderen erfolgreich getestet.

Bitte in Adapterconfig auf "Meine Geräte" klicken und den output bräuchte ich zur Analyse.
Ansonsten wäre noch ein screenshot des Objektbaumes interessant inwieweit dort für die Lampe etwas unvollständig angelegt wurde.
Und dann helfen ggf. Hinweise aus dem log.

**Comment by foxthefox** [comment]
Gibt es schon Neuigkeiten?

**Comment by foxthefox** [comment]
Ich gehe davon aus, daß es sich erledigt hat
