### ISSUE TITLE
Adaper Version 2.1.10 Error in Log

### ISSUE THREAD

**Issue by haselchen** [foxthefox/ioBroker.fritzdect#119]
Einfach aus dem Nichts trudeln während des Tages diese Fehlermeldungen ein:

fritzdect.0 | 2021-02-07 15:00:23.424 | error | (17092) no response part in returned message
fritzdect.0 | 2021-02-07 15:00:23.422 | error | (17092) fritzbox returned this {"msg":"failed to login, wrong user name  or password","function":"send_response","error":"0000000000000000"}

Adapter ist grün, User und Passwort stimmen.
Objekte werden auch aktualisiert.
Diese Meldung gibt es mit Beta, Labor und Stable Software-Versionen der Fritzbox.

**Comment by foxthefox** [comment]
wenn User und Passwort stimmen, dann hatte höchstwahrscheinlich die Fritzbox zu viele Logins abbekommen, die dann zum Verweigern führen.
Ursache kann eine recht schnelles Abfrageintervall, viele Befehle zur gleichen Zeit (ggf. "unsaubere" Skripte, andere Adapter/apps die auch auf FB einloggen) sein.
Dazu müsste man ggf. das log ,al anschauen, wann es passiert und in welchem sonstigen Umfeld.

**Comment by haselchen** [comment]
Aufgetreten seit der neuen 7.24 der FB würde ich sagen. Vorher kam dieser Fehler nicht.
Auf die Box greift nur dein Adapter alle 300sek zu.
Und wenn hier einer Anruft, der TR-064 Adapter. Das wars.

**Comment by foxthefox** [comment]
aus Adaptersicht ist der User ein String, also da schließe ich mal den Adapter aus, eher ist 7.24 als Laborversion eine Ursache.
Mit 7.24 ändert sich das Anmeldeverfahren und evtl. gibt es Probleme den Hash schnell genug auszurechnen.

**Comment by haselchen** [comment]
Aus Laiensicht, kannst Du da was mit dem Adapter machen?
AVM wird sich bestimmt nicht an Dich anpassen :) :)

**Comment by foxthefox** [comment]
Was soll ich da machen? Der Adapter versucht sich einzuloggen und das klappt auch im Normalfall. Wenn es der FB zuviel wird dann sendet sie halt 00000000 als Antwort, was soviel ist wie ich mag nicht aus verschiedensten Gründen.

**Comment by foxthefox** [comment]
Schau mal unter:
docs/de/troubleshooting.md
hab da mal etwas zusammengeschrieben

**Comment by Flyor** [comment]
Hab das gleiche Probleme - das witzige bei der Geschichte ist jedoch, falls ich das Passwort im Adapter neu eingebe und mit Speichern & schließen bestätige, ist der Adapter wieder verbunden.

**Comment by foxthefox** [comment]
> Hab das gleiche Probleme - das witzige bei der Geschichte ist jedoch, falls ich das Passwort im Adapter neu eingebe und mit Speichern & schließen bestätige, ist der Adapter wieder verbunden (Lädt alle Objekte, kann steuern etc.). Wenn die Theorie also richtig sein sollte, dann sollte dieser Zugriff doch auch "geblockt" werden, oder nicht?

Was genau ist das gleiche Problem?
Sporadisch mal ne Fehlermeldung, daß login nicht ging?

Die Fritzbox blockiert nicht auf ewig, es fängt im Sekundenbereich an und geht dann recht schnell in die Richtung 30s.

**Comment by Flyor** [comment]
> Was genau ist das gleiche Problem?
> Sporadisch mal ne Fehlermeldung, daß login nicht ging?
> 
> Die Fritzbox blockiert nicht auf ewig, es fängt im Sekundenbereich an und geht dann recht schnell in die Richtung 30s.

Der Log sieht wie folgt aus:

`

fritzdect.0 | 2021-02-11 12:31:45.223 | error | (283055) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-02-11 12:31:45.221 | error | (283055) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}

`

Die Meldung kommt in rythmischen Abständen - der Zugriff auf die DECT Objekte des Adapters (Adapter ist weiterhin grün!) kann erst durch Neueingabe des Passworts in den Einstellungen wiederhergestellt werden. Adapter neustart bringt die gleiche Fehlermeldung.

**Comment by foxthefox** [comment]
Wenn die Meldung in rhythmischen Abständen kommt, dann sollte der Rhythmus mal verlangsamt werden, indem das polling Intervall nach oben gesetzt wird.
Eine Neueingabe des Passworts im Admin scheint mir überflüssig, zumal beim Start dann die gleiche Meldung kommt.
Bitte einmal die Datei

docs/de/troubleshooting.md

hier im Repo anschauen.

**Comment by Flyor** [comment]
Hab ich gelesen. Ich werde weiter mit Polling Time experimentieren und berichten, falls es sich nicht bessert.

**Comment by Flyor** [comment]
BTW: Macht es Sinn für den TR.064 und den Dect Adapter verschiedene Benutzer anzulegen, damit die Polls sich nicht gegenseitig beeinflussen und es zu einem overflow kommt? Oder ist das egal, über welchen Benutzer auf die FB zugegriffen wird?

**Comment by foxthefox** [comment]
Ich habe mit dem tr064 keine Erfahrung, viele Nutzer richten jeweils eigene user ein. Ist evtl. nicht das verkehrteste.
Wie die FB intern mit der Anzahl von logins umgeht und diese zählt, weiß ich nicht.

**Comment by Flyor** [comment]
Ich werde es mal testen. Trotzdem Danke für deine Antwort und deine Bemühungen mit dem Adapter @foxthefox

**Comment by foxthefox** [comment]
Kann der Problemreport geschlossen werden?

**Comment by TepMan** [comment]
Habe das gleiche Problem, seit dem Update auf 2.1.11:


fritzdect.0 | 2021-03-17 21:05:31.039 | error | (4185) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-03-17 21:05:31.038 | error | (4185) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}

**Comment by haselchen** [comment]
> 
> 
> Kann der Problemreport geschlossen werden?

Vermutlich nicht. Die gleiche Meldung wie @TepMan bekomme ich weiterhin täglich regelmässig.

**Comment by foxthefox** [comment]
Wenn grundsätzlich der Adapter mit der Fritzbox kommuniziert, dann ist der Anmeldeprozeß erstmal richtig.
Bei sporadischen aber "regelmäßigen" Auftreten ist mal abzurufen, ist es ein exakter regelmäßiger Rhythmus (gleiche Zeitanstände) oder ist es ohne Regelmäßigkeit. Dies gibt evtl. erste Hinweise.
Dann ist der Eintrittszeitpunkt näher zu untersuchen, gab es ein script/cronjob/Anwesenheitserkennung/andere Interaktionen die ein Feuerwerk an FB-Kommunikation auslösen könnten. Oder eben halt auch Dinge die den gleichen Service nutzen, aber außerhalb von iobroker

**Comment by haselchen** [comment]
> 
> 
> Wenn grundsätzlich der Adapter mit der Fritzbox kommuniziert, dann ist der Anmeldeprozeß erstmal richtig.
> Bei sporadischen aber "regelmäßigen" Auftreten ist mal abzurufen, ist es ein exakter regelmäßiger Rhythmus (gleiche Zeitanstände) oder ist es ohne Regelmäßigkeit. Dies gibt evtl. erste Hinweise.
> Dann ist der Eintrittszeitpunkt näher zu untersuchen, gab es ein script/cronjob/Anwesenheitserkennung/andere Interaktionen die ein Feuerwerk an FB-Kommunikation auslösen könnten. Oder eben halt auch Dinge die den gleichen Service nutzen, aber außerhalb von iobroker

Heute zum Beispiel gab es den Fehler um 5:36, 5:55 und 15:10Uhr.
Ein Rhythmus ist da nicht zu erkennen.
Um die Zeit greift auch nichts auf die FB zu.
Ich benutze den TR064 Adapter und die Pollzeit ist 23sek.
Dann den Fritzbox Adapter wegen der HTML und JSON Daten (Pollzeit ist nicht bekannt bzw. kann nicht eingestellt werden im Adapter).
Und dann noch den Fritzdect mit einer Pollzeit von 180sek.

**Comment by Flyor** [comment]
> > Wenn grundsätzlich der Adapter mit der Fritzbox kommuniziert, dann ist der Anmeldeprozeß erstmal richtig.
> > Bei sporadischen aber "regelmäßigen" Auftreten ist mal abzurufen, ist es ein exakter regelmäßiger Rhythmus (gleiche Zeitanstände) oder ist es ohne Regelmäßigkeit. Dies gibt evtl. erste Hinweise.
> > Dann ist der Eintrittszeitpunkt näher zu untersuchen, gab es ein script/cronjob/Anwesenheitserkennung/andere Interaktionen die ein Feuerwerk an FB-Kommunikation auslösen könnten. Oder eben halt auch Dinge die den gleichen Service nutzen, aber außerhalb von iobroker
> 
> Heute zum Beispiel gab es den Fehler um 5:36, 5:55 und 15:10Uhr.
> Ein Rhythmus ist da nicht zu erkennen.
> Um die Zeit greift auch nichts auf die FB zu.
> Ich benutze den TR064 Adapter und die Pollzeit ist 23sek.
> Dann den Fritzbox Adapter wegen der HTML und JSON Daten (Pollzeit ist nicht bekannt bzw. kann nicht eingestellt werden im Adapter).
> Und dann noch den Fritzdect mit einer Pollzeit von 180sek.

Hast du denn für jeden Adapter einen eigenen Benutzer Account auf deiner FB, oder benutzen alle Adapter den gleichen Account? Falls die Adapter alle den gleichen Account benutzen, kann es durchaus vorkommen dass diese aufgrund der hinterlegten Limits den Zugang verweigert und neu anmelden lässt. Aus meiner Sicht kein Fehler des Adapters - wenn alle anderen FB Zugriffe ausgeschaltet werden, sollte dieser keinerlei Probleme verursachen.

**Comment by haselchen** [comment]
@Flyor 

Habe für jeden Fritz-Adapter einen eigenen User.
Daran kann es nicht liegen.
Heute bisher nur 1 Fehlermeldung um 17:13Uhr.
Würde die FB allergisch auf Zugriffe (bei mir)  reagieren, gäbe es mehr Meldungen am Tag.

**Comment by TepMan** [comment]
Bei mir laufen der FritzDECT und der TR064 mit dem gleichen Fritzbox-User. Der FritzDECT polled alle 23 Sekunden, der TR064 alle 27 Sekunden. Ich hatte das Problem mit den Anmeldungen früher schon mal, dann war aber nach einigen FB- und ioBroker-Neustarts das Problem lange weg und ist nach dem letzten Update des FritzDECT erst wieder aufgetreten. Heute habe ich den ioBroker-Raspi aktualisiert und neu gestartet. Ich werde jetzt mal abwarten, ob sich was ändert.

Was mich daran zweifeln lässt, dass es nur an der FB oder der Anzahl / Häufigkeit der Logins liegt, ist, dass nur der FritzDECT-Adapter das Problem hat, aber nie der TR064.

**Comment by TepMan** [comment]
Systemaktualisierung und Neustart haben leider nichts gebracht:
`

fritzdect.0 | 2021-03-27 09:29:53.512 | error | (15649) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-03-27 09:29:53.511 | error | (15649) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}


`

**Comment by Flyor** [comment]
> Bei mir laufen der FritzDECT und der TR064 mit dem gleichen Fritzbox-User. Der FritzDECT polled alle 23 Sekunden, der TR064 alle 27 Sekunden. Ich hatte das Problem mit den Anmeldungen früher schon mal, dann war aber nach einigen FB- und ioBroker-Neustarts das Problem lange weg und ist nach dem letzten Update des FritzDECT erst wieder aufgetreten. Heute habe ich den ioBroker-Raspi aktualisiert und neu gestartet. Ich werde jetzt mal abwarten, ob sich was ändert.
> 
> Was mich daran zweifeln lässt, dass es nur an der FB oder der Anzahl / Häufigkeit der Logins liegt, ist, dass nur der FritzDECT-Adapter das Problem hat, aber nie der TR064.


DECT und TR064 Adapter greifen auf verschiedene Bereich zu und es sind unterschiedliche Adapter. Der Adapter ist für ein Abrufintervall (ich glaube Standard ist 100 Sekunden) ausgelegt und funktioniert in diesem Bereich auch. Wenn du ihn händisch runterstellst, ist es ein betreiben außerhalb der Spezifikationen und kein "Issue" wert. 
Stell den Fritz DECT Poll mal auf >100 ein. Dann klappt's auch mit den Fehlermeldungen. Ich hab ihn auf 150 stehen und die Meldung kommt gar nicht mehr.

**Comment by TepMan** [comment]
> > Bei mir laufen der FritzDECT und der TR064 mit dem gleichen Fritzbox-User. Der FritzDECT polled alle 23 Sekunden, der TR064 alle 27 Sekunden. Ich hatte das Problem mit den Anmeldungen früher schon mal, dann war aber nach einigen FB- und ioBroker-Neustarts das Problem lange weg und ist nach dem letzten Update des FritzDECT erst wieder aufgetreten. Heute habe ich den ioBroker-Raspi aktualisiert und neu gestartet. Ich werde jetzt mal abwarten, ob sich was ändert.
> > Was mich daran zweifeln lässt, dass es nur an der FB oder der Anzahl / Häufigkeit der Logins liegt, ist, dass nur der FritzDECT-Adapter das Problem hat, aber nie der TR064.
> 
> DECT und TR064 Adapter greifen auf verschiedene Bereiche zu und es sind unterschiedliche Adapter. Der Adapter ist für ein Abrufintervall (ich glaube Standard ist 100 Sekunden) ausgelegt und funktioniert in diesem Bereich auch. Wenn du ihn händisch runterstellst, ist es ein betreiben außerhalb der Spezifikationen und kein "Issue" wert.
> Stell den Fritz DECT Poll mal auf >100 ein. Dann klappt's auch mit den Fehlermeldungen. Ich hab ihn auf 150 stehen und die Meldung kommt gar nicht mehr.

Ja, klar sind das unterschiedliche Bereiche, aber der selbe User für den Login an der FB, und das ist der Punkt. Wenn der User sich mit dem TR064 anmelden kann und (mehr oder weniger gleichzeitig) mit dem FritzDECT nicht, und dabei immer nur der FritzDECT das Problem hat und nie der TR064 fällt es mir schwer zu glauben, das es nicht mit dem FritzDECT-Adapter zusammenhäbgt. Poll habe ich jetzt für den FritzDECT hochgestellt. Ich gucke mal, ob es sich bessert.

**Comment by TepMan** [comment]
Den Poll-Intervall hoch zu stellen hat leider auch keine Besserung gebracht (Poll ist jetzt bei 100):

```

fritzdect.0 | 2021-03-27 18:58:34.912 | error | (12524) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-03-27 18:58:34.911 | error | (12524) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}


```

**Comment by Flyor** [comment]
> > > Bei mir laufen der FritzDECT und der TR064 mit dem gleichen Fritzbox-User. Der FritzDECT polled alle 23 Sekunden, der TR064 alle 27 Sekunden. Ich hatte das Problem mit den Anmeldungen früher schon mal, dann war aber nach einigen FB- und ioBroker-Neustarts das Problem lange weg und ist nach dem letzten Update des FritzDECT erst wieder aufgetreten. Heute habe ich den ioBroker-Raspi aktualisiert und neu gestartet. Ich werde jetzt mal abwarten, ob sich was ändert.
> > > Was mich daran zweifeln lässt, dass es nur an der FB oder der Anzahl / Häufigkeit der Logins liegt, ist, dass nur der FritzDECT-Adapter das Problem hat, aber nie der TR064.
> > 
> > 
> > DECT und TR064 Adapter greifen auf verschiedene Bereiche zu und es sind unterschiedliche Adapter. Der Adapter ist für ein Abrufintervall (ich glaube Standard ist 100 Sekunden) ausgelegt und funktioniert in diesem Bereich auch. Wenn du ihn händisch runterstellst, ist es ein betreiben außerhalb der Spezifikationen und kein "Issue" wert.
> > Stell den Fritz DECT Poll mal auf >100 ein. Dann klappt's auch mit den Fehlermeldungen. Ich hab ihn auf 150 stehen und die Meldung kommt gar nicht mehr.
> 
> Ja, klar sind das unterschiedliche Bereiche, aber der selbe User für den Login an der FB, und das ist der Punkt. Wenn der User sich mit dem TR064 anmelden kann und (mehr oder weniger gleichzeitig) mit dem FritzDECT nicht, und dabei immer nur der FritzDECT das Problem hat und nie der TR064 fällt es mir schwer zu glauben, das es nicht mit dem FritzDECT-Adapter zusammenhäbgt. Poll habe ich jetzt für den FritzDECT hochgestellt. Ich gucke mal, ob es sich bessert.

Wer sagt denn, dass der TR Adapter den vermeindlichen "Fehler" überhaupt anzeigen würde wenn er vorliegt? Bei mir hing die Häufigkeit dieser Fehlermeldung immer mit der verwendeten Firmware zusammen. Mal war das schlimmer, mal weniger. Seit ich auf 150 gestellt hab kommt er noch 1x monatlich oder so.

**Comment by TepMan** [comment]
> > > > Bei mir laufen der FritzDECT und der TR064 mit dem gleichen Fritzbox-User. Der FritzDECT polled alle 23 Sekunden, der TR064 alle 27 Sekunden. Ich hatte das Problem mit den Anmeldungen früher schon mal, dann war aber nach einigen FB- und ioBroker-Neustarts das Problem lange weg und ist nach dem letzten Update des FritzDECT erst wieder aufgetreten. Heute habe ich den ioBroker-Raspi aktualisiert und neu gestartet. Ich werde jetzt mal abwarten, ob sich was ändert.
> > > > Was mich daran zweifeln lässt, dass es nur an der FB oder der Anzahl / Häufigkeit der Logins liegt, ist, dass nur der FritzDECT-Adapter das Problem hat, aber nie der TR064.
> > > 
> > > 
> > > DECT und TR064 Adapter greifen auf verschiedene Bereiche zu und es sind unterschiedliche Adapter. Der Adapter ist für ein Abrufintervall (ich glaube Standard ist 100 Sekunden) ausgelegt und funktioniert in diesem Bereich auch. Wenn du ihn händisch runterstellst, ist es ein betreiben außerhalb der Spezifikationen und kein "Issue" wert.
> > > Stell den Fritz DECT Poll mal auf >100 ein. Dann klappt's auch mit den Fehlermeldungen. Ich hab ihn auf 150 stehen und die Meldung kommt gar nicht mehr.
> > 
> > 
> > Ja, klar sind das unterschiedliche Bereiche, aber der selbe User für den Login an der FB, und das ist der Punkt. Wenn der User sich mit dem TR064 anmelden kann und (mehr oder weniger gleichzeitig) mit dem FritzDECT nicht, und dabei immer nur der FritzDECT das Problem hat und nie der TR064 fällt es mir schwer zu glauben, das es nicht mit dem FritzDECT-Adapter zusammenhäbgt. Poll habe ich jetzt für den FritzDECT hochgestellt. Ich gucke mal, ob es sich bessert.
> 
> Wer sagt denn, dass der TR Adapter den vermeindlichen "Fehler" überhaupt anzeigen würde wenn er vorliegt? Bei mir hing die Häufigkeit dieser Fehlermeldung immer mit der verwendeten Firmware zusammen. Mal war das schlimmer, mal weniger. Seit ich auf 150 gestellt hab kommt er noch 1x monatlich oder so.

Also was denn nun? Kommt die Meldung gar nicht mehr bei dir (1. Antwort) oder 1 x im Monat (2. Antwort)? Und du kannst mal ganz fest davon ausgehen, das der TR064-Adapter Login-Fehler meldet, für den ist die Verbindung zur Fritzbox auch essentiell. Ansonsten können wir diese Unter-Diskussion hier auch beenden. Vielen Dank für deine Hinweise.

**Comment by TepMan** [comment]
Habe jetzt die letzten Tage mal mit dem Polling-Intervall herumgespielt. Hatte den Poll alle 30, 60, 100 und 150 Sekunden jeweils über einen Tag laufen. In allen Fällen ist der Login-Fehler 1 - 3 mal pro Tag aufgetreten. Ist jetzt keine empirische Studie, aber der Zusammenhang zwischen Polling-Intervall und dem Auftreten des Fehlers scheint eher nur sekundär zu sein. Das Problem muss noch irgendeine andere Ursache haben.

**Comment by foxthefox** [comment]
Aus Adaptersicht passiert immer das gleiche, auf FB einloggen und Werte holen/Kommando absetzen. Wie oft man sich eine Session ID holen kann, bis es zu dem 0000000 kommt, weiß ich nicht. Wenn es dann zu den Fehlern kommt, war evtl. zusätzlich zum Polling noch das ein oder andere Kommando dabei, so wäre meine Vermutung.

**Comment by TepMan** [comment]
Ich werde das mal weiter beobachten und gucken, ob ich irgendwas finde, das damit in Zusammenhang stehen könnte.

**Comment by totocotonio** [comment]
Hallo,
bei das gleiche Problem und das ständig. Polling ist auf 300 eingestellt.

`fritzdect.0 | 2021-05-14 07:15:41.758 | error | (630) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-05-14 07:15:41.758 | error | (630) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}`


Gibt es da mittlerweile eine Lösung

**Comment by foxthefox** [comment]
Im Normalfall kommen diese Meldungen, wenn überhaupt, nur sporadisch.

Dann hätte ich mal ein paar Fragen die zu beantworten wären:
- Welche Version des fritzdect läuft denn?
- Tritt die Meldung auch beim Start auf?
- Kommt die Meldung alle 5min (300sec)?
- Kommt die Meldung nur sporadisch?
- Gibt es scripte die Objekte der FB abfragen oder steuern?
- Ist ein login über Webinterface mit dem in iobroker eingetragenen Benutzer/PW möglich?
- sind die Berechtigungen für Smarthome richtig eingestellt?
- gibt es andere Adapter die auch auf die FB zugreifen?
- gibt es mehr als eine iobroker Instanz und dann auch dort mit fritzdect?
-

**Comment by totocotonio** [comment]
Hi,
gibt es schon eine Lösung?

Fragen habe ich per Mail beantwortet.

mfg

**Comment by foxthefox** [comment]
hab scheinbar die Mail nicht bekommen oder sie ist im ganzen Spam mit untergegangen.
Sorry, von daher ist meinerseits nichts passiert.
Bitte nochmal schicken, oder hier posten

**Comment by TepMan** [comment]
Hi, ich habe das jetzt mal über einen längeren Zeitraum beobachtet. Ich kann beim besten Willen kein Muster erkennen. Mal kommt der Fehler dreimal am Tag, dann mal zwei Tage gar nicht. Mitten in der Nacht, in den Morgen- oder Abendstunden oder einfach den Tag über. Auch kann ich keinen Zusammenhang mit anderen Zugriffen auf die FB festmachen. Meine Heizungsregelung läuft alle 30 Minuten, jeweils um voll und um halb. Der TR-064-Adapter polled alle 25 Sekunden. 

Die Fehler treten zu beliebigen Zeitpunkten auf, z.B. 11:13:47, 02:55:13, 05:43:36 und ohne das direkt davor oder danach irgendetwas anderes in Richtung FB passiert.

**Comment by haselchen** [comment]
@TepMan 

Besser hätte ich es nicht schreiben können.
1:1 wie bei mir. Aber haargenau. Mal von den Uhrzeiten abgesehen :)

**Comment by foxthefox** [comment]
Wenn es sonst nichts gab, was multiple logins zur gleichen Zeit verursacht, dann hatte die FB wohl mal kein Bock auf das login. Beim nächsten Poll ging es halt wieder.
Evtl. hab ich noch ne Idee wie ich den Treiber umbaue.

**Comment by foxthefox** [comment]
habe jetzt eine neue Version 2.2.0 erstellt, es kann gern getestet werden
Der Adapter hat solange er läuft eine Verbindung, die API zur FB ist nunmehr geändert.
Alle Kommandos greifen auf die gleiche Session zu.

**Comment by TepMan** [comment]
Hi @foxthefox , hat die irgendwelche Breaking Changes oder gibt's sonst was zu beachten bei der Version?

Guten Rutsch!

**Comment by foxthefox** [comment]
diesmal keine breaking changes, Datenpunkte bleiben gleich.
Ist vornehmlich Kommunikationsverbesserung

**Comment by TepMan** [comment]
Bin gearde etwas ratlos. Habe den Adapter via npm install https://github.com/foxthefox/ioBroker.fritzdect/tarball/master --production installiert und den ioBroker per restart-Kommando durchgestartet. NPM sagt, die 2.2.1 wurde installiert, im node_moduls liegt lt. pacckage-json auch die 2,.2.1. Der Instanzen-Tab und der Adapter-Tab zeigen aber nach wie vor die 2.1.15 an...

**Comment by TepMan** [comment]
> Bin gearde etwas ratlos. Habe den Adapter via npm install https://github.com/foxthefox/ioBroker.fritzdect/tarball/master --production installiert und den ioBroker per restart-Kommando durchgestartet. NPM sagt, die 2.2.1 wurde installiert, im node_moduls liegt lt. pacckage-json auch die 2,.2.1. Der Instanzen-Tab und der Adapter-Tab zeigen aber nach wie vor die 2.1.15 an...

Der Adapter-Tab zeigt jetzt die 2.2.1 an, die Instanz behauptet aber weiter, siehe wäre eine 2.1.15.

**Comment by foxthefox** [comment]
also 2.2.1 ist aktuell auf github
warum es noch 2.1.5 nach der Installation sein sollte, erschließt sich mir nicht
aber da gab es einen iobroker-befehl (update oder upgrade) der so etwas richten könnte,

**Comment by TepMan** [comment]
iobroker update zeitg ein merkwürdiges Eregebnis:

`Adapter    "fritzdect"     : 2.1.15   , installed 2.2.1`

Kann es sein, das die 2.2.1 irgendwo noch die alte Versionsnummer zurückmeldet?

**Comment by TepMan** [comment]
> iobroker update zeitg ein merkwürdiges Eregebnis:
> 
> `Adapter "fritzdect" : 2.1.15 , installed 2.2.1`
> 
> Kann es sein, das die 2.2.1 irgendwo noch die alte Versionsnummer zurückmeldet?

Ah, warte, kann es sein, das da die 2.1.15 steht, weil das die Release-Version ist? Vielleicht zeigt der Instanzen-Tab das auch nur einfach falsch an? Ich würde die Version so jetzt erstmal laufen lassen und gucken, ob das ursprüngliche Problem noch auftritt.

**Comment by TepMan** [comment]
Und nochmal ich: Im Log sagt der Adapter auch, er sit 2.2.1. Scheint also tatsächlich ein Anzeige-Problem im Instanzen-Tab zu sein.

**Comment by foxthefox** [comment]
> > iobroker update zeitg ein merkwürdiges Eregebnis:
> > `Adapter "fritzdect" : 2.1.15 , installed 2.2.1`
> > Kann es sein, das die 2.2.1 irgendwo noch die alte Versionsnummer zurückmeldet?
> 
> Ah, warte, kann es sein, das da die 2.1.15 steht, weil das die Release-Version ist? Vielleicht zeigt der Instanzen-Tab das auch nur einfach falsch an? Ich würde die Version so jetzt erstmal laufen lassen und gucken, ob das ursprüngliche Problem noch auftritt.

Bei der Adapterauflistung sollte zwischen verfügbar und installiert unterschieden sein und bei den Instanzen sollte es die installierte Version sein.
Ich kann nur in package.json und io-broker.json die Version eintragen (muß gleich sein). Und da steht die 2.2.1.

Dann beobachte mal bitte.

**Comment by TepMan** [comment]
Hi, die neue Version läuft jetzt seit 7 Tagen ohne das der Login-Fehler noch einmal aufgetreten ist. Das Problem scheint gelöst zu sein. Imho kann das Issue hier geschlossen werden. @foxthefox vielen Dank!

**Comment by foxthefox** [comment]
Danke fürs testen.
