### ISSUE TITLE
Wrong display of windowopenactive for group member in FritzBox / Problem with tr-064-4.2.4

### ISSUE THREAD

**Issue by testit2020** [foxthefox/ioBroker.fritzdect#120]
Setz man den Wert **fritzdect.0.DECT_.windowopenactiv** manuell auf true so wird in FritzBox/SmartHome/Geräteverwaltung **alle Geräte zur Gruppe** mit "Window open" angezeigt:

![image](https://user-images.githubusercontent.com/68483974/107186000-bfb90b00-69e3-11eb-9528-83a47e021461.png)

![image](https://user-images.githubusercontent.com/68483974/107186163-0a3a8780-69e4-11eb-8af8-763b320b8cee.png)
***
Fenster-Erkennung-**Ventil geschlossen für-Zeit** wird nicht berücksichtigt bei Berechnung für **windowopenactiveendtime**:

![image](https://user-images.githubusercontent.com/68483974/107186380-73ba9600-69e4-11eb-928f-036497246809.png)

Es wird standardmäßig eine Zeit von 5 Minuten angesetzt und entsprechend in den DP eingetragen.

***
Mit **Version 4.2.4 vom Adapter TR-064** funktioniert der fritzdect-Adapter nicht mehr. Installiert man die Version von tr-064 so meldet der fritzdect -Adapter, dass er sich nicht mehr anmelden kann.

2021-02-06 00:43:15.403 - error: fritzdect.0 (14370) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}

2021-02-06 00:43:15.403 - error: fritzdect.0 (14370) no response part in returned message

**Comment by Ilovegym66** [comment]
bei mir funktioniert TR-064 V4.2.4 und Fritzdect 2.1.7 einwandfrei miteinander, dazu mischt sogar noch fb-checkpresence an der Fritzbox mit. 
Wichtig: alle 3 Adaptern habe ich eigene Useraccounts eingerichtet!
Polling nicht so kurz einstellen!

**Comment by testit2020** [comment]
Bzgl tr-064 4.2.4 habe ich jetzt mal einen neuen User angelegt:
![image](https://user-images.githubusercontent.com/68483974/107223668-c3b25080-6a16-11eb-81af-d986726757fe.png)
Trotzdem kommt die Fehlermeldung, jetzt auch schon mit tr-064 4.2.3:

fritzdect.0 | 2021-02-08 14:02:39.961 | error | (27982) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-02-08 14:02:39.959 | error | (27982) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}

Nur mit dem admin User und admin-PW kommt der fritzdect noch an die Daten

**Comment by foxthefox** [comment]
> Setz man den Wert **fritzdect.0.DECT_.windowopenactiv** manuell auf true so wird in FritzBox/SmartHome/Geräteverwaltung **alle Geräte zur Gruppe** mit "Window open" angezeigt:
> 

hier hätte ich die Bitte den adapter in den debug Modus zu versetzen und die Aktion nochmals zu wiederholen.
Dazu müsste es im log einen Eintrag geben, daß es sich um ein Befehl gehandelt hat und mit welcher DECT_ID dies passiert. Hier sollte die ID des Thermostat erkannt sein.
Ich vermute eher, daß bei der FB ein Mechanismus greift, der die ganze Gruppe auf windowopen setzt, wenn ein Thermostat es erkannt hat. Und so ganz falsch kann es ja bei 2 Heizkörpern im gleichen Raum nicht sein.
Bitte dies mal durchprobieren.

**Comment by foxthefox** [comment]
> Mit **Version 4.2.4 vom Adapter TR-064** funktioniert der fritzdect-Adapter nicht mehr. Installiert man die Version von tr-064 so meldet der fritzdect -Adapter, dass er sich nicht mehr anmelden kann.
> 
> 2021-02-06 00:43:15.403 - error: fritzdect.0 (14370) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}
> 
> 2021-02-06 00:43:15.403 - error: fritzdect.0 (14370) no response part in returned message

evtl. liegt es ja auch am tr-064 Adapter und nicht am fritzdect :-)
fritzdect ist da ggf. nur der gebeutelte von beiden.

Welche FB-Version ist es denn? und welche Version von fritzdect?

**Comment by testit2020** [comment]
debug Modus aktiviert:

fritzdect.0 | 2021-02-08 21:25:09.925 | debug | (15100) state fritzdect.0.DECT_119610832808.windowopenactiveendtime changed: 2021-02-08T20:30:09.000Z (ack = true)
-- | -- | -- | --
fritzdect.0 | 2021-02-08 21:25:09.919 | debug | (15100) state fritzdect.0.DECT_119610832808.windowopenactiv changed: true (ack = true)
fritzdect.0 | 2021-02-08 21:25:09.911 | debug | (15100) Set thermostat windowopen 119610832808 to true until calculated 1612816209 Mon Feb 08 2021 21:30:09 GMT+0100 (GMT+01:00)
fritzdect.0 | 2021-02-08 21:25:09.910 | debug | (15100) window 1612816209 reading to Mon Feb 08 2021 21:30:09 GMT+0100 (GMT+01:00)
fritzdect.0 | 2021-02-08 21:25:09.728 | debug | (15100) unix 1612816209 real Mon Feb 08 2021 21:30:09 GMT+0100 (GMT+01:00)
fritzdect.0 | 2021-02-08 21:25:09.720 | info | (15100) DECT ID: 119610832808 identified for command (windowopenactiv) : true
fritzdect.0 | 2021-02-08 21:25:09.719 | debug | (15100) ack is not set! -> command
fritzdect.0 | 2021-02-08 21:25:09.718 | debug | (15100) state fritzdect.0.DECT_119610832808.windowopenactiv changed: true (ack = false)



>Welche FB-Version ist es denn? und welche Version von fritzdect?
FritzBox 6591 v7.22

**Comment by testit2020** [comment]
Nochmal mit dem neuen User (nicht admin) versucht ergibt:

fritzdect.0 | 2021-02-08 22:08:24.033 | error | (23064) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-02-08 22:08:24.032 | error | (23064) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}
fritzdect.0 | 2021-02-08 22:08:19.909 | debug | (23064) updating Devices / Groups
fritzdect.0 | 2021-02-08 22:08:19.908 | debug | (23064) __________________________
fritzdect.0 | 2021-02-08 22:08:19.907 | error | (23064) no response part in returned message
fritzdect.0 | 2021-02-08 22:08:19.905 | error | (23064) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}
fritzdect.0 | 2021-02-08 22:08:17.783 | error | (23064) no response part in returned message
fritzdect.0 | 2021-02-08 22:08:17.782 | error | (23064) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}
fritzdect.0 | 2021-02-08 22:08:17.588 | info | (23064) fritzdect entered ready
fritzdect.0 | 2021-02-08 22:08:17.547 | info | (23064) starting. Version 2.1.7 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v12.20.1, js-controller: 3.1.6
fritzdect.0 | 2021-02-08 22:08:16.920 | debug | (23064) statesDB connected
fritzdect.0 | 2021-02-08 22:08:16.919 | debug | (23064) States connected to redis: 0.0.0.0:9000
fritzdect.0 | 2021-02-08 22:08:16.900 | debug | (23064) States create System PubSub Client
fritzdect.0 | 2021-02-08 22:08:16.897 | debug | (23064) States create User PubSub Client
fritzdect.0 | 2021-02-08 22:08:16.884 | debug | (23064) Redis States: Use Redis connection: 0.0.0.0:9000
fritzdect.0 | 2021-02-08 22:08:16.882 | debug | (23064) objectDB connected
fritzdect.0 | 2021-02-08 22:08:16.875 | debug | (23064) Objects connected to redis: 0.0.0.0:9001
fritzdect.0 | 2021-02-08 22:08:16.851 | debug | (23064) Objects client initialize lua scripts
fritzdect.0 | 2021-02-08 22:08:16.849 | debug | (23064) Objects create User PubSub Client
fritzdect.0 | 2021-02-08 22:08:16.848 | debug | (23064) Objects create System PubSub Client
fritzdect.0 | 2021-02-08 22:08:16.844 | debug | (23064) Objects client ready ... initialize now
fritzdect.0 | 2021-02-08 22:08:16.804 | debug | (23064) Redis Objects: Use Redis connection: 0.0.0.0:9001

**Comment by testit2020** [comment]
Mit dem ADMIN gibt es usw jede Menge create datapoint :

fritzdect.0 | 2021-02-08 22:11:06.711 | info | (23671) CREATE Devices 5
-- | -- | -- | --
fritzdect.0 | 2021-02-08 22:11:06.710 | debug | (23671) [{"identifier":"11961 0834192","id":"16","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"WZ_RECHTS","battery":"30
fritzdect.0 | 2021-02-08 22:11:06.709 | debug | (23671) devices
fritzdect.0 | 2021-02-08 22:11:06.468 | info | (23671) fritzdect entered ready
fritzdect.0 | 2021-02-08 22:11:06.439 | info | (23671) starting. Version 2.1.7 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v12.20.1, js-controller: 3.1.6

**Comment by foxthefox** [comment]
Ich gehe mal davon aus, daß 119610832808 ein Thermostat ist, an dem das windowopenactiv gesetzt wurde.
Richtig?
Wenn nun die Gruppe gesetzt wurde, dann hat das die FB gemacht.

**Comment by testit2020** [comment]
Ja richtig. ok. Bleibt nur der Punkt mit der Anmeldung.

**Comment by foxthefox** [comment]
So wie es aussieht, ist der neue User wirklich nicht berechtigt. Nach dem Starten des Adapters sollte ein login möglich sein. Selbst wenn das polling zu kurz wäre, dann käme die Blockierung erst nach dem Start des Adapters.

Der neue User hat auch die entsprechenden Berechtigungen ?
Gibt es Sonderzeichen im Passwort? Mir ist zwar dahingehend nichts bekannt, aber wäre ggf. eine Ursache.

**Comment by testit2020** [comment]
Die Berechtigungen habe ich oben angezeigt. Muss er noch mehr haben?
tr-064, neuen Benutzer genutzt in fritzdect

  |   |   |  
-- | -- | -- | --
fritzdect.0 | 2021-02-08 22:28:59.558 | error | (26887) no response part in returned message
fritzdect.0 | 2021-02-08 22:28:59.556 | error | (26887) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}
fritzdect.0 | 2021-02-08 22:28:55.439 | debug | (26887) updating Devices / Groups
fritzdect.0 | 2021-02-08 22:28:55.438 | debug | (26887) __________________________
fritzdect.0 | 2021-02-08 22:28:55.437 | error | (26887) no response part in returned message
fritzdect.0 | 2021-02-08 22:28:55.436 | error | (26887) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}
fritzdect.0 | 2021-02-08 22:28:53.322 | error | (26887) no response part in returned message
fritzdect.0 | 2021-02-08 22:28:53.321 | error | (26887) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}
fritzdect.0 | 2021-02-08 22:28:53.139 | info | (26887) fritzdect entered ready
fritzdect.0 | 2021-02-08 22:28:53.110 | info | (26887) starting. Version 2.1.7 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v12.20.1, js-controller: 3.1.6

**Comment by foxthefox** [comment]
SmartHome sollte schon ausreichen, wenn alles im adapterconfig richtig geschrieben ist, sollte es eigentlich funktionieren

**Comment by testit2020** [comment]
Habe das PW nochmal geändert und kopiert in den Adapter geschrieben. Gleiches Problem.

**Comment by testit2020** [comment]
Ich lösch mal den Adapter und installiere in neu. Mal schauen. Melde mich.

**Comment by foxthefox** [comment]
In der Version 2.1.10 hatte ich schon den benutzten User mit dazugebt, ich sollte wohl mal auch noch das PW mit einem Schalter aus dem config im debug log sichtbar machen. Um da jedwede Dinge ausschließen zu können.

**Comment by foxthefox** [comment]
du könntest auch mal im log der FB nachschauen, was dort so drin steht.

**Comment by testit2020** [comment]
Also habe jetzt komplett neu installiert. Gleiches Problem. tr-064 weiter auf Pause.
FB:
![image](https://user-images.githubusercontent.com/68483974/107286035-55927b80-6a60-11eb-9c20-b64ca399c03a.png)

**Comment by testit2020** [comment]
Installiere jetzt die neueste Version von fritzdect.

**Comment by testit2020** [comment]
Ergebnis:

fritzdect.0 | 2021-02-08 22:55:26.949 | info | (31866) creating devices/groups finished
-- | -- | -- | --
fritzdect.0 | 2021-02-08 22:55:26.948 | error | (31866) no response part in returned message
fritzdect.0 | 2021-02-08 22:55:26.947 | error | (31866) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}


fritzdect.0 | 2021-02-08 22:55:07.783 | info | (31866) fritzdect uses USER: fritzdect
-- | -- | -- | --
fritzdect.0 | 2021-02-08 22:55:07.741 | info | (31866) fritzdect entered ready
fritzdect.0 | 2021-02-08 22:55:07.697 | info | (31866) starting. Version 2.1.10 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v12.20.1, js-controller: 3.1.6

**Comment by testit2020** [comment]
Habe jetzt dem User fritzdect dasselbe PW gegeben wie dem ADMIN und es läuft.

**Comment by testit2020** [comment]
In der neuen Version fällt mir auf ist die fritzdect.0.DECT_119610832808.windowopenactivetime geändert worden steht jetzt eine Zahl.
Kann man den Wert nicht aus der Fritzbox auslesen?
![image](https://user-images.githubusercontent.com/68483974/107287898-ed916480-6a62-11eb-8157-f30a30dc9cc7.png)

**Comment by foxthefox** [comment]
> In der neuen Version fällt mir auf ist die fritzdect.0.DECT_119610832808.windowopenactivetime geändert worden steht jetzt eine Zahl.
> Kann man den Wert nicht aus der Fritzbox auslesen?
> ![image](https://user-images.githubusercontent.com/68483974/107287898-ed916480-6a62-11eb-8157-f30a30dc9cc7.png)

für den Adapter wird der Endzeitpunkt zurückgelesen und das steht auch im gleichnamigen Datenpunkt

**Comment by foxthefox** [comment]
> Habe jetzt dem User fritzdect dasselbe PW gegeben wie dem ADMIN und es läuft.

Das ist mehr als merkwürdig.

Ich baue auf jeden Fall mal die debug Ausgabe für das PW ein.

Eine weitere Bitte:
Falls raspberry, befindet sich im Pfad
/opt/iobroker/node_modules/iobroker.fritzdect/docs/de

die Referenzimplementierung von AVM.

dazu müsstest du python3 fritz.py "http://adresseFB" "USER" "PW"
eingeben.
Wenn USER und PW akzeptiert kommt: "Successful login ..."
Dies bitte mit dem fritzdect und neuem PW probieren.

Falls es nicht raspberry ist, ist natürlich das Verzeichnis ggf. anders.

**Comment by testit2020** [comment]
Es kommt kein Successful login:

pi@raspberrypi:/opt/iobroker/node_modules/iobroker.fritzdect/docs/de $ python3 fritz.py fritzdect fritzdect1234
Usage: fritz.py http://fritz.box user pass

**Comment by testit2020** [comment]
>für den Adapter wird der Endzeitpunkt zurückgelesen und das steht auch im gleichnamigen Datenpunkt

Wird fritzdect.0.DECT_119610832808.windowopenactiv auf true gesetzt, so wird die fritzdect.0.DECT_119610832808.windowopenactiveendtime gesetzt. 
![image](https://user-images.githubusercontent.com/68483974/107375739-5c190580-6ae9-11eb-8572-17cab9c16fe0.png)

Mit der Zeit die in fritzdect.0.DECT_119610832808.windowopenactivetime steht.
![image](https://user-images.githubusercontent.com/68483974/107375805-6d621200-6ae9-11eb-9d94-833a7ce5d327.png)

![image](https://user-images.githubusercontent.com/68483974/107375413-02b0d680-6ae9-11eb-95b8-3d1a9931e9be.png)

Da wird nichts zurückgelesen? Der Wert 5 min kommt nicht aus der FB.

**Comment by foxthefox** [comment]
Sehr komisch.
Aus meiner Sicht ist es wohl dann weniger ein Problem des Adapters. Wenn das Login auf dem python Weg nicht geht, dann wird's im Adapter nicht besser, immerhin die der gleiche Mechanismus.
Kann sich der neue Nutzer denn über die Weboberfläche anmelden?

**Comment by testit2020** [comment]
![image](https://user-images.githubusercontent.com/68483974/107403283-3994e580-6b05-11eb-8a6a-f16964415232.png)
Da kann ich keinen User angeben.

**Comment by testit2020** [comment]
Bleibt nur noch das Thema mit den WindowOpen Zeiten, 5 Minuten im Adapter, 10 Minuten in der FritzBox.
Wobei bei Aktivierung die 5 Minuten gesetzt werden.

**Comment by foxthefox** [comment]
Betrifft die 5min Öffnung:
Im Adapter werden die 5min auf die aktuelle Zeit addiert.
Diese Zeit wird beim übermitteln an die FB geschickt.
Wenn die Übernahme an der FB erfolgreich war, dann meldet sie die Endzeit zurück.
Diese wird dann unter windowopanactiveendtime geschrieben.

Nachzuverfolgen ist dies im debug-log.
... unix "TimestampINCL5min" real "Zeit" -> die Zeit die im Adapter ermittelt wird
... window "TimestampDerFB" reading to "Zeit" -> zurückgelesene Zeit aus der FB
die beiden Zeitstempel könnten evtl. differieren

**Comment by foxthefox** [comment]
> Bleibt nur noch das Thema mit den WindowOpen Zeiten, 5 Minuten im Adapter, 10 Minuten in der FritzBox.
> Wobei bei Aktivierung die 5 Minuten gesetzt werden.
> Zum Thema Anmeldung, kannst du das aus dem Adapter heraus prüfen ob die Version "Anmeldung mit User und Kennwort" eingeschaltet ist?
> https://avm.de/service/schnittstellen/
> Änderung ab 7.25


Das geänderte Anmeldeverfahren habe ich schon umgesetzt mit der Version 2.1.x
Was ist jetzt das Resultat.
- das Häkchen für Webanmeldung gesetzt
- der neue Benutzer mit eigenem PW lässt sich in Weboberfläche einloggen
- mit Python als auch mit fritzdect ist ein login des neuen Benutzers möglich
- adapter läuft
-???

**Comment by testit2020** [comment]
Soweit gut. Können wir dann schließen.
