### ISSUE TITLE
adapter 2.1.7 - plötzlicher absturz

### ISSUE THREAD

**Issue by sokrates-sith** [foxthefox/ioBroker.fritzdect#121]
hallo, seit heute nacht bricht der adapter plötzlich mit folgender fehlermeldung ab:

fritzdect.0 | 2021-02-12 09:15:25.733 | error | (5025) Cannot read property '1' of null -- | -- | -- | --
fritzdect.0 | 2021-02-12 09:15:25.733 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
fritzdect.0 | 2021-02-12 09:15:25.733 | error | at endReadableNT (_stream_readable.js:1241:12)
fritzdect.0 | 2021-02-12 09:15:25.733 | error | at IncomingMessage.emit (events.js:326:22)
fritzdect.0 | 2021-02-12 09:15:25.733 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/@root/request/index.js:182:17)
fritzdect.0 | 2021-02-12 09:15:25.733 | error | at /opt/iobroker/node_modules/iobroker.fritzdect/lib/fritzhttp.js:389:76
fritzdect.0 | 2021-02-12 09:15:25.733 | error | (5025) TypeError: Cannot read property '1' of null
fritzdect.0 | 2021-02-12 09:15:25.731 | error | (5025) uncaught exception: Cannot read property '1' of null

mein aktueller js-controller: 3.2.16

kann es sein, dass er hier probleme mit den versionen gibt?

**Comment by foxthefox** [comment]
Das weiß ich leider nicht, ob es mit js-controller Probleme gibt. Keine Ahnung was da alles gebaut wird.
Die Fehlermeldung ist eher auf die Kommunikation mit der FB zuzuschreiben.
Ist die FW der FB kürzlich hochgerüstet worden?
Was sagt das log in der FB?
Läuft der Adapter? Ist das ein dauerhafter Zustand?

**Comment by sokrates-sith** [comment]
hm... ich schau mal. vielleicht hat vodafon da im hintergrund rumgepfuscht. 
ich hab den adapter mal deinstalliert und werde ihn heute abend neu installieren. bin gespannt.

**Comment by sokrates-sith** [comment]
after the new installation everything is running fine (y) 
thanks for your support :)
