### ISSUE TITLE
Adapterfunktion

### ISSUE THREAD

**Issue by Schmusekater76** [foxthefox/ioBroker.fritzdect#122]
Wird noch die Funktion der neuen Templates mit rein genommen?

Gemeint ist damit, das man ja jetzt über ein Template die Telefone klingeln lassen kann.

Es wäre echt genial, wenn das mit übernommen würde.

LG Matze

**Comment by Ilovegym66** [comment]
OH ja, das wäre prima! Habs gerade mal getestet, erkennt der Adapter leider nicht automatisch.
@foxthefox brauchst du ein debug-log?

**Comment by foxthefox** [comment]
Bin grad überfragt, welche Templates gemeint sind.
Ja, ich bräuchte eine debug log (Meine Templates, ggf. auch Meine Geräte)

**Comment by Ilovegym66** [comment]
Hi, wir meinen die neuen Templates für die Telefonie, ist in der aktuellen Beta für die 7590 drin, ist mir auch nicht gleich aufgefallen. Du siehst in den Templates eine neue Aktion [{"identifier":"tmp7A1AB5-3C1F5CDF1","id":"60106","functionbitmask":"0","applymask":["256",{"dialhelper":""}],"name":"FritzFonAppBernd","devices":""},
diese kann interne oder externe Nummern wählen, hier wird mein Handy mit der FritzFon-App angerufen und klingeln lassen.
Gut wenn jemand an der Tür ist etc.. 

Hier mal meine Geräte:
`[{"identifier":"11959 0824920","id":"17","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Wohnzimmer DG","battery":"80","batterylow":"0","temperature":{"celsius":"225","offset":"0"},"hkr":{"tist":"45","tsoll":"44","absenk":"36","komfort":"44","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1613944800","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11960 0089920","id":"18","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Büro DG","battery":"80","batterylow":"0","temperature":{"celsius":"225","offset":"0"},"hkr":{"tist":"45","tsoll":"44","absenk":"36","komfort":"44","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1613944800","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11959 0824888","id":"19","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Flur oben DG","battery":"80","batterylow":"0","temperature":{"celsius":"225","offset":"0"},"hkr":{"tist":"45","tsoll":"44","absenk":"36","komfort":"44","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1613944800","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11960 0189000","id":"20","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Bad DG","battery":"80","batterylow":"0","temperature":{"celsius":"215","offset":"0"},"hkr":{"tist":"43","tsoll":"42","absenk":"36","komfort":"42","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1613934000","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11960 0189312","id":"21","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Küche DG","battery":"60","batterylow":"0","temperature":{"celsius":"225","offset":"0"},"hkr":{"tist":"45","tsoll":"44","absenk":"36","komfort":"44","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"60","nextchange":{"endperiod":"1613944800","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11960 0090480","id":"22","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Flur unten OG","battery":"80","batterylow":"0","temperature":{"celsius":"220","offset":"0"},"hkr":{"tist":"44","tsoll":"44","absenk":"36","komfort":"44","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1613944800","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11960 0090160","id":"23","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Bad OG Bernd","battery":"80","batterylow":"0","temperature":{"celsius":"205","offset":"0"},"hkr":{"tist":"41","tsoll":"36","absenk":"36","komfort":"46","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1613962800","tchange":"46"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11960 0189512","id":"24","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Schlafzimmer OG Bernd","battery":"80","batterylow":"0","temperature":{"celsius":"175","offset":"0"},"hkr":{"tist":"35","tsoll":"30","absenk":"36","komfort":"44","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1613930400","tchange":"44"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11961 0287536","id":"25","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Büro OG","battery":"80","batterylow":"0","temperature":{"celsius":"180","offset":"0"},"hkr":{"tist":"36","tsoll":"34","absenk":"34","komfort":"42","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"0","tchange":"42"},"summeractive":"0","holidayactive":"0"}},{"identifier":"13356 0953248","id":"26","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Gast OG","battery":"70","batterylow":"0","temperature":{"celsius":"220","offset":"0"},"hkr":{"tist":"44","tsoll":"42","absenk":"34","komfort":"42","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"70","nextchange":{"endperiod":"1613941200","tchange":"34"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11960 1017160","id":"27","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Eingang Haustür","battery":"40","batterylow":"0","temperature":{"celsius":"175","offset":"0"},"hkr":{"tist":"35","tsoll":"34","absenk":"28","komfort":"34","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"40","nextchange":{"endperiod":"1613934000","tchange":"28"},"summeractive":"0","holidayactive":"0"}},{"identifier":"13356 0969552","id":"28","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Küche EG","battery":"60","batterylow":"0","temperature":{"celsius":"235","offset":"0"},"hkr":{"tist":"47","tsoll":"46","absenk":"36","komfort":"46","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"60","nextchange":{"endperiod":"1613939400","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"13356 0968304","id":"29","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Büro EG","battery":"70","batterylow":"0","temperature":{"celsius":"235","offset":"0"},"hkr":{"tist":"47","tsoll":"46","absenk":"36","komfort":"46","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"70","nextchange":{"endperiod":"1613939400","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11963 0520976","id":"30","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Wohnzimmer EG vorne","battery":"70","batterylow":"0","temperature":{"celsius":"225","offset":"0"},"hkr":{"tist":"45","tsoll":"44","absenk":"38","komfort":"44","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"70","nextchange":{"endperiod":"1613939400","tchange":"38"},"summeractive":"0","holidayactive":"0"}},{"identifier":"13356 0185360","id":"31","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Wohnzimmer EG hinten","battery":"60","batterylow":"0","temperature":{"celsius":"220","offset":"0"},"hkr":{"tist":"44","tsoll":"44","absenk":"38","komfort":"44","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"60","nextchange":{"endperiod":"1613939400","tchange":"38"},"summeractive":"0","holidayactive":"0"}},{"identifier":"14079 0328920","id":"32","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Bad OG Treppenhaus","battery":"80","batterylow":"0","temperature":{"celsius":"215","offset":"0"},"hkr":{"tist":"43","tsoll":"42","absenk":"34","komfort":"42","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1613941200","tchange":"34"},"summeractive":"0","holidayactive":"0"}},{"identifier":"09995 0608747","id":"33","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FRITZ!DECT 440 Marianne","battery":"100","batterylow":"0","temperature":{"celsius":"210","offset":"0"},"humidity":{"rel_humidity":"41"},"button":[{"identifier":"09995 0608747-1","id":"5000","name":"FRITZ!DECT 440 Marianne: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0608747-3","id":"5001","name":"FRITZ!DECT 440 Marianne: Unten rechts","lastpressedtimestamp":""},{"identifier":"09995 0608747-5","id":"5002","name":"FRITZ!DECT 440 Marianne: Unten links","lastpressedtimestamp":""},{"identifier":"09995 0608747-7","id":"5003","name":"FRITZ!DECT 440 Marianne: Oben links","lastpressedtimestamp":""}]},{"identifier":"09995 0612915","id":"34","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FRITZ!DECT 440 Gast","battery":"100","batterylow":"0","temperature":{"celsius":"190","offset":"0"},"humidity":{"rel_humidity":"54"},"button":[{"identifier":"09995 0612915-1","id":"5004","name":"FRITZ!DECT 440 Gast: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0612915-3","id":"5005","name":"FRITZ!DECT 440 Gast: Unten rechts","lastpressedtimestamp":""},{"identifier":"09995 0612915-5","id":"5006","name":"FRITZ!DECT 440 Gast: Unten links","lastpressedtimestamp":""},{"identifier":"09995 0612915-7","id":"5007","name":"FRITZ!DECT 440 Gast: Oben links","lastpressedtimestamp":""}]}]`

Hier das wichtigste, die Templates:
`[{"identifier":"tmp7A1AB5-3C1F5CDF1","id":"60106","functionbitmask":"0","applymask":["256",{"dialhelper":""}],"name":"FritzFonAppBernd","devices":""},{"identifier":"tmp7A1AB5-3BFDC48DB","id":"60005","functionbitmask":"4160","applymask":["4",{"hkr_temperature":""}],"name":"Gast Heizung AUS","devices":{"device":{"identifier":"grp7A1AB5-3BFDC427C"}}},{"identifier":"tmp7A1AB5-3BFDC46E9","id":"60006","functionbitmask":"4160","applymask":["4",{"hkr_temperature":""}],"name":"Gast Heizung EIN","devices":{"device":{"identifier":"grp7A1AB5-3BFDC427C"}}},{"identifier":"tmp7A1AB5-3B25E4FEB","id":"60002","functionbitmask":"4160","applymask":["4",{"hkr_temperature":""}],"name":"Heizung aus Bernd","devices":{"device":{"identifier":"grp7A1AB5-3B598D28A"}}},{"identifier":"tmp7A1AB5-3B29E8AB1","id":"60001","functionbitmask":"4160","applymask":["4",{"hkr_temperature":""}],"name":"Heizung aus EG","devices":{"device":{"identifier":"grp7A1AB5-3B5E8CC62"}}},{"identifier":"tmp7A1AB5-3BFA9E5FE","id":"60003","functionbitmask":"4160","applymask":["4",{"hkr_temperature":""}],"name":"Heizung ein Bernd","devices":{"device":{"identifier":"grp7A1AB5-3B598D28A"}}},{"identifier":"tmp7A1AB5-3BFA9E871","id":"60004","functionbitmask":"4160","applymask":["4",{"hkr_temperature":""}],"name":"Heizung ein EG","devices":{"device":{"identifier":"grp7A1AB5-3B5E8CC62"}}}]1`

**Comment by foxthefox** [comment]
Super das hilft weiter

**Comment by foxthefox** [comment]
ihr könntet es mal mit der Version 2.1.11 versuchen, ob das template nun angelegt wird

**Comment by Ilovegym66** [comment]
Super, laeuft !! Dankeschoen !!
Keine Fehler.
