### ISSUE TITLE
Keine Temperaturwerte aus Fritz!DECT 440 Taster und definierter Gruppe

### ISSUE THREAD

**Issue by chris-nacho** [foxthefox/ioBroker.fritzdect#123]
Hallo liebe Community,

leider kann ich über den Fritz!DECT 440 4-fach Taster inkl. Temperatursensor keine Temperatur auslesen und einbinden.
Das Einzige, was ich abfragen kann sind die 4 Tasten, aber keine IST-Temperatur (Screenshot).

Die DECT-Heizkörperthermostate und DECT-Steckdosen geben problemlos die Temperatur zurück.

Ich nutze bei zwei Thermostaten den DECT 440 als externen Temperatursensor und habe diese in eine Gruppe zusammengefasst.
Bei dieser Gruppe kann ich auch nicht die IST-Temperatur auslesen (Screenshot).

Ist es ein Bug oder kommt das noch mit einem Update?

Vielen Dank schon Mal und viele Grüße
chris-nacho

[fritzdect_groups.log](https://github.com/foxthefox/ioBroker.fritzdect/files/6029923/fritzdect_groups.log)
[fritzdect_mydevices.log](https://github.com/foxthefox/ioBroker.fritzdect/files/6029924/fritzdect_mydevices.log)
![fritzdect_objects](https://user-images.githubusercontent.com/79527778/108866831-dae76580-75f4-11eb-8c1c-4b66daf608db.png)

**Comment by Ilovegym66** [comment]
Hi, welche Version vom Adapter benutzt du? Bei mir funktioniert der 440 einwandfrei, Temp wird angezeigt.
Bei einer Gruppe eine Temp auslesen, welche denn? Denke das ist nicht im Sinne des Erfinders.. :-)

Hier der 440:
![grafik](https://user-images.githubusercontent.com/36229898/108871255-416e8280-75f9-11eb-8fee-f7428865632b.png)

**Comment by chris-nacho** [comment]
Hi,

ich habe die 0.2.4 und es gibt keine neuere Version für mich zum updaten.

Danke und Gruß
![Adapter](https://user-images.githubusercontent.com/79527778/108897214-252d0e80-7616-11eb-894a-a0a539972a97.png)

**Comment by foxthefox** [comment]
Ich denke mit einer 2.1.11 aus GitHub wärst du gut bedient. Da ist dann auch DECT440 richtig drin. So wurde nur die Kennung von Buttons erkannt.

**Comment by foxthefox** [comment]
> Bei dieser Gruppe kann ich auch nicht die IST-Temperatur auslesen (Screenshot).

allerdings ist in dem  fritzdect_groups.log auch kein Wert für tist drin. Wo FB nix sendet kann ich auch nix erfinden.

 
> Ist es ein Bug oder kommt das noch mit einem Update?
> Update ist schon da

**Comment by chris-nacho** [comment]
So, habe jetzt die Version 2.1.11 aus GitHub installiert und voilà, es tut :-)

Vielen Dank für den Hinweis. Dann kann ich den Issue schließen.

Schönen Abend und danke für die Unterstützung
