### ISSUE TITLE
State "fritzdect.0.Hgroup_grp3474F0-3BD062165.temp" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by Kludi2019** [foxthefox/ioBroker.fritzdect#124]
Hallo Foxthefox,

mit dem Update auf 0.2.4 gibt es die obige Warnmeldung für zusammengefasste Heizkörperventile aus einer Gruppe.  Mache ich da etwas falsch oder fehlt noch etwas? Bei der vorherigen Version hat das problemlos funktioniert.

Vielleicht hast Du eine Idee, wo der Fehler liegt.....

Gruß und danke
Gerhard

**Comment by foxthefox** [comment]
Hallo Gerhard,

die Version 2.1.11 wäre die aktuelle (hat ein paar breaking changes, sind aber in der README beschrieben).
Da sollte es diesen Fehler nicht mehr geben.

Gruß
Klaus

**Comment by Kludi2019** [comment]
Hallo Klaus, 
vielen Dank für die schnelle Antwort. Ich werde das Morgen gleich mal ausprobieren. 

Gruß Gerhard
