### ISSUE TITLE
FritzDECT 200 dont switch on/off

### ISSUE THREAD

**Issue by Jackiiiii** [foxthefox/ioBroker.fritzdect#13]
My DECT 200 does not switch off or on
iobroker have all stats of the DECT 200 like temp or is it off or on but if i change any Valve it do nothing not even when i tell alexa... 

The Console says:

fritzdect.0 | 2017-10-29 13:36:42.184 | info | SWITCH ID: 087617891997 identified for command : true
-- | -- | -- | --
fritzdect.0 | 2017-10-29 13:31:05.301 | info | no thermostats found
fritzdect.0 | 2017-10-29 13:31:04.987 | info | setting up switch object 087617891997 
fritzdect.0 | 2017-10-29 13:31:04.982 | info | Switches AIDs: 087617891997 
fritzdect.0 | 2017-10-29 13:31:02.614 | info | entered ready
fritzdect.0 | 2017-10-29 13:31:02.574 | info | starting. Version 0.0.9 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v6.11.5
host.wd | 2017-10-29 13:30:57.968 | info | instance system.adapter.fritzdect.0 started with pid 15142
host.wd | 2017-10-29 13:30:57.943 | info | object change system.adapter.fritzdect.0
host.wd | 2017-10-29 13:30:41.957 | info | Restart adapter system.adapter.fritzdect.0 because enabled

**Comment by foxthefox** [comment]
Please check the new version 0.0.10 from github repository.
I changed to OO interface and it works with my setup (FW 6.83). But I had also in previous version no problems.

**Comment by foxthefox** [comment]
please use the npm version 0.0.10, the github is undergoing changes, which might not work immediately.
