### ISSUE TITLE
FritzDECT 200 Steckdosen - Iobroker aktualisiert Werte nicht mehr

### ISSUE THREAD

**Issue by MattN82** [foxthefox/ioBroker.fritzdect#132]
Hallo,

ich habe vor ein paar Tagen (nach längerem Offlinebetrieb und Updatepause des IOBrokers) mal wieder durchgeupdated.
Seither aktualisieren sich die Leistungs- und Verbrauchswerte der FritzDECT 200 Steckdosen nicht mehr.

Sie werden nach wie vor unter "Objekte" angezeigt...die Werte "flashen" auch regelmäßig kurz grün (scheinen zu updaten) aber die Werte sind eingefroren.

Paradox: Wenn ich in den Einstellungen der Instanz "fritzdect.0" auf "Meine Geräte" klicke, sehe ich im Output die korrekten Werte. Sie werden anscheinend nur nicht in die Werte der Iobrokerobjekte übernommen.

Ist das bekannt? Mach ich was falsch? Habe aber nichts am System geändert außer eben....update gemacht.

Danke und Gruß

**Comment by foxthefox** [comment]
So kann ich es erstmal nicht nachvollziehen. Das geht im Normalfall und es ist höchstwahrscheinlich kein Fehler im Adapter.
Welche AdapterVersion ist denn im Einsatz 2.1.11?
Stehen bei Meine Geräte im output wirklich Werte für die genannten Datenpunkte drin?
Dann ggf. mal den Adapter in den debug modus versetzen und im log schauen wenn ein Update kommt, was dort mitgeschrieben wird. Dort sollten Einträge mit den Werten für die Datenpunkte geschrieben sein.

**Comment by MattN82** [comment]
Version ist 2.1.11

Ja, es stehen definitiv Datenpunkte drin....auch korrekte...also im Sinne von "liegen im Erwartungswert".

Debugmodus hab ich jetzt nicht ausprobiert, weil sich das Problem scheinbar anders gelöst hat:

Ich habe eine zusätzliche Instanz (".1") des Adapters installiert, neu eingerichtet und die alte Instanz (".0") deaktiviert.
Jetzt...zumindest im Moment...funktioniert es wieder einwandfrei. Die Werte vom Output in "Meine Geräte" sind jetzt Deckungsgleich mit den Werten der Objekte von "fritzdect.1".

Ich beobachte und würde ein Update posten sofern die Aktualisierung wieder einfriert.

**Comment by foxthefox** [comment]
Die neue Instanz(.1) nutzt die gleiche SW wie die alte(.0), also das ist schon irgendwie komisch

**Comment by MattN82** [comment]
Seh ich genauso. Ich hatte zwar zeitgleich einige andere Adapter geupdated und auch das Linux auf dem der Iobroker läuft...aber das ist ja jetzt nicht das erste Mal.

Wie gesagt, ich hab mal verstärkt ein Auge drauf und update den Thread, wenn es nochmal auftreten sollte.

Danke btw für die schnelle Antwort :-)

**Comment by mar565** [comment]
Gleiches Problem mit zwei 546E Steckdosen.
Der Tipp mit dem Hinzufügen einer weiteren Instanz hat funktioniert. Die ursprüngliche blieb aber trotz identischer Einstellungen tod.
Ich habe dann beide Instanzen gelöscht und eine wieder installiert. Funktioniert jetzt wieder.
Nehme an, dass man auch direkt löschen und wieder hinzufügen kann.

**Comment by foxthefox** [comment]
Für mich sehr komisch, aber ja, man kann gleich die Instanz löschen und neu aufsetzen.
