### ISSUE TITLE
Adapter liefert, sendet keine Daten mehr

### ISSUE THREAD

**Issue by Moormerlander** [foxthefox/ioBroker.fritzdect#133]
Ich habe 7 Comet DECT Thermostate an einer FB 6591 im Einsatz. Bis vor kurzem konnte ich noch die Zieltemperatur und den Istwert auslesen, aber das funktioniert alles nicht mehr. Ein Adapter-Restart liefert im Log keine Fehler und die Werte in den Objekten sind alle veraltet. Ich habe keinen Schimmer woran das liegen kann.

**Comment by MattN82** [comment]
Hi...könnte es sein, dass du dasselbe Problem hat, wie ich mit Issue #132 ?

Falls ja, Ich hab meine "Lösung" dort gepostet. Zumindest geht es bisher.

**Comment by foxthefox** [comment]
Was hat sich denn in der Zwischenzeit im Umfeld geändert?
ioBroker irgendwas hochgerüstet?
FB neue FW?
Sonstige Veränderungen?

Was ist in "Meine Geräte" drin? alles auf Stand?

**Comment by skvarel** [comment]
Welche Version? Ab der 2.0.0 haben sich die Namen der Datenpunkte geändert. Nihct das Du an der falschen Stelle guckst?

**Comment by Sedrah87** [comment]
> Welche Version? Ab der 2.0.0 haben sich die Namen der Datenpunkte geändert. Nihct das Du an der falschen Stelle guckst?

Das war es bei mir! Statt DECT200 heißen die Datenpunkte jetzt DECT...
