### ISSUE TITLE
Warning in Log for DECT500 unknown datapoint

### ISSUE THREAD

**Issue by SebeSebe** [foxthefox/ioBroker.fritzdect#134]
**Describe the bug**  
Iobroker log contains 4 warning messages each call  for adapter fritzdect:
„(xxxx) unknown datapoint DECT_nnnnnnnnnnnn-1.xxxxxxxxxxxx please inform devloper and open issue in github“

Missing datapoint xxxxxxxxxx are:
- fullcolorsupport
- mapped
- unmapped_hue
- Unmapped_saturation

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by foxthefox** [comment]
Dann bräuchte ich den output von "Meine Geräte" um die neuen Datenpunkte zu eröffnen.

**Comment by SebeSebe** [comment]
[{"identifier":"11657 0071676","id":"16","functionbitmask":"35712","fwversion":"04.17","manufacturer":"AVM","productname":"FRITZ!DECT 210","present":"1","txbusy":"0","name":"Außendose","switch":{"state":"0","mode":"manuell","lock":"0","devicelock":"0"},"simpleonoff":{"state":"0"},"powermeter":{"voltage":"227475","power":"0","energy":"2393756"},"temperature":{"celsius":"200","offset":"0"}},{"identifier":"08761 0199938","id":"17","functionbitmask":"35712","fwversion":"04.16","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","txbusy":"0","name":"Xxxxxxxq","switch":{"state":"0","mode":"manuell","lock":"0","devicelock":"0"},"simpleonoff":{"state":"0"},"powermeter":{"voltage":"227640","power":"0","energy":"64275"},"temperature":{"celsius":"205","offset":"-10"}},{"identifier":"08761 0199944","id":"20","functionbitmask":"35712","fwversion":"04.16","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","txbusy":"0","name":"Xxxxxxxxxcc","switch":{"state":"0","mode":"manuell","lock":"0","devicelock":"0"},"simpleonoff":{"state":"0"},"powermeter":{"voltage":"227980","power":"0","energy":"91845"},"temperature":{"celsius":"190","offset":"-25"}},{"identifier":"11657 0207793","id":"21","functionbitmask":"1280","fwversion":"04.16","manufacturer":"AVM","productname":"FRITZ!DECT Repeater 100","present":"1","txbusy":"0","name":"DECT Repeater","temperature":{"celsius":"215","offset":"0"}},{"identifier":"13077 0018976","id":"408","functionbitmask":"1","fwversion":"34.10.16.16.015","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"1","txbusy":"0","name":"FRITZ!DECT Lampe"},{"identifier":"13077 0018976-1","id":"2001","functionbitmask":"237572","fwversion":"0.0","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"1","txbusy":"0","name":"FRITZ!DECT Lampe","simpleonoff":{"state":"0"},"levelcontrol":{"level":"175","levelpercentage":"69"},"colorcontrol":{"supported_modes":"5","current_mode":"1","fullcolorsupport":"1","mapped":"1","hue":"35","saturation":"214","unmapped_hue":"15","unmapped_saturation":"255","temperature":""},"etsiunitinfo":{"etsideviceid":"408","unittype":"278","interfaces":"512,514,513"}}]

**Comment by foxthefox** [comment]
Habe Version 2.1.12 auf GitHub erzeugt. Bitte Testen und Berichten.

Die Warnungen über unbekannte Datenpunkte sollte weg sein. Auch sollten die Datenpunkte entsprechend angelegt und befüllt sein. Welche Auswirkungen diese haben, bzw. wann es gesetzt wird ist mir nicht klar.

**Comment by SebeSebe** [comment]
Danke, habe 2.1.12 aktualisiert. 3 Warnungen sind verschwunden aber folgende Meldung kommt weiterhin:

(3037) State "fritzdect.0.DECT_nnnnnnnnnn-1.unmapped_saturation" has no existing object, ...

Die anderen drei neuen Datenpunkte sind gefüllt, weiß aber auch nicht wofür sie benötigt werden. 

Rest läuft bisher wie zuvor.

**Comment by foxthefox** [comment]
komisch, Schreibfehler scheint es erstmal nicht zu sein.

**Comment by SebeSebe** [comment]
Kleiner Tippfehler

else if (key === 'unmapped_saturation>') {

„>“ ist zuviel

**Comment by SebeSebe** [comment]
Danke
