### ISSUE TITLE
Fehler: (18998) State "fritzdect.0.Hgroup_91:EA:3C-900.temp" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by BurkerKingjw** [foxthefox/ioBroker.fritzdect#135]
Ich bekomme immer folgende Fehlermeldung.
![iobroker](https://user-images.githubusercontent.com/80596031/111041169-4b84e380-8437-11eb-8d42-a97fbf6bba5f.png)
![iobroker2](https://user-images.githubusercontent.com/80596031/111041323-01503200-8438-11eb-96ce-5bda50a93ced.png)
Lösung war im Objektordner "fritzdect.0.Hgroup_91:EA:3C-900" ein neues Objekt mit dem Nahmen "temp" hinzuzufügen danach trat die Fehlermeldung nicht mehr auf. 
![iobroker5](https://user-images.githubusercontent.com/80596031/111041371-293f9580-8438-11eb-964b-a4ccfeac50ff.png)
![iobroker7](https://user-images.githubusercontent.com/80596031/111041414-58ee9d80-8438-11eb-86fa-9e582f7235a5.png)
Folgende Version des Adapters verwende ich.
![iobroker6](https://user-images.githubusercontent.com/80596031/111041433-73287b80-8438-11eb-9d03-e2b8087f100b.png)

**Comment by BurkerKingjw** [comment]
Version:
Adapter version: 2.1.4
JS-Controller version: 3.2.16
Node version: v12.20.1

**Comment by foxthefox** [comment]
es gibt mittlerweile fritzdect 2.1.11, dort sind diese Probleme behoben.
Achtung, ab Version 2.x sind einige Datenpunkte geändert -> README.md

**Comment by BurkerKingjw** [comment]
Hallo, 

Wie kann ich dann diesen Adapter updaten? Denn über der iobroker Oberfläche bin ich aktuell. Siehe Bild. Muss ich das irgendwie über das Terminal machen. Wenn ja wie geht das? Gibt es dazu eine Anleitung? 

⁣Mit freundlichen Grüßen, 

Jens Weber

**Comment by foxthefox** [comment]
es gibt ein icon (dritte von rechts
![Bildschirmfoto 2021-03-15 um 10 32 50](https://user-images.githubusercontent.com/16841643/111132654-e7b70380-8579-11eb-81fb-909e982e3d3d.png)
dort draufklicken und fritzdect eingeben, dann wird die Version von GitHub installiert

**Comment by BurkerKingjw** [comment]
Danke hat geklappt.
