### ISSUE TITLE
Error (9620) unknown datapoint DECT 500

### ISSUE THREAD

**Issue by Bjoern2006** [foxthefox/ioBroker.fritzdect#136]
Seit dem Update auf Version 2.1.11 kommen in regelmäßigen mehrere Fehlermeldungen, die die DECT 500 Lampe betreffen.
Ich habe 2 Instanzen bei diesem Adapter, weil ich 2x FRITZ!Box 7590 in Betrieb habe.

Gibt es für diesen Fehler schon ein Fix?
![Dect Fehler](https://user-images.githubusercontent.com/28015256/111389850-f99bc200-86b1-11eb-8fe0-13c7c91453c7.jpg)

**Comment by foxthefox** [comment]
dazu habe ich schon einen fix mit Version 2.1.12 auf GitHub.
Bitte installieren und testen.

Es ist wohl weniger die Version 2.1.11 die Ursache, sondern die FB kennt jetzt mehr Datenpunkte.

**Comment by foxthefox** [comment]
2.1.12 ist jetzt auch auf npm

**Comment by Bjoern2006** [comment]
@foxthefox Vielen Dank. Habe die Version 2.1.12 installiert, jetzt scheint das Problem "weg" zu sein.
