### ISSUE TITLE
Verbindungsprobleme zur FB nach Update auf 2.1.11

### ISSUE THREAD

**Issue by TepMan** [foxthefox/ioBroker.fritzdect#137]
**Describe the bug**  
Seit dem Update kommt es wieder alle paar Stunden zu Verbindungsfehlern:

fritzdect.0 | 2021-03-17 21:05:31.039 | error | (4185) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-03-17 21:05:31.038 | error | (4185) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}

**Versions:**  
 - Adapter version: 2.1.11
 - JS-Controller version: 3.2.16
 - Node version: v12.20.2
 - Operating system: Raspian OS

**Comment by TepMan** [comment]
Doppelter Eintrag.

**Comment by TepMan** [comment]
Eintrag geschlossen

**Comment by foxthefox** [comment]
selbst wenn es ein doppelter Eintrag ist, 

https://github.com/foxthefox/ioBroker.fritzdect/blob/master/docs/de/troubleshooting.md
