### ISSUE TITLE
DECT500 - Gruppenschaltung funktioniert nicht

### ISSUE THREAD

**Issue by vdi-cloud** [foxthefox/ioBroker.fritzdect#138]
Nach update auf 2.1.12 funktionieren meine scripts dann nicht mehr, sobald ich DECT500 Gruppen ansteuere.
Ein simples an-aus führt zu keiner Reaktion. Ab und zu wird ein Fehler im log geworfen, aber auch nicht immer:

fritzdect.0 | 2021-03-25 09:05:50.504 | debug | (3878) state fritzdect.0.DECT_grp9CEFB6-3BDCFFC80.levelpercentage changed: 82 (ack = true)
-- | -- | -- | --
fritzdect.0 | 2021-03-25 09:05:50.498 | debug | (3878) Set level %grp9CEFB6-3BDCFFC80 to 82
fritzdect.0 | 2021-03-25 09:05:50.420 | error | (3878) unhandled promise rejection: undefined
fritzdect.0 | 2021-03-25 09:05:50.420 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
fritzdect.0 | 2021-03-25 09:05:50.416 | info | (3878) DECT ID: grp9CEFB6-3BDCFFC80 identified for command (state) : true
fritzdect.0 | 2021-03-25 09:05:50.416 | debug | (3878) ack is not set! -> command
fritzdect.0 | 2021-03-25 09:05:50.416 | debug | (3878) state fritzdect.0.DECT_grp9CEFB6-3BDCFFC80.state changed: true (ack = false)

Sobald ich eine Lampe aus einer Gruppe einzeln anspreche, funktioniert es.

**Comment by foxthefox** [comment]
Ich nehme an mit 2.1.11 hatte es funktioniert. Habe eigentlich nur eine weitere functionbitmask aufgenommen.
Kannst du mir den output von "Meine template" schicken?

**Comment by vdi-cloud** [comment]
hier ist er:
[{"identifier":"tmp9CEFB6-3BB5C6827","id":"60002","functionbitmask":"4416","applymask":["4",{"hkr_temperature":""}],"name":"Daheim","devices":{"device":[{"identifier":"grp9CEFB6-3BB5C5FBE"},{"identifier":"grp9CEFB6-3BB5C6181"},{"identifier":"09995 0482571"},{"identifier":"09995 0498078"},{"identifier":"09995 0372664"},{"identifier":"09995 0312779"}]}},{"identifier":"tmp9CEFB6-3BB650752","id":"60001","functionbitmask":"4416","applymask":["4",{"hkr_temperature":""}],"name":"Normal","devices":{"device":[{"identifier":"grp9CEFB6-3BB5C5FBE"},{"identifier":"grp9CEFB6-3BB5C6181"},{"identifier":"09995 0482571"},{"identifier":"09995 0498078"},{"identifier":"09995 0372664"},{"identifier":"09995 0312779"}]}}]

**Comment by foxthefox** [comment]
Danke, aber hab grad festgestellt, daß es die Gruppe gar nicht über ein template geschalten wird. Mein Fehler.

**Comment by foxthefox** [comment]
Der Fehler war wohl im fehlenden switchtype für die Gruppen.
Hab es hoffentlich jetzt mit 2.1.13 verbessert.
Bitte mal testen.

**Comment by vdi-cloud** [comment]
Die Korrektur scheint zu funktionieren :-)
