### ISSUE TITLE
(16606) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}

### ISSUE THREAD

**Issue by BurkerKingjw** [foxthefox/ioBroker.fritzdect#140]
Hallo bekomme aktuell mehrere Fehlermeldungen seitdem das ich meinen ioBroker neu gestartet habe. hab aber keine Ahnung warum ich  die Meldungen bekomme.  vor dem Neustart hatte ich damit keine Probleme.
![fritzdect01](https://user-images.githubusercontent.com/80596031/113043850-519bf380-919d-11eb-98a7-d83f526326fd.png)
![fritzdect02](https://user-images.githubusercontent.com/80596031/113043853-52cd2080-919d-11eb-88a2-ae4690916425.png)

**Comment by foxthefox** [comment]
der erste screenshot zeigt, daß der Adapter richtigerweise eine Verbindung mit der FB aufnimmt (und sich natürlich erfolgreich einloggt) und Datenpunkte anlegt.
Dann geht er in den zyklischen Betrieb über (polling) und die FB akzeptiert logins nicht mehr.

Bitte auch das hier mal anschauen und versuchen:
https://github.com/foxthefox/ioBroker.fritzdect/blob/master/docs/de/troubleshooting.md

Ich tippe auf eine sehr kurz eingestellte Pollingzeit, bzw. andere Aktivitäten die parallel ein Login auf der FB verursachen.

**Comment by BurkerKingjw** [comment]
Danke für deine Antwort. Dass mit der Pollingzeit war das Problem. Hatte im tr-064.0 Adapter eine Zeit von 10s drin und im fritzdect Adapter eine Zeit von 5s drinnen. Das hat sich anscheinend aufgeschaukelt und es entstand der Fehler. ich habe jetzt die Zeiten auf:
tr-064.0 Adapter 11s
fritzdect Adapter 3s
eingestellt und seitdem kommt der Fehler nichtmehr.

**Comment by Ilovegym66** [comment]
ohje, warum so kurze Pollings? 
Ich hab bei beiden 300 sekunden, das reicht doch.

**Comment by BurkerKingjw** [comment]
Ich hab über meine fritzbox die Telekom DECT Rauchmelder laufen. Dafür hab ich ein blockly geschrieben das sie mir ein WhatsApp Nachricht schreiben sollen wenn es brennt. Wenn ich die nur alle 300s Abfrage, könnte es vieleicht zu spätsein, dachte ich mir.

**Comment by foxthefox** [comment]
Na dann hat sich ja das issue erledigt
