### ISSUE TITLE
Nach Update auf 2.1.12 doppelte Gerätebezeichner ohne Gerätetyp DECT_1234 statt DECT200_1234

### ISSUE THREAD

**Issue by gwse** [foxthefox/ioBroker.fritzdect#151]
Hi,
gestern habe ich eine neue Instanz für eine weitere Fritzbox angelegt mit Version 2.1.11, ohne Probleme wurde eine neue DECT210 ausgelesen und der neuen Instanz zugeordnet (DECT200_12345...). 
Am Abend wurde mir ein Update auf 2.1.12 angeboten das ich auch durchgeführt habe. Anschließend wurde bei beiden Instanzen neue Geräte ohne Gerätebezeichnung eingefügt und die alten werden nicht mehr aktualisiert. Ein Downgrade auf 2.1.11 brachte keine Verbesserung. Auch eine neue Instanz legt die Geräte jetzt ohne den Bezeichnernummer (z.B. DECT200) an. Aus DECT200_12345 wurde DECT_12345 
aus BUTTON_45678 wurde auch DECT_45678
![image](https://user-images.githubusercontent.com/57746241/113549719-2d537300-95f2-11eb-80dd-76c832caa635.png)

**Versions:**  
Node.js: v12.20.0
NPM: v6.14.8
ioBroker.fritzdect 2.1.12
JS-Controller version: 3.1.6
Iobroker läuft bei mir in einem Docker Container buanet/iobroker 5.1.0 auf einer Synology DS218+ DSM 6.2.3-25426 Update 3

**Comment by foxthefox** [comment]
Mit der Version 2.x gab es Änderungen (breaking changes) in der Bezeichnung der Datenpunkte, da die Bezeichnungen nicht mehr repräsentativ sind. D.h. es startete mal mit DECT200 als Bezeichnung und zu dem Zeitpunkt gab es nur diese eine Steckdose. Das hat sich mittlerweile überholt.
Mit der Version 2.x werden nur noch Datenpunkte mit DECT_xxx angelegt. Also sind im Objektbaum alle Datenpunkte mit DECT200 obsolet und werden natürlich auch nicht mehr nachgeführt.
Daraus ergibt sich die gemachte Beobachtung und auch das Verhalten beim Aktualisieren.
Wenn nichts dagegen spricht würde ich mindestens die Datenpunkte vom fritzdect mal komplett neu löschen und durch einen Adapterneustart neu aufbauen lassen.

**Comment by gwse** [comment]
Vielen Dank für das Feedback, dann entferne ich die alten Datenpunkte und versuche die Historie der Messpunkte zu migrieren
