### ISSUE TITLE
CometDECT Kein Objekt update nach setmodeauto/setmodeon/setmodeoff

### ISSUE THREAD

**Issue by thesnoopy** [foxthefox/ioBroker.fritzdect#152]
Wenn ich die Schalter für die Mode änderung drücke, wird diese zwar an die FritzBox gesendet und akzeptiert, allerdings werden die Werte in dem Thermostat nicht geändert.

Reproduktion:
Click auf setmodeauto.
Erwartet: Änderung in den Werten: hkrmode, operationmode
Was ich bekomme: die werte bleiben gleich und werden nicht angepasst.

Version: 2.1.11

[debug.txt](https://github.com/foxthefox/ioBroker.fritzdect/files/6277625/debug.txt)

**Comment by foxthefox** [comment]
#139 hatte ein ähnlich gelagertes Problem.

Wobei ich hier eher vermute es geht um das direkte Nachführen nach dem Absetzen des Befehls und nicht erst die Aktualisierung mit dem Poll Intervall. Richtig?

Im Zuge der Auseinandersetzung mit obig genannten Issue habe ich auch die Version 2.1.14 erstellt, die nach erfolgreichen Kommandos auch hkrmode und operationmode nachführt.
Bitte dies mal zu Testen, ist bis jetzt nur auf GitHub.

**Comment by thesnoopy** [comment]
Hab es gerade mal aufprobiert. Mit der Version 2.1.14 scheint es zu funktionieren. Jetzt habe ich aber noch ein anderes Problem, was ich unter #153 beschrieben habe.
