### ISSUE TITLE
Compatibility check to js-controller 3.3 and Admin5 React UI

### ISSUE THREAD

**Issue by ioBrokerChecker** [foxthefox/ioBroker.fritzdect#161]
Dear Adapter developer,

with js-controller 3.2 and js-controller 3.3 some additional checks were added to make sure that created objects match to the specifications and also written state values match to the object definition.

If something is not correct this is logged as 'warning' or 'info' log.

Please take the time to verify your adapter by ideally starting with a fresh instance and do some actions and verify the log. If you see a warn log there from these checks please adjust the adapter and fix the relevant cases.

For questions please refer to https://github.com/ioBroker/ioBroker.js-controller/issues/1301 

Additionally we are preparing Admin 5 which will have a completely rewritten UI. Please install Admin 5, activate that new UI and verify that the configuration of you adapter works as expected also there.

More informations on Admin 5 can be found in Forum https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui 

Please close the issue after you checked it.

Thank you very much for your support!

**Comment by Flyor** [comment]
![image](https://user-images.githubusercontent.com/64526892/117556211-b84ae180-b066-11eb-9f5f-a777d6d7506a.png)

**Comment by foxthefox** [comment]
mit der Version 2.1.15 ist das Problem behoben, dazu auch die Adapter Instanz löschen, sonst wird es weiterhin als number anstatt string gehandhabt.

**Comment by foxthefox** [comment]
die neueste Version aus GitHub kann man über das "Okctocat" Icon installieren. Nach dem klicken ist dann fritzdect einzugeben und dann wird die GitHub version installiert.

**Comment by domstick** [comment]
![image](https://user-images.githubusercontent.com/39016069/128497502-57461212-3050-4771-a1d6-045310fd8e34.png)

fritzbox dect: 2.1.15
JS controller: 3.3.15

**Comment by Apollon77** [comment]
did you tried to delete the objects and restart adapter?

**Comment by domstick** [comment]
> did you tried to delete the objects and restart adapter?

Did that an fixed it! - Thanks, my bad, didn't know that!
