### ISSUE TITLE
State value to set for XXX.komfort has value "126.5" greater than max "32"

### ISSUE THREAD

**Issue by zokkai** [foxthefox/ioBroker.fritzdect#164]
Following Logentries since couple of days for all my thermostates:

State value to set for "fritzdect.0.DECT_xxxxx.komfort" has value "126.5" greater than max "32"
State value to set for "fritzdect.0.DECT_xxxxx.absenk" has value "126.5" greater than max "32"
State value to set for "fritzdect.0.DECT_xxxxx.tchange" has value "126.5" greater than max "32"

I actually dont know what causes thie problem.

  **Versions:**  
 - Adapter version: <2.15>tried several Versions too,
 - JS-Controller version: <3.3.8> 
 - Node version: <12.22.1> 
 - Operating system: <debian, Raspberry>

thx in advance!

**Comment by foxthefox** [comment]
the js-controller checks now the value ranged puts this on a info message.
the fritzbox is transmitting the values as 2x of the value in the range of 16-56 (8°-28°), that is calculated in the adapter.
Value 254 is permanent ON and 253 is permanent OFF. 126.5 is probably derived from 253 and I have to check in the adapter why in OFF state it is calculating and memorizing this as a temperature

**Comment by foxthefox** [comment]
I checked the documentation of API, at Komfort/tchange/absenk it is not expected to have the value range up to 254. It seems that FB has changed something here.

Can you send the output from click on My Devices/Meine Geräte in the admin of the adapter?

**Comment by zokkai** [comment]
thanks for your reply.
the logs shows the entries as warning thats confusing. 

here the result from my devices:

[{"identifier":"09995 0070483","id":"18","functionbitmask":"320","fwversion":"04.94","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Heizung Flur","battery":"80","batterylow":"0","temperature":{"celsius":"220","offset":"-15"},"hkr":{"tist":"44","tsoll":"44","absenk":"253","komfort":"253","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"0","tchange":"253"},"summeractive":"0","holidayactive":"0"}},{"identifier":"10971 1036864","id":"19","functionbitmask":"320","fwversion":"04.85","manufacturer":"AVM","productname":"FRITZ!DECT 300","present":"1","txbusy":"0","name":"Heizung Jonas Fenster zur Seite","battery":"70","batterylow":"0","temperature":{"celsius":"210","offset":"-5"},"hkr":{"tist":"42","tsoll":"42","absenk":"253","komfort":"253","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"70","nextchange":{"endperiod":"0","tchange":"253"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11963 0133392","id":"20","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Heizung Jonas Fenster nach hinten","battery":"100","batterylow":"0","temperature":{"celsius":"205","offset":"-5"},"hkr":{"tist":"41","tsoll":"42","absenk":"253","komfort":"253","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"100","nextchange":{"endperiod":"0","tchange":"253"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11963 0197776","id":"21","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Heizung Küche Terrasse","battery":"100","batterylow":"0","temperature":{"celsius":"225","offset":"0"},"hkr":{"tist":"45","tsoll":"42","absenk":"253","komfort":"253","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"100","nextchange":{"endperiod":"0","tchange":"253"},"summeractive":"0","holidayactive":"0"}},{"identifier":"11963 0195560","id":"22","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Heizung Wohnzimmer","battery":"100","batterylow":"0","temperature":{"celsius":"210","offset":"-15"},"hkr":{"tist":"42","tsoll":"43","absenk":"253","komfort":"253","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"100","nextchange":{"endperiod":"0","tchange":"253"},"summeractive":"0","holidayactive":"0"}},{"identifier":"13356 0208760","id":"23","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Heizung Küche Tür","battery":"40","batterylow":"0","temperature":{"celsius":"220","offset":"0"},"hkr":{"tist":"44","tsoll":"42","absenk":"253","komfort":"253","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"40","nextchange":{"endperiod":"0","tchange":"253"},"summeractive":"0","holidayactive":"0"}},{"identifier":"13356 0157984","id":"24","functionbitmask":"320","fwversion":"03.54","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Heizung Bad","battery":"40","batterylow":"0","temperature":{"celsius":"215","offset":"-10"},"hkr":{"tist":"43","tsoll":"43","absenk":"253","komfort":"253","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"40","nextchange":{"endperiod":"0","tchange":"253"},"summeractive":"0","holidayactive":"0"}}]

**Comment by zokkai** [comment]
seems to be a good workaround.

thx

**Comment by duczz** [comment]
@foxthefox i have the same problem, will be worked on this issue?

**Comment by Henny4184** [comment]
Hallo habe das selbe Problem. Wo kann man das genau in der Fritzbox umstellen um die Meldungen zu verhindern? ODer gibt es schon eine ander Lösung ?

**Comment by foxthefox** [comment]
Wie oben beschrieben, bei Absenktemperatur kann man auch an Stelle Ventil zu auch eine Temperatur eingeben.

**Comment by Henny4184** [comment]
> Wie oben beschrieben, bei Absenktemperatur can man auch an Stelle Ventil zu auch eine Temperatur eingeben.

Hallo, ich steuer nur mit Temperaturen über Iobroker. 6 Grad dann geht die Heizung aus. Oder was soll ich noch anders machen?

**Comment by duczzz** [comment]
Ist doch nicht Sinn der Sache, sollte trotzdem gefixt werden.

**Comment by foxthefox** [comment]
steht ja auch als "work in progress" -> wird gemacht.
Zeit dafür braucht es halt und die ist knapp

**Comment by duczz** [comment]
Gibt's hierzu Neuigkeiten?

**Comment by foxthefox** [comment]
immerhin hab ich schon einen branch angelegt. es wird kommen

**Comment by duczz** [comment]
@foxthefox  Reicht's hier nicht einfach nur den Max Wert in dem Objekt zu erhöhen?

**Comment by foxthefox** [comment]
als fast-hack geht das natürlich, mach ich gleich mal in der git Version

**Comment by duczz** [comment]
Schade, meine Idee und der aktuelle Git beheben das Problem leider nicht.

**Comment by foxthefox** [comment]
da der Datenpunkt schon angelegt ist, wird er nicht überschrieben.
es ist mindestens der Datenpunkt zu löschen, damit beim nächsten Adapterstart beim Neuanlegen die Bereiche mit übernommen werden.

**Comment by steinhuegel** [comment]
Hallo, seit heute (admin und js update) ist mir aufgefallen das ich folgende Warnungen erhalte:
State value:
tchange" has value "126.5" greater than max "32"
komfort" has value "126.5" greater than max "32"
absenk" has value "126.5" greater than max "32"
celsius" has value "0" less than min "8" <- Heizkörperthermostat 1
celsius" has value "1" less than min "8" <- Heizkörperthermostat  2

Datenpunkt löschen und Adapter neustart bewirken das wieder 126.5° ausgelesen werden.
Vielen Dank

**Comment by foxthefox** [comment]
habe jetzt eine neue Version 2.2.0 erstellt, es kann gern getestet werden

**Comment by steinhuegel** [comment]
Vielen Dank es Ist jetzt deutlich besser, lediglich wenn der Wert z.B.  bei der Messsteckdose ins negative geht (Balkonkraftwerk) bringt es die Warnung. 

Was ich jetzt auch gesehen habe ist diese Meldung:

State value to set for "fritzdect.0.DECT_xxxx5.celsius" has value "7.5" less than min "8"

**Comment by foxthefox** [comment]
wenn das noch kommt (celsius ist nun -30..50), dann sind die Eigenschaften nicht neu übernommen, da vorhandene Objekte nicht neu angelegt werden.
Dazu bitte den Adpater stoppen, den Objektbaum für fritzdect löschen und Adapter starten, dann werden die Objekte neu angelegt.

sollte ich bei der Steckdose was anpassen?

**Comment by Stopuhr** [comment]
Sorry, ich bekomme den Fehler wieder in der Version 2.3.1.
_State value to set for "fritzdect.0.DECT_099950xxxxxx.absenk" has value "126.5" greater than max "32"_
Analog beim 2. Adapter und der Gruppe aus beiden.
Gesamter Objektbaum des Adapters gelöscht. Logs nach Neustart weiterhin vorhanden.

**Comment by foxthefox** [comment]
Was ist denn für die Absenktemperatur eingestellt?

**Comment by Stopuhr** [comment]
> Ich schau mal was ich mit dem AUS mache

Zum Verständnis für später:
Das dürfte eine Antwort auf meinen Post gewesen sein, dass ich in der 2.3.1 einen Error bekomme, wenn die Absenktemperatur auf AUS steht - es wird dann ein Wert von 126,5° gemeldet.
Ich hatte den Post wieder gelöscht, nachdem ich gelernt habe, dass bereits eine 2.4.1 existiert (nur in ioBroker nicht als stable). Vermutlich habe ich nicht vorher aktualisiert, sonst hätte ich den Post nicht gelöscht.
Sorry!

**Comment by foxthefox** [comment]
Ich habe ein Version 2.5.2 in github zum Testen erstellt.

**Comment by foxthefox** [comment]
Bitte Testen

**Comment by Stopuhr** [comment]
Moin!
Sorry, war verhindert und bin nicht wirklich zum ioBroker gekommen.
Ich versuche mich gleich mal, muss aber erstmal recherchieren, wie ich die Version von hier manuell installiert und später wieder auf die Stable gesiecht bekomme. Gib einen Moment :-)

und danke für die schnelle Reaktion (gut, dass Du schneller bist als ich;-))

**Comment by foxthefox** [comment]
Null ist auch eine Möglichkeit, kann ich umsetzen. 
Allerdings scheint mir dann die Umsetzung auch nicht ganz eindeutig.
Aus meiner Sicht verhält sich es wie folgt:
- AUS -> Ventil zu -> Frostmodus
- Wert zwischen 8 und 32 -> Regeln
- EIN -> Ventil offen -> Saunamodus
AUS und EIN als NULL im Sinne kein Wert abzubilden ist auch doppeldeutig, aber für mich kein Problem.
Mit 8 und 32 trifft man zwar Frost und Sauna auch nicht richtig, hätte aber einen tendenziellen Wert.

Naja, aus meiner Sicht wäre es ohnehin besser wenn AVM hier nicht den Sollwert misbraucht hätte. Es ist nun aber mal wie es ist.
Das mit der NULL mach ich dann nach meinem Kurzurlaub am 3.10 oder so

**Comment by Stopuhr** [comment]
Es gibt doch aber bei der Absenktemperatur keine Schaltung. Der Wert ist doch eine Grad-Zahl. Analog dazu auch wieder 'tist' bei Gruppen.
Nicht, dass Du jetzt gedanklich bei einem der Modi oder diesem hkr-Dingens warst?!

**Comment by foxthefox** [comment]
Nochmals zum Verständnis, absenk und komfort lassen sich nur über die FB setzen, das geht nicht über die Schnittstelle.
Diese beiden Solltemperaturen werden dann entweder zeitgesteuert oder durch Ereignisse (Szenen, Trigger) als neue Solltemperatur tsoll übernommen. Diese Einstellung wird somit an tsoll durchgereicht.
Da tsoll das gleiche Problem hat, gibt es hier die zusätzlichen Punkte hkrmode (Anzeige und Bedienung) und operationmode (nur Anzeige). 0=AUTO/1=OFF/2=ON sind dann die Einstellmöglichkeiten, die sich aus eine korrekten Temperatur oder 253/254 ergeben. 
tist als aktuelle Temperatur sollte immer einen Temperaturwert zurückgeben und nicht mit 253/254 als Status des Ventils.

**Comment by Stopuhr** [comment]
Willkommen zurück.
Ich hatte das Thema bei mir zurückgestellt (regeln via Homekit zur Heizperiode, da kann man besser testen).
Das 'ist' bezog sich bei mir auf Thermostat-Gruppen, dort wir null ausgegeben, weshalb ich ja nun via Skript selbst rechne.

Letztlich war der Anlass ja auch ein Eintrag im Log, dass ein Wert ausserhalb des Bereichs liegt.
Ich bleibe da bei der Meinung, dass ich im Falle AUS/SAUNE die Rückgabe von null besser finde als eine Gradangabe aus dem erlaubten Bereich.
Wenn da Null kommt, dann kann man (wenn das benötigt wird) sich anhand anderer Werte (oder durch Betrachtung über einen Zeitraum) den Status ermitteln. Aber wie Du ja auch sagst, dass ist dann der Wert, der in der FB eingestellt wurde, im Prinzip weiß man dann also, welcher das ist.

Ich bin Pro-Null :-)

Testen geht dieses Mal wohl auch schneller ;-)

**Comment by foxthefox** [comment]
ich wollte es grad auf "null" setzen
das mag eslint nicht:
Type 'null' is not assignable to type 'number'.ts(2322)
also wird es NaN

**Comment by foxthefox** [comment]
so, ist in der github version 2.5.2 jetzt geändert
es kann getestet werden

**Comment by Stopuhr** [comment]
Installiert, Adapter loggt keine Warning mehr beim Start und der Datenpunkt wird nun mit `(null) °C` angezeigt.
Ich bin zufrieden :-) Jetzt muss das nur noch stable werden.
Thx!

**Comment by foxthefox** [comment]
alles klar, danke
