### ISSUE TITLE
admin 5.x 

### ISSUE THREAD

**Issue by arteck** [foxthefox/ioBroker.fritzdect#165]
![grafik](https://user-images.githubusercontent.com/6681528/120061864-73abd800-c05f-11eb-96d4-4b147b9e5eb8.png)

**Comment by foxthefox** [comment]
das hat nichts mit admin 5 zu tun, das kommt durch js-controller 3.3.x

Bitte Adapter stoppen -> Adapter Updaten auf 2.1.15 aus GitHub
Instanz löschen (damit werden alle Datenpunkte vom der Instanz gelöscht)
Danach wieder eine Instanz "installieren".
Zugangsdaten eintragen und aktivieren.

**Comment by arteck** [comment]
ich war im flow mit dem admin.. hast ja recht

**Comment by foxthefox** [comment]
bei mir läuft admin5 und das Rollo Zeitstempelproblem sollte auch gelöst sein.
