### ISSUE TITLE
fritzdect warn

### ISSUE THREAD

**Issue by poand** [foxthefox/ioBroker.fritzdect#176]
Hello ladies and gentlemen,

Rademacher RolloTron DECT 1213 are operated via Fritz! Box 7590 FRITZ!OS: 7.27.

The following message appears in the "Log" of ioBroker:

(794) State "fritzdect.0.DECT_142760470432-1.mode" has no existing object, this might lead to an error in future versions
(794) unknown datapoint DECT_142760470432-1.endpositionsset please inform devloper and open issue in github

**Comment by poand** [comment]
fritzdect.0 version 2.1.11

**Comment by foxthefox** [comment]
please upgrade to 2.1.5 from GitHub and this problem is solved

**Comment by poand** [comment]
Do you mean 2.1.15?

how do I do that?

**Comment by poand** [comment]
Thanks. I installed 2.1.15. Problem solved.
