### ISSUE TITLE
Present = true obwohl device offline ist

### ISSUE THREAD

**Issue by RK62** [foxthefox/ioBroker.fritzdect#180]
Object present bleibt auf true obwohl die Steckdose offline ist.
Wenn Sie eingesteckt ist, funktioniert alles normal.

![2021-06-19 10_57_49-ioBroker-ESK01](https://user-images.githubusercontent.com/39200469/122674473-acaa1900-d1d5-11eb-9ec1-e9ee92560fb0.png)

Versionen im Einsatz :
- Adapter Admin 4.2.1,
- Adapter fritzbox DECT 2.1.11
- JS-Controller version: 3.2.16
- Node version:v12.20.2
- Operating system: Debian on Docker
- Redis v6.2.1

Gruß, Ralf

**Comment by foxthefox** [comment]
bitte mal die Version 2.1.15 aus GitHub installieren und ausprobieren

**Comment by RK62** [comment]
Danke, funktioniert!
