### ISSUE TITLE
Feature: Heater Groups

### ISSUE THREAD

**Issue by Scrounger** [foxthefox/ioBroker.fritzdect#19]
@foxthefox 
Great plugin, thanks a lot!
Could you please implement heater groups?

**Comment by foxthefox** [comment]
Basically the groups already appear in the objects list. 
But it could be nicer, with only the valid (reduced) entries which are applicable for groups.

**Comment by Scrounger** [comment]
@foxthefox 
I only see groups for switches in the object list. How is it possible to show the heater groups or to get the ids of groups in javascript?

**Comment by foxthefox** [comment]
These are bad news. I only own the switches and there seems that the groups are included in the response. If it is not included for thermostats I have no glue how to catch it then.
If you have created groups of thermostats in your environment, you could help me by calling the following and providing the output:

go to
/opt/iobroker/node_modules/iobroker.fritzdect/node_modules/fritzapi

and call 

node example -u yourUsername -p yourPassword

That could help to figuring out the low level response of the API.

**Comment by Scrounger** [comment]
@foxthefox 
Here is the result:
![fb_error](https://user-images.githubusercontent.com/6370451/34637841-e1dca704-f2be-11e7-830d-dd663cc42326.png)

I think you use the http api of the fb?
I have written an android api using the http api. Here is the xml file with heater group inside, hope that can be helpful:
```
<?xml version="1.0"?>

-<devicelist version="1">


-<device productname="FRITZ!DECT 200" manufacturer="AVM" fwversion="03.87" functionbitmask="2688" id="18" identifier="XXXX XXXXXX">

<present>0</present>

<name>FRITZ!DECT 200 #3</name>


-<switch>

<state/>

<mode/>

<lock/>

<devicelock/>

</switch>


-<powermeter>

<power/>

<energy/>

</powermeter>

</device>


-<group productname="" manufacturer="AVM" fwversion="1.0" functionbitmask="6784" id="901" identifier="69:41:85-901">

<present>1</present>

<name>SWITCH GROUP</name>


-<switch>

<state>0</state>

<mode>manuell</mode>

<lock>0</lock>

<devicelock>0</devicelock>

</switch>


-<powermeter>

<power>0</power>

<energy>0</energy>

</powermeter>


-<groupinfo>

<masterdeviceid>18</masterdeviceid>

<members>18</members>

</groupinfo>

</group>


-<device productname="Comet DECT" manufacturer="AVM" fwversion="03.54" functionbitmask="320" id="19" identifier="XXXX XXXXXX">

<present>1</present>

<name>Wohnzimmer 2</name>


-<temperature>

<celsius>200</celsius>

<offset>-10</offset>

</temperature>


-<hkr>

<tist>40</tist>

<tsoll>44</tsoll>

<absenk>32</absenk>

<komfort>44</komfort>

<lock>0</lock>

<devicelock>1</devicelock>

<errorcode>0</errorcode>

<batterylow>1</batterylow>


-<nextchange>

<endperiod>2019970800</endperiod>

<tchange>44</tchange>

</nextchange>

</hkr>

</device>


-<group productname="" manufacturer="AVM" fwversion="1.0" functionbitmask="4160" id="900" identifier="69:41:85-900">

<present>1</present>

<name>HEATER GROUP</name>


-<hkr>

<tist>50</tist>

<tsoll>44</tsoll>

<absenk>32</absenk>

<komfort>44</komfort>

<lock>0</lock>

<devicelock>0</devicelock>

<errorcode>0</errorcode>

<batterylow>0</batterylow>


-<nextchange>

<endperiod>2019970800</endperiod>

<tchange>44</tchange>

</nextchange>

</hkr>


-<groupinfo>

<masterdeviceid>0</masterdeviceid>

<members>19,20</members>

</groupinfo>

</group>


-<device productname="FRITZ!DECT 301" manufacturer="AVM" fwversion="04.59" functionbitmask="320" id="20" identifier="XXXX XXXXXX">

<present>1</present>

<name>Wohnzimmer 1</name>


-<temperature>

<celsius>205</celsius>

<offset>-10</offset>

</temperature>


-<hkr>

<tist>41</tist>

<tsoll>44</tsoll>

<absenk>32</absenk>

<komfort>44</komfort>

<lock>0</lock>

<devicelock>1</devicelock>

<errorcode>0</errorcode>

<batterylow>0</batterylow>


-<nextchange>

<endperiod>2019970800</endperiod>

<tchange>44</tchange>

</nextchange>

</hkr>

</device>

</devicelist>
```

The Batterylow values is also not read correct.

@foxthefox : Do you speak german?

**Comment by foxthefox** [comment]
@foxthefox : Do you speak german?
Yes, I do.
Wir könnten auch in Deutsch miteinander kommunizieren.

**Comment by Scrounger** [comment]
Perfekt.
Bringt dich der xml Auszug weiter?
mit welchem argument kann ich bei node example noch die IP von meiner FB angeben?

**Comment by foxthefox** [comment]
Die Rohdaten aus der xml sehen ja nicht schlecht aus, so ähnlich würde es ja auch aus der fritzapi kommen.
Ich denke ich müsste einiges von deiner Implementation nachbauen, damit das mit den Gruppen auch solche Rohdaten mit js in json ergibt.

wenn man die example ohne Argumente aufruft, dann gibts Hinweise wie die Kommandozeile aussieht.
sollte --Url sein

**Comment by Scrounger** [comment]
> Die Rohdaten aus der xml sehen ja nicht schlecht aus, so ähnlich würde es ja auch aus der fritzapi kommen.
Das sind die Rohdaten wie sie aus der FB kommen, sofern du das [AVM Home Automation HHTP Interface ](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwiM_rzW5sXYAhXG1ywKHUw6ACIQFggzMAE&url=https%3A%2F%2Favm.de%2Ffileadmin%2Fuser_upload%2FGlobal%2FService%2FSchnittstellen%2FAHA-HTTP-Interface.pdf&usg=AOvVaw0SUv8nMKHNcA1QjsIhKBb-) nutzt.

**Comment by foxthefox** [comment]
Ok, benutze bis jetzt die fritzapi und dort nicht die Funktion getDeviceListInfos. Sehe jetzt auch den xml output und kann damit weitermachen.

**Comment by foxthefox** [comment]
0.1.0 enthält nun heater groups, bitte testen!

**Comment by Scrounger** [comment]
@foxthefox 
Vielen Dank, HeaterGroups werden jetzt erkannt und als Objekt dargestellt.
