### ISSUE TITLE
Ständige Verbindung/Connect bereitet FritzBox Probleme

### ISSUE THREAD

**Issue by UweLoyal** [foxthefox/ioBroker.fritzdect#205]
Hier der Kommentar von AVM:

Guten Tag,
danke für Ihre Geduld.

Das Gerät mit der IP-Adresse "192.168.178.81" öffnet alle 2-3 Minuten eine neue FTP-Sitzung ohne die alte zu beenden. Da wir Mehrfachsitzungen pro Gerät unterbinden, kommt es zur beobachteten Nichterreichbarkeit des FRITZ!NAS.

Dasselbe Gerät stellt außerdem im Sekundentakt DNS-Anfragen an "fritz.box" zur FRITZ!Box und obwohl FRITZ!Box diese stets immer beantwortet, wird unsere TTL von 9 Sekunden ignoriert und die Anfragen erfolgen sekündlich. 

Bitte verhindern Sie diese ständigen Sitzungs- sowie DNS-Anfragen des Geräts mit der MAC-Adresse (XX:XX:XX:XX:XX:XX), dann sollte auch der FTP-Zugriff wieder zuverlässig funktionieren, auch von der MyFRITZ!App aus.

Freundliche Grüße aus Berlin
(AVM Support)

**Nach der deaktivierung der FritzDEC Instanz läuft der FTP wieder!**

Gruß
Uwe Loyal

**Comment by foxthefox** [comment]
Ich eröffne im Adapter keine FTP Sitzungen. Das es eine Beschränkung von gleichzeitigen Logins gibt ist bekannt.
Gerade wenn es sehr viele Zugriffe aus IOB gibt (schnelles polling, scripte...) kann es zum blockieren kommen.

**Comment by UweLoyal** [comment]
Ich verwende nur noch fritzbox und tr-064, Verbesserung gab es nur nach Abschaltung von fritzdect. Irgend eine Idee?

Mit freundlichen Grüßen

Uwe Loyal
Am 10. Sept. 2021, 21:46 +0200 schrieb foxthefox ***@***.***>:

**Comment by foxthefox** [comment]
was sind denn die Einstellungen und was wird sonst so mit fritzdect gemacht?

**Comment by UweLoyal** [comment]
Fritzbox Abrufintervall (sek.):300
Fritzbox IP: http://192.168.178.1
.... und natürlich die Login Daten.

LG
Uwe Loyal

**Comment by UweLoyal** [comment]
Habe nochmal den Adapter Abgeschaltet, danach klappte die Verbindung zur FritzBox per FTP wieder.
Könnte es an einer offenen Verbindung liegen, zu viele offene Verbindungen?

LG
Uwe Loyal

**Comment by foxthefox** [comment]
kann sein, kann aber auch an scripten liegen die ein feuerwerk von kommandos verursachen

**Comment by UweLoyal** [comment]
Das ist nun aber eine seltsame Aussage.
Selbst wenn man ein Feuerwerk an Kommandos sendet, so wird doch das öffnen und schließen von fritzdect geregelt, zumindest habe ich habe ich nichts davon gelesen, dass der Nutzer dies steuern muss!
Ich schalte momentan lediglich eine Fritz Lampe nach Sonnenuntergang  und eingeschaltetem TV ein.

Was heißt denn jetzt “kann sein”, bleibt die Verbindung offen oder nicht?

Mit freundlichen Grüßen

Uwe Loyal
Am 15. Sept. 2021, 20:32 +0200 schrieb foxthefox ***@***.***>:

**Comment by foxthefox** [comment]
habe jetzt eine neue Version 2.2.0 erstellt, es kann gern getestet werden
Der Adapter hat solange er läuft eine Verbindung, die API zur FB ist nunmehr geändert.
Alle Kommandos greifen auf die gleiche Session zu.

**Comment by UweLoyal** [comment]
Das scheint die Lösung für das Problem gewesen sein!
Die Verbindug zur NAS funktioniert jetzt wieder auch bei eingeschaltetem FritzDect.
Da hat wohl AVM recht gehabt...

;-)
