### ISSUE TITLE
 has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by nob0dy80** [foxthefox/ioBroker.fritzdect#207]
Nach JS-Controller update die typischen fehler.

hier betreffend das objekt .energy.

während bei allen anderen adaptern das löschen des objekts  und restart geholfen hat, klappt das bei diesem adapter net.

Ist kein Bug und hat keine Auswirkung, nur störend im Log.

**Comment by foxthefox** [comment]
vor dem löschen der Instanzen sollte die neueste Version installiert sein, dann den Adapter stoppen, Instanzen löschen und Adapter neustart
