### ISSUE TITLE
CometDECT - Keine Reaktion auf windowopenactiv

### ISSUE THREAD

**Issue by derkostka** [foxthefox/ioBroker.fritzdect#216]
Hallo, es scheint, als wenn der CometDECT nicht auf windowopenactiv reagiert. Wurde das schonmal beobachtet ? Eine Bestätigung der Zeit (1440 Minuten gesetzt), wird auch nicht übernommen (in der Fritz Oberfläche unverändert).

Danke !

**Comment by foxthefox** [comment]
Ich hatte es noch  nicht beobachtet, werde es aber mal prüfen.
Immerhin hat der Thermostat jetzt wieder Batterien ;-)

**Comment by foxthefox** [comment]
1440 Minuten sind hart an der Grenze zu 24h, die maximal mögliche Zeit die gesetzt werden kann.
Das habe ich jetzt mal vorsoglich noch begrenzt, da es sich noch eingeben lässt.
Ich arbeite gerade an einer neuen Version, melde mich, wenn es getestet werden kann

**Comment by foxthefox** [comment]
habe jetzt eine neue Version 2.2.0 erstellt, es kann gern getestet werden
