### ISSUE TITLE
Heater Groups: values bug

### ISSUE THREAD

**Issue by Scrounger** [foxthefox/ioBroker.fritzdect#22]
@foxthefox:
Heater Groups funktionier jetzt, allerdings werden bei mir nicht alle Werte ausgelesen, siehe Screenshot.
Weiter kann ich bei targetTemp keinen Wert eingeben.

![heater_groups_no_values](https://user-images.githubusercontent.com/6370451/35233299-fe741398-ff9d-11e7-94e9-273c0b7bce62.png)

**Comment by foxthefox** [comment]
das sollte jetzt behoben sein. das einlesen der isttemperatur hat wegen schreibfehler die schleife gekillt.

**Comment by foxthefox** [comment]
Werte werden jetzt richtig eingelesen.

http://forum.iobroker.net/viewtopic.php?p=117189#p117189
