### ISSUE TITLE
present" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by Lucky-ESA** [foxthefox/ioBroker.fritzdect#224]
Hallo foxthefox,
danke für die "present" Umsetzung. Hier kommt es leider zu einem Fehler wie im Header beschrieben. Bitte deine main.js wie folgt anpassen.
Suche:
`								await this.setStateAsync(
									'DECT_' + devices[i].identifier.replace(/\s/g, '') + '.present',
									{
										val: false,
										ack: true
									}
								);
								this.log.debug(
									'DECT_' +
										devices[i].identifier.replace(/\s/g, '') +
										' is not present, check the device connection, no values are written'
								);`

Ersetzen durch:
`								await this.getForeignObject(this.namespace + '.DECT_' + devices[i].identifier.replace(/\s/g, '') + '.present', async (err, obj) => {
									if (!obj || !obj.common) {
										this.log.debug(
											'DECT_' +
												devices[i].identifier.replace(/\s/g, '') +
											'.present is not present, check the device connection, no values are written'
											);
									} else {
										await this.setStateAsync(
											'DECT_' + devices[i].identifier.replace(/\s/g, '') + '.present',
											{
												val: false,
												ack: true
											}
										);
									}
								});`

Gruß//Lucky

**Comment by foxthefox** [comment]
eigentlich sollte das Objekt angelegt sein, ist ja immerhin ein grundsätzliches. und nicht eines, welches durch ein neues Feature dazukommt.

**Comment by Lucky-ESA** [comment]
Du weißt genau so gut wie ich das einige Devices 2 x gesendet werden. Die FW hast du ja schon als ToDo gekennzeichnet.
`<device identifier="xxxxx xxxxxxx" id="417" functionbitmask="1" fwversion="34.10.16.16.015" manufacturer="AVM" productname="FRITZ!DECT 500"><present>1</present><txbusy>0</txbusy><name>Lampe</name></device>
<device identifier="xxxxx xxxxxxx-1" id="2009" functionbitmask="237572" fwversion="0.0" manufacturer="AVM" productname="FRITZ!DECT 500"><present>1</present><txbusy>0</txbusy><name>Lampe</name><simpleonoff><state>1</state></simpleonoff><levelcontrol><level>255</level><levelpercentage>100</levelpercentage></levelcontrol><colorcontrol supported_modes="5" current_mode="4" fullcolorsupport="1" mapped="0"><hue></hue><saturation></saturation><unmapped_hue></unmapped_hue><unmapped_saturation></unmapped_saturation><temperature>3000</temperature></colorcontrol><etsiunitinfo><etsideviceid>417</etsideviceid><unittype>278</unittype><interfaces>512,514,513</interfaces></etsiunitinfo></device>`

**Comment by foxthefox** [comment]
FW ToDo?

**Comment by Lucky-ESA** [comment]
Die Firmware
identifier="xxxxx xxxxxxx" id="1" functionbitmask="1" fwversion="34.10.16.16.015"
identifier="xxxxx xxxxxxx-1" id="2009" functionbitmask="237572" fwversion="0.0"
Hier wird dann xxxxx xxxxxxx-1 als channel angelegt aber im Datenpunkt fwversion steht dann 0.0.
Hoffentlich habe ich mich richtig ausgedrückt..In deinem Code hast du unter functionbitmask 1 bereits ein ToDo eingetragen.

**Comment by foxthefox** [comment]
Ah, jetzt hab ichs. Ich hatte in der Readme geschaut und da hab ich es nicht gelistet. Die FW Version ist in diesen 2geteilten Geräten schlecht zu mappen. Ist ein ToDo mit niedriger prio. Hab grad nicht so viel Zeit.

**Comment by Lucky-ESA** [comment]
Lass und nimm dir die Zeit. Da ich Fensterkontakte habe musste ich mir einen eigenen Adapter schreiben damit ich die Daten der Fritz pro Sekunde bekomme. Wenn ich Zeit habe kann ich bei deinem mal schauen, wie die FW eingefügt werden kann.

**Comment by Lucky-ESA** [comment]
Hi foxthefox, wegen der FW habe ich diese Lösung. In der main.js das suchen:
`								if (devices[i].functionbitmask == 1) {
									this.log.debug(' functionbitmask 1');`

Darunter habe ich dann das eingefügt.
`                                                               devices[i + 1].fwversion = devices[i].fwversion;`

Es gibt natürlich viele Lösungen ab das war die einfachste.
Gruß//Lucky

**Comment by foxthefox** [comment]
wobei der fasthack auch voraussetzt, daß die FB immer in der Reihenfolge antwortet. Aber es ist mal eine schnelle Lösung.
Danke

**Comment by Lucky-ESA** [comment]
Wenn die Fritz nicht so anwortet hast du mir deinem Adapter ganz andere Probleme:-)

**Comment by foxthefox** [comment]
Könntest du die anderen Probleme näher ausführen?

**Comment by foxthefox** [comment]
habe jetzt eine neue Version 2.2.0 erstellt, es kann gern getestet werden
