### ISSUE TITLE
Außensteckdosen können auch eine Temperatur < 0 liefern

### ISSUE THREAD

**Issue by asmitconsulting** [foxthefox/ioBroker.fritzdect#225]
Dann erhält man folgende Warnung:
2021-11-16 09:45:44.400 | warn | State value to set for "fritzdect.0.DECT_116570269232.celsius" has value "-0.5" less than min "0"

Ist zwar im Augenblick kein Beinbruch - bitte bei Gelegenheit (ggf. mit dem Wert > 32°) mit fixen

**Comment by foxthefox** [comment]
hab mal in Git den Bereich erweitert auf +-60, ob die Steckdose das auch bedient, weiß ich nicht.

**Comment by asmitconsulting** [comment]
Danke schön - AVM nennt im Datenblatt einen Temperaturbereich von -20° C bis +40° C. Wird ja sicher bald wieder etwas kälter draußen, dann melde ich, ob es klappt.
Kommt die Änderung demnächst auch im beta-Kanal (den habe ich aktiv) oder muss ich die git-Version installieren?

**Comment by foxthefox** [comment]
erstmal auf git, hab noch andere Dinge für die nächste Version anzuschauen

**Comment by franks06347** [comment]
Hallo,
ich habe diese Meldungen auch massenhaft im Log:
fritzdect.0 | 2021-12-06 12:39:45.808 | warn | State value to set for "fritzdect.0.DECT_116570336286.celsius" has value "7" less than min "8"
Aber bei mir nicht mit "0", sondern mit kleiner "8".
Viele Grüße
Frank

**Comment by foxthefox** [comment]
das ist allerdings recht komisch, da vor der Anpassung der Messbereichsanfang bei 0° lag

**Comment by foxthefox** [comment]
habe jetzt eine neue Version 2.2.0 erstellt, es kann gern getestet werden

**Comment by heitec11** [comment]
Funktioniert leider immer noch nicht:
State value to set for "fritzdect.0.DECT_116570135360.celsius" has value "0" less than min "8"

**Comment by foxthefox** [comment]
Dann kann es nur daran liegen, daß die neuen Eigenschaften nicht übernommen sind, da die Objekte nicht überschrieben werden.
Bitte den Adapter stoppen, den Objektbaum von fritzdect löschen und mit Adapter Start den Objektbaum neu aufbauen lassen.

**Comment by heitec11** [comment]
Danke.
Das war der entscheidene Tip.
Das vorher gemachte Update auf 2.2.3 hatte keinen Effekt auf diese Meldungen.

**Comment by foxthefox** [comment]
dann läuft es ja.
