### ISSUE TITLE
... greater than max "250"

### ISSUE THREAD

**Issue by baerenwaldfreund** [foxthefox/ioBroker.fritzdect#226]
Hallo!

Ich bekomme häufig ein Warning, dass die Spannung den Wert von 250V überschritten hat:

`State value to set for "fritzdect.0.DECT_xxxxxxxxxxxx.voltage" has value "250.589" greater than max "250"`

Ich kann nicht wirklich bewerten, ob der Wert wirklich 250V überschritten hat. Aber da wir direkt neben einem Kraftwerk wohnen, kann das schon sein. Die Warnings kommen immer spät in der Nacht, wenn wenig Strom benötigt wird und deshalb die Spannung kurzfristig diesen Wert überschreiten kann. Die Braunkohlekraftwerke sind halt recht träge. Wir haben dauerhaft eine Spannung von >=240V.

Da man die Höhe der Spannung nicht beeinflussen kann, ist m.E. der Loglevel "warning" unangemessen. Hier wäre "info" besser.

**Comment by foxthefox** [comment]
Als Elektrtechniker finde ich das schon beachtlich, daß die Spannung so hoch ist.
Ich glaube an der Meldung kann ich nicht viel machen, da es meiner Meinung nach eine neue Basisfunktion ist, daß die Grenzen beim Abspeichern geprüft werden.
Was ich machen kann, die obere Grenze mal auf 260 setzen.

**Comment by baerenwaldfreund** [comment]
Ja, das finde ich als Elektrotechniker auch beachtlich, zumal wir eine Nennspannung von 230VAC haben. Habe es gerade nochmal mit einem Multimeter kontrolliert. Aktuell etwas über 240VAC. Das ist auch der Wert, den die DECT-Steckdosen anzeigen. Deshalb gehe ich mal nicht davon aus, dass es nächtliche Fehlmessungen waren.

Ich habe es bisher nur gesehen, dass die max. Spannung, die gemeldet wurde, nie über 251 ging, wäre mir schon geholfen, wenn Du die Grenze auf 251V setzen könntest. Ich lasse jetzt auch mal die Werte in eine Datenbank schreiben, dann sehe ich den Verlauf. Dauert natürlich etwas, bis die Daten da sind bzw. genug Daten zur Auswertung vorhanden sind.

**Comment by foxthefox** [comment]
ich mach mal den max auf 255, dann ist es knapp über 110% Un

**Comment by baerenwaldfreund** [comment]
Super! Recht herzlichen Dank :-)

**Comment by foxthefox** [comment]
habe jetzt eine neue Version 2.2.0 erstellt, es kann gern getestet werden

**Comment by baerenwaldfreund** [comment]
Die Meldungen, dass die Spannung über 250V liegt kommen noch immer:

`State value to set for "fritzdect.0.DECT_xxxxxxxxxxxx.voltage" has value "250.524" greater than max "250"`

**Comment by foxthefox** [comment]
Auch bei version 1.0.0

**Comment by baerenwaldfreund** [comment]
Habe es jetzt so wie beschrieben gemacht. Der Fehler ist seit drei Tagen nicht mehr aufgetreten. Ich gehe davon aus das war's. Danke!
