### ISSUE TITLE
fritzdect Fehler im Protokoll

### ISSUE THREAD

**Issue by JogiBarbarski** [foxthefox/ioBroker.fritzdect#233]
[Raspberry]([url]([url](url))) Pi 4, 8GB![C4A2CB0E-1626-444A-A915-22811C5DD890_1_201_a](https://user-images.githubusercontent.com/59523523/147445645-b76e826b-ab67-4ecb-9f5e-4c459ad3f79a.jpeg)ioBroker.admin 5.2.3
Node.js: v14.18.2
NPM: 6.14.15
js-controller
JS controller Installiert: 3.3.22
OS: linux
Hallo, ich bekomme immer diesen Fehler im Protokoll angezeigt. Benutzername und Passwort habe ich schon mehrfach überprüft, ohne erfolg. Gibt es irgendwas das ich noch tun kann? Viele Grüße und Danke für eure Arbeit  Jörg Barbarski 

2021-12-27 06:28:48.792 | error | no response part in returned message
-- | -- | --
fritzdect.0 | 2021-12-27 06:28:48.789 | error | fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}

**Comment by foxthefox** [comment]
Sind die Berechtigungen in der FB vorhanden?

hier gibt es noch Hinweise:
https://github.com/foxthefox/ioBroker.fritzdect/blob/master/docs/de/troubleshooting.md

**Comment by JogiBarbarski** [comment]
Ja, in der FritzBox sind die gleichen Benutzerdaten eingegeben wie im Adapter. Ich hatte das schonmal gehabt und da hat mir ein netter Mensch im Forum ein Befehl für SSH gegeben und dann war der Fehler weg. Leider habe ich mir das nicht abgespeichert.

**Comment by foxthefox** [comment]
was sagt denn die Fritzbox unter Ereignisse?

**Comment by JogiBarbarski** [comment]
Anmeldung an der Benutzeroberfläche von IP-Adresse [IP-Adresse] gescheitert (ungültige Sitzungskennung). Zur Sicherheit werden alle noch gültigen Sitzungen zur IP-Adresse [IP-Adresse] beendet.

**Comment by foxthefox** [comment]
Es ist die gleiche Aussage, wie im iobroker log. Es gibt keine gültige Session (000000000000).
Welche FW Version hat die FB?
Welche Adapter-Version?

**Comment by JogiBarbarski** [comment]
FRITZ!OS: 07.29 - Version aktuell, 
Adapter Installierte Version: 2.1.15

**Comment by foxthefox** [comment]
hab auch grad nach 7.29 aktualisiert, Anmeldemechanismus funktioniert
welche Meldungen gibt es nach dem Start des Adapters, sind da auch schon Fehler gemeldet? oder ist es nur während des Laufens?

**Comment by foxthefox** [comment]
es kann gern auch die neue Version 2.2.0 probiert werden (github oder npm)
dort gibt es im log auch gleich noch eine Liste der Rechte

**Comment by JogiBarbarski** [comment]
Hallo, jetzt mit der neuen  Version 2.2.0 kommt kein Fehler mehr bis jetzt. Herzlichen Dank für die schnelle Bearbeitung. Euch einen guten Rutsch. Mit freundlichen Grüßen Jörg Barbarski

**Comment by foxthefox** [comment]
dann war es ein Problem was durch viele aufeinanderfolgende Kommandos hrvorgerufen wurde.
