### ISSUE TITLE
State Value to set for "???" has to be type "XXX" but received type "YYY"

### ISSUE THREAD

**Issue by Hini2001** [foxthefox/ioBroker.fritzdect#242]
Guten Morgen und frohes neues Jahr. Seit dem Update auf JS-Controller 3.3.22 habe ich folgendes Problem u.a. mit dem FritzDect Adapter.
Der Adapter schreibt das LogFile regelmäßig mit folgender Meldung voll:

<html>
<body>

fritzdect.0 | 2022-01-02 11:18:12.228 | info | State value to set for "fritzdect.0.DECT_109710520840.endperiod" has to be type "number" but received type "string"
-- | -- | -- | --
fritzdect.0 | 2022-01-02 11:18:12.227 | info | State value to set for "fritzdect.0.DECT_109710520840.boostactiveendtime" has to be type "number" but received type "string"
fritzdect.0 | 2022-01-02 11:18:12.226 | info | State value to set for "fritzdect.0.DECT_109710520840.windowopenactiveendtime" has to be type "number" but received type "string"
fritzdect.0 | 2022-01-02 11:18:12.094 | info | State value to set for "fritzdect.0.DECT_109710365112.endperiod" has to be type "number" but received type "string"
fritzdect.0 | 2022-01-02 11:18:12.094 | info | State value to set for "fritzdect.0.DECT_109710365112.boostactiveendtime" has to be type "number" but received type "string"
fritzdect.0 | 2022-01-02 11:18:12.093 | info | State value to set for "fritzdect.0.DECT_109710365112.windowopenactiveendtime" has to be type "number" but received type "string"

</body>
</html>

Ein löschen der Datenpunkte, sowie ein Neuanlegen (durch den Adapter selbst), hat das Problem nicht gelöst.
Ich hoffe jemand hat ne Idee und kann helfen, das LogFile wird sonst riesig... muss ja nicht sein. :-D

**Versions:**  
 - Adapter version: 2.1.15
 - JS-Controller version: 3.3.22
 - Node version: 12.22.1
 - NPM version: 6.14.12
 - Operating system: debian

**Comment by foxthefox** [comment]
dann ist irgenwas ganz schräg. diese Dinge sind seit längeren schon vom gleichen Typ und das Problem sollte so nicht auftreten.
Korrekt ist das Stoppen des Adapters und das Löschen des Objektbaumes für fritzdect.
Ansonsten bin ich da ratlos.

Auch wenn es keine Änderung an der Stelle gab, darf gern die 2.2.1 von github installiert werden, mit der die Kommunikation IOB-FB verbessert ist.

**Comment by Hini2001** [comment]
Vielen Dank. Habe noch ein weiteres mal alle DPs gelöscht und neu angelegt und jetzt scheint der Fehler weg zu sein. Dieser Fehler scheint bei einigen Adaptern aufzutreten, habe mehrere Issues offen. 
Ansonsten läuft der Adapter einwandfrei. Vielen Dank für die schnelle Hilfe. :-D
