### ISSUE TITLE
Bitte um Erläuterung

### ISSUE THREAD

**Issue by andreaskoerber** [foxthefox/ioBroker.fritzdect#244]
Hallo,
ich verstehe die Definition der Datenpunkte nicht ganz.

1. ) "es gibt 3 Datenpunkte:
windowopenactiv -> zustand bzw. für Kommando"

Ist es der Zustand ("Fenster ist "offen" - oder ein Kommando?)

2.) "windowopenacteendtime -> Zeit wann WIndowactiv beendetest"

Was genau wird hier angegeben? Bei mir steht der Wert immer auf 1.1.1970
Ist es die Zeit, wann das Fenster wieder geschlossen wurde?

3.) "windowopenactivetime -> die Zeit wie lange das eigene Kommando gültig sein soll (neu)"

Welches Kommando? Wenn es der Zustand ist: Was bedeutet dann das "soll"? 
M.E. sinnvoll wäre ein Zähler, wie lange der Zustand "Fenster Offen" schon true ist (wie lange das Fenster also offen ist). Dann kann man abfragen und bei zu langem Lüften ggf. eine Warnung ausgeben o.ä. 

Dank im Voraus

**Comment by foxthefox** [comment]
Windowopenactiv ist Befehl als auch Zustand. Ack=false ist Befehl ack=True ist ein zustandseintrag. 
windowopenactivetime ist die gewünschte Zeit für die eine Fensteroffenkennung gesetzt werden soll. Angabe in Minuten Max 1440. Diese Zeitangabe wird vor Übermittlung in einen Zeitpunkt umgerechnet.
Die übermittelte Zeit wird in der fritzpunkt in einen endzeitpunkt gemerkt und als Status übermittelt.
Soll der fensteroffenkennung zurückgesetzt werden, wird die Zeitangabe 0 übermittelt, was im unixsprachgebrauch 1970 ist, und das steht dann auch im datenpunkt

**Comment by andreaskoerber** [comment]
Danke: Vielleicht bin ich zu sehr Laie:

Wenn Window Open der Zustand ist, inwiefern ist es dann sinnvoll, vorab die Dauer dafür festzulegen, wenn man gar nicht weiß, wie lange das Fenster tatsächlich offen bleibt?

**Comment by foxthefox** [comment]
Der Thermostat hat auch eine eigene Erkennung für offenes Fenster, bzw. auch eine Bedienmöglichkeit am Gerät selbst. Wenn dies erkannt oder betätigt wird, wird es dann auch an die FB und somit an iobroker gemeldet. Dann ändert sich der Zustand.
Die Bedienung aus iobroker heraus kann ein Fenstersensor benutzt werden und dann nimmt man eine Zeit die länger ist als die Lüftungszeit. Bei Statuswechsel am Fenstersensor kann dann zurückgesetzt werden.
