### ISSUE TITLE
Button bei Rollotron verschwunden

### ISSUE THREAD

**Issue by heitec11** [foxthefox/ioBroker.fritzdect#251]
Beim DECT Rollotron Opjekt sind die Button für das direkte Fahren verschwunden.

Version 2.2.3

![Dect_Rollotron](https://user-images.githubusercontent.com/44260876/149072653-15f0991d-8603-489f-b23c-f798610de1d6.jpg)

**Comment by foxthefox** [comment]
die buttons sind noch da, dazu muß man aus dem Expertenmodus herausgehen.
Dann steht anstatt (null) unitialisiert der Button wieder da.
Aber dennoch habe ich die (null) nun mal wie die anderen Werte mal auf false initialisiert. Das war zwar nicht der Punkt, fiel mir aber grad auf.

**Comment by heitec11** [comment]
Danke

**Comment by heitec11** [comment]
Das sieht mit false nun wirklich besser aus.
Der Punkt könnte jetzt geschlossen werden.
