### ISSUE TITLE
hkrmode Änderung ohne Änderung

### ISSUE THREAD

**Issue by Plasmachef** [foxthefox/ioBroker.fritzdect#254]
Danke für die neue (2.2.3) und beste Version ever :-)

Gibt es eine Möglichkeit oder lässt sich das in den kommenden Version berücksichtigen, das der Datenpunkt "hkrmode" nicht bei jeder Abfrage (Fritzbox Polling Interval) eine Änderung erfährt, obwohl er sich de-facto nicht geändert hat?

Das ist für Überwachungs- und Meldesystem etwas verwirrend und muss speziell abgefangen werden.

Herzlichen Dank!

**Comment by foxthefox** [comment]
Die nächste Version soll einen generischen Schalter bekommen, ob Daten immer übernommen werden, oder nur bei Änderung, siehe #76 
Den Code gibt es quasi schon, muß ich nur in die 2.2.3 übernehmen.
Braucht Zeit, ist aber absehbar.

**Comment by Plasmachef** [comment]
Danke für die Antwort / Info!
Ich übe mich in Geduld :smiley:

**Comment by ghostrider95** [comment]
Hi, gibt's dazu schon was neues? Ich wollte mir ein Log zusammenbasteln, wann die Heizungen geschalten wurden (da meine Apple Home Automationen offenbar nicht zuverlässig funktionieren). Leider wird hkrmode bei jeder Aktualisierung auf 1 gesetzt und 500 ms später erst wieder der korrekte, von der FritzBox abgerufene Wert gesetzt. Es kommt somit immer zu Änderungen bei jeder Aktualisierung, obwohl sich faktisch nichts geändert hat.

**Comment by foxthefox** [comment]
eventuell hat sich dein Problem jetzt erledigt, da ich mit der Version 2.3.0 einen Schalter eingeführt habe, der im aktiven Zustand die Datenpunkte nur bei Differenz beschreibt.
Bitte mal Testen und berichten.
