### ISSUE TITLE
fritzdect Adapter zeigt keine Geräte mehr an

### ISSUE THREAD

**Issue by hofb1860** [foxthefox/ioBroker.fritzdect#257]
Mein Fritz Dect Adapter zeigt mir keine Geräte mehr an. Im Log kommt immer diese Fehlermeldung.

![fritz3](https://user-images.githubusercontent.com/96349415/150655828-139d2eba-b2ab-4275-af08-64d957002d34.png)

Ich habe schon alle Versionen durchprobiert. Die 2.2.0, die 2.2.3 und die 2.2.4
Der Adapter 2.2.3 lief Anfangs auch schon mal, bis er plötzlich keine Temperaturen mehr aktualisierte. Hab dann die Instanz und den Adapter gelöscht und wollte neu installieren. Seit dem bekomme ich gar keine Daten mehr. Es kommt immer der selbe Fehler.

[https://forum.iobroker.net/topic/51613/probleme-mit-fritzdect-adapter/15](https://forum.iobroker.net/topic/51613/probleme-mit-fritzdect-adapter/15)
Hier ist alles Dokumentiert was wir schon versucht haben.

Gruß Markus

**Comment by justTux** [comment]
Ich hab exakt das gleiche Problem ... erst lief alles wie gewohnt und dann nicht mehr. Ich habe ebenfalls den Adapter entfernt und neuinstalliert; leider ohne erfolg.

**Comment by ilsirg** [comment]
Bei mir das gleiche...frische iobroker & adapter installation.
Objektbaum wird nicht angelegt und das Log bringt folgende meldung:

fritzdect.0
2022-01-23 12:18:58.268	error	no response part in returned message
fritzdect.0
2022-01-23 12:18:58.268	error	fritzbox returned this {}
fritzdect.0
2022-01-23 12:18:58.268	error	errorHandlerTypeError: Converting circular structure to JSON --> starting at object with constructor 'Socket' | property 'parser' -> object with constructor 'HTTPParser' --- property 'socket' closes the circle

**Comment by foxthefox** [comment]
mit dem log im Forum wird es etwas klarer.
Ich habe keine Ahnung was die FB an Antwort schickt, aber das scheint ein korruptes xml Foramt zu sein, was so nicht umgewandelt werden kann.
Ich habe auf git eine Version die hoffentlich den Fehler abfängt und eine Ausgabe liefert, die weitere Analyse zulässt.
Also bitte mal die Version aus git verwenden.
Welche FW hat die FB?

**Comment by justTux** [comment]
Moin,
ich verwende eine 7390 FRITZ!OS: 06.87 (ja ich weiß die ist EoL aber für die Steckdosen im Keller reicht die noch :D )

Das gibt mir mein Log aus: 
```

fritzdect.0 | 2022-01-24 09:45:55.501 | error | no response part in returned message
fritzdect.0 | 2022-01-24 09:45:55.501 | error | fritzbox returned this {}
fritzdect.0 | 2022-01-24 09:45:55.500 | error | errorHandlerTypeError: Cannot read property 'response' of undefined
fritzdect.0 | 2022-01-24 09:45:55.499 | error | fritzbox returned this undefined
fritzdect.0 | 2022-01-24 09:45:55.499 | error | no response part in returned message
fritzdect.0 | 2022-01-24 09:45:55.498 | error | fritzbox returned this "error http.request: no body received"
fritzdect.0 | 2022-01-24 09:45:54.543 | info | start creating templates
fritzdect.0 | 2022-01-24 09:45:54.543 | info | finished creating devices/groups (if any)
fritzdect.0 | 2022-01-24 09:45:54.499 | info | setting up temperature
fritzdect.0 | 2022-01-24 09:45:54.452 | info | setting up powermeter
fritzdect.0 | 2022-01-24 09:45:54.451 | info | setting up temperature
fritzdect.0 | 2022-01-24 09:45:54.407 | info | setting up powermeter
fritzdect.0 | 2022-01-24 09:45:54.403 | info | setting up alert
fritzdect.0 | 2022-01-24 09:45:54.394 | info | setting up switch
fritzdect.0 | 2022-01-24 09:45:54.393 | info | setting up switch
fritzdect.0 | 2022-01-24 09:45:54.375 | info | CREATE Devices 3
fritzdect.0 | 2022-01-24 09:45:54.073 | info | start creating devices/groups
fritzdect.0 | 2022-01-24 09:45:54.072 | info | checking user permissions
fritzdect.0 | 2022-01-24 09:45:53.674 | info | fritzdect uses USER: iobroker
fritzdect.0 | 2022-01-24 09:45:53.660 | info | fritzdect entered ready
fritzdect.0 | 2022-01-24 09:45:53.647 | info | starting. Version 2.2.4 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v14.18.3, js-controller: 3.3.22
```

**Comment by hofb1860** [comment]
Die letzte Version von Github funktioniert jetzt bei mir wieder.

**Comment by foxthefox** [comment]
> Moin, ich verwende eine 7390 FRITZ!OS: 06.87 (ja ich weiß die ist EoL aber für die Steckdosen im Keller reicht die noch :D )
> 
> Das gibt mir mein Log aus:
> 
> ```
> 
> fritzdect.0 | 2022-01-24 09:45:55.501 | error | no response part in returned message
> fritzdect.0 | 2022-01-24 09:45:55.501 | error | fritzbox returned this {}
> fritzdect.0 | 2022-01-24 09:45:55.500 | error | errorHandlerTypeError: Cannot read property 'response' of undefined
> fritzdect.0 | 2022-01-24 09:45:55.499 | error | fritzbox returned this undefined
> fritzdect.0 | 2022-01-24 09:45:55.499 | error | no response part in returned message
> fritzdect.0 | 2022-01-24 09:45:55.498 | error | fritzbox returned this "error http.request: no body received"
> fritzdect.0 | 2022-01-24 09:45:54.543 | info | start creating templates
> ```

Die FRITZ!OS version (<7.2) verwendet noch das alte login Verfahren, das sollte aber dennoch klappen. Dem log zu urteilen tut es das auch, da 3 geräte angelegt werden.

Tritt der error nur beim Start auf, oder auch später noch mal?
Der Adapter sollte dennoch laufen, oder?
Könnte sein, daß templates in der 6.87 noch nicht unterstützt sind und die Anfrage ins leere läuft.

**Comment by ilsirg** [comment]
Ich verwende auch eine FritzBox 7390 mit 6.87.
Mit der aktuellen Version von git funktioniert es wieder. Danke!

**Comment by justTux** [comment]
> Die FRITZ!OS version (<7.2) verwendet noch das alte login Verfahren, das sollte aber dennoch klappen. Dem log zu urteilen tut es das auch, da 3 geräte angelegt werden.

Anmeldung klappt auch ohne Probleme (meldet auch die FritzBox)
Ja es werden 3 Objekte angelet (passt auch soweit) nur bekommen die keine Werte steht überall null 


> Tritt der error nur beim Start auf, oder auch später noch mal?

Der ganze Adapter schreibt dann keine Logs mehr nach dem error Im Log (außer nache einem Neustart des Updaters)



> Der Adapter sollte dennoch laufen, oder?

zumindest laut ioBroker  läuft er

**Comment by foxthefox** [comment]
habe diverse Verbesserungen gemacht und auch das falsch formatierte xml nun besser verarbeitet.
die Version 2.2.5 auf git sollte laufen und darf gern getestet werden

**Comment by justTux** [comment]
@foxthefox vielen Dank :) scheint wieder zu funktionieren :)
Es gibt nun zwar andere Fehlermeldungen aber ansich läuft es wohl wieder. Ich pack Dir mal das Log mit in den Post, falls es wichtig sein könnte ^^

`

fritzdect.0 | 2022-01-28 14:09:29.247 | info | going over to cyclic polling, messages to poll activity only in debug-mode
-- | -- | -- | --
fritzdect.0 | 2022-01-28 14:09:29.247 | info | finished initial updating devices/groups
fritzdect.0 | 2022-01-28 14:09:29.247 | info | going over to cyclic polling, messages to poll activity only in debug-mode
fritzdect.0 | 2022-01-28 14:09:29.247 | info | finished initial updating devices/groups
fritzdect.0 | 2022-01-28 14:09:28.938 | info | start initial updating devices/groups
fritzdect.0 | 2022-01-28 14:09:28.938 | info | finished creating templates (if any)
fritzdect.0 | 2022-01-28 14:09:28.937 | error | API  err  => [object Object]
fritzdect.0 | 2022-01-28 14:09:28.937 | error | no response part in returned message
fritzdect.0 | 2022-01-28 14:09:28.937 | error | API funct => executeCommand2
fritzdect.0 | 2022-01-28 14:09:28.936 | error | API msg   => relogin failed
fritzdect.0 | 2022-01-28 14:09:28.935 | error | --------------- error calling the fritzbox -----------
fritzdect.0 | 2022-01-28 14:09:27.944 | info | start creating templates
fritzdect.0 | 2022-01-28 14:09:27.944 | info | finished creating devices/groups (if any)
fritzdect.0 | 2022-01-28 14:09:27.900 | info | setting up temperature
fritzdect.0 | 2022-01-28 14:09:27.899 | info | setting up temperature
fritzdect.0 | 2022-01-28 14:09:27.897 | info | setting up powermeter
fritzdect.0 | 2022-01-28 14:09:27.853 | info | setting up powermeter
fritzdect.0 | 2022-01-28 14:09:27.847 | info | setting up switch
fritzdect.0 | 2022-01-28 14:09:27.845 | info | setting up switch
fritzdect.0 | 2022-01-28 14:09:27.838 | info | CREATE Devices 2
fritzdect.0 | 2022-01-28 14:09:27.540 | info | start creating devices/groups
fritzdect.0 | 2022-01-28 14:09:27.539 | error | error in permission xml2json TypeError: Cannot read property 'rights' of undefined
fritzdect.0 | 2022-01-28 14:09:27.538 | info | raw perm =>undefined
fritzdect.0 | 2022-01-28 14:09:27.538 | error | API  err  => [object Object]
fritzdect.0 | 2022-01-28 14:09:27.538 | error | no response part in returned message
fritzdect.0 | 2022-01-28 14:09:27.537 | error | API funct => check_SID
fritzdect.0 | 2022-01-28 14:09:27.537 | error | API msg   => error calling executeCommand
fritzdect.0 | 2022-01-28 14:09:27.536 | error | --------------- error calling the fritzbox -----------
fritzdect.0 | 2022-01-28 14:09:27.518 | info | checking user permissions
fritzdect.0 | 2022-01-28 14:09:27.110 | info | fritzdect uses USER: iobroker
fritzdect.0 | 2022-01-28 14:09:27.097 | info | fritzdect entered ready
fritzdect.0 | 2022-01-28 14:09:27.084 | info | starting. Version 2.2.5 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v14.18.3, js-controller: 3.3.22
fritzdect.0 | 2022-01-28 14:09:23.434 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
fritzdect.0 | 2022-01-28 14:09:23.434 | info | terminating
fritzdect.0 | 2022-01-28 14:09:23.433 | info | cleaned everything up...
fritzdect.0 | 2022-01-28 14:09:23.433 | info | Got terminate signal TERMINATE_YOURSELF
fritzdect.0 | 2022-01-28 14:05:51.299 | info | going over to cyclic polling, messages to poll activity only in debug-mode
fritzdect.0 | 2022-01-28 14:05:51.299 | info | finished initial updating devices/groups
fritzdect.0 | 2022-01-28 14:05:50.993 | info | start initial updating devices/groups
fritzdect.0 | 2022-01-28 14:05:50.992 | info | finished creating templates (if any)
fritzdect.0 | 2022-01-28 14:05:50.992 | error | API  err  => [object Object]
fritzdect.0 | 2022-01-28 14:05:50.991 | error | no response part in returned message
fritzdect.0 | 2022-01-28 14:05:50.991 | error | API funct => executeCommand2
fritzdect.0 | 2022-01-28 14:05:50.990 | error | API msg   => relogin failed
fritzdect.0 | 2022-01-28 14:05:50.990 | error | --------------- error calling the fritzbox -----------
fritzdect.0 | 2022-01-28 14:05:50.032 | info | start creating templates
fritzdect.0 | 2022-01-28 14:05:50.032 | info | finished creating devices/groups (if any)
fritzdect.0 | 2022-01-28 14:05:49.987 | info | setting up temperature
fritzdect.0 | 2022-01-28 14:05:49.945 | info | setting up powermeter
fritzdect.0 | 2022-01-28 14:05:49.943 | info | setting up temperature
fritzdect.0 | 2022-01-28 14:05:49.900 | info | setting up powermeter
fritzdect.0 | 2022-01-28 14:05:49.893 | info | setting up switch
fritzdect.0 | 2022-01-28 14:05:49.892 | info | setting up switch
fritzdect.0 | 2022-01-28 14:05:49.879 | info | CREATE Devices 2
fritzdect.0 | 2022-01-28 14:05:49.582 | info | start creating devices/groups
fritzdect.0 | 2022-01-28 14:05:49.582 | error | error in permission xml2json TypeError: Cannot read property 'rights' of undefined
fritzdect.0 | 2022-01-28 14:05:49.581 | info | raw perm =>undefined
fritzdect.0 | 2022-01-28 14:05:49.581 | error | API  err  => [object Object]
fritzdect.0 | 2022-01-28 14:05:49.581 | error | no response part in returned message
fritzdect.0 | 2022-01-28 14:05:49.581 | error | API funct => check_SID
fritzdect.0 | 2022-01-28 14:05:49.580 | error | API msg   => error calling executeCommand
fritzdect.0 | 2022-01-28 14:05:49.580 | error | --------------- error calling the fritzbox -----------
fritzdect.0 | 2022-01-28 14:05:49.561 | info | checking user permissions
fritzdect.0 | 2022-01-28 14:05:49.155 | info | fritzdect uses USER: iobroker
fritzdect.0 | 2022-01-28 14:05:49.140 | info | fritzdect entered ready
fritzdect.0 | 2022-01-28 14:05:49.127 | info | starting. Version 2.2.5 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v14.18.3, js-controller: 3.3.22

`

**Comment by foxthefox** [comment]
Danke
Das log zeigt mir zumindest, daß in der alten Firmware scheinbar keine templates unterstützt werden.
Und der Aufruf die SessionID zu prüfen scheint auch nicht unterstützt zu sein.
Aber es wird immerhin alles abgefangen und der Adapter läuft weiter.
