### ISSUE TITLE
falscher type

### ISSUE THREAD

**Issue by Scrounger** [foxthefox/ioBroker.fritzdect#26]
@foxthefox 

Ich bekomme immer eine Warn Meldung das der Type falsch sei:
`2018-04-15 08:40:52.105 - warn: javascript.0 Wrong type of fritzdect.0.Comet_XXXXXX.batterylow: "number". Please fix, while deprecated and will not work in next versions.`
das müsste ein Boolean sein, denke das du die Werte 1zu1 aus der API übergibst. Müssten aber in Boolean umgewandelt werden.

Genaus das gleiche hier.
`2018-04-15 08:40:52.105 - warn: javascript.0 Wrong type of fritzdect.0.Comet_XXXXXX.errorcode: "string". Please fix, while deprecated and will not work in next versions.`
Sollte in Number umgewandelt werden.

Kannst du das bitte fixen?

**Comment by foxthefox** [comment]
Bin aus Urlaub zurück und werd mich darum kümmern.

**Comment by foxthefox** [comment]
Bin aus Urlaub zurück und werd mich darum kümmern.

**Comment by foxthefox** [comment]
Bin aus Urlaub zurück und werd mich darum kümmern.

**Comment by foxthefox** [comment]
@scrounger

Ich habe es mir angeschaut, ich habe in beiden Fällen schon den richtigen Datentyp drin.

[boolean](https://github.com/foxthefox/ioBroker.fritzdect/blob/master/main.js#L686)

[number](https://github.com/foxthefox/ioBroker.fritzdect/blob/master/main.js#L698)

dürfte also ein Problem im verwendeten code für den Javascript Adapter liegen.
Dort scheint eine Typumwandlung das Problem zu lösen.

**Comment by Scrounger** [comment]
@foxthefox 
ok type ist richtig definiert, aber ich glaube du übergibst die Werte nicht korrekt.
Weil Boolean darf ja nur true oder false sein. Im datenpunkt steht aber 0 bzw. 1.
![datenpunkt](https://user-images.githubusercontent.com/6370451/38888288-6fd265ce-427b-11e8-9236-3d7741ec12be.jpg)
Musst du da nicht den Wert parsen, da ja die HTTP Api einen xml ausgibt wo eh nur strings drin stehen.
Genauso müsste das auch bei .errorcode sein. Der Wert müsste vor übergabe in Integer geparst werden.

**Comment by foxthefox** [comment]
habe mal die 0.1.2 erstellt, bitte einmal testen, ob es noch zu den type mismatches kommt

**Comment by Scrounger** [comment]
@foxthefox
In der Version 0.2.2 sind ist der Type der neuen Datenpunkte leider auch wieder falsch.

Beispiel:
- fritzdect.0.Comet_XXXX.summeractive ist vom type 'boolean', nimmer aber die Werte 0/1 an

Entweder sollte hier seitens des Adapters eine Übersetzung in false / true erfolgen, oder diese Datenpunkte vom type 'number' sein.

Folgende Datenpunkte sind davon betroffen:
- fritzdect.0.Comet_XXX.devicelock
- fritzdect.0.Comet_XXX.holidayactive
- fritzdect.0.Comet_XXX.lock
- fritzdect.0.Comet_XXX.present
- fritzdect.0.Comet_XXX.summeractive

Das macht bei der Verwendung in Skripten leider immer Probleme

**Comment by Scrounger** [comment]
fixed in #49

**Comment by foxthefox** [comment]
Danke
