### ISSUE TITLE
Wrong temperature warnings in log

### ISSUE THREAD

**Issue by schweigel** [foxthefox/ioBroker.fritzdect#261]
**Describe the bug**  
I get endless of the following log messages: >>State value to set for "fritzdect.0.DECT_116300005183.celsius" has value "6.5" less than min "8"<<
I used an FritzDECT 200 which AVM says it can work from 0°C to 40°C.

**To Reproduce**  
1. Use FritzDECT 200
2. Wait for temperature under 8°C
3. see at log

**Expected behavior**  
No warnings over 0°C.

**Screenshots & Logfiles**  
>>State value to set for "fritzdect.0.DECT_116300005183.celsius" has value "6.5" less than min "8"<<

**Versions:**  
 - Adapter version: 2.2.3
 - JS-Controller version: <js-controller-version> 
 - Node version: 12.22.9
 - Operating system: debian 11

**Additional context**

**Comment by foxthefox** [comment]
the temperature is corrected already to -30...50°C

probably the corrected range is not taken over to the already existing objects.
when an object already exists, it will not be overwritten.
therfore please do:
- stop the adapter
- delete the fritzdect object tree
- start the adapter
all objects will be created with the corrected range.

**Comment by schweigel** [comment]
Ok, I corrected the limits. Thanks
