### ISSUE TITLE
Warnung im Log mit neuer Beta  07.39-94458 der 7590

### ISSUE THREAD

**Issue by ihavenonick** [foxthefox/ioBroker.fritzdect#271]
Adapter Version: 2.2.4

`<html><body>

2022-02-10 10:10:49.956  - warn: fritzdect.0 (2731714)  new datapoint in API detected -> adaptiveHeatingActive
--
2022-02-10 10:10:49.958  - warn: fritzdect.0 (2731714)  new datapoint in API detected -> adaptiveHeatingRunning
2022-02-10 10:10:49.969  - warn: fritzdect.0 (2731714)  new datapoint in API detected -> adaptiveHeatingActive
2022-02-10 10:10:49.970  - warn: fritzdect.0 (2731714)  new datapoint in API detected -> adaptiveHeatingRunning
2022-02-10 10:10:50.790  - warn:  fritzdect.0 (2731714) unknown datapoint  DECT_109710188104.adaptiveHeatingActive please inform devloper and open  issue in github
2022-02-10 10:10:50.791  - warn:  fritzdect.0 (2731714) unknown datapoint  DECT_109710188104.adaptiveHeatingRunning please inform devloper and open  issue in github
2022-02-10 10:10:50.965  - warn:  fritzdect.0 (2731714) unknown datapoint  DECT_092950223000.adaptiveHeatingActive please inform devloper and open  issue in github
2022-02-10 10:10:50.966  - warn:  fritzdect.0 (2731714) unknown datapoint  DECT_092950223000.adaptiveHeatingRunning please inform devloper and open  issue in github

</body>
</html>`

Ansonsten scheint aber alles zu funktionieren.

**Comment by TurboRadler** [comment]
Ich kann den Fehler bestätigen.
Gestern meine Fritz!Box 7590 auf FRITZ!OS 07.39-94458 BETA aktualisiert, seitdem die gleichen Fehlermeldungen für alle Thermostate.

**Comment by ihavenonick** [comment]
Bitte schön ;)

`[{"identifier":"10971 0188104","id":"21","functionbitmask":"320","fwversion":"03.68","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Heizung Wohnzimmer","battery":"10","batterylow":"0","temperature":{"celsius":"210","offset":"-5"},"hkr":{"tist":"42","tsoll":"45","absenk":"32","komfort":"43","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"10","nextchange":{"endperiod":"0","tchange":"43"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"0","adaptiveHeatingRunning":"0"}},{"identifier":"09295 0223000","id":"18","functionbitmask":"320","fwversion":"03.68","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Heizung Bad","battery":"10","batterylow":"0","temperature":{"celsius":"220","offset":"-5"},"hkr":{"tist":"44","tsoll":"44","absenk":"32","komfort":"42","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"10","nextchange":{"endperiod":"0","tchange":"42"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"0","adaptiveHeatingRunning":"0"}},{"identifier":"08761 0043216","id":"23","functionbitmask":"35712","fwversion":"04.16","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","txbusy":"0","name":"Kamera","switch":{"state":"0","mode":"manuell","lock":"0","devicelock":"0"},"simpleonoff":{"state":"0"},"powermeter":{"voltage":"232109","power":"0","energy":"529"},"temperature":{"celsius":"115","offset":"0"}}]`

**Comment by TurboRadler** [comment]
Guten Tag,
bei mir handelt es sich um mehrere FRITZ!DECT 301:
"identifier":"09995 0201755","id":"20003","functionbitmask":"320","fwversion":"04.95","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"HKV-EG-Hobby","battery":"90","batterylow":"0","temperature":{"celsius":"130","offset":"0"},"hkr":{"tist":"26","tsoll":"20","absenk":"26","komfort":"30","lock":"1","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"90","nextchange":{"endperiod":"1645725600","tchange":"26"},"summeractive":"0","holidayactive":"1","adaptiveHeatingActive":"0","adaptiveHeatingRunning":"0"}},

Viel Erfolg

**Comment by foxthefox** [comment]
Danke.
Noch eine Frage, ist in der neuen FB-Oberfläche dazu auch etwas?
Beides Anzeigen? oder eines davon ein Schalter/Taster? Wenn ja, welches der beiden?

**Comment by ihavenonick** [comment]
Wenn Du dafür "adaptiveHeatingRunning" ein Schalter meinst, dann nein zumindest wäre mir nichts aufgefallen.

**Comment by foxthefox** [comment]
die version 2.2.6 auf github kann getestet werden

**Comment by TurboRadler** [comment]
Guten Abend,
bei meinen FRITZ!DECT 301 konnte ich keinen Eintrag in der Bedienoberfläche finden.
Aber mir ist aufgefallen, daß bei den vier Geräten, die direkt am Mesh-Master angemeldet sind, der Wert für "adaptiveHeatingActive" jeweils auf "1" gesetzt ist und bei den anderen auf "0".
"adaptiveHeatingRunning" ist bei allen auf "0" gesetzt. 
In diesem Bereich Smart Home und  FRITZ!DECT 301 hat AVM wohl auch noch "offene Baustellen" vom letzten größeren Upgrade!?
Ich hoffe, das hilft etwas.

**Comment by foxthefox** [comment]
> Die Warnung kommt immer noch. hab mal das Log auf debug und den Adapter neu gestartet:
> 
Hab zwar die Datenpunkte angelegt, hatte aber den Teil beim update vergessen.
Nun sollte es besser sein

**Comment by ihavenonick** [comment]
Nun sind die Warnungen weg

**Comment by TurboRadler** [comment]
> Danke. Noch eine Frage, ist in der neuen FB-Oberfläche dazu auch etwas? Beides Anzeigen? oder eines davon ein Schalter/Taster? Wenn ja, welches der beiden?

Guten Tag,
ich habe im Nachgang doch etwas gefunden:
Entweder bei Gruppe für Geräte, die in einer Gruppe sind oder beim Gerät selbst, wenn es nicht in einer Gruppe ist.
![FritzOS739-AdaptiveHeating](https://user-images.githubusercontent.com/99428808/154153921-ef178cd9-c255-4c88-922f-d7c1ce925d06.jpg)

Die Umsetzung ist noch fehlerhaft, weil der Parameter nur für die Fritz!DECT 301 gesetzt wird, die über die Fritz!Box 7590 angemeldet sind. Bei Geräten aus der gleichen Gruppe, die über eine 7490 angemeldet sind ist der Wert adaptiveHeatingActive nicht gesetzt (0).
