### ISSUE TITLE
New Datapoints available for FritzDect301 (FritzOS 7.39 Labor)

### ISSUE THREAD

**Issue by Jack-RK-24** [foxthefox/ioBroker.fritzdect#277]
As part of the further development AVM has released a new Labor version 7.39 for the FB 7590. This includes further new enhancements for existing Smarthome Devices, incl. FritzDect301 new FW version.
("Verbesserung Für Heizkörperregler kann die Funktion "Adaptiver Heizbeginn" deaktiviert werden (Voraussetzung: Firmware 4.99 für FRITZ!DECT 301) (neu)")

As part of this 2 new Datapoints seem to have been added which are detected by the Adapter:
- adaptiveHeatingRunning
- adaptiveHeatingActive

(see Log screenshot attached)
![Bildschirmfoto vom 2022-02-14 10-49-02](https://user-images.githubusercontent.com/63138075/153840374-64575370-2d5d-421c-bfc6-ae5bc70ebb30.png)

**Comment by foxthefox** [comment]
ist in der 2.2.6 auf github schon implementiert

**Comment by foxthefox** [comment]
schon ausprobiert?

**Comment by Jack-RK-24** [comment]
Jup, sieht gut aus & kann somit geschlossen werden.

**Comment by fichte-112** [comment]
@Jack-RK-24 
Hallo, ich habe das gleiche Problem. 
Wie kann ich die Version 2.2.6 installieren? Im git kann ich sie nicht finden.
