### ISSUE TITLE
unknown datapoint DECT_xxxxxxxxxxxx.adaptiveHeatingRunning

### ISSUE THREAD

**Issue by DeepZone** [foxthefox/ioBroker.fritzdect#278]
Das Protokoll wird aktuell stark von genau solchen Meldungen überhäuft. 
Eine Einschränkung kann ich jedoch bislang keine erkennen. 

Aktuell läuft auf meiner FRITZ!Box die Labor -> 7.39
Ob die Meldungen auch auf der 7.29 auftreten, kann ich nicht sagen. 

Adapterversion: 2.2.3
Node.JS: v14.19.0
ioBroker: v5.2.3
OS: Debian 12

Auszug aus den Protokollen:
fritzdect.0 | 19443 | 2022-02-18 06:27:44.250 | warn | unknown datapoint DECT_xxxxxxxxx.adaptiveHeatingRunning please inform devloper and open issue in github
-- | -- | -- | -- | --
fritzdect.0 | 19443 | 2022-02-18 06:27:44.250 | warn | unknown datapoint DECT_xxxxxxxxx.adaptiveHeatingActive please inform devloper and open issue in github

Diese Fehlermeldung wiederholt sich ständig zu allen angebundenen HKR´s

**Comment by foxthefox** [comment]
ist schon mit der Version 2.2.6 auf github implementiert

**Comment by Deanna4711** [comment]
> Das Protokoll wird aktuell stark von genau solchen Meldungen überhäuft. Eine Einschränkung kann ich jedoch bislang keine erkennen.
> 
> Aktuell läuft auf meiner FRITZ!Box die Labor -> 7.39 Ob die Meldungen auch auf der 7.29 auftreten, kann ich nicht sagen.
> 
> 
Hier genau dasselbe. Der Fehler trat mit dem installieren der Labor Version 7.39 auf.

**Comment by myssv** [comment]
Ich habe die Meldungen auch. Kommt die 2.2.6 bald in stable?

**Comment by foxthefox** [comment]
ja, muß ich mal einen Pull Request aufmachen.

Ansonsten hilft auf jeden Fall die Version aus GitHub zu nehmen und Adapter stoppen und starten
