### ISSUE TITLE
Info: lastalertchgtimestamp" has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by Brainbug01** [foxthefox/ioBroker.fritzdect#288]
Info im Log:

`State value to set for "fritzdect.0.DECT_142760503198-1.lastalertchgtimestamp" has to be type "number" but received type "string"`

Node.js:v12.22.10
NPM:6.14.16
JS:4.0.15

Ist ein RolloTron DECT

**Comment by foxthefox** [comment]
welche Adapter-Version ist es denn?
Sollte eigentlich nicht mehr auftauchen.
Da vorhandene Datenpunkte nicht überschrieben werden, wäre 
- der Adapter zu stoppen
- den Datenpunkt im Objektbaum löschen
-  den Adapter starten
dann wird der Datenpunkt als String angelegt

**Comment by Brainbug01** [comment]
2.2.3 und das löschen hab ich gestern schon gemacht. Ich probier's nochmals.

**Comment by Brainbug01** [comment]
Meldung kam nicht mehr, lag dann doch an mir.
