### ISSUE TITLE
Fritz DECT!200 / 210  "energy" mehr Daten.

### ISSUE THREAD

**Issue by NEA8** [foxthefox/ioBroker.fritzdect#289]
Hallo,

wäre es möglich mehr "Energie Daten" aus den oben genannten DECT Geräten zu erhalten bzw, diese vorzukonfigurieren?
Auf der Fritzbox ist es möglich sich die Daten in verschiedenen Ansichten darstellen zu lassen und somit könnte man eventuell mehr Daten bekommen. 

Wofür wird es benötigt?
Ich nutze die FritzDECT Produkte um den Verbrauch zu anzuzeigen/loggen.
Bsp:
- aktueller Verbrauch (W)
- aktueller Tagesverbrauch (Wh)
- aktueller Wochenverbrauch (Wh)
- aktueller Monatsverbrauch (Wh)
- aktueller Jahresverbrauch (Wh)

Schöne Grüße!

Edit:
Sorry, ich hatte falsche Einstellungen bei den Objekten gehabt Wh sind völlig ausreichend. Hatte es mit kWh verwechselt. Deshalb habe ich den Post etwas angepasst.

**Comment by foxthefox** [comment]
Ich wusste schon nicht wie ich darauf antworten soll, wenn die Auflösung in Wh zu fein ist. :-)
Grundsätzlich ist der Adapter so aufgabeut, daß er die zur Verfüngung gestellten Werte nach ioBroker bringt.
Es gibt noch eine Möglichkeit den Verlauf aus der Fritzbox zu holen, das wäre dann ein Array mit Werten mit einem bestimmten Zeitbereich. Dies kann die API schon, aber ich habe noch keine sinnvolle Implementierung für ioB gefunden. Also ich kann einen Datenpunkt aufmachen und darin befindet sich das array über die Daten, aber das bringt wohl weniger, außer das die Daten in ioB sichtbar sind.
Eher wäre hier eventuel ein anderer Adapter auf die Werte anzusetzen, wie z.B. statistics und sourceanalytics

**Comment by SirFlour** [comment]
Bin grad dabei ein Dashboard mit Neo Creator zu basteln und dort würde das sehr gut helfen. Ich könnte somit dann direkt die Werte mit anzeigen lassen, ohne extra Adapter oder Datenbank laufen zu lassen. Nur weiß ich noch nicht so richtig, ob ich den Array im Neo Creator sauber auseinander bekomme :o/ Müsste ich testen. Oder ginge es auch im iObroker dann aus dem Array in neue Datenpunkte die einzelnen Werte zu schreiben?

![grafik](https://github.com/foxthefox/ioBroker.fritzdect/assets/52317499/cdb8bd2b-f8d6-48b1-aa35-a54abb88adfa)

**Comment by SirFlour** [comment]
ja wow das wäre sehr gut. Sind ja immer doch mehr Konstellationen als man denkt. In meinem Fall ist es nur zum Anzeigen und nicht weiterrechnen. Gerne teste ich hier intensiv und gebe Feedback. Schon mal vielen dank für dein klasse Support hier :)

**Comment by foxthefox** [comment]
Ich habe eine Version 2.5.0 erzeugt, die gern mal getestet werden darf.
Die stats werden genauso oft geholt wie der Rest der Werte, default ist 5min (300 in der admin Seite).
Also kein extra updatezyklus für die stats.
Falls das array angezeigt werden soll, so ist links das neueste und rechts das älteste.

**Comment by SirFlour** [comment]
Top! Konnte version 2.50 erfolgreich installieren. Musste jedoch json controller auf die neuste version updaten, davor wurden keine werte angezeigt. ggf kann man hier ne info / abhängigkeit einbauen. 

Werte kommen an. Für energy day to date aber nicht aktualisert zu werden. Die anderen wurden alle um 8:17 aktualsiert. 

![grafik](https://github.com/foxthefox/ioBroker.fritzdect/assets/52317499/a3865951-3ebc-46b5-822f-80f481d294e7)

![grafik](https://github.com/foxthefox/ioBroker.fritzdect/assets/52317499/7895c2d6-c244-4444-bfe9-8597b32ccf2c)

Jetzt wurde nochmal aktualisert. Die anderen Aktualiseren sich.

![grafik](https://github.com/foxthefox/ioBroker.fritzdect/assets/52317499/1fa59483-468d-4984-a933-fd31a5999f4d)

Passt auch mit der FritzBox excel werte.
![grafik](https://github.com/foxthefox/ioBroker.fritzdect/assets/52317499/2aa10290-d1f9-4df0-9998-2ffbd1abd4b3)

Ich beabachte mal weiter :) vielen dank für die klasse & schnelle Umsetzung sowie ich hoffe mein feedback hilft. bei fragen oder mehr infos, einfach kurz melden

**Comment by foxthefox** [comment]
Also bei mir ist sogar noch js-controller 4.0.2 am laufen. Ich weiß nicht welche Abhängigkeit da jetzt reinspucken sollte, so daß nur die neueste Version geht.
Evetntuell hat es damit zu tun, daß die erste Wertaktualisierung erst mit dem ersten Update kommt, also nach 5min. Die Geräte werden im Gegensatz dazu gleich nach dem Start erstmalig aufgenordet.

Wenn ich es richtig sehe, müsste eigentlich die 82 bzw 105Wh am Tag drin stehen und nicht die 228Wh (Vortag). Wundert mich nur da ich den ersten Wert des dayarrays dafür nehme.
Könnte sein, daß die Werte für mtd und ytd auch nicht passen, das könntest du mal parallel prüfen.

**Comment by foxthefox** [comment]
Ich denke es betraf nur den Tageswert. Den habe ich nach dem mtd aus einem geänderten array entnommen, und nicht aus dem originalen.
mtd und ytd müssten richtig sein.
Es gibt nun eine Version 2.5.1 in github zum testen

**Comment by SirFlour** [comment]
Ja genau, war nur der Day Wert. Die anderen Werte haben sich aktualisiert.

Ahh dann hatte ich wohl nicht lange genug gewartet. Kann jetzt aber bestätigen, dass es mit dem 5er js-controller auch funktioniert^^ 

Habe die 2.5.1 version am Testen. :)

**Comment by SirFlour** [comment]
Werte aktualisieren sich alle gut und der Adapter lief ohne Probleme durch. Hab es für zwei Steckdosen und der FritzBox 6890 LTE getestet. 

Konnte es auch gut in mein Dashboard integrieren (siehe unten).

Kann ich noch was testen? :) 

![grafik](https://github.com/foxthefox/ioBroker.fritzdect/assets/52317499/f44216a3-600c-41f3-9ddc-8af29cd81316)

**Comment by foxthefox** [comment]
Ich denke für den Teil der Statistik passt es.
Falls ein Thermostat vorhanden ist, dann wäre mit 2.5.2 das Issue #164 noch zu testen.

Das hier mach ich dann mal zu.
