### ISSUE TITLE
Request, support new ULE-Devices like dect switch 

### ISSUE THREAD

**Issue by hhl-de** [foxthefox/ioBroker.fritzdect#29]
Hello,

the newest AVM-Update (7.0) opens the DECT protocol for other deces via ULE. 

see:
[link to AVM Page, supported ULE devices](https://avm.de/fritz-labor/fritz-labor-fuer-fritzbox-7490-7590-und-7580/neues-verbesserungen/unterstuetzung-von-dect-ulehan-fun/)

I've bought the following device to test:
[WandTaster](https://www.smarthome.de/geraete/smarthome-wandtaster-weiss)

It is perfectly integrated into FritzBox, but unfortunate it is not working with the gretaioBroker.fritzdect plugIn. I've read out via the debug button the following lines.

```javascript
[{"identifier":"119XXXXXXX-2","id":"2000","functionbitmask":"8200","fwversion":"0.0","manufacturer":"0x0feb","productname":"HAN-FUN","present":"1","name":"DectTaster_F1","etsiunitinfo":{"etsideviceid":"406","unittype":"273","interfaces":"772"},"button":{"lastpressedtimestamp":"1538426492"}},
{"identifier":"119XXXXXXX-1","id":"2001","functionbitmask":"8200","fwversion":"0.0","manufacturer":"0x0feb","productname":"HAN-FUN","present":"1","name":"DectTaster_F2","etsiunitinfo":{"etsideviceid":"406","unittype":"273","interfaces":"772"},"button":{"lastpressedtimestamp":"1538426453"}},
{"identifier":"1165700XXXXX","id":"16","functionbitmask":"2688","fwversion":"03.87","manufacturer":"AVM","productname":"FRITZ!DECT 210","present":"0","name":"Weihnachtsbeleuchtung","switch":{"state":"","mode":"","lock":"","devicelock":""},"powermeter":{"voltage":"","power":"","energy":""}},
{"identifier":"087610XXXXXX","id":"17","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"3D-Drucker","switch":{"state":"0","mode":"auto","lock":"0","devicelock":"0"},"powermeter":{"voltage":"241046","power":"0","energy":"17960"},"temperature":{"celsius":"220","offset":"0"}},{"identifier":"119XXXXXXX","id":"406","functionbitmask":"1","fwversion":"00.00","manufacturer":"0x0feb","productname":"HAN-
```
Is it possible to extend it with such a device? 
Would be great - thanks. I can support with testing.

**Comment by foxthefox** [comment]
Perfect, that you have found the button for the debugging. :-)
It should be easy to add the contact, the adapter already contains a contact, seems that the function bit mask is different. I'll check it and come back to you.

**Comment by foxthefox** [comment]
one additional question, the button can be pressed and the it returns in the depressed state, correct?
Inside the lines is only the information when it was pressed and not the state, so I presume that it is the above case. If it is like that, then the implementation in the adapter is probably not what you expect. The adapter polls the data (usually within 5 min) so it will appear after a certain time and it does only say, that it was pressed at a certain time. So it will not be promply do an action within iobroker.

**Comment by foxthefox** [comment]
please check the version 0.1.4 if the button is recognized.
timestamp ist currently only in epoch (ms from 1970)
if adapter works, I could additional change to readable format

**Comment by hhl-de** [comment]
Hi, thanks for adaptation!
Unfortunate its not working.

I interpret the information the same way like you, there is only a lastpressedtimestamp available.
I've attached a short protocol...
[IoBrokerDect_v0_14.docx](https://github.com/foxthefox/ioBroker.fritzdect/files/2457807/IoBrokerDect_v0_14.docx)

Log find here:
[IoBrokerDect_v0_14.txt](https://github.com/foxthefox/ioBroker.fritzdect/files/2457864/IoBrokerDect_v0_14.txt)

hope this helps you - BR, Hagen

Here some newest logs. In the Main-Log file there is only one error due to missing rights for WiFi reading.
`[{"identifier":"119340141058-2","id":"2000","functionbitmask":"8200","fwversion":"0.0","manufacturer":"0x0feb","productname":"HAN-FUN","present":"1","name":"DectTaster_F1","etsiunitinfo":{"etsideviceid":"406","unittype":"273","interfaces":"772"}
,"button":{"lastpressedtimestamp":"1539031310"}
}
,{"identifier":"119340141058-1","id":"2001","functionbitmask":"8200","fwversion":"0.0","manufacturer":"0x0feb","productname":"HAN-FUN","present":"1","name":"DectTaster_F2","etsiunitinfo":{"etsideviceid":"406","unittype":"273","interfaces":"772"}
,"button":{"lastpressedtimestamp":"1539031311"}
}`

**Comment by foxthefox** [comment]
Thanks a lot for the protocols and especially the docx. Now I see a short but important thing, the button has one address but consists of 2 elements which can be pressed and therefore -01 and -02 is added to the AIN.
I will change my implementation and come back to you.

**Comment by foxthefox** [comment]
I have added some more and also more debugging.
Please install the github version (best to delete the adapter first).
And please post the log.

**Comment by hhl-de** [comment]
SUCCESS :+1: 

I've tested the newest version, and there are created object data for each taster. In a java script I was able to react on a new timestamp and if I set the pollin time to one sec. it is really ok. Many many thanks.

There are some screenshots in the attachement. Do you need more logs?

[IoBrokerDect_v0_14_2018_01_10.docx](https://github.com/foxthefox/ioBroker.fritzdect/files/2465882/IoBrokerDect_v0_14_2018_01_10.docx)

**Comment by foxthefox** [comment]
Thanks for the feedback, I think that I will delete the useless portion of the device. Do you need the timestamp in another format, or can I leave it like it is?
