### ISSUE TITLE
State value to set for "fritzdect.0.DECT_XXXXX.energy"  greater than max "999999999"

### ISSUE THREAD

**Issue by DominikJaco** [foxthefox/ioBroker.fritzdect#290]
Adapterversion: 2.2.6
Node.JS: v14.19.1
ioBroker: v5.2.3
NPM: 6.14.16
OS: Debian GNU/Linux 11
Auszug aus den Protokollen:

fritzdect.0	warn	State value to set for "fritzdect.0.DECT_XXXXXXX.energy" has value "1080878761" greater than max "999999999"

0127273","id":"25","functionbitmask":"35712","fwversion":"XXXX","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","txbusy":"0","name":"XX","switch":{"state":"0","mode":"manuell","lock":"0","devicelock":"0"},"simpleonoff":{"state":"0"},"powermeter":{"voltage":"228853","power":"0","energy":"1080878761"},"temperature":{"celsius":"180","offset":"-55"}},{"identifier":"XXXX

**Comment by foxthefox** [comment]
das ist ein wenig komisch der aktuelle wert ist 10% vom maximalen Wert, die Meldung dürfte also so nicht kommen. Im Adapter habe ich die 999999999 als maximalen Wert eingetragen, das entspricht glaube ich dem Datenblatt.
Die Meldungen kommen glaube ich aus dem JS-controller, welche Version hat der denn?

**Comment by DominikJaco** [comment]
Meinst du den?
Node.JS: v14.19.1

**Comment by foxthefox** [comment]
nein, den js-controller, der steht unter hosts und kann 3.3.x oder 4.0.x sein

**Comment by DominikJaco** [comment]
okay, ist 4.0.21
(sorry für die späte Antwort, war in Urlaub und konnte es daher nicht nachschauen)

**Comment by foxthefox** [comment]
zeigt eigentlich die fritzbox auf der Oberfläche den gleichen hohen wert?

**Comment by foxthefox** [comment]
hab jetzt eine 9 mehr spendiert
