### ISSUE TITLE
Comet Dect Boost

### ISSUE THREAD

**Issue by duczz** [foxthefox/ioBroker.fritzdect#297]
Der Comet Dect hat ja keine Boost Funktion.
Wäre es möglich im Adapter folgendes einzurichten?
Wenn Boost gedrückt wird, wird geprüft ob das Model "Comet Dect" ist wenn ja mir der hkmode auf auf gestellt, wenn die hinterlegte Zeit abgelaufen ist wieder zurück.

Wäre doch eine sinnvolle Funktion im Adapter oder?

**Comment by foxthefox** [comment]
Grundsätzlich wäre die Idee verwirklichbar, macht den Adapter auch komplizierter.
Lässt sich aber genausogut über ein script lösen.

**Comment by duczz** [comment]
Dann lassen wir das mal als Feature offen, es wundern sich bestimmt viele warum man boost drückt und nix passiert.

**Comment by foxthefox** [comment]
das war mir so nicht klar, daß es den Datenpunkt boost gibt. Aber das ist dann ein Problem der FB, es werden nur Datenpunkte angelegt, die von der FB über die API gemeldet werden. Ich gehe davon aus, daß die FB nicht pauschal alle Datenpunkte anbietet, die es mittlerweile gibt, sondern diejenigen die vom DECT Gerät auch unterstützt werden.

**Comment by duczz** [comment]
Anbei das simple Blockly, falls du es implementieren willst.
![image](https://user-images.githubusercontent.com/25475385/162889670-cd44ddbb-82f4-4e43-bc80-4dace52702a9.png)

**Comment by Chaot1** [comment]
Die Boot Funktion funktioniert doch einwandfrei mit den Comet Dect Thermostaten.
Kann doch mittlerweile geschlossen werden.

**Comment by duczz** [comment]
@Chaot1 Welche FritzOS Version und Comet Dect Version nutzt du? Bei mir funktioniert die funktion nämlich nicht, in der Fritzbox wird es zwar angezeigt am Comet kommt der boost aber nicht an, nur wenn ichs via hrmode mache

**Comment by Chaot1** [comment]
Ich habe eine FB 6690 mit FW 7.50 (hat auch mit 7.29 funktioniert), Comet-Dect Thermostate mit der FW 3.4 und FritzDect 301 mit FW 5.08. An allen Thermostaten klappt das Boost ohne Probleme

**Comment by duczz** [comment]
FW 3.4 ist ja richtig alt ^^- unter der aktuellen Firmware klappts auf jeden fall nicht

**Comment by Chaot1** [comment]
Ich habe für die Dinger nie eine aktuellere FW gefunden. Da habe ich scheinbar Glück, dass es mit der alten Firmware klappt.
