### ISSUE TITLE
Warnmeldungen wegen zu hoher Temperatur

### ISSUE THREAD

**Issue by ManfredHi** [foxthefox/ioBroker.fritzdect#298]
Einer meiner FritzDect 200 hat im Sommer über immer eine Temperatur von über 32 Grad, da er am Dachboden installiert ist. Dadurch erscheint im Log-File bei jeder Abfrage eine Warn-Meldung auf.

Könnte man in den Adaptereinstellungen eventuell einen Minimal- und Maximalwert für die Temperatur vorsehen? 

![image](https://user-images.githubusercontent.com/103682996/163458631-b85b74e1-5d1d-4c80-bb6a-68674046cc0f.png)

**Comment by foxthefox** [comment]
Sollte eigentlich jetzt schon kein Problem sein. Max Temp ist auf 50° eingestellt.
Welche Version des Adapters ist es denn?
Ggf. müssen die Datenpunkte gelöscht werden, da beim Update diese nicht neu angelegt werden, und somit die neuen Grenzen nicht übernommen werden. (Adapter upgrade, Adapter stop, Datenpunkte löschen, Adapter starten)

**Comment by 4eversr** [comment]
Hallo, ich hatte das gleiche Problem mit einem meiner Fritzdect-Adapter, der mir eine Temperatur von 33,5 meldete. Das führte auch zur "grester than max 32" Meldung.
Ich habe dann den fritzdect Adapter gestoppt, und dann den "Celsius"-Datenpunkt des betroffenen FritzDect-Steckers gelöscht. Danach habe ich den iobroker fritzdect-Adapter wieder gestartet und die Fehlermeldung im Log ist weg, obwohl der Adapter mir natürlich immer noch 33,5 Grad meldet.

**Comment by foxthefox** [comment]
Ist aus meiner sicht ein normales Verhalten, wenn der Adapter die neue Version mit verbesserten Range hat. Der neue Meßbereich wird nicht übernommen, da es einen exitierenden Datenpunkt gibt, erst wenn dieser gelöscht wird, wird bei der Neuanlage (durch Neustart) der erweiterte Meßbereich berücksichtigt
