### ISSUE TITLE
FritzBox Passwort im Klartext

### ISSUE THREAD

**Issue by ratte-rizzo** [foxthefox/ioBroker.fritzdect#31]
Das Passwort zum Login in die FritzBox wird im Klartext auf der Adapter-Config-Seite angezeigt. Sicherheitstechnisch bedenklich. 

Danke fürs Korrigieren.

**Comment by foxthefox** [comment]
hab mal etwas eingebaut, bitte prüfen.

**Comment by ratte-rizzo** [comment]
Shit, das hab ich jetzt davon. Ich bin bei Github ein totaler Frischling. Magst Du mir nen Tipp geben, was ich genau machen muss?

Danke übrigens für die schnelle Antwort!!!

**Comment by foxthefox** [comment]
adapter löschen und in der Kommandozeile

npm install https://github.com/foxthefox/ioBroker.fritzdect/tarball/master --production

ggf mit sudo

und auf jeden Fall im iobroker-Verzeichnis (raspi -> /opt/ioboker)

ausführen

**Comment by andreas-hafner** [comment]
Funktioniert prima. Danke.
