### ISSUE TITLE
Fritzdect V2.2.3 unknown datapoint 

### ISSUE THREAD

**Issue by uwered** [foxthefox/ioBroker.fritzdect#319]
Fritzdect V2.2.3
unknown datapoint DECT_119590251608.adaptiveHeatingActive please inform devloper and open issue in github
unknown datapoint DECT_119590252008.adaptiveHeatingRunning please inform devloper and open issue in github

Die Meldungen kommen für jedes Thermostat.

Fritz CometDect v.3.54

**Comment by foxthefox** [comment]
mit der Version 2.2.6 von Github sollte dies schon behoben sein

**Comment by blabond** [comment]
Hey,

Bei mir kommt das gleiche:

fritzdect.0 2022-09-04 12:27:27.808	warn	unknown datapoint DECT_XXX.adaptiveHeatingRunning please inform devloper and open issue in github

fritzdect.0 2022-09-04 12:27:27.807	warn	unknown datapoint DECT_XXX.adaptiveHeatingActive please inform devloper and open issue in github

fritzdect.0 2022-09-04 12:27:27.658	warn	unknown datapoint DECT_XXX.adaptiveHeatingRunning please inform devloper and open issue in github

fritzdect.0 2022-09-04 12:27:27.657	warn	unknown datapoint DECT_XXX.adaptiveHeatingActive please inform devloper and open issue in github



Die DECT ID Nummer habe ich raus editiert.

Verwendetes Gerät: FRITZ!DECT 301 (Thermostate)
Version: 05.02

FritzBox Version FRITZ!OS:7.39-99494 BETA (Beta von 7.50)

**Comment by foxthefox** [comment]
bitte die version aus github installieren und dann sollten die neuen Datenpunkte auch eröffnet sein
