### ISSUE TITLE
Adapter wird jede Minute neu gestartet

### ISSUE THREAD

**Issue by actionbyte** [foxthefox/ioBroker.fritzdect#321]
Laut dem Log wird der Adapter jede Minute neu gestaret. Warum?

`<html><body>

host.raspberrypi | 2022-06-24 05:13:00.697 | info | instance system.adapter.fritzdect.0 scheduled normal terminated and will be restarted on schedule.
-- | -- | -- | --
host.raspberrypi | 2022-06-24 05:12:02.065 | info | instance system.adapter.fritzdect.0 started with pid 19541
host.raspberrypi | 2022-06-24 05:12:00.706 | info | Restart adapter system.adapter.fritzdect.0 because enabled
host.raspberrypi | 2022-06-24 05:12:00.705 | info | instance system.adapter.fritzdect.0 scheduled normal terminated and will be restarted on schedule.
host.raspberrypi | 2022-06-24 05:11:01.915 | info | instance system.adapter.fritzdect.0 started with pid 9824
host.raspberrypi | 2022-06-24 05:11:00.716 | info | Restart adapter system.adapter.fritzdect.0 because enabled
host.raspberrypi | 2022-06-24 05:11:00.715 | info | instance system.adapter.fritzdect.0 scheduled normal terminated and will be restarted on schedule.

</body>
</html>`

**Comment by foxthefox** [comment]
Der Adapter ist so nicht konzipiert und bisher so auch nicht beobachtet.
Welche Adapter Version ist es und welche nodejs und iobroker Version?
Was wird noch so geloggt? Warnungen Errors?
Was passiert wenn man in debug umstellt und sind dort andere Meldungen vor dem normalen termination?

**Comment by actionbyte** [comment]
Habe beim Umschalten auf Debug über Expert-Modus jetzt gesehen das ich beim Neustart des Adapters anstatt "05***" das hier "*5***" eingetragen hatte. Daher der Neustart jede Minute. Mein Fehler, sorry. Hatte irgendwann den Neustart eingestellt weil die FB das Login verweigerte obwohl User und PW passte. Ich beobachte das Verhalten weiter, sonst nehme ich den Neustart um 5 Uhr ebenfalls raus.
