### ISSUE TITLE
GuestWLAN falsch bzw. kein Zugriff

### ISSUE THREAD

**Issue by fs-plugins** [foxthefox/ioBroker.fritzdect#33]
Fritzbox 7590, OS 07.01
in der Fritzbox: Gastzugang aktiv

Adapterversionen  0.1.4, 0.1.5, 0.2.0
state im Adapter-Objekt: false (ack-> false)

ack bleibt false und state bleibt false, egal ob Objekt oder Fritzbox geändert wird

**Comment by foxthefox** [comment]
Fritzboxänderungen kommen erst nach 5min durch, sofern es in den Adaptereinstellungen bei 300 geblieben ist. Und es braucht ein Häkchen für die GastWLAN Abfrage.
Ack=false ist Kommando und Ack=true eine Rückmeldung.

Du könntest mal eine Umschaltung machen und im debug modus schauen, ob es auch einen Befhl gabe " Turned WLAN ..."

Ich muß dazusagen, daß GästeWLAN keine native Funktion von der Fritzbox API ist und eigentlich nicht in den Adapter gehört. Überlege auch schon das herauszuwerfen, weil die Funktion über Auswertung von Webseiteninhalt funktioniert und bei Änderungen der FritzOS Oberfläche immer wieder Probleme auftauchen.

**Comment by fs-plugins** [comment]
es hatte ja mal funktioniert, sonst wäre ich gar nicht auf einen Fehler gekommen (Einstellungen sind also korrekt)
wäre schade, wenn es nicht mehr berücksichtigt würde
habe es mal mit dem Adapter tr-064 versucht, da geht es jetzt nach dem letzten Update 

2019-01-19 12:35:33.657 - info: fritzdect.0 GuestWLAN identified for command (state) : false
2019-01-19 12:35:35.488 - debug: fritzdect.0 Turned WLAN off
2019-01-19 12:35:35.491 - debug: fritzdect.0 stateChange fritzdect.0.GuestWLAN.state {"val":true,"ack":false,"ts":1547897735489,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1547897735489}
2019-01-19 12:35:35.491 - debug: fritzdect.0 ack is not set! -> command

**Comment by foxthefox** [comment]
from version 1.0.0 the adapter will only use the native API functions from AVM. Any scraping from the webpage is not a sustainable solution. TR64 is the right way for such things.
