### ISSUE TITLE
error: no response part in returned message

### ISSUE THREAD

**Issue by ts617284** [foxthefox/ioBroker.fritzdect#331]
Hello,

I have the following problem with my installed fritzdect adapter (v2.2.3): When connecting the returend object ist empty, and no data points are generated under "objects". Log says:

`fritzdect.0 | 2022-08-27 14:31:58.433 | error | no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2022-08-27 14:31:58.432 | error | fritzbox returned this {}
fritzdect.0 | 2022-08-27 14:31:58.432 | error | errorHandlerTypeError: Converting circular structure to JSON     --> starting at object with constructor 'TLSSocket'     \|     property 'parser' -> object with constructor 'HTTPParser'     --- property 'socket' closes the circle
fritzdect.0 | 2022-08-27 14:31:58.418 | info | checking user permissions
fritzdect.0 | 2022-08-27 14:31:57.799 | info | fritzdect uses USER: iobroker
fritzdect.0 | 2022-08-27 14:31:57.781 | info | fritzdect entered ready
fritzdect.0 | 2022-08-27 14:31:57.759 | info | starting. Version 2.2.3 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v14.19.1, js-controller: 4.0.23
`

BUT: If I look directly in the settings of the adapter into "debug output" I find all the correct data , for example here "my devices":
![grafik](https://user-images.githubusercontent.com/22727405/187030655-cd9083b5-94ae-4e03-8880-6e001c94ac50.png)
also all the other debug outputs deliver correct data.

I am using the IP address "https://192.168.1.1", but also using only "http://" doesn't change the error.

Any idea how to fix that?

Every help is appreciated! Thanks!

Regards,
Tim

**Comment by ts617284** [comment]
I have tested version 2.2.6 from github. 
It solves most of the issues (object are now generated).
But I still have some error messages in the log about "no response part in returned message":

fritzdect.0 | 2022-08-28 14:08:07.937 | info | going over to cyclic polling, messages to poll activity only in debug-mode
-- | -- | -- | --
fritzdect.0 | 2022-08-28 14:08:07.937 | info | finished initial updating devices/groups
fritzdect.0 | 2022-08-28 14:08:07.671 | info | start initial updating devices/groups
fritzdect.0 | 2022-08-28 14:08:07.670 | info | finished creating templates (if any)
fritzdect.0 | 2022-08-28 14:08:07.619 | info | setting up Template DG_Gaeste_weg
fritzdect.0 | 2022-08-28 14:08:07.618 | info | setting up Template DG_Gaeste_da
fritzdect.0 | 2022-08-28 14:08:07.615 | info | create Templates 2
fritzdect.0 | 2022-08-28 14:08:06.859 | info | start creating templates
fritzdect.0 | 2022-08-28 14:08:06.859 | info | finished creating devices/groups (if any)
fritzdect.0 | 2022-08-28 14:08:06.769 | info | setting up thermostat nextchange
fritzdect.0 | 2022-08-28 14:08:06.762 | info | setting up thermostat nextchange
fritzdect.0 | 2022-08-28 14:08:06.739 | info | setting up thermostat
fritzdect.0 | 2022-08-28 14:08:06.737 | info | setting up thermostat
fritzdect.0 | 2022-08-28 14:08:06.736 | info | setting up groupinfo
fritzdect.0 | 2022-08-28 14:08:06.735 | info | setting up groupinfo
fritzdect.0 | 2022-08-28 14:08:06.727 | info | CREATE groups 2
fritzdect.0 | 2022-08-28 14:08:06.632 | info | setting up thermostat nextchange
fritzdect.0 | 2022-08-28 14:08:06.622 | info | setting up thermostat nextchange
fritzdect.0 | 2022-08-28 14:08:06.609 | info | setting up thermostat nextchange
fritzdect.0 | 2022-08-28 14:08:06.478 | info | setting up thermostat
fritzdect.0 | 2022-08-28 14:08:06.477 | info | setting up thermostat
fritzdect.0 | 2022-08-28 14:08:06.475 | info | setting up thermostat
fritzdect.0 | 2022-08-28 14:08:06.473 | info | setting up temperature
fritzdect.0 | 2022-08-28 14:08:06.472 | info | setting up temperature
fritzdect.0 | 2022-08-28 14:08:06.439 | info | setting up temperature
fritzdect.0 | 2022-08-28 14:08:06.381 | info | CREATE Devices 3
fritzdect.0 | 2022-08-28 14:08:06.170 | info | start creating devices/groups
fritzdect.0 | 2022-08-28 14:08:06.170 | error | error in permission xml2json TypeError: Cannot read property 'rights' of undefined
fritzdect.0 | 2022-08-28 14:08:06.170 | info | raw perm =>undefined
fritzdect.0 | 2022-08-28 14:08:06.169 | error | API  err  => [object Object]
fritzdect.0 | 2022-08-28 14:08:06.169 | error | no response part in returned message
fritzdect.0 | 2022-08-28 14:08:06.169 | error | API funct => check_SID
fritzdect.0 | 2022-08-28 14:08:06.169 | error | API msg   => error calling executeCommand
fritzdect.0 | 2022-08-28 14:08:06.168 | error | --------------- error calling the fritzbox -----------
fritzdect.0 | 2022-08-28 14:08:06.131 | info | checking user permissions
fritzdect.0 | 2022-08-28 14:08:04.571 | info | fritzdect uses USER: ioBroker
fritzdect.0 | 2022-08-28 14:08:04.552 | info | fritzdect entered ready
fritzdect.0 | 2022-08-28 14:08:04.526 | info | starting.  Version 2.2.6 (non-npm: foxthefox/ioBroker.fritzdect) in  /opt/iobroker/node_modules/iobroker.fritzdect, node: v14.19.1,  js-controller: 4.0.23

**Comment by foxthefox** [comment]
At the moment I have no idea, whats going on. The second log shows problems to connect with the FB, no session (SID) and no response to see the permissions. But strangely the FB has answered with the objects and the devices are created.

What FB is it? and which software version?

**Comment by ts617284** [comment]
Hi,

it's a Fritz!Box 6660 with FRITZ!OS: 07.24
Here are the settings:
![grafik](https://user-images.githubusercontent.com/22727405/187087346-e0182fa8-897a-47cc-8f68-9536ccce647c.png)


What kind of user rights does the FritzBox user need to have? Currently my user has "smart home", but no admin rights.

Thx for your help!

**Comment by foxthefox** [comment]
The settings are OK. 
What is displayed if you hit "Meine Rechte"? 
only "smart home" should be sufficient.
How often is the FB having an empty response and causing the error? I hope that it is not every 5min

**Comment by ts617284** [comment]
"meine Rechte":
![grafik](https://user-images.githubusercontent.com/22727405/187088626-6bea477b-a1cc-45dc-ae69-a3c1a54a8fd0.png)

the error in the log appears only when starting the adapter. Normal log shows nothing afterwards, log level "debug" shows no error, only the normal polling activities every 5min. Didn't see the error anywhere else.

**Comment by foxthefox** [comment]
thanks for the information.
If it is only at startup, I have some time for investigation

**Comment by foxthefox** [comment]
The error message is an error in communication and states that the API-call was not succesful and outputs the relevant messages. It is related to an API-call after start of the adapter.
I extended the text in the message, to be more precise
