### ISSUE TITLE
07.08-64610 Labor Version

### ISSUE THREAD

**Issue by slimline33** [foxthefox/ioBroker.fritzdect#34]
Hi, habe aktuell Probleme mit der letzten Fritzbox Labor 07.08-64610 BETA. 

Damit geht leider die API bzw. der TR-64 Zugang nicht. Kann das jemand nachvollziehen? Werde wieder auf die letzte Version downgraden!

Debuglog: 

`

fritzdect.0 | 2019-01-16 13:50:55.237 | debug | Did not get session id- invalid username or password?
-- | -- | -- | --
fritzdect.0 | 2019-01-16 13:50:54.852 | debug | Did not get session id- invalid username or password?
fritzdect.0 | 2019-01-16 13:50:54.263 | debug | Did not get session id- invalid username or password?
fritzdect.0 | 2019-01-16 13:50:53.075 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-16 13:50:48.309 | debug | Did not get session id- invalid username or password?
fritzdect.0 | 2019-01-16 13:50:47.695 | info | SWITCH ID: 087610389707 identified for command (state) : true
fritzdect.0 | 2019-01-16 13:50:47.695 | debug | ack is not set! -> command
fritzdect.0 | 2019-01-16 13:50:47.693 | debug | stateChange fritzdect.0.DECT200_087610389707.state {"val":true,"ack":false,"ts":1547643047669,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1547643047669}
fritzdect.0 | 2019-01-16 13:50:27.225 | debug | Did not get session id- invalid username or password?
fritzdect.0 | 2019-01-16 13:50:26.940 | debug | Did not get session id- invalid username or password?
fritzdect.0 | 2019-01-16 13:50:26.641 | debug | Did not get session id- invalid username or password?
fritzdect.0 | 2019-01-16 13:50:26.338 | debug | Did not get session id- invalid username or password?
fritzdect.0 | 2019-01-16 13:50:26.037 | debug | Did not get session id- invalid username or password?
fritzdect.0 | 2019-01-16 13:50:25.737 | debug | Did not get session id- invalid username or password?
fritzdect.0 | 2019-01-16 13:50:25.440 | debug | Did not get session id- invalid username or password?
fritzdect.0 | 2019-01-16 13:50:23.069 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-16 13:50:23.019 | debug | WLAN poll :true
fritzdect.0 | 2019-01-16 13:50:22.997 | info | entered ready
fritzdect.0 | 2019-01-16 13:50:22.950 | info | starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v8.15.0

`

Gruß slimline

**Comment by frankyboy1973** [comment]
Hi, ich hatte nach Update auf die neue Adapter Version 0.1.5 auch Probleme mit der Anmeldung. Ich habe in der Adapter Konfiguration meinen Benutzernamen und mein Passwort neu eingegeben und seit dem läuft es wieder.
Fritzbox 7360, OS 6.85

**Comment by foxthefox** [comment]
Habe in 0.1.5 auch etas mit der Sichtbarkeit des Passwortes geändert, somit ist es erklärbar.

**Comment by frankyboy1973** [comment]
Mir wurde nur leider im Iobroker Log keine Fehlermeldung ausgegeben und die Instanz stand auch auf grün. Ich habe es nur daran gemerkt das die Thermostate nicht mehr gesteuert wurden, ich keine Aktuellen Werte mehr bekommen habe und es dann im Log der Fritzbox gesehen, das die Anmeldung fehlgeschlagen ist.

**Comment by slimline33** [comment]
Es gibt wohl probleme mit der Authentifizierung. Habe das selbe auch mit einem bash script wo ich die dect Steckdosen schalten möchte. Er generiert dann keine SessionID.

**Comment by Leviathan09** [comment]
Habe das gleiche Problem, kein steuern mehr möglich, keine aktuellen Werte.

**Comment by slimline33** [comment]
Also bei mir war es eine Neuinstallation. Was für Informationen benötigst Du genau?

Ich habe die gestrige Labor nochmal aufgespielt. Jetzt kommt zwar kein Login Fehler mehr, allerdings findet der Adapter keine Geräte mehr ausser das GuestWifi

`

fritzdect.0 | 2019-01-26 21:29:53.457 | debug | polling! fritzdect is alive
-- | -- | -- | --
fritzdect.0 | 2019-01-26 21:28:53.440 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:27:53.429 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:26:53.411 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:25:53.397 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:24:53.377 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:23:53.357 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:22:53.348 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:21:53.328 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:20:53.313 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:19:53.297 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:18:53.281 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:17:53.273 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:16:53.253 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:15:53.241 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:14:53.221 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:13:53.203 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:12:53.193 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:11:53.173 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:10:53.160 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:09:53.142 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:08:53.105 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:07:53.097 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:06:53.090 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:05:53.073 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:04:53.063 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:03:53.058 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:02:53.050 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:01:53.033 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 21:00:53.027 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:59:53.023 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:58:53.019 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:57:53.012 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:56:52.994 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:55:52.980 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:54:52.975 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:53:52.955 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:52:52.943 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:51:52.925 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:50:52.910 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:49:52.907 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:48:52.897 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:47:52.889 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:46:52.873 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:45:52.866 | debug | polling! fritzdect is alive
fritzdect.0 | 2019-01-26 20:45:52.825 | debug | WLAN poll :true
fritzdect.0 | 2019-01-26 20:45:52.809 | info | entered ready
fritzdect.0 | 2019-01-26 20:45:52.803 | info | starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v8.15.0
fritzdect.0 | 2019-01-26 20:45:52.675 | debug | statesDB connected
fritzdect.0 | 2019-01-26 20:45:52.588 | debug | objectDB connected
host.home64 | 2019-01-26 20:45:50.148 | info | instance system.adapter.fritzdect.0 started with pid 4057
host.home64 | 2019-01-26 20:45:50.106 | info | "system.adapter.fritzdect.0" enabled
host.home64 | 2019-01-26 20:45:50.105 | info | object change system.adapter.fritzdect.0

`

**Comment by slimline33** [comment]
> Es gibt wohl probleme mit der Authentifizierung. Habe das selbe auch mit einem bash script wo ich die dect Steckdosen schalten möchte. Er generiert dann keine SessionID.

das script funktioniert mit der neuen Labor wieder.

**Comment by foxthefox** [comment]
Cannot read property 'statusCode' of undefined, kommt von einem Status Code der von der fritzbox zurückkommt. also ist da irgendwas nicht erfolgreich.

**Comment by slimline33** [comment]
Sieht sehr gut aus bisher. 
Alle Objekte wieder da und kein Error beim Log.

Danke!
