### ISSUE TITLE
failed to connect to FRITZ!Box 7590, FRITZ!OS 7.29

### ISSUE THREAD

**Issue by codingdave** [foxthefox/ioBroker.fritzdect#343]
**Describe the bug**  
The documentation does not work for me so I eventually failed to connect to my FRITZ!Box 7590 until I found out the items below. It would be very helpful to update the documentation / troubleshooting and remove red herrings (documentation for FRITZ!OS older than 7.24).

**My findings (FRITZ!Box 7590, FRITZ!OS 7.29)**  
* The password should not exceed 32 characters, or neither the adapter, nor fritz.js are able to connect. (I have only tried A-Z, a-z, 0-9, I haven't tried other characters like /, *, &, and no extended ASCII as well)
* The only requirements on the Fritz!Box user: 1: enabled, 2. Smart Home
* As explained in the ([notice](https://avm.de/service/schnittstellen/)) there is no page "Anmeldung mit Fritz!Box-Benutzernamen und Kennwort" any longer but the decision process to offer the username is based on the existence of multiple Fritz!Box users with enabled access to the web-administration (FRITZ!Box Einstellungen) [de](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/Empfehlungen%20zur%20Benutzerfu%CC%88hrung%20bei%20der%20Anmeldung%20an%20einer%20FRITZ%21Box_v1.1.pdf)/[en](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/Recommendations%20for%20user%20guidance%20for%20logging%20into%20a%20FRITZBox_v1.1_EN.pdf)

**Comment by foxthefox** [comment]
so it is only the update of the documentation to the newest FritzOS? Or do you still have problems to connect the adapter to the FB?

**Comment by codingdave** [comment]
I can very well connect to the adapter when I shorten by password to 32
characters and when my user account has the smart Home permission.

Kind regards

foxthefox ***@***.***> schrieb am Do., 27. Okt. 2022, 12:35:

**Comment by foxthefox** [comment]
with version 2.3.0 the doc files are updated
#353
