### ISSUE TITLE
Es werden nicht alle Objekte angelegt.

### ISSUE THREAD

**Issue by burow1978** [foxthefox/ioBroker.fritzdect#35]
Hallo, es werden leider nicht alle Geräte angelegt, die mit meiner FritzBox 7490 per DECT verbunden sind. Es sind 8 FRITZ!DECT 301, 2 FRITZ!Powerline 546E, 1 FRITZ!DECT Repeater 100 und ein 1 Fensterkontakt von der Telekom per DECT mit der FritzBox verbunden und von dort auch steuerbar. Alle Geräte haben die neuste Firmware.
Wenn ich in unter Instanzen bei FritzBox Adapter Debugging bei MY DEVICES schaue, werden  alle Geräte angezeigt. 
Unter Objekte, fehlen jedoch 3 der FRITZ!DECT 301(Flur, Bungalow und Kueche). (Die 2 FRITZ!Powerline 546E werden ja nicht unterstützt.)
Getestet habe ich vom ioBroker.fritzdect Version 0.1.0, 0.1.2, 0.1.4, 0.1.5 und 0.2.0 .

Einen Auszug der DEBUG LOG-Datei:
[iobroker.2019-01-21.zip](https://github.com/foxthefox/ioBroker.fritzdect/files/2778613/iobroker.2019-01-21.zip)

Bitte um Hilfestellung. 
DANKE :-)

**Comment by foxthefox** [comment]
Ich denke das bekommen wir hin, laut dem log scheint es mit dem Repeater ein Problem zu geben. Danach kommen in der Struktur die anderen Geräte, aber mit dem Rpeater bricht der Objektaufbau ab.
Alle deine Geräte sollten angelegt werden, auch Powerline.

Wenn ich etwas zum neuen testen habe, melde ich mich.

**Comment by foxthefox** [comment]
Ich denke, daß ich den Fehler gefunden habe. Der DECT100 bei dir liefert keine Temperatur mit und da gibt es ein Abbruch beim Anlagen der Objekte.

Bitte die aktuelle Version von github testen und berichten. Wenn OK dann checke ich es bei npm ein.

**Comment by burow1978** [comment]
Hallo foxthefox, Test war erfolgreich und alle Objekte werden jetzt angelegt. 

DANKESCHÖN!!! :-)

Zur Info, der DECT100 liegt hinter mir im Regal und kommt nur im Sommer zum Einsatz. Daher konnte er auch keine Werte melden.

**Comment by foxthefox** [comment]
Super. Egal ob hinter Regal oder nicht, die fritzbox sagt, da gäbe es keine Temperatur  drin.
Ich check es dann bei npm ein
