### ISSUE TITLE
unknown datapoint DECT_139790037754.adaptiveHeatingRunning please inform devloper and open issue in github

### ISSUE THREAD

**Issue by sonie69** [foxthefox/ioBroker.fritzdect#351]
**Describe the bug**  
BugReport from fritzdect in iobroker default configuration

**To Reproduce**  
default communication with driver and fritzbox (sample 7590: os: [7.39-101351 BETA])

**Expected behavior**  

**Screenshots & Logfiles**  
2022-11-14 00:41:08.835 | warn | unknown datapoint DECT_139790037754.adaptiveHeatingRunning please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:41:08.834 | warn | unknown datapoint DECT_139790037754.adaptiveHeatingActive please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:41:08.771 | warn | unknown datapoint DECT_099950573066.adaptiveHeatingRunning please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:41:08.769 | warn | unknown datapoint DECT_099950573066.adaptiveHeatingActive please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:41:08.650 | warn | unknown datapoint DECT_099950570176.adaptiveHeatingRunning please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:41:08.650 | warn | unknown datapoint DECT_099950570176.adaptiveHeatingActive please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:41:08.518 | warn | unknown datapoint DECT_099950670969.adaptiveHeatingRunning please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:41:08.518 | warn | unknown datapoint DECT_099950670969.adaptiveHeatingActive please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:36:08.883 | warn | unknown datapoint DECT_139790037754.adaptiveHeatingRunning please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:36:08.882 | warn | unknown datapoint DECT_139790037754.adaptiveHeatingActive please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:36:08.790 | warn | unknown datapoint DECT_099950573066.adaptiveHeatingRunning please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:36:08.789 | warn | unknown datapoint DECT_099950573066.adaptiveHeatingActive please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:36:08.694 | warn | unknown datapoint DECT_099950570176.adaptiveHeatingRunning please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:36:08.693 | warn | unknown datapoint DECT_099950570176.adaptiveHeatingActive please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:36:08.540 | warn | unknown datapoint DECT_099950670969.adaptiveHeatingRunning please inform devloper and open issue in github
fritzdect.0 | 2022-11-14 00:36:08.540 | warn | unknown datapoint DECT_099950670969.adaptiveHeatingActive please inform devloper and open issue in github
 

<br class="Apple-interchange-newline">
**Versions:**  
Verfügbare Version:
2.2.3
Installierte Version:
2.2.3
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Knallix** [comment]
The same with me.
Fritzbox 7590 7.39-101351 BETA
fritzdect.0: Vers. 2.2.6
NPM 6.14.17
Node.js v14.19.3

<html>
<body>


fritzdect.0 | 2022-11-14 09:29:35.660 | warn | State "fritzdect.0.DECT_099950525015.adaptiveHeatingRunning" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
fritzdect.0 | 2022-11-14 09:29:35.660 | warn | State "fritzdect.0.DECT_099950525015.adaptiveHeatingActive" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.613 | warn | State "fritzdect.0.DECT_099950524942.adaptiveHeatingRunning" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.613 | warn | State "fritzdect.0.DECT_099950524942.adaptiveHeatingActive" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.566 | warn | State "fritzdect.0.DECT_099950524946.adaptiveHeatingRunning" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.566 | warn | State "fritzdect.0.DECT_099950524946.adaptiveHeatingActive" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.507 | warn | State "fritzdect.0.DECT_099950524934.adaptiveHeatingRunning" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.507 | warn | State "fritzdect.0.DECT_099950524934.adaptiveHeatingActive" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.395 | warn | State "fritzdect.0.DECT_119600240848.adaptiveHeatingRunning" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.395 | warn | State "fritzdect.0.DECT_119600240848.adaptiveHeatingActive" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.300 | warn | State "fritzdect.0.DECT_119610848320.adaptiveHeatingRunning" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.300 | warn | State "fritzdect.0.DECT_119610848320.adaptiveHeatingActive" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.243 | warn | State "fritzdect.0.DECT_119600237792.adaptiveHeatingRunning" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-11-14 09:29:35.243 | warn | State "fritzdect.0.DECT_119600237792.adaptiveHeatingActive" has no existing object, this might lead to an error in future versions


</body>
</html>

**Comment by foxthefox** [comment]
@sonie69 you should try the version 2.2.6
the mentioned datapoints are part of this version

**Comment by foxthefox** [comment]
@Knallix did you update the fritzbox without restarting the adapter? please restart the adapter

**Comment by sonie69** [comment]
yes. this was not helpfull.


mit freundlichen Grüßen,


*Wolfgang Weinbrecht*IT-Projektmanager
Bachelor of Industry and Science
***@***.***

*Disclaimer*
Dieser Inhalt der eMail ist streng vertraulich und nur für den Empfänger
bestimmt.
Jegliche Weitergabe, Auswertung oder sonstige Weiterbearbeitung ist ohne
schriftliche Zusage des Absenders untersagt. Um die Echtheit des Absenders
zu überprüfen, fragen sie nach den gültigen Schüssel.


Am Mo., 14. Nov. 2022 um 21:31 Uhr schrieb foxthefox <
***@***.***>:

**Comment by foxthefox** [comment]
I did not have issues in my environment with version 2.2.6.
you can try the version 2.3.0 from github and report.
if it still appears, then I would like to have screenshot of the objecttree for the concerend thermostat.
