### ISSUE TITLE
tist von Gruppen wird nicht übermittelt

### ISSUE THREAD

**Issue by mcuiobroker** [foxthefox/ioBroker.fritzdect#356]
V2.2.3(evtl vorher) - v2.3.0 (testweise) es wird keine tist von der Gruppe übermittelt.

![image](https://user-images.githubusercontent.com/84818934/204813035-81af52a5-d583-4a9e-ae12-83d07f58088e.png)

![image](https://user-images.githubusercontent.com/84818934/204813138-a268cd47-defb-4045-b3e7-c93f88ebb0e9.png)

Datenpunkt komplett gelöscht -> keine Änderung

v2.2.4, v2.2.5 werden angezeigt sind aber nicht vorhanden

![image](https://user-images.githubusercontent.com/84818934/204813473-063004bb-f684-4e89-96df-d23be29715d1.png)

```
iobroker npm ERR! code ETARGETnpm ERR! notarget No matching version found for iobroker.fritzdect@2.2.4.npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2022-11-30T13_43_17_078Z-debug-0.log
```

![image](https://user-images.githubusercontent.com/84818934/204814201-9434469b-c478-4aae-ba5a-47b10879c90d.png)

debug-LOG
![image](https://user-images.githubusercontent.com/84818934/204817370-d1deb063-5a75-4b1d-819c-aa099e9997f4.png)

![image](https://user-images.githubusercontent.com/84818934/204817793-cf746a59-5869-4cdd-816d-e0f4462ca86e.png)

```
,"hkr":{"tist":"","tsoll":"33","absenk":"42",
```
FritzBox
![image](https://user-images.githubusercontent.com/84818934/204814506-c602dfcd-50e2-46a6-9722-c6d01789003f.png)

**Comment by foxthefox** [comment]
die Version 2.2.4, 2.2.5 sind nicht auf npm
Version 2.2.6 ist auf npm, steht auch in Klammern in der History
Entweder 2.2.6 von npm installieren (sollte auch über iobroker admin page angeboten werden)oder 2.3.0 aus github installieren.

Ich nehme an, daß die vorletzte Zeile der output aus "Meine Geräte" ist, somit wäre klar, warum der Adapter nichts anzeigt.

**Comment by mcuiobroker** [comment]
Dann scheint es an der FritzBox bzw. an der Firmware zu liegen.
