### ISSUE TITLE
Warnmeldung Temperatur zu gering

### ISSUE THREAD

**Issue by Beezy141** [foxthefox/ioBroker.fritzdect#365]
Ich bekomme in "Protokolle" ständig die Warnmeldung das die Temperatur zu gering ist weil sie kleiner als 8 Grad ist. Es handelt sich bei dem Gerät um das Fritz DECT 210 (Außensteckdose). Die Meldung kommt da die Außentemperatur natürlich unter 8 Grad ist. Das ist aber für das Gerät kein Problem. Laut Herstellerangaben ist es geeignet für Umgebungstemperaturen von -20° C bis +40° C.
Installierte Version: 2.2.6

LG Ronny

![fdect](https://user-images.githubusercontent.com/102716537/206109403-ed8f4ba6-6995-4260-bfa9-261d82f2a558.png)

**Comment by foxthefox** [comment]
sorry für die späte Antwort, war im Urlaub.

die temperatur hat schon länger einen Bereich von -30 bis 50 Grad, d.h. der Datenpunkt wird beim Neuanlegen diesen Bereich haben. Wenn der Datenpunkt schon Vorhanden ist, dann wird allerdings nichts überschrieben.
Deswegen bitte:
- Adapter stoppen
- den Datenpunkt löschen
- Adapter starten
Dann wird neu angelegt und das Setting übernommen

**Comment by Beezy141** [comment]
Alles klar. Danke dir. 😃👍
