### ISSUE TITLE
nach Update der fritzbox "warnungen has no existing object"

### ISSUE THREAD

**Issue by softwarecrash** [foxthefox/ioBroker.fritzdect#367]
servus,
es gab ja jetzt ein update der aktuellen fritzboxen, seitdem habe ich im log alle paar minuten das hier, bekommt man das weg oder muss man erstmal damit leben? sonst funktioniert alles
`<html>
<body>

fritzdect.0 | 2022-12-15 14:56:51.359 | warn | State "fritzdect.0.DECT_119590232616.adaptiveHeatingRunning" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
fritzdect.0 | 2022-12-15 14:56:51.358 | warn | State "fritzdect.0.DECT_119590232616.adaptiveHeatingActive" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-12-15 14:56:51.064 | warn | State "fritzdect.0.DECT_109710519552.adaptiveHeatingRunning" has no existing object, this might lead to an error in future versions
fritzdect.0 | 2022-12-15 14:56:51.063 | warn | State "fritzdect.0.DECT_109710519552.adaptiveHeatingActive" has no existing object, this might lead to an error in future versions

</body>
</html>`

**Comment by foxthefox** [comment]
Bitte den Adapter neu starten, dann werden die neuen Datenpunkte auch angelegt.
oder installier bitte die Version 2.2.6 oder die neueste aus github, sofern es noch nicht aktuell ist.

Falls dann immer noch Warnungen sind,
- Adapter stoppen
- bemängelten Datenpunkt löschen
- Adapter starten

**Comment by softwarecrash** [comment]
neustart hatte ich schon ohne erfolg, warum auch immer nach einer neuinstallation des adapters ist es weg. danke!
