### ISSUE TITLE
FRITZDECT301 Wert für gemessene Temperatur fehlt

### ISSUE THREAD

**Issue by chris47803** [foxthefox/ioBroker.fritzdect#376]
Hallo.

Nachdem ich nun Tage damit verbracht habe mich einzuarbeiten,
musste ich heute feststellen, das die Temperatur falsch ist.
Der Datenpunkt Celsius zeigt den Wert an, den man in der Fritzbox selbst wählt.
Für die gemessene Temperatur gibt es leider keinen DP.

![01](https://user-images.githubusercontent.com/119003261/213910480-670f0c4f-b529-4e3b-a5e7-bea0fa8050f2.JPG)

**Comment by foxthefox** [comment]
Adapter scheint ja zu laufen, dann hätte ich gern den output von "Meine Geräte".
celsius und tist sind die von der FB übermittelten Werte, offset kommt separat auch von der FB
im obigen screenshot wäre zu erwarten, daß der Adapter in celsuis und tist 25,5 zeigt und offset 3.

**Comment by chris47803** [comment]
Was meinst du mit "Meine Geräte"?
Unter Celsius hätte ich den Wert 28,5 erwartet.

**Comment by foxthefox** [comment]
auf der Adapterseite gibt es unterhalb der Einstellungen mehrere buttons, einer davon sollte "Meine Geräte" oder "my devices" heißen, wenn man den klickt kommt Text in einem Fenster, welches die Rohdaten der FB sind.
Der am Heizkörper gemessene Wert wird nicht übertragen, sondern nur der korrigierte Wert.
Der Heizkörperwert ist je nach Einbaugegebenheit nicht repräsentativ für die Raumtemperatur, deswegen gibt es in der FB eine Korrekturmöglichkeit und somit wird nun um 3 grad korrigiert, was dann auch als celsius und tist von der FB kommt. Wenn du die falsch gemessene Temperatur wissen willst, kannst du celsius und offset zusammenrechnen.

**Comment by chris47803** [comment]
Ich sehe da leider nichts.
![01](https://user-images.githubusercontent.com/119003261/213929970-a14fc0d0-4b6a-4e21-adca-2dd9c2d32a10.JPG)

**Comment by foxthefox** [comment]
auf der Seite vom fritzdect Adapter, bei Instanzen auf den "Schlüssel" bei fritzdect gehen

**Comment by chris47803** [comment]
`[{"identifier":"09995 0216627","id":"25","functionbitmask":"320","fwversion":"05.02","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Heizung Bad","battery":"70","batterylow":"0","temperature":{"celsius":"260","offset":"-50"},"hkr":{"tist":"52","tsoll":"46","absenk":"36","komfort":"46","lock":"0","devicelock":"1","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"70","nextchange":{"endperiod":"1674428400","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"09995 0304795","id":"20","functionbitmask":"320","fwversion":"05.02","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Heizung Büro","battery":"60","batterylow":"0","temperature":{"celsius":"230","offset":"-35"},"hkr":{"tist":"46","tsoll":"46","absenk":"36","komfort":"46","lock":"0","devicelock":"1","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"60","nextchange":{"endperiod":"1674428400","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"09995 0214189","id":"24","functionbitmask":"320","fwversion":"05.02","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Heizung Küche","battery":"80","batterylow":"0","temperature":{"celsius":"210","offset":"-50"},"hkr":{"tist":"42","tsoll":"42","absenk":"36","komfort":"42","lock":"0","devicelock":"1","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1674428400","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"09995 0279527","id":"17","functionbitmask":"320","fwversion":"05.02","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Heizung Schlafzimmer","battery":"80","batterylow":"0","temperature":{"celsius":"200","offset":"-20"},"hkr":{"tist":"40","tsoll":"38","absenk":"36","komfort":"38","lock":"0","devicelock":"1","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1674428400","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"09995 0273573","id":"23","functionbitmask":"320","fwversion":"05.02","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Heizung Serverraum","battery":"30","batterylow":"0","temperature":{"celsius":"220","offset":"-10"},"hkr":{"tist":"44","tsoll":"36","absenk":"36","komfort":"36","lock":"0","devicelock":"1","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"30","nextchange":{"endperiod":"1674428400","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"09995 0308576","id":"16","functionbitmask":"320","fwversion":"05.02","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Heizung Wohnzimmer","battery":"60","batterylow":"0","temperature":{"celsius":"235","offset":"-30"},"hkr":{"tist":"47","tsoll":"46","absenk":"36","komfort":"46","lock":"0","devicelock":"1","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"60","nextchange":{"endperiod":"1674428400","tchange":"36"},"summeractive":"0","holidayactive":"0"}}]`

**Comment by foxthefox** [comment]
also wenn der Adapter im Bad 26° anzeigt und 5° Offset, dann wird das ankommende richtig umgesetzt.
Büro 23° mit 3,5° Offset, Küche 21° mit 5° Offset
Das dürfte auch mit der Anzeige in der, bevor es in die Details geht zusammenpassen. oder auch die APP auf dem Handy.

**Comment by chris47803** [comment]
Okay.
Danke dir.
Ich habe das wohl falsch interpretiert.

LG, Chris

**Comment by foxthefox** [comment]
Dann schließ ich das mal
