### ISSUE TITLE
sporadisch kein Login möglich

### ISSUE THREAD

**Issue by ihavenonick** [foxthefox/ioBroker.fritzdect#38]
Die Fritzbox lehnt sporadisch das Login des Adapter ab.

2019-02-25 05:45:00.647  - error: fritzdect.0 fritzbox returned this "0000000000000000"
2019-02-25 05:45:00.650  - error: fritzdect.0 Did not get session id- invalid username or password?
2019-02-25 05:45:00.775  - error: fritzdect.0 fritzbox returned this "0000000000000000"
2019-02-25 05:45:00.775  - error: fritzdect.0 Did not get session id- invalid username or password?
2019-02-25 05:45:00.906  - error: fritzdect.0 fritzbox returned this "0000000000000000"
2019-02-25 05:45:00.907  - error: fritzdect.0 Did not get session id- invalid username or password?
2019-02-25 05:45:01.033  - error: fritzdect.0 fritzbox returned this "0000000000000000"
2019-02-25 05:45:01.034  - error: fritzdect.0 Did not get session id- invalid username or password?

FritzBox 7590 mit aktueller Beta: 07.08-65777

**Comment by ihavenonick** [comment]
fritzdect.0 | 2019-02-26 08:11:46.376 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
-- | -- | -- | --
fritzdect.0 | 2019-02-26 08:11:46.375 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-02-26 08:11:46.373 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAM

Das kommt ebenfalls sporadisch und außer Zugriff aus dem Internet hat der User alle Rechte.

**Comment by ihavenonick** [comment]
fritzdect.0 | 2019-02-26 10:15:12.670 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
-- | -- | -- | --
fritzdect.0 | 2019-02-26 10:15:12.670 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-02-26 10:15:12.669 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAMEORIG
fritzdect.0 | 2019-02-26 10:15:12.523 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
fritzdect.0 | 2019-02-26 10:15:12.523 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-02-26 10:15:12.523 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAMEORIG
fritzdect.0 | 2019-02-26 10:15:12.367 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
fritzdect.0 | 2019-02-26 10:15:12.367 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-02-26 10:15:12.366 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAMEORIG
fritzdect.0 | 2019-02-26 10:15:12.214 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
fritzdect.0 | 2019-02-26 10:15:12.214 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-02-26 10:15:12.213 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAMEORIG
fritzdect.0 | 2019-02-26 10:15:12.035 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
fritzdect.0 | 2019-02-26 10:15:12.035 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-02-26 10:15:12.034 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAMEORIG
fritzdect.0 | 2019-02-26 10:15:11.879 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
fritzdect.0 | 2019-02-26 10:15:11.879 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-02-26 10:15:11.878 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAMEORIG
fritzdect.0 | 2019-02-26 10:15:11.723 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
fritzdect.0 | 2019-02-26 10:15:11.723 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-02-26 10:15:11.723 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAMEORIG
fritzdect.0 | 2019-02-26 10:15:11.553 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
fritzdect.0 | 2019-02-26 10:15:11.553 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-02-26 10:15:11.553 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAMEORIG
fritzdect.0 | 2019-02-26 10:15:11.398 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
fritzdect.0 | 2019-02-26 10:15:11.398 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-02-26 10:15:11.398 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"

**Comment by Ilovegym66** [comment]
ja, und kam dann wieder.. habe auch den Adapter mal geloescht, neu installiert, upload, gleiches Spiel.. laeuft eine Zeitlang.. dann holt er Daten / aktualisiert und dann gleich drauf der Loginerror.. ?! Anscheinend ist der Aufruf dann zu oft oder er versucht sich doppelt was abzuholen..??

` 

fritzdect.0 | 2019-04-10 13:45:09.212 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
-- | -- | -- | --
fritzdect.0 | 2019-04-10 13:45:09.212 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-04-10 13:45:09.212 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAMEORIG
fritzdect.0 | 2019-04-10 13:45:09.065 | error | error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAME
fritzdect.0 | 2019-04-10 13:45:09.065 | error | no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-04-10 13:45:09.064 | error | fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"SAMEORIG
fritzdect.0 | 2019-04-10 13:45:05.537 | error | Did not get session id- invalid username or password?
fritzdect.0 | 2019-04-10 13:45:05.536 | error | fritzbox returned this "0000000000000000"
fritzdect.0 | 2019-04-10 13:45:00.042 | info | Comet ID: 119600189512 identified for command (mode) : 0
fritzdect.0 | 2019-04-10 13:45:00.042 | info | Comet ID: 119600090160 identified for command (mode) : 1
fritzdect.0 | 2019-04-10 13:45:00.041 | info | Comet ID: 119600189000 identified for command (mode) : 0
fritzdect.0 | 2019-04-10 13:45:00.041 | info | Comet ID: 119600189312 identified for command (mode) : 0
fritzdect.0 | 2019-04-10 13:45:00.041 | info | HGROUP ID: 9E:FF:EA-900 identified for command (mode) : 0
fritzdect.0 | 2019-04-10 13:45:00.040 | info | HGROUP ID: 9E:FF:EA-900 identified for command (mode) : 0
fritzdect.0 | 2019-04-10 13:45:00.039 | info | HGROUP ID: 9E:FF:EA-900 identified for command (mode) : 0
fritzdect.0 | 2019-04-10 13:45:00.039 | info | HGROUP ID: 9E:FF:EA-900 identified for command (mode) : 0
fritzdect.0 | 2019-04-10 13:45:00.038 | info | Comet ID: 119600089920 identified for command (mode) : 0
fritzdect.0 | 2019-04-10 13:45:00.034 | info | HGROUP ID: 9E:FF:EA-900 identified for command (mode) : 0

`

**Comment by ihavenonick** [comment]
Ja das Passwort neu eingeben wäre ja auch etwas zu einfach. Wenn das funktioniert hätte, hätte ich wohl das hier nicht geöffnet.
Kann funktionieren, macht es aber nur sehr selten.

**Comment by ihavenonick** [comment]
Passiert hier noch was oder ist das Projekt tot? 
Heute verweigert meine Fritz 7590 mal wieder das Login des Adapter und das ohne Änderung am User oder Login des Adapter

**Comment by foxthefox** [comment]
Das Projekt ist nicht tot. Seit gestern habe ich nun auch eine 7590 und kann somit ggf. die Probleme auch entdecken. Prinzipiell sollte es nicht am Adapter selbst liegen, da ja die Mechanismen funktionieren.
Wie oben schon geschrieben, kann es natürlich sein, daß versucht wird zu oft Daten abzuholen. Da gibt es Beschränkungen. Falls also das 5min Intervall nach unten gesetzt ist und dann noch parallel Apps benutzt werden, dann kann das auch zum Verweigern des logins führen.

**Comment by ihavenonick** [comment]
Ich habe das schon von 300 Sekunden auf 600 Sekunden hoch geschraubt und ändern tut sich nix. Dann ist da noch der TR-064 Adapter der alle 10 Sekunden sein Poll Intervall hat und nie Probleme.
Das seltsame ist ja auch, dass es sein kann, dass es eine Zeitlang funktioniert und dann eben wieder nicht mehr. Was ich ebenfalls nicht verstehe, die Fritz protokolliert das ganze auch als abgelehnten Zugriff genau so wie der Adapter, nur die Kommunikation steht wohl, sonst wären die DPs nie aktuell.
Also irgendwas stimmt da am Adapter nicht, wobei die Funktion ja durch das  angeblich abgelehnte Login  nicht wirklich beeinträchtigt wird. Was hier allerdings problematisch ist, ist die dadurch sehr schnell wachsende Größe des IOBroker Log.

Wenn ich irgendwie helfen kann um das Problem zu lösen, ich stehe bereit.

**Comment by ihavenonick** [comment]
Ich mach das mal wieder zu, da ich es angelegt hatte und der Fehler nicht am Adapter lag.

**Comment by Ilovegym66** [comment]
Also ich bin auf die Version 0.2.1 zurück, und damit sind die Login-Errors Geschichte. Habe nichts an den Scripten verändert. Bitte nochmal öffnen.. da stimmt was nicht .

**Comment by ihavenonick** [comment]
Schau Dir noch mal genau an welche Scripte wann über den Adapter auf die Fritz zugreifen. Ich hatte bei mir auch den Adapter im Verdacht, weil ich extra an längeres Intervall bei meinen Scripten angelegt hatte und dann war erst mal Ruhe. Aber ab und an kam trotzdem wieder der Fehler. Hier war die Lösung ebenfalls eine zu schnell hinter einander erfolgter Zugriff auf die Fritz und das kam bei  mir weil zwei unabhängige Scripte ab und an eine Zeitliche Überschneidung hatten. das eine alle 10 Minuten und das andere alle 2 Minuten. Hab dann den 2 Minuten Intervall auf 3 gestellt und schon wars besser. Hier könnte man dann auch noch Sekunden mit einbauen, dann gibts überhaupt keine Überschneidungen mehr.

**Comment by Ilovegym66** [comment]
Version 0.2.4 hat die Login Errors alle paar Minuten, und wenn ich auf die 0.2.1 zurück gehe, kommt den ganzen Tag kein einziger Login error mehr.
Was soll das mit den Scripten zu tun haben?

**Comment by ihavenonick** [comment]
Ich habe ebenfalls die 0.2.4 und keine Errors mehr seit ich die Scripte angepasst habe. Was natürlich sein kann, dass die 0.2.4er Version allgemein etwas agiler ist und die Anfragen schneller absetzt. Dann wäre ein ungünstiges Script auch auffälliger was das auslösen der Errors betrifft.
Warte mal was foxthefox dazu sagt.

**Comment by Ilovegym66** [comment]
Meine Scripte reagieren nur, wenn ich das Haus verlasse, oder per Hand einen Wert ändere, oder ein Fenster auf - zu geht.. und das macht keiner im Sekundentakt.. hab auch schon den loglevel auf debug gestellt, und auch bei meinen Scripten mir alles per Telegram schicken lassen, das funktioniert. Ist auch überall ein delay drin, damit es erst garnicht zu schnellen wechsel kommen kann. Irgendwas mit dem Login- oder der Abfrage der Fritzbox muss mit den höheren Versionen anders sein.. 

Habe jetzt auf einem Testsystem auch auf die 0.2.4 installiert, das gleiche. 
Dann dacht ich mir, warum nehm ich meinen 'meshmaster' - ich hab genug andere FritzBoxen im Netz, die ich auch damit abfragen kann, vielleicht ist die Masterbox ja etwas überfordert..

Und siehe da, auf ner anderen läuft es ohne Fehler. 

Trotzdem ist es komisch, dass es mit der 0.2.1 geht und mit der 0.2.4 nicht. :-)

**Comment by bjoern77** [comment]
Hallo
Ich bekomme 0.2.4 auch nicht zum Laufen. Kein Login möglich. Da ich Dect 400 einbinden möchte, suche ich die 0.2.1 oder 0.2.2. Kann mir jemand sagen, wo ich die finde?
Danke und Gruß
Björn
