### ISSUE TITLE
boostactivetime

### ISSUE THREAD

**Issue by duczz** [foxthefox/ioBroker.fritzdect#381]
Hallo,
wenn man den Standardwerte vom "boostactivetime" von 15Min auf Z.B. 30Min setzt, beendet sich der Boost trotzdem nach 15 Min, ist das normal oder ein Fehler?

**Comment by foxthefox** [comment]
Laut API Beschreibung darf die übermittelte Zeit bis 24h in der Zukunft liegen, also 30min sollte realisiert werden.
Der zeitpunkt, wo es sich beenden wird, ist im Datenpunkt boostactiveendtime abzulesen.
Der Wert sollte auch beim nächsten Abfragen der FB noch der gleiche sein, wie beim Absenden des Kommandos.
Damit kann man sehen, daß der Wert auch von der FB übernommen wurde.

**Comment by duczz** [comment]
Du hast Recht, es liegt daran das es 10-15 Minuten dauert bis das Thermostat den Wert überhaupt bekommt.
Gibt es keine Möglichkeit den Wert um diese Zeit zu erhöhen? Sprich, kannst du abfragen wann die nächste Übergabe statt findet und den Timer entsprechend anpassen?

**Comment by foxthefox** [comment]
Wann der nächste Kommunikationszyklus mit dem Themostat stattfindet, lässt sich mit der API nicht auslesen.
