### ISSUE TITLE
FritzDECT 200

### ISSUE THREAD

**Issue by hallerdavid** [foxthefox/ioBroker.fritzdect#388]
Hey zusammen,

ich habe folgendes Problem: Der Adapter ist korrekt installiert und der Benutzer eingerichtet auf der Fritzbox, die beiden vis-Instanzen laufen auch (die benötige ich jedoch nur für ne Visualisierung oder?).

Der Adapter zeigt mir auch alle Infos zu meinen FritzDect!200 Steckdosen, Watt, State, alles. Jedoch kann ich diese nicht steuern. Wenn ich den State wechsle von True auf False oder umgekehrt, funktioniert das zwar im ioBroker, jedoch ändert sich der Zustand der Steckdosen in der Fritzbox nicht, noch auf dem Telefon, noch schalten diese real ab / an.

Wenn sich der Adapter nach der angegebenen Zeit den zustand der fritzbox wieder zieht ist der state wieder der alte.

Wo kann ich hier anfangen zu suchen? Ich freue mich auf Rückmeldung! :-)

**Comment by foxthefox** [comment]
ja, vis wird nur für Anzeige benötigt, wenn das mitgelieferte widget benutzt wird.

wie wird denn gesteuert, über vis oder über die Datenpunkte direkt?
was heißt die Steckdosen ändern den Zustand über das Telefon nicht, über die Fritz SmartHome App?
Dort in der App funktioniert das Schalten der Steckdosen auch nicht?

Wenn der Adapter in der FB die Berechtigung hat, die Geräte auszulesen, dann hat er im Normalfall auch die Berechtigung zu steuern. Es gibt noch einen Datenpunkt "locked", ggf. kann der etwas verhindern, wüsste aber nicht wo der in der FB-Oberfläche gesetzt werden kann.
Gibt es Einträge im log von der FB oder im log von iobroker?

**Comment by hallerdavid** [comment]
Ich benutze zum Steuern nur die Datenpunkte bzw. ändere den Wert vom Datenpunkt "state". Ist das der Weg der funktionieren sollte?

der Datenpunkt locked steht auf false - wenn ich mich richtig erinnere..

Im Log von iobroker hab ich nichts gefunden, kann den aber gerne mal hier rein pasten. Ein Log in der Fritzbox muss ich suchen. Bin aber aktuell nicht vor Ort.

**Comment by foxthefox** [comment]
das Steuern über die Datenpunkte sollte immer gehen, bei vis könnte z.B. der falsche Datenpunkt angebunden sein und dann müsste man dies erstmal erkennen.

wenn nichts im log steht, wäre auch einmal eine Variante den Adapter in den debug modus zu schalten und dann im log schauen, was so an Meldungen kommt. Dort wird dann auch der Befehl mit geloggt.

**Comment by hallerdavid** [comment]
<img width="1067" alt="Bildschirm­foto 2023-04-12 um 17 21 09" src="https://user-images.githubusercontent.com/43130293/231504490-879df9a0-30f1-467a-aee1-008d61c1b396.png">

Das wäre mein Log im Debug Modus und einmal State von true auf false..

**Comment by hallerdavid** [comment]
geändert hat sich der zustand allerdings nicht
