### ISSUE TITLE
FRITZ! DECT 400 - Schalter not supported

### ISSUE THREAD

**Issue by jp66** [foxthefox/ioBroker.fritzdect#40]
FRITZ! DECT 400 - Schalter is not supported so far

**Comment by foxthefox** [comment]
I have implemented the button long time ago with version 0.1.4.
If you go to the admin page and click on my devices, then please post the output which is returned in the popup window. Then I could check if there is something different, to what is expected right now.

**Comment by foxthefox** [comment]
After intensive research and not having an output of the API, I have realized that there is a difference between the implemented button and the FD400.

I have implemented the FD400!
Please check the github version and report.

**Comment by jp66** [comment]
Thanks very much!

IOBroker identifies the DECT400 but unfortunately does not add an entry under Objects



LOG 1:
….
{"identifier":"130960008587","id":"27","functionbitmask":"32","fwversion":"04.86","manufacturer":"AVM","productname":"FRITZ!DECT 400","present":"1","name":"FRITZ!DECT 400 #12"},{"identifier":"116570093330","id":"28","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 210","present":"1","name":"FRITZ!DECT 210 Gardena Gateway","switch“: ….

2019-05-21 14:29:27.036 - debug: fritzdect.0 update Devices 13



LOG 2:
...
2019-05-21 14:29:27.043 - debug: fritzdect.0 DECT200_087610497947 : temp : 31.5
2019-05-21 14:29:27.043 - debug: fritzdect.0 DECT200_087610497947 : temp offset: 0
2019-05-21 14:29:27.043 - debug: fritzdect.0 DECT200_087610497947 : voltage : 235.55
2019-05-21 14:29:27.044 - error: fritzdect.0 fritzbox returned this {}
2019-05-21 14:29:27.044 - error: fritzdect.0 no response part in returned message
2019-05-21 14:29:27.057 - debug: fritzdect.0 redis pmessage io.fritzdect.0.* io.fritzdect.0.DECT100_087610948034.name {"val":"FRITZ!DECT Rep 100 EG 
...

**Comment by foxthefox** [comment]
can you please go to the admin page of the adapter and hit the button "my devices" and post the data from the pop-up window?
The messages you posted are not so helpful

**Comment by foxthefox** [comment]
if it is in German it is "Meine Geräte"

**Comment by jp66** [comment]
Vielen Dank, anbei die Ausgabe:

Result: 
[{"identifier":"087610948034","id":"16","functionbitmask":"1280","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT Repeater 100","present":"1","name":"FRITZ!DECT Rep 100 EG Sauna","temperature":{"celsius":"235","offset":"0"}},{"identifier":"087610965719","id":"17","functionbitmask":"1280","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT Repeater 100","present":"1","name":"FRITZ!DECT Rep 100 OG","temperature":{"celsius":"230","offset":"0"}},{"identifier":"116570117551","id":"18","functionbitmask":"1280","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT Repeater 100","present":"1","name":"FRITZ!DECT Rep 100 EG ArZi","temperature":{"celsius":"220","offset":"0"}},{"identifier":"087610383219","id":"19","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"FRITZ!DECT 200 Waschmaschine","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"236448","power":"2430","energy":"213696"},"temperature":{"celsius":"235","offset":"0"}},{"identifier":"087610509681","id":"20","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"FRITZ!DECT 200 Trockner","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"236688","power":"780","energy":"164757"},"temperature":{"celsius":"245","offset":"0"}},{"identifier":"087610509679","id":"21","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"FRITZ!DECT 200 Pumpe Heizung Pool","switch":{"state":"0","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"235715","power":"0","energy":"8690"},"temperature":{"celsius":"320","offset":"0"}},{"identifier":"087610509683","id":"22","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"FRITZ!DECT 200 Entsalzung Grünbeck","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"235511","power":"1210","energy":"7243"},"temperature":{"celsius":"330","offset":"0"}},{"identifier":"087610509677","id":"23","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"FRITZ!DECT 200 Pumpe Warmwasser Haus","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"235296","power":"7510","energy":"15001"},"temperature":{"celsius":"350","offset":"0"}},{"identifier":"087610509675","id":"24","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"FRITZ!DECT 200 Panel HomeAutomation","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"235779","power":"3140","energy":"23889"},"temperature":{"celsius":"345","offset":"0"}},{"identifier":"087610497946","id":"25","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"FRITZ!DECT 200 OurMacMini","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"235794","power":"30040","energy":"33204"},"temperature":{"celsius":"345","offset":"0"}},{"identifier":"087610497947","id":"26","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"FRITZ!DECT 200 ETC","switch":{"state":"0","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"236001","power":"0","energy":"13"},"temperature":{"celsius":"335","offset":"0"}},{"identifier":"130960008587","id":"27","functionbitmask":"32","fwversion":"04.86","manufacturer":"AVM","productname":"FRITZ!DECT 400","present":"1","name":"FRITZ!DECT 400 JP"},{"identifier":"116570093330","id":"28","functionbitmask":"2944","fwversion":"04.09","manufacturer":"AVM","productname":"FRITZ!DECT 210","present":"1","name":"FRITZ!DECT 210 Gardena Gateway","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"233888","power":"1380","energy":"1980"},"temperature":{"celsius":"230","offset":"0"}}]



Viele Grüsse

Jürgen Pinkl

**Comment by foxthefox** [comment]
Hallo Jürgen,
im Normalfall würde ich einen Datenpunkt "lasttimepressed" erwarten, der für beide Tasten vorhanden ist. Bei dir ist lediglich der Basiseintrag vorhanden:{"identifier":"130960008587","id":"27","functionbitmask":"32","fwversion":"04.86","manufacturer":"AVM","productname":"FRITZ!DECT 400","present":"1","name":"FRITZ!DECT 400 JP"}
Muss in der Fritzbox der Taster noch aktiviert werden?
Welche Fritzbos FW ist es denn?
Wird denn in der Fritzbox der Tastendruck erkannt und angezeigt?

Gruß
Klaus

PS.
Natürlich kann ich den Basiseintrag anlegen, das nützt aber nicht so viel ohne den interessanten Datenpunkt.

**Comment by foxthefox** [comment]
Ich denke in version0.2.2 sollte es alles laufen, vorausgesetzt, daß die FD400 richtig in der fritzbox parametriert sind.

Ich schließ mal das Issue, falls es doch nicht geht, dann bräuchte ich mehr Info wie es in der fritzbox aussieht und dann kann man das Issue wiederbeleben.

**Comment by jp66** [comment]
Danke, hab die FritzBox auf 7.11 gebracht und das Problem ist weg.

Vielen Dank

Juergen 


_______________________________________________________________________________________
Jürgen Pinkl
Bahnhofstraße 10/1
88471 Laupheim
