### ISSUE TITLE
It would be nice if this adapter can be found when using the search word AVM

### ISSUE THREAD

**Issue by Gaspode69** [foxthefox/ioBroker.fritzdect#418]
Hi,
as discussed [here](https://forum.iobroker.net/post/1029509) it would be nice if this adapter can be found using the search word AVM. According to mcm57, this can be reached simply by changing the adapter description accordingly. Probably just "AVM" has to be added to the keywords?

**Comment by foxthefox** [comment]
No problem, I will add the keyword.
