### ISSUE TITLE
Stromstärke aktuell anzeigen

### ISSUE THREAD

**Issue by baerenmarke90** [foxthefox/ioBroker.fritzdect#42]
Hallo,

lässt sich die Stromstärke aktuell in ioBroker einbinden?

<img width="310" alt="image" src="https://user-images.githubusercontent.com/49028921/55987166-31698600-5ca1-11e9-8a9e-19249fdf2cde.png">

VG

**Comment by foxthefox** [comment]
leider nicht auf dem Wege der normalen API-Anbindung, die die Fritzbox bietet.
Solange die API diese Werte nicht mit anbietet, wird es nicht im Adapter ankommen.
