### ISSUE TITLE
Add Szenarios and new templates

### ISSUE THREAD

**Issue by SirFlour** [foxthefox/ioBroker.fritzdect#426]
**Describe the bug**  

The new Szenarios and Templates (eg for GuestWlan) are not showing up in iObroker

**To Reproduce**  
Create Szenarios and the new templates and nothing shows up in iObroker

**Expected behavior**  

Beeing able to control it.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

![grafik](https://github.com/foxthefox/ioBroker.fritzdect/assets/52317499/9017a057-a1eb-410d-961f-cd3e1482ea39)
![grafik](https://github.com/foxthefox/ioBroker.fritzdect/assets/52317499/cf6deac4-2eab-4d4a-bd20-d0b42933cdcf)

Hope you can help :) also i am more than happy to test :)

**Comment by foxthefox** [comment]
I will have a look what the API provides and if this can be implemented.

**Comment by SirFlour** [comment]
great thanks a lot for your help :)

**Comment by foxthefox** [comment]
I have created version 2.4.0 which you can install from github.
Please test and report

**Comment by SirFlour** [comment]
Perfect! I tested "Email_An" and was able via iObroker to send the email. I also see all other Templates (GuestWlan, etc) and new created Szenarios. So from my point of view it is working great :) Many thanks for your creat and fast support.

![grafik](https://github.com/foxthefox/ioBroker.fritzdect/assets/52317499/cb0bde97-ea44-4e94-a1ce-144d5ffc5a66)

![grafik](https://github.com/foxthefox/ioBroker.fritzdect/assets/52317499/f850453b-7f95-47ac-b642-af6ba5433954)

**Comment by foxthefox** [comment]
Perfect, thanks for testing
