### ISSUE TITLE
Temperaturabweichung (Offset) wird bei FRITZ!DECT 200 doppelt gerechnet

### ISSUE THREAD

**Issue by RK62** [foxthefox/ioBroker.fritzdect#44]
Echte Temperatur am FRITZ! Actor: 21,5 °C.
Raumtemperatur in FRITZ! Box auf 16,5 °C gesetzt (5° Differenz):

![image](https://user-images.githubusercontent.com/39200469/57194933-1828c200-6f4d-11e9-942f-9d7fd421b3f6.png)

Die wird bei den FRITZ! Programmen auch angezeigt:

![image](https://user-images.githubusercontent.com/39200469/57194940-2c6cbf00-6f4d-11e9-9072-74408cf25068.png)

Objekt im iobroker (fritzdect.0.DECT200_xxx.temp) zeigt 11,5°C (10° Differenz):

![image](https://user-images.githubusercontent.com/39200469/57194968-7a81c280-6f4d-11e9-8918-ac583c8cbce2.png)

Gruß, Ralf

**Comment by foxthefox** [comment]
Das war schon einmal ein Thema und da hatt ich dann noch einen neuen Datenpunkt aufgemacht. Jetzt gibt es actualtemp und temp.
Einer davon sollte der unbeeinflusste sein. 
Evtl. ist es sinnvoll einfach nur den übermittelten Offset als Datenpunkt mit aufzunehmen und dann kann man in vis rechnen wie man es braucht oder anzeigen will.

Gruß
Klaus

**Comment by RK62** [comment]
Wo ist denn die 2.Temperatur? Ich habe die 0.2.1 installiert, da sehe ich nur den korrigierten Wert.
Habe mir jetzt allerdings auch beholfen, in dem ich den halben Korrekturwert einsetze ;-)

Danke, Ralf

![image](https://user-images.githubusercontent.com/39200469/58043337-2f66d280-7b3d-11e9-8f54-7c24cc692e78.png)

**Comment by foxthefox** [comment]
da hab ich wohl an den DECT300 geschaut und nicht richtig verglichen, weil es hier um DECT200 ging.
Also ich nehme mal den offset komplett raus und eröffne einen neuen Datenpunkt

**Comment by foxthefox** [comment]
in 0.2.2 behoben
