### ISSUE TITLE
Feature Request: Powerline Switch

### ISSUE THREAD

**Issue by mar565** [foxthefox/ioBroker.fritzdect#45]
Hallo zusammen,
ich suche nach einer Möglichkeit im ioBroker die Powerline Funktion des 546E zu schalten.

![546E Powerline](https://user-images.githubusercontent.com/49168222/57575262-6d7e3b00-7447-11e9-8974-e6f9f1983a99.JPG)

**Comment by foxthefox** [comment]
Der Adapter sollte diesen Switch auch schalten können.
Am besten den Adapter starten und schauen ob er mit angelegt wird.
Ansonsten auf der Admin Seite auf "my devices" klicken, da sollte die "Powerline-Basis" auftauchen und wenn sie es tut, dann sollte auch das automatische Anlegen klappen. Wenn nicht, dann mit Fehlerbeschreibung mir den zurückgelieferten text schicken.

**Comment by mar565** [comment]
Danke für die Hilfe.
Der Adapter wird erfolgreich angelegt und das schalten der Steckdose, sowie alle sonstigen Werte, funktionieren auch.
Der Wert "Powerline aktiv" taucht allerdings nirgends auf.
Wäre ganz nützlich, um Nachts Strom zu sparen.

**Comment by foxthefox** [comment]
Ich habe leider kein PowerLine und kann nicht einschätzen, was "Powerline aktiv" genau bedeutet. So etwas ist nicht in der API von der Fritzbox enthalten. Es gibt den Datenpunkt "present" der anzeigt, ob ein Gerät von der Fritzbox erreichbar ist, oder nicht. Evtl. hilft dir dieser Wert ja irgendwie.

**Comment by foxthefox** [comment]
Das aktiv Flag scheint nicht Bestandteil der API von AVM zu sein.
Daher gibt es diesen keine Möglichkeit dies über ioBroker zu steuern.
