### ISSUE TITLE
Wert Absenk Komfort und tist

### ISSUE THREAD

**Issue by imo1983** [foxthefox/ioBroker.fritzdect#458]
Hallo, 
Seid Version 2.5.2, Mit 2.4.1 läuft alles 

Der Wert für Absenk und komfort wird periodisch zwischen dem richtigen Wert und 0 geschrieben 

State value to set for "fritzdect.0.DECT_099950598975.komfort" has value "0" less than min "8"

State value to set for "fritzdect.0.DECT_099950598975.absenk" has value "0" less than min "8"

State value to set for "fritzdect.0.DECT_099950598975.tist" has value "0" less than min "1"

Schöne Grüße

**Comment by foxthefox** [comment]
In der Tat habe ich wegen #164 die Übernahme von Werten geändert, allerdings wundert mich grad warum es zu "0" wird.
Eigentlich sollte NaN oder null herauskommen.
Deswegen noch ein paar Fragen:
- was ist für Absenk und Komfort eingestellt und verursacht die 0?
- was zeigt tist in der FB? Gibt es dort auch AUS und EIN?
- was ist mit periodisch gemeint?

**Comment by imo1983** [comment]
Hi, 
Hab mal die Option
"Write only Changes to Objects" deaktiviert und damit funktioniert wieder alles ohne 0 Werte und den  Fehlermeldungen im log 

Periodisch: schwer zu sagen, aber würde mal auf jeden zweiten Wert tippen der neu geschrieben wird

In der FRITZ App kann ich keine Auffälligkeiten erkennen. Schaut alles ok aus

Schöne Grüße

**Comment by foxthefox** [comment]
und was ist bei Absenk und Komfort eingestellt?

**Comment by imo1983** [comment]
Mit aktivierten Option "Write only Changes to Objects“ und bei 0 Werten 

[{"identifier":"09995 0591128","id":"26","functionbitmask":"320","fwversion":"05.08","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Wohnzimmer","battery":"80","batterylow":"0","temperature":{"celsius":"185","offset":"0"},"hkr":{"tist":"37","tsoll":"38","absenk":"32","komfort":"38","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1697400000","tchange":"32"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"1","adaptiveHeatingRunning":"0"}},{"identifier":"09995 0552016","id":"25","functionbitmask":"320","fwversion":"05.08","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Küche","battery":"80","batterylow":"0","temperature":{"celsius":"180","offset":"0"},"hkr":{"tist":"36","tsoll":"38","absenk":"32","komfort":"38","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1697392800","tchange":"32"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"1","adaptiveHeatingRunning":"0"}},{"identifier":"09995 0416257","id":"29","functionbitmask":"320","fwversion":"05.08","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Schlafzimmer","battery":"90","batterylow":"0","temperature":{"celsius":"185","offset":"0"},"hkr":{"tist":"37","tsoll":"38","absenk":"32","komfort":"38","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"90","nextchange":{"endperiod":"1697392800","tchange":"32"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"1","adaptiveHeatingRunning":"0"}},{"identifier":"09995 0598642","id":"27","functionbitmask":"320","fwversion":"05.08","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Badezimmer","battery":"50","batterylow":"0","temperature":{"celsius":"190","offset":"0"},"hkr":{"tist":"38","tsoll":"38","absenk":"32","komfort":"38","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"50","nextchange":{"endperiod":"1697392800","tchange":"32"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"1","adaptiveHeatingRunning":"0"}},{"identifier":"09995 0598975","id":"28","functionbitmask":"320","fwversion":"05.08","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Flur","battery":"70","batterylow":"0","temperature":{"celsius":"190","offset":"0"},"hkr":{"tist":"38","tsoll":"38","absenk":"32","komfort":"38","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"70","nextchange":{"endperiod":"1697392800","tchange":"32"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"1","adaptiveHeatingRunning":"0"}}]

****
Mit Deaktivieren option


[{"identifier":"09995 0591128","id":"26","functionbitmask":"320","fwversion":"05.08","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Wohnzimmer","battery":"80","batterylow":"0","temperature":{"celsius":"185","offset":"0"},"hkr":{"tist":"37","tsoll":"38","absenk":"32","komfort":"38","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1697400000","tchange":"32"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"1","adaptiveHeatingRunning":"0"}},{"identifier":"09995 0552016","id":"25","functionbitmask":"320","fwversion":"05.08","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Küche","battery":"80","batterylow":"0","temperature":{"celsius":"180","offset":"0"},"hkr":{"tist":"36","tsoll":"38","absenk":"32","komfort":"38","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1697392800","tchange":"32"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"1","adaptiveHeatingRunning":"0"}},{"identifier":"09995 0416257","id":"29","functionbitmask":"320","fwversion":"05.08","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Schlafzimmer","battery":"90","batterylow":"0","temperature":{"celsius":"185","offset":"0"},"hkr":{"tist":"37","tsoll":"38","absenk":"32","komfort":"38","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"90","nextchange":{"endperiod":"1697392800","tchange":"32"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"1","adaptiveHeatingRunning":"0"}},{"identifier":"09995 0598642","id":"27","functionbitmask":"320","fwversion":"05.08","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Badezimmer","battery":"50","batterylow":"0","temperature":{"celsius":"190","offset":"0"},"hkr":{"tist":"38","tsoll":"38","absenk":"32","komfort":"38","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"50","nextchange":{"endperiod":"1697392800","tchange":"32"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"1","adaptiveHeatingRunning":"0"}},{"identifier":"09995 0598975","id":"28","functionbitmask":"320","fwversion":"05.08","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","txbusy":"0","name":"Flur","battery":"70","batterylow":"0","temperature":{"celsius":"190","offset":"0"},"hkr":{"tist":"38","tsoll":"38","absenk":"32","komfort":"38","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"70","nextchange":{"endperiod":"1697392800","tchange":"32"},"summeractive":"0","holidayactive":"0","adaptiveHeatingActive":"1","adaptiveHeatingRunning":"0"}}]

**Comment by foxthefox** [comment]
habe die version 2.5.3 auf github erstellt, bitte installieren und testen

**Comment by imo1983** [comment]
2.5.3 läuft seid heute morgen ohne Auffälligkeiten auch mit aktiven Option "Write only Changes to Objects“

Vielen Dank
