### ISSUE TITLE
2.5.2	[Polling] <== TypeError: 

### ISSUE THREAD

**Issue by fichte-112** [foxthefox/ioBroker.fritzdect#460]
Seit dem letzten Update bekomme ich alle 10 Sekunden folgende Fehlermeldung

`fritzdect.0 | 2023-10-17 19:53:10.497 | warn | [Polling] <== TypeError: Cannot read properties of undefined (reading 'count')
-- | -- | -- | --
fritzdect.0 | 2023-10-17 19:53:08.828 | info | glob state ["XXXX00053174","grpXXXX7D-XXXX75E9E"]`

**Comment by mcm1957** [comment]
duplicate #459

**Comment by foxthefox** [comment]
Ich konnte es nachstellen. 
Wenn das Gerät nicht in der Steckdose ist, dann ist die Antwort der Fritzbox anders.
Werde heute eine Korrektur erarbeiten.

**Comment by fichte-112** [comment]
Es sind alle Geräte angeschlossen und in Betrieb.

**Comment by foxthefox** [comment]
Hmm, dann ists immerhin ein ähnliches Problem mit der Antwort von der FB.
habe die version 2.5.3 auf github erstellt, bitte installieren und testen

**Comment by fichte-112** [comment]
Die Fehlermeldung kommt jetzt nicht mehr. Vielen Dank.
