### ISSUE TITLE
Error Calling the Fritzbox

### ISSUE THREAD

**Issue by JBSullivan** [foxthefox/ioBroker.fritzdect#465]
Adapter Version 2.5.4

Ist die Meldung bekannt? Die kommt eigentlich seit Monaten in immer wieder unterschiedlicher Intensität was zu mehreren dutzend MB großen Log Dateien führt.

Aktuell sind drei DECT Schaltsteckdosen an der Fritte angemeldet. Diese lassen sich sowohl über Alexa, die neue Fritz SmartHome App und auch über den ioB Adapter ansprechen. Deswegen will mir die Fehlermeldung nicht so recht in den Kopf.

Neustart der Fritzbox bringt auch kein reproduzierbares Ergebnis. Mal kommen die Meldungen 10-15 Minuten, mal 2-3 Tage nach einem Neustart wieder.

`<html>
<body>

fritzdect.0 | 15404 | 2023-10-31 12:01:32.168 | warn | [Polling] <== TypeError: Cannot read properties of undefined (reading 'replace')
-- | -- | -- | -- | --
fritzdect.0 | 15404 | 2023-10-31 12:01:32.167 | error | API err => [object Object]
fritzdect.0 | 15404 | 2023-10-31 12:01:32.167 | error | no response part in returned error message
fritzdect.0 | 15404 | 2023-10-31 12:01:32.167 | error | API funct => login_SID
fritzdect.0 | 15404 | 2023-10-31 12:01:32.167 | error | API msg => error calling executeCommand
fritzdect.0 | 15404 | 2023-10-31 12:01:32.167 | error | --------------- error calling the fritzbox -----------
fritzdect.0 | 15404 | 2023-10-31 12:01:30.567 | error | API err => [object Object]
fritzdect.0 | 15404 | 2023-10-31 12:01:30.567 | error | no response part in returned error message
fritzdect.0 | 15404 | 2023-10-31 12:01:30.567 | error | API funct => login_SID
fritzdect.0 | 15404 | 2023-10-31 12:01:30.567 | error | API msg => error calling executeCommand
fritzdect.0 | 15404 | 2023-10-31 12:01:30.566 | error | --------------- error calling the fritzbox -----------

</body>
</html>`

**Comment by foxthefox** [comment]
Welche FB?
UpdateZyklus im Adapter? 300=5min?
Skripte die mit fritzdect-Zuständen arbeiten?
Andere Adapter die auf die FB zugreifen?
Andere Hausautomatisierung mit Zugriff auf die FB?
Kann man Alexa für eine gewisse Zeit für die FB deaktivieren?

Da es zwar regelmäßig aber eher sporadisch auftritt, ist es kein Problem des Logins an sich, sondern eher etwas bzgl. Gleichzeitigkeit von Aktivitäten an der FB.

Vielfach ist es weniger der Adapter selbst, sondern die FB die nur eine begrenzte Anzahl von Zugriffen erlaubt.

**Comment by JBSullivan** [comment]
Sorry, war wohl mein Fehler - auf dein Posting hin, habe ich mal die Adapter Einstellungen durchgesehen und muss zu meiner Schande gestehen, das mir beim Update Zyklus unbewusst die beiden Nullen abhanden gekommen sind. Der stand tatsächlich auf "3".
Ich habe ihn jetzt wieder auf 300 gestellt und seit dem ist Ruhe im Karton mit den Fehler Meldungen. Danke für die Unterstützung. Kann somit geschlossen werden.
