### ISSUE TITLE
fritzdect has an invalid jsonConfig:

### ISSUE THREAD

**Issue by Brainbug01** [foxthefox/ioBroker.fritzdect#478]
Kommt beim öffnen des Adapters V2.5.5

```
warn

fritzdect has an invalid jsonConfig: 
[{
"instancePath":"",
"schemaPath":"#/additionalProperties",
"keyword":"additionalProperties",
"params":{"additionalProperty":"label"},
"message":"must NOT have additional properties"
}]
```

**Comment by foxthefox** [comment]
Hmm, bei mir kommt es nicht.
Ich habe admin Version 6.12.0 installiert.
Evtl. ist deine admin Version zu alt?
Passwort muß übrigens neu eingegeben werden

**Comment by Brainbug01** [comment]
Ich hab Admin 6.12.2 installiert. Ja Passwort hab ich schon neu eingegeben.

**Comment by foxthefox** [comment]
Die hab ich auch mittlerweile und da gibts auch kein Problem.
Fehlt etwas ? oder nervt die Meldung nur?

**Comment by Brainbug01** [comment]
Ich hab das bei einigen Adapter siehe: https://github.com/ioBroker/ioBroker.admin/issues/2184

**Comment by Brainbug01** [comment]
v2.5.6 funktioniert.
