### ISSUE TITLE
Why no Offset anymore...

### ISSUE THREAD

**Issue by kugelkopf123** [foxthefox/ioBroker.fritzdect#48]
Hey!

In the latest Version 0.2.2 there is no offset anymore in the temp datapoint. 
But Why?
With, i think v.0.1.9 i've got 2 Datapoints Acutal Temp and Temp. One with the Offset and one without That was totally great. Why dont leave it this way?

Greetings..

**Comment by foxthefox** [comment]
I have put in a new datapoint for the offset -> temp_offset.
In the comments which I got, is my understanding, that the data transmitted from fritzbox is already including the offset. So tweaking it in the adapter again is doubling the correction. If you deem that this offset is necessary, then you can combine the temp and temp_offset in your visualization.
For now I left the 2 datapoints, even there is no difference anymore.

**Comment by sky-it** [comment]
Würde einen änderbaren Offset-Wert begrüßen.
Es ist richtig, dass die Werte den Offset bereits berücksichtigen, es gibt jedoch noch Anwender die am Heizkörper direkt die Temperatur einstellen und hier würde man ja die Temp einstellen die man haben möchte, der Offset trägt dazu bei, dass die richtige Raumtemperatur vom Thermostat erreicht wird.

Anwendungsfall bei mir:
301 ist auf 22 Grad eingestellt. Im Raum ist es jedoch erst 21 Grad (Temperatursensor eines anderen Herstellers im Raum)
Offset soll sich durch setzen über ioBroker dynamisch an die Raumtemperatur anpassen.

**Comment by foxthefox** [comment]
mit der Version 2.x habe ich auf die Daten der Fritzbox umgestellt und sie sind jetzt genau so benannt wie die API sie rüberbringt.
Mit dem Poll wird alles überschrieben und somit ergäbe es keinen Sinn den Offset zu ändern, ebensowenig ist er an die Fritzbox übertragbar. In dem Fall wäre wohl eine geeignetes JS script in iobroker das richtigere.

**Comment by kugelkopf123** [comment]
Ja, aber es war so schön als der Adapter sowohl den Errechneten Offset wert als auch den tatsächlichen Wert ausspuckte. Da brauchte man kein unnötiges Script um sich selbst einen Datenpunkt zu erzeugen und die Differenz zu errechnen. 
:)

**Comment by foxthefox** [comment]
Die Rechnerei die gemacht hatte, war ja ohnehin falsch. Ich habe den Offset ja nochmals bei der Übernahme in iobroker hineingerechnet und der celsius wert hatte den schon dabei. also 2mal eingerechnet, erste mal in der fritzbox selbst und dann nochmal im adapter.
