### ISSUE TITLE
fritzdect.0 (3872233) [Polling] <== TypeError: Cannot read properties of null (reading 'val')

### ISSUE THREAD

**Issue by asmitconsulting** [foxthefox/ioBroker.fritzdect#483]
Ich habe regelmäßig die o.G, Meldung im LOG (alle 300s).
Versucht habe ich schon eine Neuinstallation, das Löschen aller Datenpunkte und Neustart des Adapters - der Fehler kommt immer wieder - und zumindest im normalen LOG nicht erkennbar aus welchem Grund / welches Gerät.
Also heute mal für eine gewisse Zeit das DEBUG-LOG eingeschaltet und Ergebnis hier beigefügt. Vielleicht findet Ihr was.
Zumindest 2x ist der Fehler da auch dokumentiert, allerdings erkenne ich den Grund nicht, woran er sich stößt. 
[iobroker.2023-11-12.log.zip](https://github.com/foxthefox/ioBroker.fritzdect/files/13327736/iobroker.2023-11-12.log.zip)

Die Test-Systemumgebung ist ein Multihost-System (Proxmox/RASPI 4) der Adapter läuft auf dem RASPI 
Alle Systeme laufen mit Node.js: v18.18.2 und NPM: 9.8.1 (ioBroker aus BETA-REPOS)
Controller: 5.0.16 und Fritzdect-Version: 2.5.8 
Im Netz sind 2 FB 7590 (1 Mesh-Master im EG / 1 Slave im OG) 
Bitte bei Gelegenheit mit abstellen - Danke schön

**Comment by foxthefox** [comment]
Als Übergangslösung mal das häckchen bei exclude statistics setzen.

**Comment by asmitconsulting** [comment]
Danke - 
bisher (seit 22:30) gibt es kein neues Auftreten der Meldung - sollte es wieder auftreten, gebe ich Bescheid

**Comment by foxthefox** [comment]
ich habe eine Version 2.5.9 in github erstellt, bitte ausprobieren (exclude statistics wieder häckchen raus)

**Comment by asmitconsulting** [comment]
ist installiert, und das Häkchen ist wieder raus genommen - 

2023-11-18 21:05:09.482 | info | starting. Version 2.5.9 (non-npm: foxthefox/ioBroker.fritzdect) in /opt/iobroker/node_modules/iobroker.fritzdect, node: v18.18.2, js-controller: 5.0.16

Bisher keine Auffälligkeiten - Danke :-)

**Comment by foxthefox** [comment]
scheint gefixt zu sein
