### ISSUE TITLE
Kein Login mehr möglich auf Fritzbox

### ISSUE THREAD

**Issue by jansios** [foxthefox/ioBroker.fritzdect#484]
**Describe the bug**  
Der ioBroker kann seit heute keinen Login mehr auf der Fritzbox durchführen und meldet, dass das Kennwort falsch wäre.

**To Reproduce**  
Ich muss den Adapter nur neu starten, schon klappt es wieder nicht.

**Expected behavior**  
Erfolgreicher Login und funktionierender Adapter ;)

**Screenshots & Logfiles**  

ioBroker:
fritzdect.0 | 2023-11-12 19:32:09.465 | error | login not possible, check user and permissions
-- | -- | -- | --
fritzdect.0 | 2023-11-12 19:32:09.464 | error | API err => [object Object]
fritzdect.0 | 2023-11-12 19:32:09.463 | error | no response part in returned error message
fritzdect.0 | 2023-11-12 19:32:09.463 | error | API funct => login_SID
fritzdect.0 | 2023-11-12 19:32:09.462 | error | API msg => error calling executeCommand
fritzdect.0 | 2023-11-12 19:32:09.461 | error | --------------- error calling the fritzbox -----------
fritzdect.0 | 2023-11-12 19:32:08.439 | info | fritzdect uses USER: iobroker_fritzdect
fritzdect.0 | 2023-11-12 19:32:08.396 | info | fritzdect entered ready
fritzdect.0 | 2023-11-12 19:32:08.355 | info | starting. Version 2.5.8 (non-npm: foxthefox/ioBroker.fritzdect) in /opt/iobroker/node_modules/iobroker.fritzdect, node: v18.18.2, js-controller: 5.0.12

Fritzbox:
12.11.23   19:32:09   Anmeldung des Benutzers iobroker_fritzdect an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.168.30 gescheitert (falsches Kennwort).

**Versions:**  
 - Adapter version: 2.58
 - JS-Controller version: 5.0.12, Problem trat auch bei 4.24 auf - Update wurde als Lösung probiert, leider ohne Erfolg
 - Node version: 18.18.2
 - Operating system: Linux (Docker auf Diskstation, Image von https://smarthome.buanet.de/2019/05/iobroker-unter-docker-auf-der-synology-diskstation-v3/ )

**Additional context**  
Ich habe
- den ioBroker neu gestartet,
- die Fritzbox neu gestartet,
- einen anderen User verwendet,
- beide User im Webbrowser erfolgreich an der Fritzbox angemeldet
- den ioBroker upgedatet (JS-Controller) und
- den Container mit neuestem Docker Image neu erstellt.

Leider alles ohne Erfolg.

**Comment by jansios** [comment]
Auch noch ergänzend des Debug-Log des Adapters:

fritzdect.0 | 2023-11-13 11:31:45.583 | error | login not possible, check user and permissions
-- | -- | -- | --
fritzdect.0 | 2023-11-13 11:31:45.583 | error | API err => [object Object]
fritzdect.0 | 2023-11-13 11:31:45.583 | error | no response part in returned error message
fritzdect.0 | 2023-11-13 11:31:45.583 | error | API funct => login_SID
fritzdect.0 | 2023-11-13 11:31:45.582 | error | API msg => error calling executeCommand
fritzdect.0 | 2023-11-13 11:31:45.581 | error | --------------- error calling the fritzbox -----------
fritzdect.0 | 2023-11-13 11:31:44.816 | info | fritzdect uses USER: iobroker_fritzdect
fritzdect.0 | 2023-11-13 11:31:44.745 | info | fritzdect entered ready
fritzdect.0 | 2023-11-13 11:31:44.709 | info | starting. Version 2.5.8 (non-npm: foxthefox/ioBroker.fritzdect) in /opt/iobroker/node_modules/iobroker.fritzdect, node: v18.18.2, js-controller: 5.0.16
fritzdect.0 | 2023-11-13 11:31:44.365 | debug | States connected to redis: 0.0.0.0:9000
fritzdect.0 | 2023-11-13 11:31:44.192 | debug | States create User PubSub Client
fritzdect.0 | 2023-11-13 11:31:44.190 | debug | States create System PubSub Client
fritzdect.0 | 2023-11-13 11:31:44.087 | debug | Redis States: Use Redis connection: 0.0.0.0:9000
fritzdect.0 | 2023-11-13 11:31:43.920 | debug | Objects connected to redis: 0.0.0.0:9001
fritzdect.0 | 2023-11-13 11:31:43.862 | debug | Objects client initialize lua scripts
fritzdect.0 | 2023-11-13 11:31:43.860 | info | Sets unsupported
fritzdect.0 | 2023-11-13 11:31:43.623 | debug | Objects create User PubSub Client
fritzdect.0 | 2023-11-13 11:31:43.620 | debug | Objects create System PubSub Client
fritzdect.0 | 2023-11-13 11:31:43.617 | debug | Objects client ready ... initialize now
fritzdect.0 | 2023-11-13 11:31:43.518 | debug | Redis Objects: Use Redis connection: 0.0.0.0:9001

Ein weiteres Upgrade des js_Controllers auf 5.0.16 brauchte auch keine Besserung

**Comment by foxthefox** [comment]
Wurde auch das Passwort neu in der Admin Page des Adapters eingegeben?
