### ISSUE TITLE
Restart loop after updating to Version 2.5.9

### ISSUE THREAD

**Issue by delta2308151984** [foxthefox/ioBroker.fritzdect#500]
Hi, after updating to version 2.5.9 the instance is in restart loop.
Thanks for any help

ioBroker Docker Container v. 9.0.1
Node.js v18.19.0

log output:

host.buanet-iobroker | 2023-12-12 23:07:14.475 | info | Restart adapter system.adapter.fritzdect.0 because enabled
-- | -- | -- | --
host.buanet-iobroker | 2023-12-12 23:07:14.473 | error | instance system.adapter.fritzdect.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
fritzdect.0 | 2023-12-12 23:07:14.203 | info | terminating
fritzdect.0 | 2023-12-12 23:07:14.075 | error | undefined
fritzdect.0 | 2023-12-12 23:07:14.075 | error | unhandled promise rejection: undefined
fritzdect.0 | 2023-12-12 23:07:14.072 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
fritzdect.0 | 2023-12-12 23:07:13.982 | info | going over to cyclic polling, messages to poll activity only in debug-mode
fritzdect.0 | 2023-12-12 23:07:13.977 | info | finished initial updating devices/groups
fritzdect.0 | 2023-12-12 23:07:13.698 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
fritzdect.0 | 2023-12-12 23:07:13.697 | info | terminating
fritzdect.0 | 2023-12-12 23:07:13.694 | info | cleaned everything up...
fritzdect.0 | 2023-12-12 23:07:13.690 | error | undefined
fritzdect.0 | 2023-12-12 23:07:13.689 | error | unhandled promise rejection: undefined
fritzdect.0 | 2023-12-12 23:07:13.688 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
fritzdect.0 | 2023-12-12 23:07:11.873 | info | start initial updating devices/groups
fritzdect.0 | 2023-12-12 23:07:11.873 | info | finished creating routines (if any)
fritzdect.0 | 2023-12-12 23:07:11.525 | info | start creating routines
fritzdect.0 | 2023-12-12 23:07:11.522 | info | routines are used(false)
fritzdect.0 | 2023-12-12 23:07:11.522 | info | finished creating templates (if any)
fritzdect.0 | 2023-12-12 23:07:11.397 | info | CREATE Templates 2
fritzdect.0 | 2023-12-12 23:07:10.874 | info | start creating templates
fritzdect.0 | 2023-12-12 23:07:10.873 | info | templates are used(false)
fritzdect.0 | 2023-12-12 23:07:10.873 | info | finished creating devices/groups (if any)
fritzdect.0 | 2023-12-12 23:07:10.432 | info | create Main object DECT_ xxx Wohnzimmer thermo.heat
fritzdect.0 | 2023-12-12 23:07:10.432 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:10.431 | info | CREATE groups 1
fritzdect.0 | 2023-12-12 23:07:09.843 | info | create Main object DECT_ xxx Dachboden thermo.heat
fritzdect.0 | 2023-12-12 23:07:09.843 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:09.146 | info | create Main object DECT_ xxx Küche thermo.heat
fritzdect.0 | 2023-12-12 23:07:09.145 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:08.646 | info | create Main object DECT_ xxx Baum switch
fritzdect.0 | 2023-12-12 23:07:08.645 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:08.208 | info | create Main object DECT_xxx.button. xxx Buttons button
fritzdect.0 | 2023-12-12 23:07:08.208 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:08.207 | info | create Main object DECT_xxx.button. xxx Buttons button
fritzdect.0 | 2023-12-12 23:07:08.207 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:08.207 | info | create Main object DECT_xxx.button. xxx Buttons button
fritzdect.0 | 2023-12-12 23:07:08.207 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:08.206 | info | create Main object DECT_xxx.button. xxx Buttons button
fritzdect.0 | 2023-12-12 23:07:08.206 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:08.055 | info | create Main object DECT_ xxx Schalter Wohnzimmer thermo
fritzdect.0 | 2023-12-12 23:07:08.054 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:07.466 | info | create Main object DECT_ xxx Thermostat Bad thermo.heat
fritzdect.0 | 2023-12-12 23:07:07.466 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:06.764 | info | create Main object DECT_ xxx Thermostat Esszimmer thermo.heat
fritzdect.0 | 2023-12-12 23:07:06.763 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:06.043 | info | create Main object DECT_ xxx Thermostat Wohnzimmer thermo.heat
fritzdect.0 | 2023-12-12 23:07:06.042 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:05.146 | info | create Main object DECT_ xxx Thermostat Flur thermo.heat
fritzdect.0 | 2023-12-12 23:07:05.145 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:05.133 | info | CREATE Devices 9
fritzdect.0 | 2023-12-12 23:07:04.500 | info | start creating devices/groups
fritzdect.0 | 2023-12-12 23:07:04.498 | info | finished creating global values
fritzdect.0 | 2023-12-12 23:07:04.443 | info | create Main object global channel list
fritzdect.0 | 2023-12-12 23:07:04.443 | info | ____________________________________________
fritzdect.0 | 2023-12-12 23:07:04.442 | info | start creating global values
fritzdect.0 | 2023-12-12 23:07:04.441 | info | the rights are : {"Rights":{"Name":["Dial","App","HomeAuto","BoxAdmin","Phone","NAS"],"Access":["2","2","2","2","2","2"]}}
fritzdect.0 | 2023-12-12 23:07:04.184 | info | checking user permissions
fritzdect.0 | 2023-12-12 23:07:01.903 | info | fritzdect uses USER: xxx
fritzdect.0 | 2023-12-12 23:07:01.764 | info | fritzdect entered ready
fritzdect.0 | 2023-12-12 23:07:01.727 | info | starting. Version 2.5.9 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v18.19.0, js-controller: 5.0.16
host.buanet-iobroker | 2023-12-12 23:06:58.975 | info | instance system.adapter.fritzdect.0 started with pid 3246

**Comment by delta2308151984** [comment]
when i checked the box "must be checked (true) to activate the reduced logging" in the instance settings, all is fine. 
If i unchecked the box, the instance get in restart loop.

**Comment by foxthefox** [comment]
unfortunately I can not reproduce the problem at my setup, can you provide a log in debug mode?

**Comment by zicheee** [comment]
I had the same problem and searched for solutions and found this thread. In the meantime I noticed, that when recreating the docker container and pulling the latest image, I noticed that I still had js-controller 4.* (don't remember the exact version), but Node.js 18 and docker container 9.0.1. 
I upgraded iobroker using the maintenance script through the docker terminal of my iobroker instance:

```
maintenance on
maintenance upgrade
```

Now everything is working correct. 
@delta2308151984 Maybe your js controller version is also outdated?

**Comment by delta2308151984** [comment]
Thanks for your answers.
@foxthefox it is a 7590 AX. How can i provide a log in debug mode?
@zicheee i recreated the container with v 9.0.1 and js.controller 5.0.17. Still the same problem

**Comment by foxthefox** [comment]
in the instance tab the expert mode needs to be enabled.
After that each adapter has the possibility to switch from info to debug mode.

**Comment by foxthefox** [comment]
in absence of debug logs I have inserted some more routines to catch some errors
please have a try with the 2.5.10 from github
