### ISSUE TITLE
Fritz Dect 302 hkrmode funktioniert nicht 

### ISSUE THREAD

**Issue by mbefore305** [foxthefox/ioBroker.fritzdect#501]
**Describe the bug**  
Per Blockly Script ändere ich den hkrmode eines Fritz Dect 302 Thermostates (0 oder 1).
Diese Änderung ist im hkrmode Objekt sichtbar aber der Thermostat ändert den Modus nicht.

**To Reproduce**  
Am Thermostat eine Temperatur einstellen (z.B. 20°).
Im Script den hkrmode auf 1 (closed) setzen (control ...).
Warten (max 15 Minuten)

**Expected behavior**  
Am Thermostat sollte nun das Schneeflockensymbol angezeigt werden.
Stattdessen bleibt das Ventil offen und die vorher eingestellte Temperatur bleibt.

**Screenshots & Logfiles**  
-

**Versions:**  
 - Adapter version: 2.5.9
 - JS-Controller version: <js-controller-version>  5.0.17
 - Node version: <node-version>  v18.19.0
 - Operating system: <os-name> Docker Buanet 

**Additional context**  
Mit den vorherigen Dect 301 hat das Script und der Adapter funktioniert.

**Comment by foxthefox** [comment]
Ein paar Fragen dazu:
- Das Passwort wurde neu im Adapter Admin eingegeben (war notwendig wegen Wechsel auf das jsonUI) ?
- Der Befehl im blockly ist mit ack=false abgesetzt?

**Comment by mbefore305** [comment]
Wow, danke für die schnelle Antwort.
Auf die Idee, dass mit dem Login etwas nicht stimmt wäre ich nie drauf gekommen.
Temperatur Änderung (tsoll) funktioniert einwandfrei. Auch ist der Adapter Grün, auch, wenn ich absichtlich ein falsches Passwort eingebe.

Änderungen mache ich per Blockly mit "Control". Da gibt es kein "ack", oder übersehe ich da etwas?

Egal ob hkrmode oder tsoll, es kommt angehängter Fehler im Log.
Seltsam ist, dass die Temperaturänderung funktioniert (!) aber hkrmode Änderung nicht.

<img width="1006" alt="image" src="https://github.com/foxthefox/ioBroker.fritzdect/assets/6396795/c37deb7d-c840-481f-8f5d-ddeb6ffcb02d">

**Comment by foxthefox** [comment]
OK, wenn blockly "control" hat, dann wird es das entsprechend für ack=false sein.
Im Normalfall sollte eigentlich eine Mitteilung aufgehen, daß es eine Neueingabe des PW braucht, wenn man 2.5.9 installiert.

Grün ist der Adapter, wenn er läuft. Da man sich zyklisch die Daten von der FB holt, ist man zwischendrin quasi offline. Deswegen habe ich keine weitere Implementierung gemacht, hier noch zwischen Gelb und Grün zu wechseln.

Falls es ein neues Blockly ist, würde ich hier mal noch prüfen, ob es den Befehl nicht permanent absetzt, also ständig geriggert wird. Da würde auch ein längeres Log, wenn der Adapter auf debug gestellt wurde, helfen. Die Fehlermeldung selbst steht meist im Kontext mit Dingen davor. 
Oftmals mag die FB ein Feuerwerk von kurz hintereinanderfolgenden Befehlen nicht.

Ansonsten würde ich wirklich nochmal das PW prüfen und den Adapter neu starten und den Beginn des logs anschauen. Da müsste mindestens eine Zeile mit Rights kommen, wo "2" genügend Berechtigung darstellt.

**Comment by mbefore305** [comment]
Was mich einfach sehr verwundert ist, das tsoll klappt aber hkrmode nicht.
Habe den Adapter neu installiert

**Comment by mbefore305** [comment]
Jetzt scheint es zu funktionieren!
Habe den Adapter neu installiert. Vorher nur das PW neu einzugeben hat nicht geholfen.
Die Fehlermeldung taucht nicht mehr auf.
Mich wunder nur, warum tsoll funktioniert hat.

Das Script ist alt, habe darin aber zusätzlich 5 Sekunden Timeouts eingebaut, damit die Befehle nicht zu schnell kommen.
In meinen Fall gibt es wenige Trigger. Zeitabhängig von der Uhrzeit und wenn Fenster geschlossen oder geöffnet werden.

Vielen Dank für Deine Hilfe und Tipps!

**Comment by foxthefox** [comment]
das freut mich, wenn es geht.
Wenn dir der Adapter gefällt, dann freu ich mich über ein "star"
