### ISSUE TITLE
ioBroker wiederkehrende Fehler im Log /  Adapter optionen "exclude..."

### ISSUE THREAD

**Issue by HolgerOnGithub** [foxthefox/ioBroker.fritzdect#502]
fritzdect.0 | 2023-12-30 01:20:18.894 | error | API  err  => {"msg":"AHA request error","function":"fritzAHA_Request","error":400,"status":400}
-- | -- | -- | --
fritzdect.0 | 2023-12-30 01:20:18.893 | error | no response part in returned error message
fritzdect.0 | 2023-12-30 01:20:18.893 | error | API funct => executeCommand2
fritzdect.0 | 2023-12-30 01:20:18.893 | error | API msg   => relogin failed, or status400/500
fritzdect.0 | 2023-12-30 01:20:18.892 | error | --------------- error calling the fritzbox -----------
fritzdect.0 | 2023-12-30 01:19:48.596 | error | API  err  => {"msg":"AHA request error","function":"fritzAHA_Request","error":400,"status":400}
fritzdect.0 | 2023-12-30 01:19:48.596 | error | no response part in returned error message
fritzdect.0 | 2023-12-30 01:19:48.596 | error | API funct => executeCommand2
fritzdect.0 | 2023-12-30 01:19:48.595 | error | API msg   => relogin failed, or status400/500
fritzdect.0 | 2023-12-30 01:19:48.595 | error | --------------- error calling the fritzbox -----------

Nach Aktivierung aller Adapter Optionen:

exclude templates (check if older FB)

exclude routines (check if older FB)

exclude statistics (check if older FB)

bleiben diese Fehlermeldungen aus

**Comment by foxthefox** [comment]
Ist es denn eine ältere FB? Wenn ja, dann passt es ja, da  ältere FW nicht die neuesten Funktionen hat. Deswegen gibt es die Option zum Abwählen.

**Comment by HolgerOnGithub** [comment]
7590 mit V7.29

**Comment by foxthefox** [comment]
Die 7590 ist zwar nicht alt, aber die FW. Somit passt es, denn die alte FW kennt die neuen Funktionen nicht und antwortet nicht darauf. Also verhindern die Häckchen zum Ausschluss der Funktion die Fehlermeldung.

Für 7590 gibt es schon die V7.57, da wären die Funktionen drin und die Häckchen könnten wieder raus.

Falls der Adapter gefällt, freue ich mich über ein „Star“ im repository.

**Comment by HolgerOnGithub** [comment]
Vielen Dank, vielleicht wäre eine "Grenzdefinition" in der Beschreibung gut was alt und neu ist. #Update läuft
