### ISSUE TITLE
Password field hides itself

### ISSUE THREAD

**Issue by r101170** [foxthefox/ioBroker.fritzdect#509]
Good Morning FoxTheFox and a happy new year,
thank you for the well working adapter so far.
Since my nodejs update on yetserday I not able to enter the password in the
adapter because it hides itself, when I start editing the field.

Do you know this issue?
![image](https://github.com/foxthefox/ioBroker.fritzdect/assets/107350059/0f342cba-c4af-4967-bfd8-596951245e2e)

Adapterversion:2.5.9
nodejs: 18.19.0
node: 18.19.0
npm: 10.2.3

best regards 
Rana

**Comment by r101170** [comment]
Hi FoxTheFox,
I found a solution for bringing the adapter back to work via exporting, editing and reimporting the
expert json data.
But the issue with hiding/deleting the password field stays alive.

best wishes 
Rana

**Comment by foxthefox** [comment]
I wish you all the best for 2024.

this looks strange and is new for me, I have to check it, when I am back on my computer.

which version do you have as the admin-adapter?
My version 6.1x looked good.

btw if you like the adapter I appreciate if you give a star to the repo. Thanks

**Comment by r101170** [comment]
my admin adapter is 5.3.8
I will update in a moment

**Comment by r101170** [comment]
You are absolutly right. The update fixed the problem.
I updated to 6.12.0 and gave you all stars
thanks

**Comment by foxthefox** [comment]
Thanks a lot.
I am glad that the solution was simple.
