### ISSUE TITLE
Comet Dect Thermostat wird nicht angezeigt

### ISSUE THREAD

**Issue by funboxbolzer** [foxthefox/ioBroker.fritzdect#51]
Hallo, muss ich für die Comet Dect Thermostate noch etwas zusätzlich konfigurieren? Habe über Git die aktuelle Version 0.2.4 installiert. Bekomme aber nur die Dect 100 und 200 angezeigt. 
Danke Gruß Klaus

**Comment by foxthefox** [comment]
Nein, es ist nichts zusätzlich zu installieren.
Bitte mal den Button "Meine Geräte" in der Adapter-Config benutzen, danach öffnet sich ein Fenster. In dessen Text sollten die Thermostate auftauchen, falls ja, dann bräuchte ich den output, weil dann der Adapter was nicht richtig tut, falls nein, dann ist etwas in der Fritzbox nicht richtig konfiguriert.

Gruß
Klaus

**Comment by funboxbolzer** [comment]
Hi. Mittlerweile funktioniert alles. Habe meinen iobroker mal aktualisiert.
Brauchst du noch den output? Hast geschrieben „falls ja“? Wenn ja, welchen output bzw. was genau?
