### ISSUE TITLE
Adapter überträgt die geänderten Werte nicht an die Fritzbox. Adapterversion: 2.5.9 von MIT. Gibt es neue Erkenntnisse. Die Daten unterscheiden sich zwischen IoBroker und Fritzbox-Anzeige. Z.B. fritzdect.0.DECT_[XXX].absenk (Fritz!DECT 301).im 

### ISSUE THREAD

**Issue by Holle-031261** [foxthefox/ioBroker.fritzdect#510]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by foxthefox** [comment]
Wurde denn auch das Passwort wie in der Meldung beschrieben, neu eingegeben?
Wenn der Adapter startet kommt im log etwas zu den Benutzern undcderen berechtigungsstufe, eine 2 sollte dort stehen.
Bitte mal prüfen.

**Comment by foxthefox** [comment]
Antworten auf meine Fragen würden mir weiterhelfen

**Comment by AlRo75** [comment]
Ich kann das bestätigen. Ich habe gestern den Adapter von der 2.3.1 auf die 2.5.9 angehoben. Dann das Passwort neu gesetzt und es sah alles perfekt aus. Die Steckdosen (DECT 200) ohne Probleme, Daten kamen.

Bei den DECT 301 (Heizung) sah auch alles gut aus, nur Anderungen z.b. Temperatur per Hand oder durch FB (Zeitplan) an den Geräten kamen nich im Adapter an. Änderung der Temperatur über den Adapter wurden **nicht** zur FB und damit zum DECT 301 übertragen.

Also mit viel hängen und würgen wieder zurück zur 2.3.1 und alles ok.

Ich würde gerne die neue Features nutzen, aber mit diesem BUG ist das unmöglich.

**Comment by foxthefox** [comment]
Korrekterweise sollte das Issue "enabled reduced logging is not working for thermostat values" heissen.
Damit kann man dann auch was machen.

**Comment by Holle-031261** [comment]
Passwort wurde korrekt eingegeben, mittlerweile wurde der Community-Adapter
installiert, bei dem es auch nicht funktioniert hat. Bin gerade am Testen,
ob ich Szenarien, die ich auf der Box einrichte wenigstens einrasten kann -
zunächst Mal in der Programmieroberfläche.

foxthefox ***@***.***> schrieb am So., 28. Jan. 2024, 19:56:

**Comment by foxthefox** [comment]
was ist denn der community adapter?

**Comment by foxthefox** [comment]
bitte die Version 2.5.10 aus github testen und berichten

**Comment by Holle-031261** [comment]
Ich hatte gerade für 2 Monate kein Internet, und dann ist mir der Router
beim Versuch eine Netzwerkbrücke zu erstellen so abgestützt, dass ich ihn
nur per Werksreset wieder gekriegt habe. Hat trotz Backup einiges an Arbeit
gekostet. Kann mich auch die nächsten 7 Wochen nicht weiter damit
beschäftigen. Sorry

foxthefox ***@***.***> schrieb am Mo., 15. Apr. 2024, 20:54:

**Comment by foxthefox** [comment]
wenn doch noch das gleiche Problem sein sollte, kann das gleiche Issue ja nochmal aufgemacht werden
