### ISSUE TITLE
actualtemp wird nicht angezeigt bzw. falsch angezeigt

### ISSUE THREAD

**Issue by andre1974** [foxthefox/ioBroker.fritzdect#53]
Hallo,
ich habe folgendes Problem.
Ich habe einen DECT200 eingebunden der drei Thermostate regelt.
Unter den Datenpunkten des DECT200 wird die falsche aktuelle Temperatur angezeigt.
In der Fritzbox werden nach dem Offset von 0.5°C aktuell 19.5°C angezeigt.
Und unter den Datenpunkten der geschalteten Gruppe wird gar keine aktuelle Temperatur eingetragen.

![Zwischenablage02](https://user-images.githubusercontent.com/11474126/66276734-d0a8b800-e895-11e9-8c31-8b7b3a41e29c.jpg)

**Comment by foxthefox** [comment]
Die aktuelle Temperatur sollte nun mit 0.2.5 angezeigt werden.
Bitte die Version ausprobieren.

Auch die die "temp" sollte nun passend zur Fritzbox sein. Der Offset wird seit geraumer Zeit nicht nochmal zur Berechnung benutzt.

**Comment by andre1974** [comment]
Hallo,
habe soeben 0.2.5 getestet.
Leider werden 0°C angezeigt.
![Zwischenablage07](https://user-images.githubusercontent.com/11474126/72679930-9f569f80-3ab4-11ea-80c2-7066daa0dab8.jpg)

**Comment by foxthefox** [comment]
Danke fürs testen. Könntest du mir bitte den output von "Meine Gruppen" in der admin Oberfläche schicken?

Ich gehe davon aus, daß das andere temp problem gelöst ist?

**Comment by andre1974** [comment]
Sorry, ich versteh nicht ganz was du von mir möchtest.
Wo finde ich den Output?

Gruß

**Comment by foxthefox** [comment]
Der Adapter hat eine Admin-Oberfläche (wo die fritzbox login daten eingegeben werden usw.) dort befinden sich im unteren Teil 3 blaue Tastflächen, dort auf die mittlere "Meine Gruppen" klicken und den Text der sich dann im popup befindet, ist der output.

Den output brauche ich eigentlich nicht, wenn du mir bestätigst daß dort "tist":"0" drin steht. Dann kann ich da nix machen.

**Comment by andre1974** [comment]
[{"identifier":"099950224310","id":"16","functionbitmask":"320","fwversion":"04.89","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","name":"Arbeitszimmer","battery":"40","batterylow":"0","temperature":{"celsius":"200","offset":"-20"},"hkr":{"tist":"40","tsoll":"40","absenk":"32","komfort":"40","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","batterylow":"0","battery":"40","nextchange":{"endperiod":"0","tchange":"40"},"summeractive":"0","holidayactive":"0"}},{"identifier":"099950170923","id":"17","functionbitmask":"320","fwversion":"04.89","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","name":"Wohnzimmer","battery":"40","batterylow":"0","temperature":{"celsius":"200","offset":"-10"},"hkr":{"tist":"38","tsoll":"40","absenk":"32","komfort":"40","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","batterylow":"0","battery":"40","nextchange":{"endperiod":"0","tchange":"40"},"summeractive":"0","holidayactive":"0"}},{"identifier":"099950222926","id":"18","functionbitmask":"320","fwversion":"04.89","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","name":"Esszimmer","battery":"40","batterylow":"0","temperature":{"celsius":"200","offset":"-30"},"hkr":{"tist":"42","tsoll":"40","absenk":"32","komfort":"40","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","batterylow":"0","battery":"40","nextchange":{"endperiod":"0","tchange":"40"},"summeractive":"0","holidayactive":"0"}},{"identifier":"116300053380","id":"20","functionbitmask":"2944","fwversion":"04.16","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"Wohnzimmersteckdose","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"228697","power":"0","energy":"3981"},"temperature":{"celsius":"200","offset":"15"}},{"identifier":"099950283953","id":"22","functionbitmask":"320","fwversion":"04.89","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","name":"Kinderzimmer","battery":"80","batterylow":"0","temperature":{"celsius":"180","offset":"-40"},"hkr":{"tist":"34","tsoll":"36","absenk":"32","komfort":"36","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"0","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"116300094434","id":"24","functionbitmask":"2944","fwversion":"04.16","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"Kinderzimmersteckdose","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"228512","power":"1070","energy":"3626"},"temperature":{"celsius":"180","offset":"5"}},{"identifier":"116300093987","id":"25","functionbitmask":"2944","fwversion":"04.16","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"Badezimmersteckdose","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"225862","power":"2153920","energy":"16765"},"temperature":{"celsius":"160","offset":"10"}},{"identifier":"116300094089","id":"26","functionbitmask":"2944","fwversion":"04.16","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","name":"Schlafzimmersteckdose","switch":{"state":"1","mode":"manuell","lock":"0","devicelock":"0"},"powermeter":{"voltage":"230040","power":"0","energy":"3"},"temperature":{"celsius":"155","offset":"10"}},{"identifier":"099950283960","id":"28","functionbitmask":"320","fwversion":"04.89","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","name":"Schlafzimmer","battery":"20","batterylow":"0","temperature":{"celsius":"155","offset":"0"},"hkr":{"tist":"38","tsoll":"32","absenk":"32","komfort":"36","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","batterylow":"0","battery":"20","nextchange":{"endperiod":"0","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"099950487635","id":"29","functionbitmask":"320","fwversion":"04.89","manufacturer":"AVM","productname":"FRITZ!DECT 301","present":"1","name":"Badezimmer","battery":"100","batterylow":"0","temperature":{"celsius":"160","offset":"0"},"hkr":{"tist":"43","tsoll":"36","absenk":"32","komfort":"42","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","batterylow":"0","battery":"100","nextchange":{"endperiod":"0","tchange":"42"},"summeractive":"0","holidayactive":"0"}}]

**Comment by andre1974** [comment]
Ich hoffe damit ist dir geholfen.

Gruß

**Comment by foxthefox** [comment]
leider nein, das ist der output der Geräte, ich bräuchte den output von Gruppen.

**Comment by andre1974** [comment]
Sorry, mein Fehler.
Hier der richtige Output.

[{"identifier":"grpCBEEB3-39ED8FDDF","id":"900","functionbitmask":"4160","fwversion":"1.0","manufacturer":"AVM","present":"1","name":"Wohnbereich","hkr":{"tist":"0","tsoll":"32","absenk":"32","komfort":"40","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","nextchange":{"endperiod":"0","tchange":"40"},"summeractive":"0","holidayactive":"0"},"groupinfo":{"masterdeviceid":"0","members":"16,17,18"}}]

**Comment by foxthefox** [comment]
so wie ich befürchtet hatte, die Fritzbox liefert "tist":"0"
diesen Wert kann ich leider nur so weiterverarbeiten, wie er ankommt. Also ist die Anzeige 0 °C zwar falsch, aber kein Fehler im Adapter.
