### ISSUE TITLE
Password in plain text?

### ISSUE THREAD

**Issue by funker** [foxthefox/ioBroker.fritzdect#54]
Hey there,

just started to use this adapter and I was quite shocked to see, that the password for the FritzBox login is stored and displayed in plain text. Could you please fix this?

Best regards and thanks for all you hard work. Awesome adapter nonetheless.

**Comment by funker** [comment]
Aaand... I have an additional request (sorry):
The connection to the FB is only possible via http. Would it be possible to use https instead?

**Comment by foxthefox** [comment]
> Hey there,
> 
> just started to use this adapter and I was quite shocked to see, that the password for the FritzBox login is stored and displayed in plain text. Could you please fix this?
> 
> Best regards and thanks for all you hard work. Awesome adapter nonetheless.

with version 0.1.5 there was already encryption implemented, so where did you find the password in plain text. Also in the admin page the text is shown as stars.

Could you provide a hint where you discovered the problem and which version?

**Comment by funker** [comment]
OK, that might be the issue here. I installed it from the default adapters page in ioBroker after a fresh installation of it. I have 0.1.4.
Still don't get why the packages are sometimes very old. How can I make ioBroker get the latest adapter versions without updating them manually via the "Install from GitHub" button?

Thanks for the quick reply. With 0.2.4 the password is masked 👍

**Comment by foxthefox** [comment]
Install from github is one quick possible way for updating to the newest version, but not always the github repo is 100% functional. So using command line with the official released npm version should for sure give a stable running adapter

**Comment by foxthefox** [comment]
I tried https some time ago, but there was an issue with the library I am using. I can check again, but probably will have same result

**Comment by funker** [comment]
Hmn... But is only 0.1.4 then considered as stable?

https: I will try that again with the new version. Didn't check that yet.

**Comment by funker** [comment]
Nope, https does not work. 
I spits out 

> fritzbox returned this "0000000000000000"

and 

> Did not get session id- invalid username or password?

in the ioBroker log.

**Comment by foxthefox** [comment]
> Hmn... But is only 0.1.4 then considered as stable?
> 
> https: I will try that again with the new version. Didn't check that yet.

no, but I did not put my new version in the latest repository. something I have to do.

**Comment by foxthefox** [comment]
0.2.4 now in stable repo.
