### ISSUE TITLE
Restart loop, Dect 301 (FW 5.08), Unhandled promise rejection, tsollTypeError: Cannot read properties of null (reading 'val')

### ISSUE THREAD

**Issue by Stopuhr** [foxthefox/ioBroker.fritzdect#551]
**Describe the bug**  
Adapter is in restart-loop, logs in debug showing:
`
fritzdect.0 | 2024-07-05 19:09:58.385 | error | undefined
-- | -- | -- | --
fritzdect.0 | 2024-07-05 19:09:58.385 | error | unhandled promise rejection: undefined
fritzdect.0 | 2024-07-05 19:09:58.384 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
fritzdect.0 | 2024-07-05 19:09:58.384 | debug | issue in update datapoint [object Object]
fritzdect.0 | 2024-07-05 19:09:58.383 | debug | issue in update datapoint 0999504xxxxx.tsollTypeError: Cannot read properties of null (reading 'val')
fritzdect.0 | 2024-07-05 19:09:58.359 | debug | updating data DECT_0999504xxxxx : endperiod new: Sat Aug 31 2024 23:00:00 GMT+0200 (Mitteleuropäische Sommerzeit) old: Sat Aug 31 2024 23:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)
`
All adapters and groups have been removed and newly installed. Script using fritzdect-datapoints had been disabled.

Changes to the environment:
- ioBroker moved to docker (network host, I think, everything work after that)
- Fritz!Box changed from 7490 to 7530AX a view days later
- When moving settings from old to new fritzbox, I had to update both (seems, that I missed some on the 7490).
- Meanwhile, all groups / adapters had been removed an reinstalled
- Everything ist up to date now.

I belief, that there had been changed to the Fritos, because the message `tsollTypeError: Cannot read properties of null (reading 'val')` was logged on both adapters **and** the group (I removed the faulty-adapter and retried).

**Comment by foxthefox** [comment]
Which adapter version is it?
Can you click on My devices in the adapter admin page and post the returned text?

**Comment by Stopuhr** [comment]
Sry, forgot that: it is 2.5.9. admin-adapter is 6.17.14. Am 06.07.2024 um 00:23 schrieb foxthefox ***@***.***>:﻿
Which adapter version is it?
Can you click on My devices in the adapter admin page and post the returned text?

**Comment by foxthefox** [comment]
you can try the version 2.5.10 from github, which had some changes recently related to tsoll.
if the problem remains, I would like to get the output of "My devices" to check the incomming data

**Comment by Stopuhr** [comment]
Ich bin mir nicht sicher, wie ich die 2.5.10 jetzt installiert habe, aber sie ist installiert und startet ohne Probleme.

**Comment by foxthefox** [comment]
sehr gut, dann können wir das Problem schließen?

**Comment by Stopuhr** [comment]
Denke ja - wenn diese Version es dann mal in die Produktion schafft ;-)Mobil gesendet.Am 06.07.2024 um 22:11 schrieb foxthefox ***@***.***>:﻿
sehr gut, dann können wir das Problem schließen?

**Comment by foxthefox** [comment]
2.5.11 ist nun im stable
