### ISSUE TITLE
ungültige Sitzungskennung

### ISSUE THREAD

**Issue by ihavenonick** [foxthefox/ioBroker.fritzdect#57]
Meine Heizungsregelung läuft über den fritzdect Adapter, die auch so weit läuft, nur habe ich regelmäßig diesen Fehler im Log:
`

fritzdect.0 | 2019-10-30 01:45:03.161 | error | (22723) error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-option
-- | -- | -- | --
fritzdect.0 | 2019-10-30 01:45:03.161 | error | (22723) no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-10-30 01:45:03.160 | error | (22723) fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"
fritzdect.0 | 2019-10-30 01:45:03.024 | error | (22723) error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-option
fritzdect.0 | 2019-10-30 01:45:03.023 | error | (22723) no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-10-30 01:45:03.023 | error | (22723) fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"
fritzdect.0 | 2019-10-30 01:45:02.869 | error | (22723) error calling the fritzbox  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-option
fritzdect.0 | 2019-10-30 01:45:02.868 | error | (22723) no permission for this call (403), has user all the rights and access to fritzbox?
fritzdect.0 | 2019-10-30 01:45:02.868 | error | (22723) fritzbox returned this  {"error":null,"response":{"statusCode":403,"body":"","headers":{"connection":"close","content-length":"0","content-type":"text/plain;  charset=utf-8","x-frame-options":"
fritzdect.0 | 2019-10-30 01:45:01.520 | error | (22723) Did not get session id- invalid username or password?
fritzdect.0 | 2019-10-30 01:45:01.519 | error | (22723) fritzbox returned this "0000000000000000"
`

In der Fritz wird zu diesem Zeitpunkt das protokolliert:
`
30.10.19
01:45:01
Anmeldung des Benutzers Heizung an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.100.10.
30.10.19
01:45:01
Anmeldung an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.100.10 gescheitert (ungültige Sitzungskennung). Zur Sicherheit werden alle noch gültigen Sitzungen zur IP-Adresse 192.168.100.10 beendet.
30.10.19
01:45:01
Anmeldung des Benutzers Heizung an der FRITZ!Box-Benutzeroberfläche von IP-Adresse .
30.10.19
00:45:01
Anmeldung des Benutzers Heizung an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.100.10. [15 Meldungen seit 30.10.19 00:35:01]
`

**Comment by foxthefox** [comment]
Wie hoch ist denn das Polling Intervall in der Admin des Adapters gesetzt? Standard sind 300 Sekunden = 5 minuten. Wenn dieses Intervall zu kurz gesetzt wird, dann bekommt die Fritzbox zu viele Anfragen in einem bestimmten Zeitraum und macht dicht.
Eventuell ist das ja schon die Ursache.

Falls es nicht das Polling ist, wie oft wird denn ggf ein Befehl an die fritzbox gesendet?

**Comment by foxthefox** [comment]
Das letzte mal hattest du das Problem beschrieben, weil dein Script im Sekundentakt die DPs beschreibt, das ist ein wenig zu hastig.

**Comment by ihavenonick** [comment]
Das Intervall steht bei 300s und ja letztes mal war ein Script dafür verantwortlich. Dabei kam der Log Eintrag aber auch sehr regelmäßig. Diesmal kommt der nur ab und zu. Eben gerade geschaut und bis jetzt kein erneuter Fehler im Log.
Ich beobachte das mal weiter und gebe Bescheid, wenn ich was eingrenzen kann.
