### ISSUE TITLE
Fritz DECT440 Tasten im ioBroker

### ISSUE THREAD

**Issue by Strommix** [foxthefox/ioBroker.fritzdect#579]
Ich habe mir eine DECT440 zugelegt und möchte die Tasten im ioBroker nutzen.

fritzdct.0 Instanz ist V2.5.11.
NPM: 10.8.2
Node.js: v20.17.0
js-controller 6.0.11
Betriebssystem Linux Debian
Fritzbox ist die 7490AX Firmware 8.0 (Bei der 7.9 war das auch so).
DECT440 Firmware ist die 05.32.

Die Tasten lassen sich in der Fritzbox nutzen um z.B Steckdosen DECT#200 umzuschalten usw. das funktioniert.
Somit nehme ich an das Das Gerät OK ist.
Aber im ioBroker sehe ich keine Datenpunkte der Tasten die ich auswerten könnte.

Hier die Datenpunkte die ich sehe :
![image](https://github.com/user-attachments/assets/98fda02e-37e3-4c71-a614-a8fdaa6fd211)

Adaptereinstellung: 
![image](https://github.com/user-attachments/assets/9b72172e-2b0f-4a0e-a8d4-6a2ea0e1fc69)

Ich bin auch schon auf die Adapterversion 2.5.9 zurück gegangen aber auch da keine Button.
DECT440 immer zurückgesetzt, Datenpunkte komplett gelöscht und DECT440 neu Inkludiert.
Immer das Gleiche.
Fritzbox auch bei jedem Versuch neu gestartet ohne Erfolg.
Im Logfile ist nichts von Button zu sehen egal was ich auch mache.

Was muss ich machen um den Fehler zu beheben?

**Comment by Strommix** [comment]
Ich bin mir nicht sicher ob du das hier gemeint hast.
`
<devicelist version="1" fwversion="8.00"><device identifier="11657 0226410" id="16" functionbitmask="1280" fwversion="04.25" manufacturer="AVM" productname="FRITZ!DECT Repeater 100"><present>1</present><txbusy>0</txbusy><name>FRITZ!DECT Repeater 100 KG</name><temperature><celsius>230</celsius><offset>0</offset></temperature></device><device identifier="11657 0227742" id="17" functionbitmask="1280" fwversion="04.25" manufacturer="AVM" productname="FRITZ!DECT Repeater 100"><present>1</present><txbusy>0</txbusy><name>FRITZ!DECT Repeater 100 DG</name><temperature><celsius>235</celsius><offset>0</offset></temperature></device><device identifier="08761 0363601" id="18" functionbitmask="35712" fwversion="04.26" manufacturer="AVM" productname="FRITZ!DECT 200"><present>1</present><txbusy>0</txbusy><name>DECT-EG-Wohnzimmer-Stadt</name><switch><state>0</state><mode>manuell</mode><lock>0</lock><devicelock>0</devicelock></switch><simpleonoff><state>0</state></simpleonoff><powermeter><voltage>238750</voltage><power>0</power><energy>232220</energy></powermeter><temperature><celsius>250</celsius><offset>0</offset></temperature></device><device identifier="08761 0404393" id="19" functionbitmask="35712" fwversion="04.26" manufacturer="AVM" productname="FRITZ!DECT 200"><present>1</present><txbusy>0</txbusy><name>DECT-DG-Naehzimmer</name><switch><state>1</state><mode>manuell</mode><lock>0</lock><devicelock>0</devicelock></switch><simpleonoff><state>1</state></simpleonoff><powermeter><voltage>239181</voltage><power>3500</power><energy>126616</energy></powermeter><temperature><celsius>220</celsius><offset>0</offset></temperature></device><device identifier="08761 0404445" id="20" functionbitmask="35712" fwversion="04.26" manufacturer="AVM" productname="FRITZ!DECT 200"><present>1</present><txbusy>0</txbusy><name>DECT-DG-Schlafzimmer-FB-Heizdecke </name><switch><state>0</state><mode>manuell</mode><lock>0</lock><devicelock>0</devicelock></switch><simpleonoff><state>0</state></simpleonoff><powermeter><voltage>239244</voltage><power>0</power><energy>111024</energy></powermeter><temperature><celsius>205</celsius><offset>0</offset></temperature></device><device identifier="08761 0346472" id="21" functionbitmask="35712" fwversion="04.26" manufacturer="AVM" productname="FRITZ!DECT 200"><present>1</present><txbusy>0</txbusy><name>FRITZ!DECT 200 #6</name><switch><state>0</state><mode>manuell</mode><lock>0</lock><devicelock>0</devicelock></switch><simpleonoff><state>0</state></simpleonoff><powermeter><voltage>239834</voltage><power>0</power><energy>443605</energy></powermeter><temperature><celsius>235</celsius><offset>0</offset></temperature></device><device identifier="15282 0079585" id="22" functionbitmask="3146016" fwversion="05.32" manufacturer="AVM" productname="FRITZ!DECT 440"><present>1</present><txbusy>0</txbusy><name>FRITZ!DECT 440 #7</name><battery>100</battery><batterylow>0</batterylow><temperature><celsius>230</celsius><offset>0</offset></temperature><humidity><rel_humidity>50</rel_humidity></humidity></device></devicelist>
`

**Comment by Lucky-ESA** [comment]
In einem anderen Issue hat die Maske sich geändert von 288 auf 1048864 und du hast 3146016 mit der Firmware 05.32. Hier hat Fritzbox was geändert....Kann man in der Fritzbox irgendwas einstellen. Vielleicht müssen die Button belegt sein damit diese gesendet werden. Belege mal alles Schalter unter Smart Home -> Geräte und Gruppen -> Dein Schalter auswählen. Dann über die TAB`s (oben) die Button auswählen und belegen. Danach nochmal mydevice anklicken.

**Comment by Strommix** [comment]
So alle 4 Tasten belegt und funktionieren auf DECT Steckdosen Ein/Aus

Hier die Tabelle : 
`
<devicelist version="1" fwversion="8.00"><device identifier="11657 0226410" id="16" functionbitmask="1280" fwversion="04.25" manufacturer="AVM" productname="FRITZ!DECT Repeater 100"><present>1</present><txbusy>0</txbusy><name>FRITZ!DECT Repeater 100 KG</name><temperature><celsius>230</celsius><offset>0</offset></temperature></device><device identifier="11657 0227742" id="17" functionbitmask="1280" fwversion="04.25" manufacturer="AVM" productname="FRITZ!DECT Repeater 100"><present>1</present><txbusy>0</txbusy><name>FRITZ!DECT Repeater 100 DG</name><temperature><celsius>250</celsius><offset>0</offset></temperature></device><device identifier="08761 0363601" id="18" functionbitmask="35712" fwversion="04.26" manufacturer="AVM" productname="FRITZ!DECT 200"><present>1</present><txbusy>0</txbusy><name>DECT-EG-Wohnzimmer-Stadt</name><switch><state>1</state><mode>manuell</mode><lock>0</lock><devicelock>0</devicelock></switch><simpleonoff><state>1</state></simpleonoff><powermeter><voltage>237336</voltage><power>3290</power><energy>232222</energy></powermeter><temperature><celsius>235</celsius><offset>0</offset></temperature></device><device identifier="08761 0404393" id="19" functionbitmask="35712" fwversion="04.26" manufacturer="AVM" productname="FRITZ!DECT 200"><present>1</present><txbusy>0</txbusy><name>DECT-DG-Naehzimmer</name><switch><state>1</state><mode>manuell</mode><lock>0</lock><devicelock>0</devicelock></switch><simpleonoff><state>1</state></simpleonoff><powermeter><voltage>237071</voltage><power>3360</power><energy>126624</energy></powermeter><temperature><celsius>215</celsius><offset>0</offset></temperature></device><device identifier="08761 0404445" id="20" functionbitmask="35712" fwversion="04.26" manufacturer="AVM" productname="FRITZ!DECT 200"><present>1</present><txbusy>0</txbusy><name>DECT-DG-Schlafzimmer-FB-Heizdecke </name><switch><state>0</state><mode>manuell</mode><lock>0</lock><devicelock>0</devicelock></switch><simpleonoff><state>0</state></simpleonoff><powermeter><voltage>236951</voltage><power>0</power><energy>111024</energy></powermeter><temperature><celsius>200</celsius><offset>0</offset></temperature></device><device identifier="08761 0346472" id="21" functionbitmask="35712" fwversion="04.26" manufacturer="AVM" productname="FRITZ!DECT 200"><present>1</present><txbusy>0</txbusy><name>FRITZ!DECT 200 #6</name><switch><state>0</state><mode>manuell</mode><lock>0</lock><devicelock>0</devicelock></switch><simpleonoff><state>0</state></simpleonoff><powermeter><voltage>237601</voltage><power>0</power><energy>443605</energy></powermeter><temperature><celsius>240</celsius><offset>0</offset></temperature></device><device identifier="15282 0079585" id="22" functionbitmask="3146016" fwversion="05.32" manufacturer="AVM" productname="FRITZ!DECT 440"><present>1</present><txbusy>0</txbusy><name>FRITZ!DECT 440 #7</name><battery>100</battery><batterylow>0</batterylow><temperature><celsius>235</celsius><offset>0</offset></temperature><humidity><rel_humidity>52</rel_humidity></humidity></device></devicelist>
`

**Comment by Lucky-ESA** [comment]
Die Button verden nicht mitgeliefert. Das kann nun mehrere Gründe haben.
1. Es gibt einen neuen Request der in der API noch nicht hinterlegt ist (siehe Bit21)
2. Bug in der Fritzbox Firmware (mein Favorit)
3. Bug in der Aktor Firmware
4. Von Fritzbox so gewollt (wäre aber in der API noch nicht korrigiert)
5. Geräte ist defekt
6. Der Button "mydevice" liefert nicht alle Daten (das könnten wir noch testen)
7. Was mir nicht bekannt ist aber vielleicht andere drauf kommen

Sorry, vielleicht hat ja noch jemand anderes eine Lösung. Wenn nicht, musst du eventuell den Support von Fritzboch kontaktieren und auf diesen Issue referenzieren.

[Hier noch der issue mit Button](https://github.com/foxthefox/ioBroker.fritzdect/issues/85)

Auf welchem System läuft dein ioBroker?

**Comment by Strommix** [comment]
Tja also keine Lösung zumindest nicht mal eben,

Mein System ist Linux/Debian (Siehe oben da stehen ich glaube alle Systeminfos).

Ich kann ja gerne den Fritz-Support bemühen aber was genau sage ich denen, dazu weis ich zu wenig um mit denen zu reden.
Ich teste ja gerne mit um den Fehler zu finden aber das ist Opperieren am offenen Herzen.

**Comment by Lucky-ESA** [comment]
> Mein System ist Linux/Debian (Siehe oben da stehen ich glaube alle Systeminfos).

Stimmt, bin blind

Warte bis @foxthefox wieder Zeit hat (ist im Urlaub). Vielleicht hat er noch einen andere Idee.

**Comment by foxthefox** [comment]
Ich muss mal noch genauer hineinschauen, aber mir scheint die FB antwortet unvollständig. Das DECT440 ist als letztes objekt mit Daten (bat, hum, …) vorhanden, aber es fehlen die unterlagerten Taster. Müsste glaube ich <button> heißen. Evtl. @Lucky-ESA mal mit deinem Output vergleichen. Das Abholen der Daten ist immer komplett, da gibt es keine Sonderanfragen.

**Comment by Lucky-ESA** [comment]
Hier die Antwort. Issue kann geschlossen werden.

Hallo Herr xxx,

vielen Dank für Ihre Anfrage & für Ihre Geduld.

Mit FRITZ!OS 8.0 (und den Vorgängern im Labor) wurde die API nachgezogen und für FRITZ!Dect 440 der Zeitstempel des letzten Tastendrucks der 4 Ecktasten auch hier entfernt.
FRITZ!Dect 440 nutzt schon länger das 3 Anzeigen+Tastenbelegung Konzept. Eine einfache Ecktaste ohne Tastenbelegung kann dabei keine Aktion auslösen. Das Bit 21 steht für dieses Anzeigen+Tastenbelegung Konzept.

Wir werden die Dokumentation bei nächster Gelegenheit in diesem Punkt überprüfen und ggf. aktualisieren.
