### ISSUE TITLE
Fritzbox in remote subnet (VPN) switches not working

### ISSUE THREAD

**Issue by stollentroll69** [foxthefox/ioBroker.fritzdect#6]
Hi,
first of all thanks very much for this great adapter! 

Works very well for my local fritzbox with the first instance I created.

After creating a second instance for  my second fritzbox (connected via VPN, own subnet)  the adapter got connected to the remote box, discovered all devices and showed the actual attributes and values (name, consumption, switch state, etc.).

Unfortunately turning switch on or off is not working. 

I moved the same instance to a local (same subnet) iobroker installation on the remote site (multi host io broker installation) and everything works fine as it should.

Do you have an idea?

Thanks and best regards
stollentroll69

**Comment by foxthefox** [comment]
Hi,

in the iobroker forum there is also reported the issue of unsuccesful switch commands.
That seems a sporadic problem and in your case it is even more strange, when it is working without the vpn configuration.
I am still searching what the error could be. Maybe I have to use a new interface npm module.

best regards
foxthefox

**Comment by foxthefox** [comment]
I created new version of adapter, may be it is now better situation.

**Comment by stollentroll69** [comment]
Hi,

just tested the new 0.0.10 version and now switching the remote plugs is working perfectly.

Thanks very much!!!!
stollentroll69
