### ISSUE TITLE
(1835) no response part in returned message

### ISSUE THREAD

**Issue by funboxbolzer** [foxthefox/ioBroker.fritzdect#61]
Hallo.
ich habe auf einmal den Fehler:

`
fritzdect.0 | 2020-02-05 22:10:33.899 | error | (1835) no response part in returned message
`
version 0.2.5 installiert. 

ich kann keine Temperaturen, Schalter oder Wlan mehr schalten. ist das bekannt?
Gruß Klaus

**Comment by foxthefox** [comment]
Hallo,

nein ist nicht bekannt.
Wann trat dies denn auf?
Ich rate mal:
- im Admin des Adapters hast du auf eine der blauen Tasten (Meine Geräte, Meine Gruppen, Meine Templates) gedrückt
- danach kam entweder ein fenster ohne weiteren Text oder gar kein Fenster
- und die Meldung war im log
- zudem gibt es keine Aktualisierung mehr

Meine Vermutung liegt an Fritzbox, 
- ist da etwas geändert? neues Login, oder andere Berechtigungen?
- andere FW Version? Welche Fritzbox und FW ist es denn? LaborVersion?
- ist die fritzbox vom raspi erreichbar?
- Solange bei "Meine Gruppen" kein Text kommt, liegt es

Gruß
Klaus

**Comment by funboxbolzer** [comment]
: im Admin des Adapters hast du auf eine der blauen Tasten (Meine Geräte, Meine Gruppen, Meine Templates) gedrückt
- nein, adapter komplett neu installiert und immer das problem

: danach kam entweder ein fenster ohne weiteren Text oder gar kein Fenster
- nicht gemacht

: und die Meldung war im log
- ja

zudem gibt es keine Aktualisierung mehr
- verstehe ich nicht richtig. Du aktualisierst den adapter nicht mehr? Oder die Geräte aktualisieren sich nicht mehr? - das ist bei mir der fall

: Meine Vermutung liegt an Fritzbox,
- noch nicht ermittelt 

: ist da etwas geändert? neues Login, oder andere Berechtigungen?
- nein

: andere FW Version?
- nein

:  Welche Fritzbox und FW ist es denn? 
- 6490 kabel vodafone v 7.12
: LaborVersion?
- nein

: ist die fritzbox vom raspi erreichbar?
- ja

: Solange bei "Meine Gruppen" kein Text kommt, liegt es
- an was liegt es😉.

**Comment by funboxbolzer** [comment]
![39CA32FE-6B02-4775-AE5A-9FDDE55E1E84](https://user-images.githubusercontent.com/49862965/73912409-bb2fb300-48b4-11ea-9832-219b45373a14.jpeg)

So sieht es aktuell aus

**Comment by funboxbolzer** [comment]
Die 0.1.4 von npm läuft bei mir ohne fehler

**Comment by foxthefox** [comment]
mit dem screenshot ist nun klarer.
Zuerst dachte ich die Meldung bezog sich auf die Kommunikation zwischen Admin und Adapter.

Aber es ist das Resultat eines fehlgeschlagenen Anmeldeversuchs.
Also ich denke in der Fritzbox sind noch nicht alle Berechtigungen für den im Admin eingetragenen Benutzer gemacht. Oder es ist kein http:// vor der IP-Adresse im Adapter

da hat sich jetzt wohl mein text fast erledigt. -> 0.1.4 läuft ohne Fehler
Was mich sehr wundert, weil die Anmeldung schon immer gleich ist

**Comment by funboxbolzer** [comment]
Ich werde es am Wochenende mal testen mit der aktuellen version. Danke schon mal. 
Ich gebe Feedback

**Comment by foxthefox** [comment]
Ja bitte.

Ich hatte schon eben den Verdacht, daß es wegen einer neuen fritzapi 0.10.7 sein könnte, aber nach update läuft bei mir 0.2.5 mit 0.10.7 an einer 7590 7.12 so wie sonst auch.

**Comment by foxthefox** [comment]
Schon etwas vom Testen zu berichten?

**Comment by zonfacter** [comment]
Hallo,
Ich habe die gleichen Fehler.
Iobroker läuft in einer VM
Adapter Version 0.3.2 Installiert
FritzBox 7590 1&1
OS 07.12

letzes Jahr bis September hatte alles noch Funktioniert... (Da hatte ich noch die DECT Steckdosen geschaltet - Pool Umwälzpumpe)

Habe verschiedene User in der FritzBox angelegt mit verschiedenen Passwörtern / auch mal ohne Passwort angelegt. Es hat nix gebracht.


fritzdect.0 | 2020-04-11 10:45:27.856 | error | (6547) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2020-04-11 10:45:27.855 | error | (6547) fritzbox returned this {"error":{"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"192.178.2.3","port":80},"options":{"url":"http://192.178.2.3/login_sid.lua"}}

**Comment by funboxbolzer** [comment]
> Hallo,
> 
> nein ist nicht bekannt.
> Wann trat dies denn auf?
> Ich rate mal:
> 
> * im Admin des Adapters hast du auf eine der blauen Tasten (Meine Geräte, Meine Gruppen, Meine Templates) gedrückt
> * danach kam entweder ein fenster ohne weiteren Text oder gar kein Fenster
> * und die Meldung war im log
> * zudem gibt es keine Aktualisierung mehr
> 
> Meine Vermutung liegt an Fritzbox,
> 
> * ist da etwas geändert? neues Login, oder andere Berechtigungen?
> * andere FW Version? Welche Fritzbox und FW ist es denn? LaborVersion?
> * ist die fritzbox vom raspi erreichbar?
> * Solange bei "Meine Gruppen" kein Text kommt, liegt es
> 
> Gruß
> Klaus

Hallo. Sorry für die späte antwort. Die 0.2.4. ist ja im npm verfügbar bzw. im iobroker zur Installation verfügbar. 

Leider muss ich immer noch auf die 0.1.4 wechseln. Selber fehler. Kann es an der Vodafone Fritzbox liegen?

**Comment by funboxbolzer** [comment]
> Hallo,
> Ich habe die gleichen Fehler.
> Iobroker läuft in einer VM
> node: v12.13.1
> js-controller Installiert: 2.2.8
> Adapter Version 0.3.2 Installiert
> FritzBox 7590 1&1
> OS 07.12
> 
> letzes Jahr bis September hatte alles noch Funktioniert... (Da hatte ich noch die DECT Steckdosen geschaltet - Pool Umwälzpumpe)
> 
> Habe verschiedene User in der FritzBox angelegt mit verschiedenen Passwörtern / auch mal ohne Passwort angelegt. Es hat nix gebracht.
> 
> fritzdect.0	2020-04-11 10:45:27.856	error	(6547) no response part in returned message
> fritzdect.0	2020-04-11 10:45:27.855	error	(6547) fritzbox returned this {"error":{"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"192.178.2.3","port":80},"options":{"url":"[http://192.178.2.3/login_sid.lua"}}](http://192.178.2.3/login_sid.lua%22%7D%7D)

Geh mal zurück auf 0.1.4. das geht bei mir auch nicht anders. Vodafone Fritzbox:-(

**Comment by zonfacter** [comment]
@funboxbolzer leider ist es bei mir egal welche Version ich benutze.
Das einzige was sich noch geändert hatte bei mir ist das ich letztes Jahr noch die 7362 SL Fritzbox hatte. Vielleicht schließe ich die demnächst nochmal an um zu schauen ob es mit der wieder funktioniert.


Ich habe jetzt mal den Debug Log aktiviert, Version 0.3.2

fritzdect.0 | 2020-04-11 11:20:35.152 | error | (25272) Did not get session id- invalid username or password?
-- | -- | -- | --
fritzdect.0 | 2020-04-11 11:20:35.151 | error | (25272) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-04-11 11:20:35.017 | error | (25272) Did not get session id- invalid username or password?
fritzdect.0 | 2020-04-11 11:20:35.017 | error | (25272) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-04-11 11:20:33.914 | debug | (25272) polling! fritzdect is alive
fritzdect.0 | 2020-04-11 11:20:33.895 | debug | (25272) WLAN poll :true
fritzdect.0 | 2020-04-11 11:20:33.885 | info | (25272) entered ready
fritzdect.0 | 2020-04-11 11:20:33.867 | info | (25272) starting. Version 0.3.2 in /opt/iobroker/node_modules/iobroker.fritzdect, node: v12.13.1

**Comment by funboxbolzer** [comment]
Du meldest dich aber an der FritzBox oberfläche mit Benutzer und Passwort an? Nicht nur Passwort, weil das ja nicht funzt. 
Dem benutzer hast du auch zugriff auf die smarthome geräte gegeben?

**Comment by zonfacter** [comment]
Jap...

So hab es jetzt hinbekommen.
Was hab ich gemacht.
FritzBox User gelöscht
FritzBox User erneut angelegt mit allen rechten. Name / PW auch gleich wie zuvor
ioBroker Fritzdect Adapter instanz gelöscht
iobroker Fritzdect Adapter gelöscht
iobroker Fritzdect Adapter 0.3.2 Adapter installiert.
User / PW eingetippt.
läuft....

Das soll einer verstehen.

![image](https://user-images.githubusercontent.com/48339261/79040830-9a087d00-7beb-11ea-8451-f0afca7ea844.png)

**Comment by foxthefox** [comment]
@zonfacter Super, das es läuft.
@funboxbolzer Ich glaube nicht, daß es an der 1&1 Box liegt. Ich habe selbst eine schwarze Box hinter dem KDG-Modem. Der Mechanismus zum login scheint irgendwie bei dir nicht hinzuhauen. Der ist aber nach meiner Einschätzung seit sehr langer Zeit stabil und unverändert. Nur mal so als Idee, kannst du die IP-adresse der fritzbox auf einen anderen Wert stellen?

**Comment by funboxbolzer** [comment]
Hi.

 

Das Ändern der IP meiner Fritzbox ist leider nicht so einfach möglich, da Feste IPs im Netzwerk mit fester Gateway konfig etc.

Vielleich teste ich mal wenn ich meine Geräte im Netzwerk mal ne zeit lang nicht benötige 😊

 

 

Von: foxthefox <notifications@github.com> 
Gesendet: Montag, 13. April 2020 10:36
An: foxthefox/ioBroker.fritzdect <ioBroker.fritzdect@noreply.github.com>
Cc: funboxbolzer <agent2408@icloud.com>; Mention <mention@noreply.github.com>
Betreff: Re: [foxthefox/ioBroker.fritzdect] (1835) no response part in returned message (#61)

 

@zonfacter <https://github.com/zonfacter>  Super, das es läuft.
@funboxbolzer <https://github.com/funboxbolzer>  Ich glaube nicht, daß es an der 1&1 Box liegt. Ich habe selbst eine schwarze Box hinter dem KDG-Modem. Der Mechanismus zum login scheint irgendwie bei dir nicht hinzuhauen. Der ist aber nach meiner Einschätzung seit sehr langer Zeit stabil und unverändert. Nur mal so als Idee, kannst du die IP-adresse der fritzbox auf einen anderen Wert stellen?

**Comment by foxthefox** [comment]
eventuell geht ja die feste IP jetzt.
Habe die API zur fritzbox neu geschrieben und ich meine es müsste (bei vorhandenem routing) jetzt gehen.
Version  2.1.0 ist aktuell in GitHub und hat die neue API, allerdings auch breaking changes zu den Datenpunkten

**Comment by Jack-RK-24** [comment]
Hab den Fehler nach Update auf 2.0 jetzt auch, 2.1 selbes Resultat. Entfernen des Adapters + Neuinstallation, reboot vom Pi etc. nutzt alles nichts, downgrade zurück auf die 1.1.4 und er tut es wieder wie gewohnt.
![19B68FB0-CA4D-4B84-9DB9-8B6AA792C1CB](https://user-images.githubusercontent.com/63138075/103521532-35780700-4e79-11eb-8f6b-af83f31f0e88.png)

**Comment by Jack-RK-24** [comment]
Scheint als ob die FB die Übertragung von User/PW nicht mehr mag.
User/PW im Adapter neu eingetragen: selber Fehler
in der FB komplett gelöscht und neu angelegt: selber Fehler
anderen User (admin) der FB benutzt: selber Fehler
Selbstredend nach den o.g. Modifikationen an der Benutzerverwaltung der FB per Browser-Login verifiziert dass der User sich erfolgreich anmelden kann etc.
![screenshot](https://user-images.githubusercontent.com/63138075/103525421-78d57400-4e7f-11eb-8d77-b041b02cba7a.PNG)

Downgrade auf die 1.1.4 und er tut's direkt wieder mit den im Adapter hinterlegten User/PW Daten:
![screenshot2](https://user-images.githubusercontent.com/63138075/103525662-e386af80-4e7f-11eb-91eb-579b68cf476b.PNG)

**Comment by foxthefox** [comment]
sehr komisch.
http:// steht bestimmt vor der IP der fritzbox?
Was ist es denn für eine FW der Fritzbox?
Laufen noch andere Adapter mit Fritzbox Zugriff?
Was sagt das LOG in der Fritzbox?
Kannst du den adapter im debug modus laufen lassen, evtl. gibt es da noch eine Zusatzinfo.

**Comment by Jack-RK-24** [comment]
Update auf die v2.1.4 gemacht, dann sieht es wie folgt aus:
Adapter-config:
![Adapter_Config](https://user-images.githubusercontent.com/63138075/103551388-8fdd8b80-4eaa-11eb-9804-87b72d117b9c.PNG)
FB-Version (jepp ist die aktuelle beta):
![FB_Version](https://user-images.githubusercontent.com/63138075/103551463-a71c7900-4eaa-11eb-8e16-bea07782094b.PNG)
Adapter-Loglevel auf debug und gestartet (nach Fehlschlag dann wieder gestoppt):
![Adapter_Log](https://user-images.githubusercontent.com/63138075/103551555-c87d6500-4eaa-11eb-8287-35f33944bf8c.PNG)
und die Meldung auf der FB:
![FB_Log](https://user-images.githubusercontent.com/63138075/103551594-d3d09080-4eaa-11eb-9afb-a32f620fa102.PNG)

**Comment by foxthefox** [comment]
das ist schonmal ein Startpunkt.
Ab der Version 7.24 hat sich die Anmeldung von Verschlüsselung "md5" auf "pbkf2" geändert. Deswegen hatte ich auch die API in 2.x.x neu aufgesetzt. Da du hier die 7.24 hast, greift der Fallback auf md5 nicht mehr und da ist ggf. noch ein Fehler in der API drin.
Ich prüfe mal mit Beispielen aus der AVM Doku den Algorithmus.

Da es noch ggf. etwas mit nicht "zugänglichen" Zeichen gibt, wo eine Umsetzung erfolgen muß (z.B. €), noch eine Frage

sind in dem Passwort irgendwelche Sonderzeichen drin?

**Comment by Jack-RK-24** [comment]
Ja, bei dem verwendeten Account gibt‘s ne Menge Sonderzeichen. ;) Habe es jetzt mit nem einfachen PW versucht (nur Groß-Klein und Zahlen, keine Sonderzeichen, keine Umlaute) das schmeckt der Box aber auch nicht. Exakt die selben Fehlermeldungen im Adapter und der Box.

**Comment by foxthefox** [comment]
danke, prüfe grad noch die hashes

**Comment by foxthefox** [comment]
bin recht verwirrt was das hashing betrifft, bei gleicher Methodik spucken die online tools immer was unterschiedliches aus.

Habe allerdings noch einen Fehler bei mir gefunden, es fehlte ein '$' bei der Übermittlung an die fritzbox.

Ob es das schon war??? Ich hoffe es.
Bitte die 2.1.5 mal testen

**Comment by Jack-RK-24** [comment]
Update gemacht, aber leider nein, exakt das selbe Fehlerbild...

**Comment by foxthefox** [comment]
welche Version von node benutzt du denn?
Ich habe jetzt meine Implementierung (crypto aus Nodejs nativ) mit 3 weiteren Bibliotheken getestet und es kommt überall das gleiche Ergebnis, allerdings nicht wie das Beispiel in der AVM Doku.
Evtl. hängt es ja an der Nodejs version, ich habe da schon v15.

**Comment by Jack-RK-24** [comment]
12.20
![24F5D0B9-9408-475B-85A7-A3C5FF307EF5](https://user-images.githubusercontent.com/63138075/103564342-a1309300-4ebe-11eb-970a-f8e256ad1afd.jpeg)

**Comment by foxthefox** [comment]
Ich hab grad bei mir unter node10 mal getestet

```
const crypto =require('crypto');

function calculate_pbkdf2_response(challenge, password) {
        console.log('Calculate the response for a given challenge via PBKDF2');
        const challenge_parts = challenge.split('$');
        const iter1 = Math.floor(challenge_parts[1]);
        const salt1 = challenge_parts[2].toString('hex');
        const iter2 = Math.floor(challenge_parts[3]);
        const salt2 = challenge_parts[4].toString('hex');
        // Hash twice, once with static salt...
        // Once with dynamic salt.
        const hash1 = crypto.pbkdf2Sync(password, salt1, iter1, 32, 'sha256');
        console.log('hash1: ' + hash1.toString('hex'));
        const hash2 = crypto.pbkdf2Sync(hash1, salt2, iter2, 32, 'sha256');
        console.log('hash2: ' + hash2.toString('hex'));
        return challenge_parts[4] +'$'+ hash2.toString('hex');
}

console.log(calculate_pbkdf2_response('2$10000$5A1711$2000$5A1722', '1example!'));
```

bringt

```
Calculate the response for a given challenge via PBKDF2
hash1: 7ed4b4459ab69d76108fb5aa8911cb05d97eada608b627a358723a254cbc1003
hash2: 56cd16754701545557b10ae02e6ba1ab6f7688f9b951ae54b3b0657e8cdb1c10
5A1722$56cd16754701545557b10ae02e6ba1ab6f7688f9b951ae54b3b0657e8cdb1c10
```
Das könntest du mal bei dir gegenprüfen.

**Comment by Jack-RK-24** [comment]
Hab Dein Ergebnis:
Calculate the response for a given challenge via PBKDF2
hash1: 7ed4b4459ab69d76108fb5aa8911cb05d97eada608b627a358723a254cbc1003
hash2: 56cd16754701545557b10ae02e6ba1ab6f7688f9b951ae54b3b0657e8cdb1c10
5A1722$56cd16754701545557b10ae02e6ba1ab6f7688f9b951ae54b3b0657e8cdb1c10

**Comment by foxthefox** [comment]
also daran liegt es wohl nicht, daß irgendwo der pbkdf2 Algorithmus nicht richtig tut.

eine anderer Versuch:
im adapter unter docs/de befindet sich ein fritz.py (die Referenzimplementierung)
kannst du es mit fritz.py http://fritz.box deinusername daspassendePW
aufrufen, ob es eine SessionID zurückgibt?

**Comment by Jack-RK-24** [comment]
invalid syntax?
![screenshot](https://user-images.githubusercontent.com/63138075/103570551-9d563e00-4ec9-11eb-935d-1cb75f6b82f6.PNG)

**Comment by Jack-RK-24** [comment]
aufruf mit python3 bringts...  ;)
![screenshot](https://user-images.githubusercontent.com/63138075/103570706-e0b0ac80-4ec9-11eb-8c82-930a4abfa05d.PNG)

**Comment by foxthefox** [comment]
danke, d.h. jetzt muß javascript nur noch zum gleichen Ergebnis kommen

**Comment by foxthefox** [comment]
habe version 2.1.6 erstellt. das sollte jetzt hoffentlich passen. zumindest kam Nodejs zum gleichen Resultat wie python.
Bitte auch gern Sonderzeichen wieder verwenden.
Bitte testen und berichten

**Comment by Jack-RK-24** [comment]
Schaut gut aus, komplexe Passwörter mit Sonderzeichen sind kein Problem, der Adapter läuft jetzt stabil seit ca. 3h. 
Schaut als ob jetzt die vis dran ist (Anpassung an die neue Objektstruktur..).  ;)

**Comment by foxthefox** [comment]
war ein harter Kampf das rauszufinden :-) aber schön das es geht

**Comment by Flyor** [comment]
`2021-01-06 00:00:11.548  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:00:11.548  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:00:17.287  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:00:17.287  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:00:22.894  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:00:22.894  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:00:28.602  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:00:28.602  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:00:33.971  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:00:33.971  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:00:39.891  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:00:39.891  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:00:45.320  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:00:45.320  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:00:51.372  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:00:51.372  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:00:56.736  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:00:56.736  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:02.265  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:02.265  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:07.876  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:07.876  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:13.354  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:13.354  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:18.783  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:18.783  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:24.746  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:24.746  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:30.213  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:30.213  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:35.841  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:35.841  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:41.058  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:41.058  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:46.662  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:46.662  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:52.191  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:52.191  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:01:57.662  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:01:57.662  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:03.092  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:03.092  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:08.625  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:08.626  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:14.063  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:14.063  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:19.920  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:19.920  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:25.366  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:25.366  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:31.057  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:31.057  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:36.445  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:36.445  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:42.013  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:42.013  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:47.451  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:47.451  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:52.879  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:52.879  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:02:58.327  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:02:58.328  - [31merror[39m: fritzdect.0 (971070) no response part in returned message
2021-01-06 00:03:03.853  - [31merror[39m: fritzdect.0 (971070) fritzbox returned this {}
2021-01-06 00:03:03.853  - [31merror[39m: fritzdect.0 (971070) no response part in returned message`

Muss mich leider an den Fehler anschließen.

Der DECT Adapter lief vorher problemlos, hab dann die Fritzbox 7590 auf die Laborfirmware geupgradet. Seither die Fehler. 
Die DECT Geräte (Thermostate) haben auch das Update bekommen. Sie funktionieren aber bisher weiterhin (auch über iobroker).  Installiert ist 2.0.0 (DECT Adapter). Falls weiteres interessant sein sollte, reiche ich gern mehr Infos nach.

**Comment by foxthefox** [comment]
wie oben gezeigt und diskutiert -> bitte die Version 2.1.6 von GitHub verwenden!
Ist Breaking change! Datenpunkte werden anders benannt. im Forum gibt es einen Thema zum Test 2.1.x für mehr Info

**Comment by Flyor** [comment]
> wie oben gezeigt und diskutiert -> bitte die Version 2.1.6 von GitHub verwenden!
> Ist Breaking change! Datenpunkte werden anders benannt. im Forum gibt es einen Thema zum Test 2.1.x für mehr Info

Danke! Funktioniert soweit wieder bestens. Jedoch vermisse ich den Datenpunkt, um die Dauer der "Fenster offen" Zeit einzustellen. Früher gab es dazu einen Datenpunkt in den Thermostaten. Wurde der entfernt?

**Comment by foxthefox** [comment]
ich habe nichts gelöscht, eher dazuge

baut.
es gibt 3 Datenpunkte:
windowopenactiv -> zustand bzw. für Kommando
windowopenacteendtime -> Zeit wann WIndowactiv beendetest
windowopenactivetime -> die Zeit wie lange das eigene Kommando gültig sein soll (neu)
![Bildschirmfoto 2021-01-07 um 10 50 52](https://user-images.githubusercontent.com/16841643/103878256-791b7c80-50d6-11eb-823f-0b37114af04c.png)

hab grad gesehen, daß da etwas nach Datum gewandelt wird, da muß ich noch verbessern -> 2.1.7

**Comment by Flyor** [comment]
> ich habe nichts gelöscht, eher dazuge
> 
> baut.
> es gibt 3 Datenpunkte:
> windowopenactiv -> zustand bzw. für Kommando
> windowopenacteendtime -> Zeit wann WIndowactiv beendetest
> windowopenactivetime -> die Zeit wie lange das eigene Kommando gültig sein soll (neu)
> ![Bildschirmfoto 2021-01-07 um 10 50 52](https://user-images.githubusercontent.com/16841643/103878256-791b7c80-50d6-11eb-823f-0b37114af04c.png)
> 
> hab grad gesehen, daß da etwas nach Datum gewandelt wird, da muß ich noch verbessern -> 2.1.7

Das war es wohl, was ich gemeint habe. Die active time meinte ich, welche ich aufgrund des Datums nicht finden konnte. Danke!

**Comment by foxthefox** [comment]
@funboxbolzer 
> Hi. Das Ändern der IP meiner Fritzbox ist leider nicht so einfach möglich, da Feste IPs im Netzwerk mit fester Gateway konfig etc. Vielleich teste ich mal wenn ich meine Geräte im Netzwerk mal ne zeit lang nicht benötige 😊 

schon die neue Version 2.1.7 probiert, ob es mit der IP jetzt geht?

**Comment by funboxbolzer** [comment]
> @funboxbolzer
> 
> > Hi. Das Ändern der IP meiner Fritzbox ist leider nicht so einfach möglich, da Feste IPs im Netzwerk mit fester Gateway konfig etc. Vielleich teste ich mal wenn ich meine Geräte im Netzwerk mal ne zeit lang nicht benötige 😊
> 
> schon die neue Version 2.1.7 probiert, ob es mit der IP jetzt geht?

Hi. 
ich habe leider noch keine Zeit gefunden zum testen. Denke am WE werde ich dazu kommen. Muss erst noch ein Backup meines Raspi machen. Der ist mir vor kurzem erst abgeschmiert 😞. 

Habe aber die ganzen Mail verfolgt. Gebe definitiv Info. 
danke schon mal.

**Comment by darkman242** [comment]
Ich habe leider mit der 2.1.7 sporadisch 1-2x am Tag die nachfolgende Meldung im Log. Ansonsten funktioniert der Adapter.

fritzdect.0 | 2021-01-27 08:40:50.785 | error | (22248) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-01-27 08:40:50.781 | error | (22248) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}

**Comment by Chaot1** [comment]
Ich habe ebenfalls 1-2 mal täglich den Fehler.

fritzdect.0 | 2021-04-17 14:00:04.336 | error | (680) no response part in returned message
-- | -- | -- | --
fritzdect.0 | 2021-04-17 14:00:04.335 | error | (680) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}


Mein Verdacht ist das der Fehler immer dann auftaucht wenn zeitgleich der tr-064 zugreift.

Mein Lösungsvorschlag:
Lässt sich im Adapter die Fehlermeldung einmalig unterdrücken und die Fehlerausgabe erst dann aktivieren wenn der Fehler das zweite mal auftaucht? Normalerweise ist das ja nur ein einmaliger Aussetzer der beim nächsten Polling wieder erledigt ist. Dann sollte eine Fehlermeldung erst dann kommen wenn der Fehler häufiger auftritt.

**Comment by funboxbolzer** [comment]
Bei mir läuft es jetzt. 
ich habe eine weitere Instanz angelegt und dann siehe da, funktioniert. 

Mit der ursprünglichen Instanz keine Chance. 
was da der Fehler ist kann ich leider nicht sagen.

**Comment by foxthefox** [comment]
> Ich habe ebenfalls 1-2 mal täglich den Fehler.
> 
> fritzdect.0	2021-04-17 14:00:04.336	error	(680) no response part in returned message
> fritzdect.0	2021-04-17 14:00:04.335	error	(680) fritzbox returned this {"msg":"failed to login, wrong user name or password","function":"send_response","error":"0000000000000000"}
> Mein Verdacht ist das der Fehler immer dann auftaucht wenn zeitgleich der tr-064 zugreift.
> 
> Mein Lösungsvorschlag:
> Lässt sich im Adapter die Fehlermeldung einmalig unterdrücken und die Fehlerausgabe erst dann aktivieren wenn der Fehler das zweite mal auftaucht? Normalerweise ist das ja nur ein einmaliger Aussetzer der beim nächsten Polling wieder erledigt ist. Dann sollte eine Fehlermeldung erst dann kommen wenn der Fehler häufiger auftritt.

Irgendetwas unterdrücken halte ich für nicht zielführend und macht einen Aufwand der für die Problematik nicht adäquat ist. Wenn es 1-2mal vorkommt, also nur sporadisch auftritt, dann ist diese eine Meldung im log auch nicht wirklich ein Problem. Zumindest sehe ich das so.

**Comment by foxthefox** [comment]
habe jetzt eine neue Version 2.2.0 erstellt, es kann gern getestet werden
Der Adapter hat solange er läuft eine Verbindung, die API zur FB ist nunmehr geändert.
Alle Kommandos greifen auf die gleiche Session zu, es dürfte also keine Engpässe mehr geben.

**Comment by Domi920** [comment]
@foxthefox habe deine neue Version seit einigen Tagen installiert.
Die Fehlermeldung scheint endlich verschwunden zu sein! 

Tolle Arbeit!

Gruß Dominik

**Comment by foxthefox** [comment]
Danke.
Dann schließe ich das mal
