### ISSUE TITLE
FRITZ!DECT 500 - RGB E27 Lampe

### ISSUE THREAD

**Issue by sky-it** [foxthefox/ioBroker.fritzdect#62]
Bitte die Unterstützung der neuen FRITZ!DECT 500 - RGB E27 Lampe hinzufügen.

In den Objekten taucht die Lampe nicht auf.

Geräte debug:

[{"identifier":"xxxxxxxxxxxx-x","id":"2000","functionbitmask":"237572","fwversion":"0.0","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"0","txbusy":"0","name":"FRITZ!DECT 500 #1","simpleonoff":{"state":""},"levelcontrol":{"level":"","levelpercentage":""},"colorcontrol":{"supported_modes":"0","hue":"","saturation":"","temperature":""},"etsiunitinfo":{"etsideviceid":"406","unittype":"278","interfaces":"512,514,513"}},
{"identifier":"xxxxxxxxxxxx","id":"406","functionbitmask":"1","fwversion":"34.10.16.16.009","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"0","txbusy":"0","name":"FRITZ!DECT 500 #1"}]

**Comment by foxthefox** [comment]
mache ich gern, habe auch schon angefangen.
Leider fehlt mir eine offizielle Beschreibung von AVM wie die API für DECT500 aussieht.
Die Datenpunkte aus dem debug habe ich soweit schonmal drin, fehlt nur noch der Wertebereich.

Kurioserweise ist bei deiner Lampe kein Wert für farbiges Licht oder Farbtemperatur enthalten. Wenn das so normal ist, dann kann man in iobroker nicht viel damit anfangen(:"" ergibt keinen Werte im Datenpunkt).

Das wohl wichtigere sind die Befehle, die lassen sich aber nicht über die Geräte auslesen, des steht nur in der API Beschreibung.
Da müssen wir uns wohl noch in Geduld üben.

**Comment by sky-it** [comment]
Danke dir.
Ich habe gerade ein Firmwareupdate durchgeführt, nun sieht man mehr.
Keine Ahnung ob es daran liegt das die Lampe jetzt mit der Box verbunden war oder ander Firmware:

`[{"identifier":"xxxxxxxxxxxx-1","id":"2000","functionbitmask":"237572","fwversion":"0.0","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"1","txbusy":"0","name":"FRITZ!DECT 500","simpleonoff":{"state":"1"},"levelcontrol":{"level":"255","levelpercentage":"100"},"colorcontrol":{"supported_modes":"5","current_mode":"4","hue":"","saturation":"","temperature":"3400"},"etsiunitinfo":{"etsideviceid":"406","unittype":"278","interfaces":"512,514,513"}},{"identifier":"xxxxxxxxxxxx","id":"406","functionbitmask":"1","fwversion":"34.10.16.16.011","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"1","txbusy":"0","name":"FRITZ!DECT 500"}]`

**Comment by foxthefox** [comment]
super,
danke für den output

bei dem oberen ist present=1 -> Lampe ist verbunden mit FritzBox, beim unteren 0. Wichtig auch der Unterschied das es bei vorhandener Lampe einen current_mode gibt. Scheint eine Auswahl von maximal 5 Varianten ztu sein, der derzeitig auf 4 steht. das werde ich gleich einmal berücksichtigen. Wahrscheinlich ist level und levelpercentage das gleiche nur in anderer Darstellungsform.

**Comment by axelrathey** [comment]
Hi,
habe auch eine DECT 500 LED-Lamoe von AVM zum Feldtest bekommen. Habe die Lampe mal auf Farbe und dann auf rot gestellt. Dann kommen folgende debugzeilen (s.u.). "Current Mode" bzw. "supported Modes" sind vermutlich die Einstellung auf Farbe RGB bzw. Farbtemperatur innerhalb von Weiß. Wobei Current Mode = 4 offenbar Farbtemperatur ist und Current Mode = 1 ist dann der RGB-Mode. In HUE steht dann wohl die RGB-Farbe drin, vermutlich in Anlehnung an die via zigbee steuerbaren HUE Lampen. Den Namen der Lampe habe ich übrigens in der Fritzbox umbenannt.
Gruß Axel

[{"identifier":"130770000415-1","id":"2000","functionbitmask":"237572","fwversion":"0.0","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"1","txbusy":"0","name":"erste FRITZ!DECT 500","simpleonoff":{"state":"1"},"levelcontrol":{"level":"255","levelpercentage":"100"},"colorcontrol":{"supported_modes":"5","current_mode":"1","hue":"358","saturation":"179","temperature":""},"etsiunitinfo":{"etsideviceid":"406","unittype":"278","interfaces":"512,514,513"}},

**Comment by foxthefox** [comment]
D.h. der von mir erzeugte Branch verwendest du schon zum Testen? SUPER. Irgendwelche Auffälligkeiten? Befehle gehen natürlich nicht, da die API noch nicht veröffentlicht ist. Die Datenpunkte sind erstmal nur das Resultat der Rückmeldung der Fritzbox. Aber wenn dass schonmal funktioniert, dann ist es für die Unterstützung der DECT500 nicht mehr weit.

**Comment by axelrathey** [comment]
Ich muss dich entäuschen, ich verwendet nur die im iobroker freigegebene Version.
Dazu kenne ich mich mit iobroker auch zu wenig aus.
Das was ich dir dort geschickt habe ist der Teil der debug-Ausgabe, die offenbar für die Dect500 zuständig ist.
Habe daneben noch 2 DECT Repeater, die natürlich auch in der Debugausgabe standen. Deren Zeilen habe ich vorher gelöscht.
Man kann aber erkennen, wie sich die diversen Werte in dieser Debugausgabe der DECT500 ändern sobald man die Lampe über die Fritzbox (hier 7490 mit akt. Labor) oder über die DECT-Telefone ansteuert.
Viele Grüße
Axel

**Comment by sky-it** [comment]
Hab mal die Version 0.2.5 installiert.
Hier die debug-Meldung "Meine Geräte"
Einmal mit dem Strom verbunden und einmal nicht.

OFF

`[{"identifier":"130770009344-1","id":"2000","functionbitmask":"237572","fwversion":"0.0","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"0","txbusy":"0","name":"FRITZ!DECT 500","simpleonoff":{"state":""},"levelcontrol":{"level":"","levelpercentage":""},"colorcontrol":{"supported_modes":"0","hue":"","saturation":"","temperature":""},"etsiunitinfo":{"etsideviceid":"406","unittype":"278","interfaces":"512,514,513"}},{"identifier":"130770009344","id":"406","functionbitmask":"1","fwversion":"34.10.16.16.011","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"0","txbusy":"0","name":"FRITZ!DECT 500"}]`

ON

`[{"identifier":"130770009344-1","id":"2000","functionbitmask":"237572","fwversion":"0.0","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"1","txbusy":"0","name":"FRITZ!DECT 500","simpleonoff":{"state":"1"},"levelcontrol":{"level":"255","levelpercentage":"100"},"colorcontrol":{"supported_modes":"5","current_mode":"4","hue":"","saturation":"","temperature":"3800"},"etsiunitinfo":{"etsideviceid":"406","unittype":"278","interfaces":"512,514,513"}},{"identifier":"130770009344","id":"406","functionbitmask":"1","fwversion":"34.10.16.16.011","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"1","txbusy":"0","name":"FRITZ!DECT 500"}]`

Datenpunkte für den DECT500 wurden nicht angelegt

**Comment by axelrathey** [comment]
Wie installierst du die 0.2.5? Bei mir wird selbst im Expertenmodus nur der 0.2.4 angeboten.
Gruß Axel

**Comment by sky-it** [comment]
manuell. Wähle oben bei Code nicht den master branch sondern den DECT500 aus, kopiere dir rechts die URL und installiere im ioBroker mit der URL manuell die Version

**Comment by axelrathey** [comment]
Hi,
nach einigem hin und her (falsche url) habe ich die 0.2.5 aus der dect 500 branch installiert bekommen.
Zunächst, es werden Objekte für die DECT500 erzeugt. Aber diese ändern sich erst nach langer Zeit oder beim Neuladen der Instanz. Änderungen mache ich über die Smarthome App von AVM bzw. direkt über die Web Oberfläche der Friztbox. HUE-Wert für die Farbe und die Farbtemperatur sind als Objekt zwar vorhanden, werden aber gar nicht gelesen.
Anbei das json File mit den Objekten der Dect500 als zip gepackt.
Gruß Axel

[fritzdect.0.DECT500_130770000415-1.json.zip](https://github.com/foxthefox/ioBroker.fritzdect/files/4286216/fritzdect.0.DECT500_130770000415-1.json.zip)

**Comment by foxthefox** [comment]
Danke für die Hinweise und die debug-Meldungen und die angelegte Datenstruktur.
Ich mußda noch ein wenig Feinschliff reinbringen (°C bei txbusys ist wohl falsch).
Ggf. muß ich auch noch den richtigen Datentyp für hue und sat nehmen, da gibt es spezielle roles.
Was man am debug aber schon sehen, kann:
- hue und saturation sind leer, wenn es die farbtemp gibt
- evtl. ist es bei hue vorwahl in der APP dann anders??? Hier wäre noch ein debug-log hilfreich.
- wenn present=0 (nicht am Strom) dann werden fast alle wert nicht gesendet

Die Zeit für das updaten kann man in der admin-Oberfläche einstellen. 300s entspricht 5min.

Gruß Klaus

**Comment by foxthefox** [comment]
@sky-it ; @axelrathey 

Ich habe mal eine Version 0.3.0 vorbereitet, die über das github-icon installierbar ist (kein branch mehr).
Bitte einmal Testen und berichten.

Befehle gibt es noch keine, da ich die Aufrufe noch nicht kenne. Anfrage an AVM habe ich schon gestellt.

**Comment by sky-it** [comment]
> Ich habe mal eine Version 0.3.0 vorbereitet, die über das github-icon installierbar ist (kein branch mehr).
> Bitte einmal Testen und berichten.

Danke dir für die saubere Umsetzung.
Hab die Version installiert. Bei mir erscheint jetzt erstmalig der Datenpunkt für die DECT500.

Mal schauen wann sich AVM zu Wort meldet, hoffentlich vor der offiziellen Veröffentlichung der DECT500, damit die Neueinsteiger gleich durchstarten können.

**Comment by axelrathey** [comment]
Habe 0.3.0 auch installiert.
Inzwischen habe ich auch die einstellung mit dem polling Intervall gefunden. Das war bisher bei mir leer.
Nun habe ich da 20 Sekunden eingestellt. Und Siehe da die Werte der Lampe aktualisieren sich.
Ansonsten keine Auffälligkeiten festgestellt.
Gruß Axel

**Comment by foxthefox** [comment]
@sky-it ; @axelrathey

auf github liegt nun die Version 1.0.0, wo auch Kommandos für die Lampen enthalten sind.
Bitte ausführlich testen und berichten.
Ggf. kann hue bzw. saturation noch nicht funktionieren, da ich mir nicht sicher bin, ob die API hue und saturation immer gemeinsam im Aufruf benötigt.

**Comment by axelrathey** [comment]
Hallo foxthefox,
muss ich da noch irgendwas neu einstellen? Die Objekte reagieren nur auf Änderungen durch die AVM App bzw. von den DECT-Fritzphones. Ich kann die Lampe aber z.B. nicht ein und ausschalten und auch nicht den DIM-Wert ändern. Jedenfalls ändert sich nichts an der Lampe und es wird dann beim erneuten Lesen des Lampenzustandes via polling wieder überschrieben.
Gruß Axel

**Comment by axelrathey** [comment]
Hatte auch nochmal den adapter upgeloaded und die Objekte der Lampe neu erstellen lassen. Hat nichts gebracht.

**Comment by foxthefox** [comment]
Hallo Axel,

bitte den Adapter in den debug Modus versetzen (bei Instanzen etwas weiter rechts von info auf debug stellen). Dann gibt es mehr im log, welches für mich dann interessant wäre.

Es sollte so sein, daß state (false, true),level/levelpercentage (wert), temperature (wert) unter Objekte bedienbar sein sollten (einfach wert ändern).

Bei hue/saturation (wert) sollte es auch so sein, aber hier kann es noch an meinem Aufruf liegen (nicht ein Wert, sondern beide gleichzeitig schicken).

Unter Adapter sollte 1.0.0 als installierte Version angezeigt sein.

Nach einem Befehl sollte etwas wie  Lamp ID: xxxxx identified for command (state) ... stehen, und noch etwas mehr.
Bin auf das Log gespannt.

Gruß
Klaus

**Comment by foxthefox** [comment]
Habe gerade gemerkt, daß noch ein paar typos probleme machten.
1.0.1 nun auf github zum testen benutzen

**Comment by sky-it** [comment]
Hi @foxthefox,
durch die aktuelle Situation war ich etwas eingespannt... denke ich komme heute oder spätestens morgen dazu ein Log bereitzustellen.

**Comment by sky-it** [comment]
So, mal ein paar Schaltungen über die FB
[Log.txt](https://github.com/foxthefox/ioBroker.fritzdect/files/4437377/Log.txt)

Schaltungen über ioBroker wie ein/aus führten zu keiner Reaktion und der Wert wurde nach dem nächsten Polling überschrieben

**Comment by foxthefox** [comment]
hmm, irgendwie komisch.
in dem log ist kein einziger Befehl drin.

da müsste als erstes "'ack is not set! -> command'" stehen und dann
"Lamp ID xxxx identified for command ..."

oder bei Steckdosen halt :
"Switch xxx identified for command."

Kannst du nochmal bitte schauen.
Wichtig wäre für mich die Antwort der Fritzbox, wenn denn das Kommando mal abgesetzt ist (ob akzeptiert oder verworfen)

**Comment by sky-it** [comment]
Ich kann es leider aktuell nicht testen. Bei mir ist der FB aktuell kein SmartHome Gerät sichtbar und auch der Adapter schreibt raus, das er keine leere Nachrichten zurück erhält.
Hab AVM mal informiert, entweder liegt es an der aktuellen Beta oder ich muss die FB mal durchstarten (was ich aktuell jedoch nicht machen kann)

**Comment by sky-it** [comment]
Ich schau, dass ich heute noch mal ein log erstellen kann.
Das Problem das bei mir keine SmartHome Geräte mehr angezeigt wurden, lag vermutlich daran, dass ich über den Adapter versucht habe einen Temperatur-Offset am 301er durchzuführen. Das Feld ist eigentlich nicht beschreibbar, hab es dennoch versucht.
(Aktuell setze ich den Offset über ein [Loxberry-Modul](https://www.loxwiki.eu/display/LOXBERRY/Fritz.Lox), was ich ablösen wollte)

**Comment by sky-it** [comment]
Anbei mal ein aktuellen Auszug aus dem Geräte Debug:

```
[{"identifier":"13077000xxxx-1","id":"2000","functionbitmask":"237572","fwversion":"0.0","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"1","txbusy":"0","name":"FRITZ!DECT 500","simpleonoff":{"state":"0"},"levelcontrol":{"level":"82","levelpercentage":"32"},"colorcontrol":{"supported_modes":"5","current_mode":"1","hue":"266","saturation":"169","temperature":""},"etsiunitinfo":{"etsideviceid":"406","unittype":"278","interfaces":"512,514,513"}},
{"identifier":"13077000xxxx","id":"406","functionbitmask":"1","fwversion":"34.10.16.16.012","manufacturer":"AVM","productname":"FRITZ!DECT 500","present":"1","txbusy":"0","name":"FRITZ!DECT 500"}]
```

In der FritzBox selbst wird die Lampe aktuell nicht mehr als Dect500 angezeigt sondern als HUN-FUN Gerät, was aber eventuell an der Labor-Version liegt.

Im ioBroker ist mir noch aufgefallen, dass die Geräte ID eigentlich die 406 sein müsste und nicht die 2000, zudem lässt sich die Lampe über ioBroker nicht schalten.
Beim Versuch State auf true zu setzen erscheint im Log folgender Fehler:


```
fritzdect.0 | 2020-06-25 09:58:20.678 | error | (2138) error calling the fritzbox {"error":null,"response":{"statusCode":400,"body":"","headers":{"cache-control":"no-cache","connection":"close","content-length":"0","content-type":"text/plain; char
-- | -- | -- | --
fritzdect.0 | 2020-06-25 09:58:20.678 | error | (2138) bad request (400), ain correct?
```

Wird die AIN mit "-1" übergeben oder ohne?

**Comment by foxthefox** [comment]
der auszug hilft auf jeden fall weiter. DANKE.

ain = -1 ist auf jeden Fall nicht richtig und verursacht den bad request.

Ich schaue es mir an und melde mich, wenn ich weitere Tests benötige.

**Comment by foxthefox** [comment]
hat denn die Lampe in IObroker die AIN mit "130770...-1"?
Evtl. passiert hier noch ein Abschneiden des Anfangs und es verbleibt "-1" was keine gültige AIN ist.

**Comment by sky-it** [comment]
Im Objektbaum hat die DECT500 die "-1" mit drin, als einzigste. DECT 200(210), DECT301 (in ioBroker als Comet werden die AINs richtig wiedergegeben.

**Comment by foxthefox** [comment]
Wenn die AIN "130770...-1" ist und der Befehl nicht akzeptiert wird, dann muss ggf. die -1 entfallen. So eindeutig ist die Doku da leider nicht. das müsste man dann mal durchtesten. Ich schau mir vorher nochmal den Aufruf an.

Die Dect500 ist kein echtes AVM Gerät, so wie die DECT200/300. Bei der Lampe wird über das universelle HAN-FUN gearbeitet und dort hat jedes Gerät nochmals die Endung -x hinter der AIN. Im Falle der Lampe kommen 2 Datensätze rüber. Im Fall des Tasters ist alles in einem Datensatz.
PS. an der Laborversion sollte es meiner Ansicht nach nicht liegen

**Comment by computergott** [comment]
Hallo zusammen,

wie ist der aktuelle Stand dazu? Hab die v0.9.5 per NPM installiert und sehe die DECT 500 nicht in der Übersicht.

Danke!

**Comment by computergott** [comment]
Hallo zusammen,

wie ist der aktuelle Stand zur DECT 500? Hab den Adapter in der Version 0.3.2 installiert. Damit wird die DECT 500 zwar gefunden, aber leider lässt sich die Lampe damit nicht steuern.

Grüße!

**Comment by Or-son** [comment]
Hallo,
ich wollte mal nachfragen.....gibt es schon Neuigkeiten?
Mir geht es genau wie Computergott...
Ich kann die Lampe leider nicht schalten.
Nach jedem Poll wird der Wert wieder überschrieben.
Bitte Bitte Hilfe

Danke

**Comment by foxthefox** [comment]
komme kaum noch zum programmieren
versuche es mir mal anzuschauen, brauche wahrscheinlich aber diverse tests

**Comment by Or-son** [comment]
Oh, Vielen Dank,

ich finde irgendwie keine Möglichkeit dir direkt zu schreiben, also dann soll halt jeder mit lesen.....
wenn du ein Versuchsobjekt brauchst...ich kann Dir das Teil gerne schicken. So wie es im Moment ist, kann ich das Ding eh kaum verwenden.

**Comment by valkma** [comment]
Hallo foxthefox und Or-son,

ich bin hier grade drüber gestolpert, da ich das gleiche Problem habe. Ich habe vor evtl. mehrere dieser Lampen anzuschaffen (nutze zur Zeit diverse von IKEA, aber das Gateway hat oft Verbindungsfehler und dachte mir das die AVM´s evtl. dauerhafter laufen), diverse Schaltsteckdosen habe ich seit Jahren sehr zuverlässig im Einsatz.
Habe also erstmal eine bestellt und einiges ausprobiert ...
Ein / Aus geht nur über den Umweg des Level, der Rest ist nicht nutzbar.

Ich kann gerne Testen, muss nur wissen was für Infos benötigt werden.
und grundsätzlich kann ich nur abends 

Gr. Michael

**Comment by foxthefox** [comment]
ein/aus über state sollte seit heute früh 8uhr gehen. Bitte testen und berichten!

**Comment by sky-it** [comment]
> ein/aus über state sollte seit heute früh 8uhr gehen. Bitte testen und berichten!

funktioniert einwandfrei.
Danke

**Comment by Or-son** [comment]
Fritz Adapter 1.0.1 = Funktion einwandfrei.
Power geht
Dimmer geht

vielen lieben Dank
;-)))))))))))))))))))

**Comment by valkma** [comment]
@foxthefox 
Ich kann ebenfalls bestätigen, das einiges funktioniert.
Herzlichen dank dafür schonmal !!!

Im Prinzip funktionieren diese einstellbaren Werte.
neben "level" und "state" kann über "temperature" auf weiss geschaltet werden.
Also wenn farbig war ("current_mode" = 1) auf weiss, "current_mode" wechselt dadurch auf 4
wenn weiss war, auf eine andere weisse Farbtemperatur.
einstellbare Werte für "temperature" 2700, 3000, 3400, 3800, 4200, 4700, 5300, 5900, 6500

Leider habe ich es nicht geschafft wieder zurück zu bunt zu wechseln.
Auch kann mittels "hue" oder "saturation" die Farbe (noch) nicht wechseln.

Wie gesagt danke und falls du etwas Zeit bekommst (evtl. ja zwischen den Jahren) würde ich mich über ein weiterentwickeln sehr freuen.
Gr. Michael

**Comment by foxthefox** [comment]
Danke für das Feedback. Hilft enorm weiter, wenn man die Geräte nicht besitzt.
Bin am Erstellen der 1.1.0 mit weiteren Dingen. HUE und SATURATION könnte evtl. jetzt auch schon gehen!

Die Umschaltung weiß/farbe schau ich mir nochmal an, evtl. fehlt dort etwas an dem Datenpunkt für current_mode (Befehl senden).

**Comment by Or-son** [comment]
Hi, 
wie bereits geschrieben, kann das Teil gerne verschicken. dann kannste testen bis die Finger glühen ;-))))
Kommt dann ja uns allen zu gute.
Super, dass du dir solche Mühe gibst, obwohl Du selber nichts davon hast.

Kann da gerne ein paar Wochen darauf verzichen.
Die ganze SmartGeschichte ist ja eh nur Hobby und keine Lebensnotwendigkeit.

Fakt, die DECT 500 ist schon eine andere Nummer wie die Gosund WB4.
Wenn wir dann irgendwann mal genau so viel mit machen können.....das wäre toll.
LG
Torsten

PS:
für einen Hinweis wie ich PN verschicken kann wäre ich sehr dankbar ;-)
Trotz Brille finde ich keinen Button dafür.

**Comment by foxthefox** [comment]
hue und saturation sollte jetzt mit 1.1.0 auch funktionieren
Bitte mal testen und berichten.

**Comment by Or-son** [comment]
OnOff geht, dimmer geht, Rest bekomme ich nicht hin.
Mag aber auch an mir liegen

LG

**Comment by foxthefox** [comment]
mit 1.1.1 dürfte es jetzt laufen. bitte auch im debug modus mal die Meldungen anschauen
falls es scheinbar nicht geht, kann es auch daran liegen das nur ganz bestimmte werte für hue und saturation zulässig sind
dann einmal prüfen ob rot hue="358" sat="180" oder blau hue="225" sat="204" funktioniert

**Comment by foxthefox** [comment]
bitte 1.1.3 (die aktuelle Version in git) benutzen, da war noch ein Fehler im commando an die fritzbox.

**Comment by valkma** [comment]
@foxthefox 
Aber hallo, spitze und das für einen Sonntag.
Herzlichen dank.
Funktioniert alles was mein Herz begehrt.

an/aus über state
dimmen über level/levelpercent
weiss über ctemperature (mögliche Werte beachten, siehe oben oder mittels App testen)
farbe über hue und sat gleichzeitig (mögliche Werte beachten, einige siehe oben oder mittels App testen)

Bin leider etwas im Zeitstress heute und erst Freitag wieder da.
Dann kann ich bei Bedarf die möglichen Kombinationen für HUE und SAT notieren.

Nochmals danke    foxthefox

**Comment by Or-son** [comment]
Funktioniert Ast-Rein !!!
wie von Valkma beschrieben.....einwandfrei.
Aus Spass ein paar Farben mit der App getestet und über IoBroker nachgestellt:
Rot            Hue 358   Sat 180
Blau          Hue 225   Sat 204
Gelb          Hue 52    Sat 153
Orange     Hue 35    Sat 214
Grasgrün  Hue 92    Sat 123
Grün         Hue 120   Sat 160

Auf Wunsch gerne mehr Farben.

Dankeschön foxthefox 

Gruß
Torsten

**Comment by foxthefox** [comment]
das freut mich, daß es jetzt funzt.
blöde finde ich diese abgestuften Werte, aber sei es drum, ist erstmal so. Nachdem das klar ist, versuche ich mal noch Fehleingaben zu verhindern.
`     <hsdefaults>
 <hs hue_index="1">
    <name enum="5569">Rot</name>
        <color sat_index="1" hue="358" sat="180" val="230"/>
        <color sat_index="2" hue="358" sat="112" val="237"/>
        <color sat_index="3" hue="358" sat="54" val="245"/>
 </hs>
 <hs hue_index="2"
      ><name enum="5570">Orange</name>
      <color sat_index="1" hue="35" sat="214" val="255"/>
      <color
        sat_index="2"
        hue="35"
        sat="140"
        val="255"/>
      <color sat_index="3" hue="35" sat="72" val="255"/>
      </hs>
      <hs hue_index="3"
      ><name enum="5571">Gelb</name
      ><color sat_index="1" hue="52" sat="153" val="252"/><color
        sat_index="2"
        hue="52"
        sat="102"
        val="252"/><color sat_index="3" hue="52" sat="51" val="255"/></hs
    ><hs hue_index="4"
      ><name enum="5572">Grasgrün</name
      ><color sat_index="1" hue="92" sat="123" val="248"/><color
        sat_index="2"
        hue="92"
        sat="79"
        val="250"/><color sat_index="3" hue="92" sat="38" val="252"/></hs
    ><hs hue_index="5"
      ><name enum="5573">Grün</name
      ><color sat_index="1" hue="120" sat="160" val="220"/><color
        sat_index="2"
        hue="120"
        sat="82"
        val="232"/><color sat_index="3" hue="120" sat="38" val="242"/></hs
    ><hs hue_index="6"
      ><name enum="5574">Türkis</name
      ><color sat_index="1" hue="160" sat="145" val="235"/><color
        sat_index="2"
        hue="160"
        sat="84"
        val="242"/><color sat_index="3" hue="160" sat="41" val="248"/></hs
    ><hs hue_index="7"
      ><name enum="5575">Cyan</name
      ><color sat_index="1" hue="195" sat="179" val="255"/><color
        sat_index="2"
        hue="195"
        sat="118"
        val="255"/><color sat_index="3" hue="195" sat="59" val="255"/></hs
    ><hs hue_index="8"
      ><name enum="5576">Himmelblau</name
      ><color sat_index="1" hue="212" sat="169" val="252"/><color
        sat_index="2"
        hue="212"
        sat="110"
        val="252"/><color sat_index="3" hue="212" sat="56" val="255"/></hs
    ><hs hue_index="9"
      ><name enum="5577">Blau</name
      ><color sat_index="1" hue="225" sat="204" val="255"/><color
        sat_index="2"
        hue="225"
        sat="135"
        val="255"/><color sat_index="3" hue="225" sat="67" val="255"/></hs
    ><hs hue_index="10"
      ><name enum="5578">Violett</name
      ><color sat_index="1" hue="266" sat="169" val="250"/><color
        sat_index="2"
        hue="266"
        sat="110"
        val="250"/><color sat_index="3" hue="266" sat="54" val="252"/></hs
    ><hs hue_index="11"
      ><name enum="5579">Magenta</name
      ><color sat_index="1" hue="296" sat="140" val="250"/><color
        sat_index="2"
        hue="296"
        sat="92"
        val="252"/><color sat_index="3" hue="296" sat="46" val="255"/></hs
    ><hs hue_index="12"
      ><name enum="5580">Pink</name
      ><color sat_index="1" hue="335" sat="180" val="255"/><color
        sat_index="2"
        hue="335"
        sat="107"
        val="248"/><color
        sat_index="3"
        hue="335"
        sat="51"
        val="250"/></hs></hsdefaults
  ><temperaturedefaults
    ><temp value="2700"/><temp value="3000"/><temp value="3400"/><temp
      value="3800"/><temp value="4200"/><temp value="4700"/><temp
      value="5300"/><temp value="5900"/><temp
      value="6500"/></temperaturedefaults>`
die werte die es scheinbar so fix sind (was val in dem Fall bedeutet, weiß ich nicht)

**Comment by foxthefox** [comment]
Ich schließe das Thema mal.
Falls neue Probleme, dann bitte neues Issue aufmachen
Danke fürs Testen
