### ISSUE TITLE
DECT200 States falsch deklariert

### ISSUE THREAD

**Issue by ihavenonick** [foxthefox/ioBroker.fritzdect#64]
Bei den Objekten taucht unter state, was zum an/aus schalten verwendet wird 0 und 1 auf. Wenn ich den Status setze wird aber true oder false geschrieben. Das funktioniert zwar, irritiert aber weil der Adapter nach einiger Zeit das wieder mit 0 oder 1 ersetzt. Steuere ich den DP über ein Script mit 0 oder 1, gibts gleich Warnmeldungen, weil das die falsche Deklaration wäre.

**Comment by foxthefox** [comment]
Da gab es mal einen PR wo number zu bool korrigiert wurde, muss nachschauen ob da noch etwas fehlt oder sich zwischenzeitlich sich etwas an der eingebundenen API geändert hat.
Welche Version ist in iobroker installiert?

**Comment by ihavenonick** [comment]
Ist die 0.2.4

**Comment by foxthefox** [comment]
Ich habe in der 0.2.5 Korrekturen vorgenommen.
Ist derzeitig nur über github installierbar.
Bitte einmal Testen und berichten.

**Comment by ihavenonick** [comment]
sieht gut aus, state bleibt auf false oder true und keine Fehler im Log

**Comment by foxthefox** [comment]
perfekt, habe 0.2.5 auf npm veröffentlicht
