### ISSUE TITLE
Update stable version in repo to 0.2.4

### ISSUE THREAD

**Issue by GermanBluefox** [foxthefox/ioBroker.fritzdect#65]
# Think about update stable version to 0.2.4
**Version**: stable=**0.1.4** (478 days old) => latest=**0.2.4** (199 days old)
**Installs**: stable=**1898** (49.99%), latest=**1202** (31.66%), total=**3797**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L302)

**Comment by foxthefox** [comment]
done with 
https://github.com/ioBroker/ioBroker.repositories/pull/659
