### ISSUE TITLE
Error since update to 0.2.4

### ISSUE THREAD

**Issue by aleks-83** [foxthefox/ioBroker.fritzdect#71]
Node.js v10.17.0
NPM 6.11.3
JS Controller 2.2.8
Win 10

My system is on "default", not on "latest" repository.
It offers me to update from 0.1.5 to 0.2.4.
But when i click on the button to install a specific version, i can only see up to 0.1.5.

Since i updated the adapter from 0.1.5 to 0.2.4, i get these error messages.
I already reentered the username and password.
This password was working until now.
There are no special characters or something.

fritzdect.0 | 20.03.2020 08:06 | info | (26028)   entered ready
-- | -- | -- | --
fritzdect.0 | 20.03.2020 08:06 | info | (26028)   starting. Version 0.2.4 in D:/ioBroker/NUC/node_modules/iobroker.fritzdect,   node: v10.17.0
fritzdect.0 | 20.03.2020 08:06 | error | (26028)   Did not get session id- invalid username or password?
fritzdect.0 | 20.03.2020 08:06 | error | (26028) fritzbox   returned this "0000000000000000"
fritzdect.0 | 20.03.2020 08:06 | error | (26028)   Did not get session id- invalid username or password?
fritzdect.0 | 20.03.2020 08:06 | error | (26028) fritzbox   returned this "0000000000000000"
fritzdect.0 | 20.03.2020 08:06 | error | (26028)   Did not get session id- invalid username or password?
fritzdect.0 | 20.03.2020 08:06 | error | (26028) fritzbox   returned this "0000000000000000"

**Comment by foxthefox** [comment]
from version 0.1.5 onwards the password is encrypted.
Please retype the password in admin page and restart the adapter

**Comment by r2ixuz** [comment]
Reentering credentials did not help. What now?

**Comment by aleks-83** [comment]
For me it helped to reenter the username and password and **restart the NUC**

**Comment by r2ixuz** [comment]
Wow, that is really strange behaviour: I did a downgrade to the last stable version for me (0.1.4). With this version there were no errors in the log but still no updated data from my outlets. So I re-installed the 0.2.4 and it just works now without error...
