### ISSUE TITLE
DECT 400 Button - Schalter wird erkannt / Tastendruck wird nicht erkannt

### ISSUE THREAD

**Issue by noexperiance** [foxthefox/ioBroker.fritzdect#74]
Hallo foxthefox,

auch von mir ein herzliches Dankeschön für Deine Arbeit.

In ioBroker kommen meine Taster-Betätigungen nicht an. Ich glaube, das gabs mal in einem Issue, finde das aber nicht mehr, sorry.

Eine Verkopplung mit meinem DECT200 in der FritzBox funktioniert. Ich kann die Steckdose umschalten. 

In ioBroker wird der DECT400 erkannt, inkl. der Infos "lastpressed...". Die Zahl ändert sich auch nach einem Tastendruck. Hier der Auszug aus "meine Geräte":
{"identifier":"130960019140","id":"21","functionbitmask":"32","fwversion":"04.90","manufacturer":"AVM","productname":"FRITZ!DECT 400","present":"1","name":"Schalter1","battery":"100","batterylow":"0","button":[{"identifier":"13096 0019140-0","id":"5000","name":"Schalter1: Mitte","lastpressedtimestamp":"1585035847"},{"identifier":"13096 0019140-9","id":"5001","name":"Schalter1: lang","lastpressedtimestamp":"1585034850"}]}]

Unter Objekte wird mir unter "Button Clicktime" der Wert "Invalid Date" angezeigt. Wobei das Datenformat hier "Date" ist. Ändere ich das Datenformat auf "Value" wird mir der Zahlenwert angezeigt.
**-->** Macht hier hier Sinn den Wert in der Voreinstellung nicht als Datum zu definieren?

**Mein Problem:** wenn ich den Button klicke (Format ist auf Value gestellt), wird im ioBroker unter Objekte der Wert nicht aktualisiert. Was kann ich hier tun? Die Zahl wird nur nach Neustart des Adapters aktualisiert.

Fritz OS: 7.12, Adapter Versionen getestet: 0.2.4, 0.3.0 und 1.0.1
Bisher versucht: im Adapter geändert Fritzbox Abrufintervall (sek.) 0.01, 0.1, 300 
**Gibt es noch Einstellungen in der Fritzbox?**

Vielen Dank und beste Grüße

**Comment by foxthefox** [comment]
Danke für dein Feedback.
Den DECT400 besitze ich nicht und deswegen ist jede Rückmeldung wertvoll.
Die clicktime habe ich als lesbares Datum vorgesehen. Denn  millisekunden nach 1.1.1970 bringt wohl kaum etwas.
Ich schaue mir gleich mal die Problematik mit der Umwandlung an.

Wertänderungen sollten mit jedem update ankommen, welches nach dem eingestellten Intervall abgeholt wird.
Gefühlt würd ich beim setting nicht unter 10s gehen. Es wurde auch schon berichtet, daß bei sehr schnellen Anfragen an die Fritzbox, diese wegen No_Memory aussteigt und nix mehr geht.

Gruß
Klaus

**Comment by noexperiance** [comment]
Moin Klaus,

ich hab mal den Wert Fritzbox Abrufintervall (sek.) im Bereich 1s-10s getestet. Dann bekomme ich die Aktualisierung automatisch in meine Objekte rein.

Allerdings nur, wenn ich weiterhin das Datenformat weiter auf "Value" lasse. 

Und durch die "seltene" Aktualisierung alle 5-10s ist ein live-ein/ausschalten von zB Lampen ja eher suboptimal. Aber ich sehe ein, dass das ein systematisches Problem des Abrufens gegenüber des Pushens der Events.

Ich kenn das Protokoll nicht - können diese Events prinzipiell auch gepusht werden?

Beste Grüße und vielen Dank für Deine kurzfristige Reaktion
Oliver

**Comment by foxthefox** [comment]
Hi Oliver,

Problem ist mit dem Datum in der github Version gelöst.
Nun sollte ein verwertbares Datum angezeigt werden.
Kannst gerne testen.

Leider kann man nicht auf der Fritzbox Datenupdates abbonieren.
Zum Licht schalten erstmal ungeeignet, aber die DECT500 dürfte direkt auf die DECT400 reagieren.

Gruß
Klaus

**Comment by noexperiance** [comment]
Klaus, 

ich bin hier echt noch unerfahren - hab aus Versehens den Issue geschlossen. :)

In welcher Version hast Du das Datum Problem gelöst? Bei Installation aus Github bekomme ich noch Version 1.0.1.

Beste Grüße
Oliver

**Comment by foxthefox** [comment]
genau in dieser Entwicklerversion.
Ich hab dem jetzt keine neue Version verpasst, sofern du schon von github installiert hattest, einfach nochmal. Ansonsten erstmal die github version nehmen.
Danach Adapter neu starten

**Comment by noexperiance** [comment]
Perfekt,  jetzt passt es bei mir! 

Ich denke, damit habe ich einen Stand erreicht, der nur verbessert werden könnte, wenn die FritzBox den Button Status pushen würde.

Da sie das nicht tut, können wir den Punkt hier IMHO dicht machen.

Und nochmal Danke! :)
