### ISSUE TITLE
Login problem with new Fritzbox OS version

### ISSUE THREAD

**Issue by TeslaNator** [foxthefox/ioBroker.fritzdect#75]
My Fritz OS version is 06.86 since 23.3.2020. The adapter can't login anymore.  ioBroker instance indicator is green.

Box: 
FRITZ!Box Fon WLAN 7360

Log:
fritzdect.0 | 2020-03-25 18:06:26.917 | error | (4148) Did not get session id- invalid username or password?
fritzdect.0 | 2020-03-25 18:06:26.916 | error | (4148) fritzbox returned this "0000000000000000"

**Comment by foxthefox** [comment]
Which version of adapter are you using?

Did you check the login from the website to your fritzbox? Did this work?
With updating to new firmware there might be new settings available, which now have to be activated. Did you check and activate those?

If the settings in fritzbox are good for external connection:
Please retype the password and restart the adapter.
What is your vaule for the polling interval?

**Comment by TeslaNator** [comment]
Adapter Version is 1.0.1

Login to fritz box webinterface works normally.

Can't see any new settings. Fritzbox user has all rights (as before).
Adapter polling interval is set to 30.

I retyped password and restarted adapter, no success:

fritzdect.0 | 2020-03-26 07:53:51.215 | error | (4372) Did not get session id- invalid username or password?
-- | -- | -- | --
fritzdect.0 | 2020-03-26 07:53:51.214 | error | (4372) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-03-26 07:53:51.000 | error | (4372) Did not get session id- invalid username or password?
fritzdect.0 | 2020-03-26 07:53:51.000 | error | (4372) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-03-26 07:53:50.782 | error | (4372) Did not get session id- invalid username or password?
fritzdect.0 | 2020-03-26 07:53:50.781 | error | (4372) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-03-26 07:53:50.562 | error | (4372) Did not get session id- invalid username or password?
fritzdect.0 | 2020-03-26 07:53:50.561 | error | (4372) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-03-26 07:53:50.342 | error | (4372) Did not get session id- invalid username or password?
fritzdect.0 | 2020-03-26 07:53:50.342 | error | (4372) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-03-26 07:53:49.019 | info | (4372) entered ready
fritzdect.0 | 2020-03-26 07:53:49.013 | info | (4372) starting. Version 1.0.1 in C:/Program Files/iobroker/SmartHome/node_modules/iobroker.fritzdect, node: v10.16.0
host.iobroker(SmartHome) | 2020-03-26 07:53:48.483 | info | instance system.adapter.fritzdect.0 started with pid 4372
host.iobroker(SmartHome) | 2020-03-26 07:53:46.508 | info | instance system.adapter.fritzdect.0 terminated with code 4294967196 (START_IMMEDIATELY_AFTER_STOP_HEX)
fritzdect.0 | 2020-03-26 07:53:45.970 | info | (4996) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
fritzdect.0 | 2020-03-26 07:53:45.970 | info | (4996) terminating
fritzdect.0 | 2020-03-26 07:53:45.969 | info | (4996) cleaned everything up...
fritzdect.0 | 2020-03-26 07:53:45.969 | info | (4996) Got terminate signal TERMINATE_YOURSELF
host.iobroker(SmartHome) | 2020-03-26 07:53:45.964 | info | stopInstance system.adapter.fritzdect.0 send kill signal
host.iobroker(SmartHome) | 2020-03-26 07:53:45.964 | info | stopInstance system.adapter.fritzdect.0 (force=false, process=true)

**Comment by TeslaNator** [comment]
ok...
Since a few hours it works. I don't know why. I changed nothing.
