### ISSUE TITLE
Werte Aktualisierung Optimieren

### ISSUE THREAD

**Issue by lammy000** [foxthefox/ioBroker.fritzdect#76]
Hi,

mir ist aufgefallen das der Adapter wenn er alle 2 Sekunden nach Änderungen schauen soll diese auch immer Blind rein schreibt obwohl sich die Werte nicht geändert haben. Dies wird zu einem Problem mit anderen Instanzen in iobroker. Kannst du es anpassen das die Werte nur aktualisiert werden wenn sie sich zu den bereits abgefragten unterscheiden ?

thx!

**Comment by foxthefox** [comment]
was genau ist denn das Problem?
Bzw. mit welchen anderen Adaptern gibt es ein Problem und welcher Art?

Man kann natürlich jedesmal prüfen was im Speicher ist, aber ich glaube es ist recht unüblich für die Adapter.

**Comment by lammy000** [comment]
Hi,

habe den fritzDect etwas umgebaut.
Anbei der Code. für den Power Wert einer Dect200 Steckdose. Für die Restlichen würde ich es auch noch machen aber es natürlich geil finden wenn du es bei dir auch einbaustIch würde sogar den % Abweichungs Wert in der Webadmin Oberfläche mit aufnehmen wollen. Da weiß ich aber noch nicht wie das geht :-) Würde ich aber auf jeden fall mit rein basteln. Diese könnte man auch einfach in ein objekt schreiben damit man ihn auch easy abrufen kann  
`                        else {
                            let convertSwitchState = device.switch.state == 1 ? true: false;
                            adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'state :' + convertSwitchState + '(' + device.switch.state+')');
                            adapter.setState('DECT200_'+ device.identifier +'.state', {val: convertSwitchState, ack: true});

                            adapter.log.debug('neu');
                            adapter.getState('DECT200_'+ device.identifier +'.power', function (err, state) {
                                var min_delta_percent = 0.05;
                                var old_value = parseFloat(state.val);
                                var new_value = parseFloat(device.powermeter.power)/1000;
                                if (old_value - new_value < 0){
                                    // Alter Wert minus neuer Wert *-1 da das Ergebnis Negativ ist und fuer den spaeteren Vergleich unbrauchbar ist
                                    var result = old_value - new_value *-1
                                }
                                else {
                                    // Alter Wert minus neuer Wert ohne *-1 da das Ergebnis positiv ist
                                    var result = old_value - new_value
                                };

                                adapter.log.debug('Neue Daten: old_value: ' + old_value + 'new_value: ' + new_value + 'result: ' + result);
                                // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                                if (result / new_value > min_delta_percent){
                                        // Etwas Debug Loggen fuer die Entwicklung
                                        adapter.log.debug('Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                        // Werte loggen und in Objekt schreiben
                                        adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'power :' + new_value);
                                        adapter.setState('DECT200_'+ device.identifier +'.power', {val: new_value, ack: true});
                                };
                            }
                            );

                            adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'energy :' + device.powermeter.energy);
                            adapter.setState('DECT200_'+ device.identifier +'.energy', {val: device.powermeter.energy, ack: true});

                            adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'mode : ' + device.switch.mode);
                            adapter.setState('DECT200_'+ device.identifier +'.mode', {val: device.switch.mode, ack: true});

                            let convertLock = device.switch.lock == 1 ? true: false;
                            adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'lock : ' + convertLock + ' (' +  device.switch.lock + ')');
                            adapter.setState('DECT200_'+ device.identifier +'.lock', {val: convertLock, ack: true});

                            let convertDeviceLock = device.switch.devicelock == 1 ? true: false;
                            adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'devicelock : ' + convertDeviceLock + ' (' + device.switch.devicelock + ')');
                            adapter.setState('DECT200_'+ device.identifier +'.devicelock', {val: convertDeviceLock, ack: true});

                            if(device.temperature){
                                adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'temp : ' + (parseFloat(device.temperature.celsius))/10);
                                adapter.setState('DECT200_'+ device.identifier +'.temp', {val: (parseFloat(device.temperature.celsius))/10, ack: true});

                                adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'temp offset: ' + (parseFloat(device.temperature.offset))/10);
                                adapter.setState('DECT200_'+ device.identifier +'.temp_offset', {val: (parseFloat(device.temperature.offset))/10, ack: true});
                            }

                            if(device.powermeter.voltage){
                            //if( adapter.config.dect200volt_en === 'true' || adapter.config.dect200volt_en  === true || adapter.config.dect200volt_en  === 1 ) {
                                adapter.log.debug('DECT200_'+ device.identifier + ' : ' +'voltage : ' + device.powermeter.voltage / 1000);
                                adapter.setState('DECT200_'+ device.identifier +'.voltage', {val: device.powermeter.voltage / 1000, ack: true});
                            }
                        }
                    }`

**Comment by lammy000** [comment]
für den Rest habe ich es auch fertig gebaut. Jedoch nur für den Dect200 adapter.

`                    else if((device.functionbitmask & 512) == 512){ //switch

                        adapter.log.debug('neu.name');
                        adapter.getState('DECT200_'+ device.identifier +'.name', function (err, state) {
                            var old_value = state.val;
                            var new_value = device.name;
                            var result = "nothing";

                            adapter.log.debug('neu.name_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                            // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                            if (old_value != new_value){
                                    // Etwas Debug Loggen fuer die Entwicklung
                                    adapter.log.debug('neu.name_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                    // Werte loggen und in Objekt schreiben
                                    adapter.log.debug('updating Switch '+ device.name);
                                    adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'name : ' + device.name);
                                    adapter.setState('DECT200_'+ device.identifier +'.name', {val: device.name, ack: true});
                            };
                        }
                        );


                        adapter.log.debug('neu.present');
                        adapter.getState('DECT200_'+ device.identifier +'.present', function (err, state) {
                            var old_value = state.val;
                            var new_value = device.present;
                            var result = "nothing";

                            adapter.log.debug('neu.present_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                            // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                            if (old_value != new_value){
                                    // Etwas Debug Loggen fuer die Entwicklung
                                    adapter.log.debug('neu.present_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                    // Werte loggen und in Objekt schreiben
                                    let convertPresent = device.present == 1 ? true: false;
                                    adapter.log.debug('DECT200_'+ device.identifier+ ' : ' +'present : ' + convertPresent + ' (' + device.present + ')');
                                    adapter.setState('DECT200_'+ device.identifier +'.present', {val: convertPresent, ack: true});
                            };
                        }
                        );


                        if ( (device.present === "0") ||  (device.present === 0) || (device.present === false )){
                            adapter.log.warn('DECT200_'+ device.identifier + ' is not present, check the device connection, no values are written');
                            }
                        else {

                            adapter.log.debug('neu.state');
                            adapter.getState('DECT200_'+ device.identifier +'.state', function (err, state1) {
                                var old_value = state1.val;
                                var new_value = device.switch.state;
                                var result = "nothing";

                                adapter.log.debug('neu.state_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                                if (old_value != new_value){
                                        // Etwas Debug Loggen fuer die Entwicklung
                                        adapter.log.debug('neu.state_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                        // Werte loggen und in Objekt schreiben
                                        let convertSwitchState = device.switch.state == 1 ? true: false;
                                        adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'state :' + convertSwitchState + '(' + device.switch.state+')');
                                        adapter.setState('DECT200_'+ device.identifier +'.state', {val: convertSwitchState, ack: true});
                                };
                            }
                            );


                            adapter.log.debug('neu.power');
                            var min_delta_percent = 0.05;
                            adapter.getState('DECT200_'+ device.identifier +'.power', function (err, state) {
                                var old_value = parseFloat(state.val);
                                var new_value = parseFloat(device.powermeter.power)/1000;
                                if (old_value - new_value < 0){
                                    // Alter Wert minus neuer Wert *-1 da das Ergebnis Negativ ist und fuer den spaeteren Vergleich unbrauchbar ist
                                    var result = old_value - new_value *-1
                                }
                                else {
                                    // Alter Wert minus neuer Wert ohne *-1 da das Ergebnis positiv ist
                                    var result = old_value - new_value
                                };

                                adapter.log.debug('neu.power_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                                if (result / new_value > min_delta_percent){
                                        // Etwas Debug Loggen fuer die Entwicklung
                                        adapter.log.debug('neu.power_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                        // Werte loggen und in Objekt schreiben
                                        adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'power :' + new_value);
                                        adapter.setState('DECT200_'+ device.identifier +'.power', {val: new_value, ack: true});
                                };
                            }
                            );

                            adapter.log.debug('neu.energy');
                            adapter.getState('DECT200_'+ device.identifier +'.energy', function (err, state) {
                                var old_value = parseFloat(state.val);
                                var new_value = parseFloat(device.powermeter.energy);
                                if (old_value - new_value < 0){
                                    // Alter Wert minus neuer Wert *-1 da das Ergebnis Negativ ist und fuer den spaeteren Vergleich unbrauchbar ist
                                    var result = old_value - new_value *-1
                                }
                                else {
                                    // Alter Wert minus neuer Wert ohne *-1 da das Ergebnis positiv ist
                                    var result = old_value - new_value
                                };

                                adapter.log.debug('neu.energy_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                                if (result / new_value > min_delta_percent){
                                        // Etwas Debug Loggen fuer die Entwicklung
                                        adapter.log.debug('neu.energy_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                        // Werte loggen und in Objekt schreiben
                                        adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'energy :' + device.powermeter.energy);
                                        adapter.setState('DECT200_'+ device.identifier +'.energy', {val: device.powermeter.energy, ack: true});
                                };
                            }
                            );

                            adapter.log.debug('neu.mode');
                            adapter.getState('DECT200_'+ device.identifier +'.mode', function (err, state) {
                                var old_value = state.val;
                                var new_value = device.switch.mode;
                                var result = "nothing";

                                adapter.log.debug('neu.mode_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                                if (old_value != new_value){
                                        // Etwas Debug Loggen fuer die Entwicklung
                                        adapter.log.debug('neu.mode_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                        // Werte loggen und in Objekt schreiben
                                        adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'mode : ' + device.switch.mode);
                                        adapter.setState('DECT200_'+ device.identifier +'.mode', {val: device.switch.mode, ack: true});
                                };
                            }
                            );

                            adapter.log.debug('neu.lock');
                            adapter.getState('DECT200_'+ device.identifier +'.lock', function (err, state) {
                                var old_value = state.val;
                                var new_value = device.switch.lock;
                                var result = "nothing";

                                adapter.log.debug('neu.mode_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                                if (old_value != new_value){
                                        // Etwas Debug Loggen fuer die Entwicklung
                                        adapter.log.debug('neu.mode_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                        // Werte loggen und in Objekt schreiben
                                        let convertLock = device.switch.lock == 1 ? true: false;
                                        adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'lock : ' + convertLock + ' (' +  device.switch.lock + ')');
                                        adapter.setState('DECT200_'+ device.identifier +'.lock', {val: convertLock, ack: true});
                                };
                            }
                            );

                            adapter.log.debug('neu.devicelock');
                            adapter.getState('DECT200_'+ device.identifier +'.devicelock', function (err, state) {
                                var old_value = state.val;
                                var new_value = device.switch.devicelock;
                                var result = "nothing";

                                adapter.log.debug('neu.devicelock_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                                if (old_value != new_value){
                                        // Etwas Debug Loggen fuer die Entwicklung
                                        adapter.log.debug('neu.devicelock_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                        // Werte loggen und in Objekt schreiben
                                        let convertDeviceLock = device.switch.devicelock == 1 ? true: false;
                                        adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'devicelock : ' + convertDeviceLock + ' (' + device.switch.devicelock + ')');
                                        adapter.setState('DECT200_'+ device.identifier +'.devicelock', {val: convertDeviceLock, ack: true});
                                };
                            }
                            );


                            if(device.temperature){
                                adapter.log.debug('neu.temp');
                                adapter.getState('DECT200_'+ device.identifier +'.temp', function (err, state) {
                                    var old_value = parseFloat(state.val);
                                    var new_value = parseFloat(device.temperature.celsius)/10;
                                    if (old_value - new_value < 0){
                                        // Alter Wert minus neuer Wert *-1 da das Ergebnis Negativ ist und fuer den spaeteren Vergleich unbrauchbar ist
                                        var result = old_value - new_value *-1
                                    }
                                    else {
                                        // Alter Wert minus neuer Wert ohne *-1 da das Ergebnis positiv ist
                                        var result = old_value - new_value
                                    };

                                    adapter.log.debug('neu.temp_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                    // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                                    if (result / new_value > min_delta_percent){
                                            // Etwas Debug Loggen fuer die Entwicklung
                                            adapter.log.debug('neu.temp_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                            // Werte loggen und in Objekt schreiben
                                            let convertDeviceLock = device.switch.devicelock == 1 ? true: false;
                                            adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'temp : ' + (parseFloat(device.temperature.celsius))/10);
                                            adapter.setState('DECT200_'+ device.identifier +'.temp', {val: (parseFloat(device.temperature.celsius))/10, ack: true});
                                    };
                                }
                                );

                                adapter.log.debug('neu.temp_offset');
                                adapter.getState('DECT200_'+ device.identifier +'.temp_offset', function (err, state) {
                                    var old_value = parseFloat(state.val);
                                    var new_value = parseFloat(device.temperature.offset)/10;
                                    if (old_value - new_value < 0){
                                        // Alter Wert minus neuer Wert *-1 da das Ergebnis Negativ ist und fuer den spaeteren Vergleich unbrauchbar ist
                                        var result = old_value - new_value *-1
                                    }
                                    else {
                                        // Alter Wert minus neuer Wert ohne *-1 da das Ergebnis positiv ist
                                        var result = old_value - new_value
                                    };

                                    adapter.log.debug('neu.temp_offset_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                    // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                                    if (result / new_value > min_delta_percent){
                                            // Etwas Debug Loggen fuer die Entwicklung
                                            adapter.log.debug('neu.temp_offset_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                            // Werte loggen und in Objekt schreiben
                                            let convertDeviceLock = device.switch.devicelock == 1 ? true: false;
                                            adapter.log.debug('DECT200_'+ device.identifier + ' : '  +'temp offset : ' + (parseFloat(device.temperature.offset))/10);
                                            adapter.setState('DECT200_'+ device.identifier +'.temp_offset', {val: (parseFloat(device.temperature.offset))/10, ack: true});
                                    };
                                }
                                );
                            }

                            if(device.powermeter.voltage){

                                adapter.log.debug('neu.voltage');
                                var min_delta_percent = 0.05;
                                adapter.getState('DECT200_'+ device.identifier +'.voltage', function (err, state) {
                                    var old_value = parseFloat(state.val);
                                    var new_value = parseFloat(device.powermeter.voltage)/1000;
                                    if (old_value - new_value < 0){
                                        // Alter Wert minus neuer Wert *-1 da das Ergebnis Negativ ist und fuer den spaeteren Vergleich unbrauchbar ist
                                        var result = old_value - new_value *-1
                                    }
                                    else {
                                        // Alter Wert minus neuer Wert ohne *-1 da das Ergebnis positiv ist
                                        var result = old_value - new_value
                                    };

                                    adapter.log.debug('neu.voltage_Neue Daten: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                    // Auwerten ob die neue Prozentuale Abweichung größer ist als die Minimal Definierte Prozentuale Abweichung min_delta_percent
                                    if (result / new_value > min_delta_percent){
                                            // Etwas Debug Loggen fuer die Entwicklung
                                            adapter.log.debug('neu.voltage_Unterschied Ermittelt: old_value: ' + old_value + ' new_value: ' + new_value + ' result: ' + result);
                                            // Werte loggen und in Objekt schreiben
                                            //if( adapter.config.dect200volt_en === 'true' || adapter.config.dect200volt_en  === true || adapter.config.dect200volt_en  === 1 ) {
                                                adapter.log.debug('DECT200_'+ device.identifier + ' : ' +'voltage : ' + device.powermeter.voltage / 1000);
                                                adapter.setState('DECT200_'+ device.identifier +'.voltage', {val: device.powermeter.voltage / 1000, ack: true});
                                    };
                                }
                                );

                            }
                        }
                    }`

**Comment by foxthefox** [comment]
Da hast du dir ordentlich Arbeit gemacht. Kannst du einen PR aufmachen? Dann lässt sich so etwas einfacher mergen.

Was genau ist jetzt nochmal das Problem mit dem setzen der Werte?
Im history Adapter kann man ja es so parametrieren, daß nur bei Änderung ein Wert abgespeichert wird. Das löst doch in den allermeisten Fällen schon Speicherplatzprobleme.

**Comment by lammy000** [comment]
Ja das kann ich machen. Ist dann das erste mal und ich hoffe es klappt :-)

**Comment by lammy000** [comment]
Das Problem liegt in der Kombi des FritzDect und fhem Adpaters. Der FHEM Adapter überträgt alles als Telnet Befehl Richtung FHEM und der FritzDect Adapter aktualisierte bis zum Patch von mir alle x Sekunden die Werte Egal ob sie geändert wurden oder nicht.

**Comment by lammy000** [comment]
Hi,

ich habe den Adapter aktualisiert und leider schreibt er nicht wie bei meiner "selbst erstellen Version" nur die Änderungen in die Objekte sondern wieder jedes mal obwohl sich nichts geändert hat. Kannst du das noch reinpatchen ?

**Comment by lammy000** [comment]
Ich habe mir den neuen Code mal angeschaut.
Ich würde hier eine kurze IF Abfrage rein bauen ob der Wert der aktuell besteht gleich (+/- 1%) dem neuen ist und dann erst den Restlichen durchlauf starten. da der code vom aufbau aber komplett anders ist als der alte traue ich es mir nicht zu ihn anzupassen.

`async updateDatapoint(key, value, ain) {
		this.log.debug('updating data DECT_' + ain + ' : ' + key + ' : ' + value);
		try {
			if (!value || value == '') {
				this.log.debug(' no value for updating in ' + key);
				await this.setStateAsync('DECT_' + ain + '.' + key, {
					val: null,
					ack: true
				});
			} else {
   --->                    if ( aktueller wert des objektes größer/kleiner 1% zu dem neuen wert ) {                         
				if (key == 'nextchange') {
					//fasthack anstatt neue objekterkennung
					await this.updateData(value, ain)`

**Comment by foxthefox** [comment]
kein Thema, durch den neuen Code ist alles einfache geworden!
Ich habe es auch schon als "enhancement" getaggt.
Ich werde es demnächst angehen, wollte aber erstmal das komplette refactoring als lauffähig wissen, bevor ich das nächste angehe.
Seit 2 Wochen gibt es keine neuen Erkenntnisse, also werde ich die 2.2x demnächst anfangen.

**Comment by lammy000** [comment]
Ja super ! ich bin gespannt wie es aussieht. Vieleicht kannst du ja in der Admin Gui noch einen Schwellwert einbauen dann kann jeder es Variable Regeln ob es 1% oder 10% sein soll.

**Comment by foxthefox** [comment]
ich baue im Admin einen Schalter ein, der es ein oder ausschaltet. Damit nicht wieder ein Aufschrei kommt.

**Comment by foxthefox** [comment]
hab da einen Branch eröffnet "writeonhyst"
Im Admin gibt es zwar Hysterie, ist denke ich aber wieder rauszunehmen. Die Temperaturen ändern sich eh nur alle 0,5° und bei Energie und Spannung wäre das Prozent auch besser in V und Wh zu definieren. 
Hab es bisher noch nicht weiter ausprobiert, da fehlt mir ein wenig die Zeit

**Comment by foxthefox** [comment]
habe mit der version 2.3.0 diese Funktion nun umgesetzt, wenn es keine Änderung zum gespeicherten zustand gibt, wird auch nichts geschrieben
Bitte einmal Testen (aus github installieren) und berichten
