### ISSUE TITLE
Fritzdect nur noch mit neuem Nutzer funktionsfähig

### ISSUE THREAD

**Issue by JBSullivan** [foxthefox/ioBroker.fritzdect#79]
Seit dem Update auf Admin 4.0.9 und js-controller 3.17 gibt fritzdect immer wieder Fehlermeldungen wie diese aus.

Diese ist nur durch einen Workaround zu beheben, wenn man in der Fritzbox einen neuen Nutzer anlegt.

Jedes starten und stoppen der Instanz, setzt den Workaround wieder zurück und man bekommt erneut diese Fehlermeldungen. Neuen Benutzer in der FB angelegt und alles funktioniert wieder - bis zum nächsten Stop der Instanz.

Siehe auch -> https://forum.iobroker.net/topic/32481/js-controller-3-0-jetzt-im-latest/274
`

fritzdect.0 | 2020-04-23 08:34:34.828 | error | (2052) Did not get session id- invalid username or password?
-- | -- | -- | --
fritzdect.0 | 2020-04-23 08:34:34.828 | error | (2052) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-04-23 08:34:34.341 | error | (2052) Did not get session id- invalid username or password?
fritzdect.0 | 2020-04-23 08:34:34.340 | error | (2052) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-04-23 08:34:33.733 | error | (2052) Did not get session id- invalid username or password?
fritzdect.0 | 2020-04-23 08:34:33.733 | error | (2052) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-04-23 08:34:33.212 | error | (2052) Did not get session id- invalid username or password?
fritzdect.0 | 2020-04-23 08:34:33.212 | error | (2052) fritzbox returned this "0000000000000000"
C:/iobroker/GLT/node_modules/iobroker.ical, node: v10.17.0, js-controller: 3.0.17
fritzdect.0 | 2020-04-23 08:34:32.701 | error | (2052) Did not get session id- invalid username or password?
fritzdect.0 | 2020-04-23 08:34:32.700 | error | (2052) fritzbox returned this "0000000000000000"
host.GLT | 2020-04-23 08:34:31.714 | info | instance system.adapter.ical.1 started with pid 7680

`

**Comment by foxthefox** [comment]
admin 4.0 hab ich bisher nicht auf dem Schirm, da muß wohl irgendetwas zu Beeinträchtigungen führen

**Comment by nob0dy80** [comment]
Habe das gleiche Problem mit js-controller 2.2.8 und admin 3.7.8

Hab ein Update von 0.1.4 auf 0.2.4 gemacht. Danach kamen die oben genannten Fehler.
Nach Downgrade auf 0.1.4 geht alles wieder. Nach dem downgrade war das Passwort-Feld nur mit Blödsinn ausgefüllt, funktionierte aber sofort wieder nachdem ich das Passwort neu eingetippt hab.
(was vermutlich an der "password now hidden typed and encrypted"-Sache liegt ab 0.1.5)

**Comment by the78mole** [comment]
Hier das Gleiche... 
![image](https://user-images.githubusercontent.com/7723396/84083702-72167980-a9e2-11ea-8907-cad8d1ad58fa.png)

**Comment by foxthefox** [comment]
habe soeben meinen raspi neu aufgesetzt,
js-ctrl ->3.1.4
admin->4.0.10
fritzdect -> 1.0.1
läuft nach setup des Passwortes und neustart vom Adapter und vom raspi

**Comment by nob0dy80** [comment]
@foxthefox 
Ok, kann ich bestätigen. Hab auch gerade mal neu aufgesetzt. Klappt alles.

**Comment by aDabbelju** [comment]
Gibt es hier schon eine Lösung? Meinen ioBroker komplett neu aufsetzen sollte es nämlich nicht sein.

**Comment by Planetus88** [comment]
Hallo,
habe auch das gleiche Problem:
(2976) Did not get session id- invalid username or password?
(2976) fritzbox returned this "0000000000000000"

Kann mir jemand eine Lösung verraten? Einen neuen User in der Fritzbox anzulegen bringt nichts :-(

**Comment by foxthefox** [comment]
Bitte überprüfen, ob auch wirklich alle Berechtigungen für den Nutzer in der Fritzbox freigegeben sind.

**Comment by foxthefox** [comment]
Eben nochmal etwas entdeckt!

Wenn man eigens angelegte Benutzer für iobroker benutzen will, so ist auch die Anmeldung über das Heimnetz über login und Passwort notwendig!
Bei der Auswahl wird admin nicht angeboten, diesen also neu mit allen Berechtigungen anlegen, sonst sperrt man sich ggf. aus.

Bitte dies mal überprüfen und berichten

**Comment by foxthefox** [comment]
![userlogin](https://user-images.githubusercontent.com/16841643/102753415-86610900-436b-11eb-84a1-64f27b1fe55e.png)
![userpermissions](https://user-images.githubusercontent.com/16841643/102753422-8a8d2680-436b-11eb-8fff-3e6162e73fc1.png)

**Comment by nob0dy80** [comment]
@foxthefox 

Anmeldung mit Fritzbox-Benutzernamen und Kennwort ist Standard sobald man einen zweiten Nutzer anlegt.

Die Optionen "Fritz!Box Einstellungen" und "Sprachnachrichten...." sind nicht notwendig.

**Comment by foxthefox** [comment]
Anmeldung mit Benutzernamen und Kennwort war bei mir nicht vorgewählt, trotz mehrfach vorhandenen Nutzern!
Ich musste es speziell umstellen.

Läuft denn der Adapter mit dem existierenden Nutzer, oder gibt es das Problem immer noch?

**Comment by nob0dy80** [comment]
@foxthefox 
Ich kann es dir nicht sagen, weil ich, wie vor einigen Beiträgen erwähnt, einfach Iobroker neu installiert habe. Für mich war das Problem damit erledigt.
Ich bin daher auch immer noch auf der NPM-Version (1.0.1)

**Comment by foxthefox** [comment]
Ich kann die Ursache nicht wirklich ergründen.
An dem Mechanismus des Einloggens hat sich nichts geändert, nur die Randbedingungen des iobrokers.
Übrigens ist jetzt 1.1.3 auf npm und 1.1.4 kommt bald, wegen Rolladensteuerung.

**Comment by nob0dy80** [comment]
Ich hab nur die schaltbaren Steckdosen. Da es nichts sicherheitsrelevantes gibt, gibts auch kein Grund für ein Update.
Da das Problem bei erst >0.1.4 auftrat und durch eine Neuinstallation des Iobrokers behoben ist, wird vermutlich irgendwo bei einem Update was altes über bleiben, was diese Probleme verursacht.

Aber ich würde das jetzt mal locker sehen. Scheint ja wirklich nur einen Promillebereich der User zu betreffen und dafür extra die Rahmenbedingungen auseinander zu nehmen ist wohl ein wenig zu viel des Guten. Inklusive mir zähle ich hier in dem Ticket nur 3 weitere User...in über einem halben Jahr.
