### ISSUE TITLE
Comfort Temp from comet thermostat is not read

### ISSUE THREAD

**Issue by pjo12345** [foxthefox/ioBroker.fritzdect#8]
Hello!
Great job! But I have a problem.
The comfort temperature of the Comet thermostat is not read out. Nothing appears in the Objects tab. So I can not use this temperature for scripts.

![objekte_fritzdect 0_li](https://user-images.githubusercontent.com/31406990/29771956-92f7c134-8bf6-11e7-885c-cc5ebecfde03.jpg)

Greetings pjo12345

**Comment by foxthefox** [comment]
please check updated version of github, I probably found the faulty spelled variable

**Comment by pjo12345** [comment]
Yes, it works. Thanks.

**Comment by foxthefox** [comment]
thanks for the feedback.
