### ISSUE TITLE
kommen keine signale an Fritz 301

### ISSUE THREAD

**Issue by exitus27** [foxthefox/ioBroker.fritzdect#81]
Hallo könnt ihr mir sagen welchen fritzdect Adapter ihr benutzt.
Über Objekte kann ich mein Zieltemperatur änder aber mein Thermostat bekommt kein Signal es bleibt so wie es ist ich kann es nur vor Ort verstellen .
Habe die Version 1.0.1  und 0.3.2 versucht beide gehen nicht.
welche version soll ich den nehmen??

**Comment by foxthefox** [comment]
beide Versionen sollten funktionieren.
Steht die Verbindung zur Fritzbox?Welche Anzeige kommt beim betätigen der Schaltfläche "Meine Geräte" im Adapter Admin?
Gibt es irgendwelche Auffälligkeiten im LOG, ggf. dort in debug Modus für den Adapter gehen.

**Comment by foxthefox** [comment]
habe soeben meinen raspi neu aufgesetzt,
js-ctrl ->3.1.4
admin->4.0.10
fritzdect -> 1.0.1

"Meine Geräte" wird ordnungsgemäß mit den DECT geräten befüllt

**Comment by sky-it** [comment]
bei mir funktioniert alles ohne Probleme
@exitus27 bedenke das das Thermostat bis zu 15 Minuten braucht, bis es den Sollwert übernimmt. Schau lieber in der Fritzbox nach ob der Wert angenommen wurde.

**Comment by foxthefox** [comment]
Ich denke issue kann geschlossen werden.
