### ISSUE TITLE
Fritz!DECT210 mit Version 04.17 value.power immer 0

### ISSUE THREAD

**Issue by lcars79** [foxthefox/ioBroker.fritzdect#84]
Die Außensteckdose Fritz!DECT210 in der Version 04.17 ist zwar steuerbar über ioBroker doch wenn die Steckdose an ist, bleibt der value.power Wert, also der Wert wo man sieht wie viel Watt Leistung abgegeben wird immer auf 0.
Das auslesen der anderen Steckdosen (Fritz!DECT200) in der Version 04.16 funktioniert dagegen zuverlässig.

Könnte es in der 04.17 Version eine Änderung gegeben haben? 

Nachtrag plötzlich geht es. D.h. hier zeigt ioBroker eher manchmal nur 0 Watt an wenn die Steckdose an ist. Das nur als Hinweis.

**Comment by foxthefox** [comment]
Das Abbild was von der Fritzbox kommt, ist immer gleich aufgebaut. Da sollte sich zwischen den Versionen nichts ändern, da das nach typen geht.
Allerdings kann ja mit der FW auch ein anderer Mechanismus greifen. Hier dann gleich mal die DEBUG Ausgabe anstarren und im JSON nach dem Wert suchen. Höchstwahrscheinlich kommt da schon eine 0 von der Fritzbox an.

**Comment by foxthefox** [comment]
Passiert es immer noch? Was zeigt das DEBUG (Meine Geräte) aus dem fritzdect.admin?

**Comment by lcars79** [comment]
Ich habe die Steckdose momentan nicht im Einsatz daher kann ich es dir nicht sagen. Mir war es nur aufgefallen, dass ich den Energieverbrauch nicht auslesen konnte und die Version der einzige Unterschied zu den anderen Steckdosen war wo es ging.

**Comment by foxthefox** [comment]
da ich der Meinung bin, daß es an den Daten der Fritzbox hängt, bitte dies mal beobachten, wenn es wieder geht.
Selbst in der neuen Version 2.x sollte hier nichts ändern sein.
gern mal testen.
