### ISSUE TITLE
Unterstützung für Fritz!DECT 440

### ISSUE THREAD

**Issue by Jack-RK-24** [foxthefox/ioBroker.fritzdect#85]
Bitte bei Gelegenheit ebenfalls Unterstützung für die neuen FD-440 hinzufügen.
Falls das schonmal weiterhelfen sollte, hier die Debug Ausgabe des aktuellen Adapters für 2 Stück FD440:

{"identifier":"099950402089","id":"58","functionbitmask":"288","fwversion":"05.05","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Wintergarten","battery":"80","batterylow":"0","temperature":{"celsius":"310","offset":"0"},"button":[{"identifier":"09995 0402089-1","id":"5024","name":"FT-Wintergarten: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0402089-3","id":"5025","name":"FT-Wintergarten: Unten rechts","lastpressedtimestamp":""},{"identifier":"09995 0402089-5","id":"5026","name":"FT-Wintergarten: Unten links","lastpressedtimestamp":""},{"identifier":"09995 0402089-7","id":"5027","name":"FT-Wintergarten: Oben links","lastpressedtimestamp":""}]},{"identifier":"099950402933","id":"56","functionbitmask":"288","fwversion":"05.05","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Wohnzimmer","battery":"80","batterylow":"0","temperature":{"celsius":"255","offset":"0"},"button":[{"identifier":"09995 0402933-1","id":"5016","name":"FT-Wohnzimmer: Oben rechts","lastpressedtimestamp":"1596888265"},{"identifier":"09995 0402933-3","id":"5017","name":"FT-Wohnzimmer: Unten rechts","lastpressedtimestamp":""},{"identifier":"09995 0402933-5","id":"5018","name":"FT-Wohnzimmer: Unten links","lastpressedtimestamp":""},{"identifier":"09995 0402933-7","id":"5019","name":"FT-Wohnzimmer: Oben links","lastpressedtimestamp":""}]},

Danke

**Comment by roadie33** [comment]
Die Schaltflächen werden angezeigt. Leider fehlt die Temperatur. Diese würde ich gerne in einer Datenbank aufzeichnen und in einem Skript verarbeiten:
![grafik](https://user-images.githubusercontent.com/58664090/95651996-373a6480-0aee-11eb-898d-d41afadfd6bf.png)

**Comment by jhartlep** [comment]
Habe noch einen Fehler im Zusammenhang mit der DECT 440 gefunden:

Hier der JSON-Abschnitt der Debug-Ausgabe
`
{
    "identifier": "1234567890",
    "id": "23",
    "functionbitmask": "288",
    "fwversion": "05.07",
    "manufacturer": "AVM",
    "productname": "FRITZ!DECT 440",
    "present": "1",
    "txbusy": "0",
    "name": "Wohnzimmer-Zentrale",
    "battery": "100",
    "batterylow": "0",
    "temperature": {
        "celsius": "270",
        "offset": "0"
    },
    "button": [
        {
            "identifier": "12345 67890-1",
            "id": "5000",
            "name": "Wohnzimmer-Zentrale: Oben rechts",
            "lastpressedtimestamp": "1605781868"
        },
        {
            "identifier": "12345 67890-2",
            "id": "5001",
            "name": "Wohnzimmer-Zentrale: Unten rechts",
            "lastpressedtimestamp": "1605780940"
        },
        {
            "identifier": "12345 67890-3",
            "id": "5002",
            "name": "Wohnzimmer-Zentrale: Unten links",
            "lastpressedtimestamp": "1605780940"
        },
        {
            "identifier": "12345 67890-4",
            "id": "5003",
            "name": "Wohnzimmer-Zentrale: Oben links",
            "lastpressedtimestamp": "1605780940"
        }
    ]
}
`

Bei den Objekten wird dann aber der state **lastclick** nicht korrekt gesetzt. Dort steht bei mir "Invalid Date"

Adapter-Version 0.3.2

Weiter eine andere Frage:
Liefert die Debug-Ausgabe das vollständige JSON, was AVM über die Schnittstelle ausliefert?
Ich würde nämlich gerne die Schalter nicht in der FB, sondern im ioBroker belegen.

**Comment by Jack-RK-24** [comment]
Nach dem aktuellsten Beta-Update der FB (7590) und der DECT 440 auf die v5.10 unterstützen diese auch Werte für die Luftfeuchtigkeit. Weiterhin wäre es auch für die Übersichtlichkeit wesentlich sinnvoller nicht einzelne Objekte für jeden einzelnen Schalter zu haben, sondern diese als logische Unterobjekte zum jeweiligen Gerät zugeordnet, sowie natürlich zusätzlich die noch fehlenden Werte. Debug-Ausgabe nach Firmware-Update auf 5.10:
{"identifier":"099950402089","id":"58","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Wintergarten","battery":"60","batterylow":"0","temperature":{"celsius":"200","offset":"0"},"humidity":{"rel_humidity":"50"},"button":[{"identifier":"09995 0402089-1","id":"5020","name":"FT-Wintergarten: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0402089-3","id":"5021","name":"FT-Wintergarten: Unten rechts","lastpressedtimestamp":"1605782389"},{"identifier":"09995 0402089-5","id":"5022","name":"FT-Wintergarten: Unten links","lastpressedtimestamp":""},{"identifier":"09995 0402089-7","id":"5023","name":"FT-Wintergarten: Oben links","lastpressedtimestamp":""}]},{"identifier":"099950402933","id":"56","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Wohnzimmer","battery":"60","batterylow":"0","temperature":{"celsius":"185","offset":"0"},"humidity":{"rel_humidity":"52"},"button":[{"identifier":"09995 0402933-1","id":"5012","name":"FT-Wohnzimmer: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0402933-3","id":"5013","name":"FT-Wohnzimmer: Unten rechts","lastpressedtimestamp":""},{"identifier":"09995 0402933-5","id":"5014","name":"FT-Wohnzimmer: Unten links","lastpressedtimestamp":"1605727666"},{"identifier":"09995 0402933-7","id":"5015","name":"FT-Wohnzimmer: Oben links","lastpressedtimestamp":""}]},

**Comment by foxthefox** [comment]
> Habe noch einen Fehler im Zusammenhang mit der DECT 440 gefunden:
> 
> Hier der JSON-Abschnitt der Debug-Ausgabe
> `{ "identifier": "1234567890", "id": "23", "functionbitmask": "288", "fwversion": "05.07", "manufacturer": "AVM", "productname": "FRITZ!DECT 440", "present": "1", "txbusy": "0", "name": "Wohnzimmer-Zentrale", "battery": "100", "batterylow": "0", "temperature": { "celsius": "270", "offset": "0" }, "button": [ { "identifier": "12345 67890-1", "id": "5000", "name": "Wohnzimmer-Zentrale: Oben rechts", "lastpressedtimestamp": "1605781868" }, { "identifier": "12345 67890-2", "id": "5001", "name": "Wohnzimmer-Zentrale: Unten rechts", "lastpressedtimestamp": "1605780940" }, { "identifier": "12345 67890-3", "id": "5002", "name": "Wohnzimmer-Zentrale: Unten links", "lastpressedtimestamp": "1605780940" }, { "identifier": "12345 67890-4", "id": "5003", "name": "Wohnzimmer-Zentrale: Oben links", "lastpressedtimestamp": "1605780940" } ] }`
> 
> Bei den Objekten wird dann aber der state **lastclick** nicht korrekt gesetzt. Dort steht bei mir "Invalid Date"
> 
> Adapter-Version 0.3.2
> 
> Weiter eine andere Frage:
> Liefert die Debug-Ausgabe das vollständige JSON, was AVM über die Schnittstelle ausliefert?
> Ich würde nämlich gerne die Schalter nicht in der FB, sondern im ioBroker belegen.

Ja, der Inhalt in dem JSON string ist das, was die fritzbox an Antwort liefert

**Comment by foxthefox** [comment]
> Nach dem aktuellsten Beta-Update (07.24-83655 BETA) der FB 7590 und der DECT 440 auf die v5.10 unterstützen diese auch Werte für die Luftfeuchtigkeit. Weiterhin wäre es auch für die Übersichtlichkeit wesentlich sinnvoller nicht einzelne Objekte für jeden einzelnen Schalter zu haben, sondern diese als logische Unterobjekte zum jeweiligen Gerät zugeordnet, sowie natürlich zusätzlich die noch fehlenden Werte. Debug-Ausgabe nach Firmware-Update auf 5.10:
> {"identifier":"099950402089","id":"58","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Wintergarten","battery":"60","batterylow":"0","temperature":{"celsius":"200","offset":"0"},"humidity":{"rel_humidity":"50"},"button":[{"identifier":"09995 0402089-1","id":"5020","name":"FT-Wintergarten: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0402089-3","id":"5021","name":"FT-Wintergarten: Unten rechts","lastpressedtimestamp":"1605782389"},{"identifier":"09995 0402089-5","id":"5022","name":"FT-Wintergarten: Unten links","lastpressedtimestamp":""},{"identifier":"09995 0402089-7","id":"5023","name":"FT-Wintergarten: Oben links","lastpressedtimestamp":""}]},{"identifier":"099950402933","id":"56","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Wohnzimmer","battery":"60","batterylow":"0","temperature":{"celsius":"185","offset":"0"},"humidity":{"rel_humidity":"52"},"button":[{"identifier":"09995 0402933-1","id":"5012","name":"FT-Wohnzimmer: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0402933-3","id":"5013","name":"FT-Wohnzimmer: Unten rechts","lastpressedtimestamp":""},{"identifier":"09995 0402933-5","id":"5014","name":"FT-Wohnzimmer: Unten links","lastpressedtimestamp":"1605727666"},{"identifier":"09995 0402933-7","id":"5015","name":"FT-Wohnzimmer: Oben links","lastpressedtimestamp":""}]},

Die Debug Ausgabe hilft schon mal enorm weiter, weil ich kein DECt440 besitze. DANKE
Beim Datum muss ich dann wohl noch etwas nachbessern.

**Comment by foxthefox** [comment]
Nach dem update 5.10 kam ja folgendes raus:

"identifier":"099950402089","id":"58","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440"

sehr komisch, weil die Funktionbitmask, so gar nicht passt. Ist das immer noch so?

Unterobjekte zu bilden ist möglich, braucht aber einen umfassenderen Umbau, da dann Adressen in 2 verschiedenen Stellen stehen. Für Dinge wie DECT440 wo nur empfangen wird, ist es eher machbar, da nichts bedient wird.

**Comment by Jack-RK-24** [comment]
Sieht aktuell immer noch so aus:
{"identifier":"099950402089","id":"58","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Wintergarten","battery":"60","batterylow":"0","temperature":{"celsius":"185","offset":"0"},"humidity":{"rel_humidity":"41"},"button":[{"identifier":"09995 0402089-1","id":"5020","name":"FT-Wintergarten: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0402089-3","id":"5021","name":"FT-Wintergarten: Unten rechts","lastpressedtimestamp":"1607584399"},{"identifier":"09995 0402089-5","id":"5022","name":"FT-Wintergarten: Unten links","lastpressedtimestamp":"1607621812"},{"identifier":"09995 0402089-7","id":"5023","name":"FT-Wintergarten: Oben links","lastpressedtimestamp":""}]},{"identifier":"099950402933","id":"56","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Wohnzimmer","battery":"60","batterylow":"0","temperature":{"celsius":"205","offset":"0"},"humidity":{"rel_humidity":"41"},"button":[{"identifier":"09995 0402933-1","id":"5012","name":"FT-Wohnzimmer: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0402933-3","id":"5013","name":"FT-Wohnzimmer: Unten rechts","lastpressedtimestamp":"1607445281"},{"identifier":"09995 0402933-5","id":"5014","name":"FT-Wohnzimmer: Unten links","lastpressedtimestamp":"1607717879"},{"identifier":"09995 0402933-7","id":"5015","name":"FT-Wohnzimmer: Oben links","lastpressedtimestamp":""}]},{"identifier":"099950402931","id":"55","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Kinderzimmer","battery":"60","batterylow":"0","temperature":{"celsius":"195","offset":"0"},"humidity":{"rel_humidity":"42"},"button":[{"identifier":"09995 0402931-1","id":"5008","name":"FT-Kinderzimmer: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0402931-3","id":"5009","name":"FT-Kinderzimmer: Unten rechts","lastpressedtimestamp":""},{"identifier":"09995 0402931-5","id":"5010","name":"FT-Kinderzimmer: Unten links","lastpressedtimestamp":""},{"identifier":"09995 0402931-7","id":"5011","name":"FT-Kinderzimmer: Oben links","lastpressedtimestamp":""}]},{"identifier":"099950402585","id":"57","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Bad","battery":"60","batterylow":"0","temperature":{"celsius":"195","offset":"0"},"humidity":{"rel_humidity":"43"},"button":[{"identifier":"09995 0402585-1","id":"5016","name":"FT-Bad: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0402585-3","id":"5017","name":"FT-Bad: Unten rechts","lastpressedtimestamp":""},{"identifier":"09995 0402585-5","id":"5018","name":"FT-Bad: Unten links","lastpressedtimestamp":""},{"identifier":"09995 0402585-7","id":"5019","name":"FT-Bad: Oben links","lastpressedtimestamp":""}]},{"identifier":"099950401992","id":"53","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440","present":"1","txbusy":"0","name":"FT-Schlafzimmer","battery":"60","batterylow":"0","temperature":{"celsius":"205","offset":"0"},"humidity":{"rel_humidity":"45"},"button":[{"identifier":"09995 0401992-1","id":"5000","name":"FT-Schlafzimmer: Oben rechts","lastpressedtimestamp":""},{"identifier":"09995 0401992-3","id":"5001","name":"FT-Schlafzimmer: Unten rechts","lastpressedtimestamp":""},{"identifier":"09995 0401992-5","id":"5002","name":"FT-Schlafzimmer: Unten links","lastpressedtimestamp":"1607119825"},{"identifier":"09995 0401992-7","id":"5003","name":"FT-Schlafzimmer: Oben links","lastpressedtimestamp":""}]},

FritzBox 7590 FW 07.24-84159 BETA
FD440 FW 5.10
Iobroker Adapter v.1.1.0

**Comment by foxthefox** [comment]
immerhin funktioniert die neueste Version noch ;-)
Danke für die Rückmeldung

**Comment by foxthefox** [comment]
mit der jetzigen Version 1.1.0 sollte es mit Temperatur und Feuchtigkeit funktionieren.
Aber es schreit nach einem Umbau, weil die functionbitmask eher support als eine führende Rolle einnimmt.
Wenn möglich, bitte mal testen.

**Comment by Jack-RK-24** [comment]
OK, Update gerade gemacht, zur Sicherheit den gesamten Objektbaum danach bei gestopptem Adapter komplett gelöscht, damit er neu aufgebaut wird. Sehe keinen wirklichen Unterschied und auch die beiden Werte sind nicht da, dafür haut er die Objektbezeichner etwas durcheinander (mal mit mal ohne Leerzeichen):
![screenshot](https://user-images.githubusercontent.com/63138075/101983719-225c8780-3c7d-11eb-95ab-0d2fa27d0229.PNG)

Dafür schmeißt der Adapter beim Start 2 Fehlermeldungen die im laufenden Betrieb nicht mehr kommen (muss ich nochmal unter debug schauen, nur da wird das log ätzend lang):
![screenshot2](https://user-images.githubusercontent.com/63138075/101983775-62bc0580-3c7d-11eb-9fb5-4593d3079ff2.PNG)

**Comment by foxthefox** [comment]
Ich glaube die Meldung kommt, weil die Fritzbox ein leeres Telegramm geschickt hat.

Eigentlich hätte ich noch die DECT440 Einträge erwartet mit temp und humid.
Die Buttons ohne Leerzeichen sind überflüssig. Die muß ich rausbauen.
und die Leerzeichen  bei den anderen Buttons muß ich mich noch kümmern.

**Comment by Jack-RK-24** [comment]
Nupp, irgendwie ist der Wurm drin. Wenn ich auf die 1.0.1 zurück gehe ist die Meldung beim starten weg, sonst kommt sie reproduzierbar jedes mal beim starten. Außerdem sind diverse Steckdosen und Thermostate verschwunden. Hab mal für beide Versionen das log auf debug, die Objekte als json, und die Geräte, Gruppen, Templates Ausgaben gezogen, vielleicht hilfts was:
[v.1.0.1.zip](https://github.com/foxthefox/ioBroker.fritzdect/files/5683225/v.1.0.1.zip)
[v1.1.0_actual_version.zip](https://github.com/foxthefox/ioBroker.fritzdect/files/5683227/v1.1.0_actual_version.zip)

**Comment by foxthefox** [comment]
Danke. Muss ja an den letzten Änderungen liegen. Soll ja ohne Fehlermeldung anlaufen

**Comment by foxthefox** [comment]
jetzt sollte es laufen, bitte testen

**Comment by Jack-RK-24** [comment]
Ja schaut sehr gut aus, keine Fehlermeldung mehr beim Start, es sind alle Devices da wo sie hingehören und das 440er Objekt hat alle schicken Werte (Temp, Hum., Bat, etc p.p.). Super!

**Comment by foxthefox** [comment]
Danke. Dann kommt demnächst der breaking change mit Umstrukturierung
