### ISSUE TITLE
Backup on Fresh installation causes an error

### ISSUE THREAD

**Issue by Dragon0501** [foxthefox/ioBroker.fritzdect#88]
![fritzdect](https://user-images.githubusercontent.com/59663011/98072542-8e6df380-1e66-11eb-9776-1af084c84a28.png)
log of Adapter start. Some Ideas? Password and username is correct. 
Adapter Version 0.3.2
![2020-11-04 06_26_36-Window](https://user-images.githubusercontent.com/59663011/98072655-cb39ea80-1e66-11eb-85d2-2e9c82dc175f.png)

**Comment by Ilovegym66** [comment]
Hast du in der Config auch ne URL eingetragen, also http:// vor der IP Adresse? Der Programmierer hat leider dort als Beschreibung IP angegeben, dabei muss die URL rein..  und das ist nicht das gleiche :-)

**Comment by Dragon0501** [comment]
![2020-11-04 07_09_50-Window](https://user-images.githubusercontent.com/59663011/98075486-c4ae7180-1e6c-11eb-8c76-6abf1cfd864d.png)
Anderer Fehler aber immer noch ein Problem...

**Comment by Dragon0501** [comment]
gelöst! Vielen Dank!
