### ISSUE TITLE
Auto mode nicht mehr einstellbar

### ISSUE THREAD

**Issue by Dragon0501** [foxthefox/ioBroker.fritzdect#89]
Habe vier Dect Thermostate an der Fritzbox. Die EInstellung von Mode 1 und zwei funkrioniert, also auf und zu, aber bei einer 0 für auto gibt er einen Fehler aus und schreibt ihn nicht. Ich habe keine Ahnung woran das liegt...

`

fritzdect.0 | 2020-11-10 17:49:04.000 | info | (3773) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
fritzdect.0 | 2020-11-10 17:49:03.997 | info | (3773) terminating
fritzdect.0 | 2020-11-10 17:49:03.990 | info | (3773) cleaned everything up...
fritzdect.0 | 2020-11-10 17:49:03.989 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
fritzdect.0 | 2020-11-10 17:49:03.989 | error | at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
fritzdect.0 | 2020-11-10 17:49:03.989 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
fritzdect.0 | 2020-11-10 17:49:03.989 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:608:33
fritzdect.0 | 2020-11-10 17:49:03.989 | error | at /opt/iobroker/node_modules/iobroker.fritzdect/main.js:137:47
fritzdect.0 | 2020-11-10 17:49:03.989 | error | (3773) TypeError: Cannot read property 'val' of null
fritzdect.0 | 2020-11-10 17:49:03.987 | error | (3773) uncaught exception: Cannot read property 'val' of null
fritzdect.0 | 2020-11-10 17:49:03.979 | info | (3773) Comet ID: 119610662952 identified for command (mode) : 0
fritzdect.0 | 2020-11-10 17:48:12.738 | info | (3773) setting up Thermostat/DECT3xx object Badezimmer
fritzdect.0 | 2020-11-10 17:48:12.725 | info | (3773) setting up Thermostat/DECT3xx object Schlafzimmer
fritzdect.0 | 2020-11-10 17:48:12.711 | info | (3773) setting up Thermostat/DECT3xx object Wohnzimmer rechts
fritzdect.0 | 2020-11-10 17:48:12.690 | info | (3773) setting up Thermostat/DECT3xx object Wohnzimmer links
fritzdect.0 | 2020-11-10 17:48:12.688 | info | (3773) create Devices 4
fritzdect.0 | 2020-11-10 17:48:12.180 | info | (3773) Talking to FritzBox with firmware: 07.21

`

**Comment by foxthefox** [comment]
ich kann den Fehler nicht reproduzieren, passiert er immer noch?
was sind die Randbedingungen (Versionen SW und Geräte)
Bei mir funktioniert es mit fritzdect 1.1.3, iobroker 3.1.4 und admin 4.0.10

**Comment by Dragon0501** [comment]
Problem gelöst. Fehler nicht mehr reproduzierbar.
