### ISSUE TITLE
changelog  - 2 times "ON"

### ISSUE THREAD

**Issue by DDDanny** [foxthefox/ioBroker.fritzdect#9]
Hi Fox,
good work with this module - so I don't have to start by 0 as with my current python based integration ;)
I guess you have a copy n paste typo @ the changelog ;-)

...for ON
and in next line ...for OFF

> 0.0.9
> values '1' accepted for ON
> values '0' accepted for ON
> 
> 0.0.8
>  
> values 1/true/on/ON accepted for ON
> values 0/false/off/OFF accepted for ON

B.R.
Danny

**Comment by foxthefox** [comment]
...corrected.
Thank you
