### ISSUE TITLE
Think about changes in FritzOS higher 7.24 

### ISSUE THREAD

**Issue by Ilovegym66** [foxthefox/ioBroker.fritzdect#95]
Hi,
not a bug, but from FritzOS 7.24 and higher the API should be changed with the login:
https://avm.de/fritz-labor/frisch-aus-der-entwicklung/bekannte-probleme/

**Comment by foxthefox** [comment]
Thanks for the information, I didn't know such upcoming changes.
I will try to keep on track.

**Comment by Ilovegym66** [comment]
fine, so we can close this issue here. Thanks!
