### ISSUE TITLE
Ständige Fehlermeldungen im Log

### ISSUE THREAD

**Issue by Heartblood76** [foxthefox/ioBroker.fritzdect#96]
Der Adapter verbindet sich mit der FritzBox und schreibt nach kurzer Zeit ununterbrochen Fehlermeldungen ins Log. In der Fritzbox wird ebenso ein log wegen (angeblich) falschem Passwort erzeugt.

log in ioBroker
`
fritzdect.0 | 2020-12-17 15:28:30.497 | error | (6157) Did not get session id- invalid username or password?
-- | -- | -- | --
fritzdect.0 | 2020-12-17 15:28:30.497 | error | (6157) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-12-17 15:28:30.167 | error | (6157) Did not get session id- invalid username or password?
fritzdect.0 | 2020-12-17 15:28:30.167 | error | (6157) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-12-17 15:28:29.845 | error | (6157) Did not get session id- invalid username or password?
fritzdect.0 | 2020-12-17 15:28:29.845 | error | (6157) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-12-17 15:28:29.185 | error | (6157) Did not get session id- invalid username or password?
fritzdect.0 | 2020-12-17 15:28:29.184 | error | (6157) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-12-17 15:28:27.105 | error | (6157) Did not get session id- invalid username or password?
fritzdect.0 | 2020-12-17 15:28:27.104 | error | (6157) fritzbox returned this "0000000000000000"
fritzdect.0 | 2020-12-17 15:28:25.834 | error | (6157) Did not get session id- invalid username or password?

`

log in der Fritzbox
`
17.12.20
15:31:24
Anmeldung des Benutzers admin an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.100.4.
17.12.20
15:31:04
Anmeldung des Benutzers ioBroker an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.99.200 gescheitert (falsches Kennwort). [46 Meldungen seit 17.12.20 13:52:58]
17.12.20
13:50:50
Anmeldung des Benutzers ioBroker an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.99.200 gescheitert (falsches Kennwort).
17.12.20
13:48:28
Anmeldung des Benutzers ioBroker an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.99.200 gescheitert (falsches Kennwort). [4 Meldungen seit 17.12.20 13:41:55]
17.12.20
13:39:36
Anmeldung des Benutzers ioBroker an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.99.200 gescheitert (falsches Kennwort). [8 Meldungen seit 17.12.20 13:24:27]
17.12.20
13:22:17
Anmeldung des Benutzers ioBroker an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.99.200 gescheitert (falsches Kennwort). [2 Meldungen seit 17.12.20 13:20:08]`

Während der Adapter läuft und die Fehlermeldungen produziert ist ein Zugriff auf die Weboberfläche der Fritzbox nicht möglich.

Gruß Heartblood76

**Comment by foxthefox** [comment]
So wie es aussieht, ist der update cycle zu kurz gesetzt und es wird versucht sich zu oft an der Fritzbox anzumelden.
Im admin des Adapters mal wieder die 300 eintragen (entspricht 5min). und ggf. die fritzbox zusätzlich durchbooten.

**Comment by Heartblood76** [comment]
Das Updateintervall hatte ich bereits auf 900 (15 Minuten) gesetzt. Ich starte die Fritzbox mal neu und beobachte, werde dann Rückmeldung geben.

**Comment by foxthefox** [comment]
wurden timeout callback korrekt beendet?
Ich würde gern weiterhelfen, weiß aber noch nicht wo ich ansetzen soll.
Selbst im info-log müsste der Adapter Befehle die erkannt werden im log ausgeben.
Hier wäre evtl. mal zu kontrollieren, was dort in der Zwischenzeit dort geloggt wird, bevor es zudem Volllaufen kommt.
Irgendwie müssen die vielen logins ja getriggert werden.

**Comment by Heartblood76** [comment]
Erstmal vielen Dank! Ich werde nachher mal den Adapter starten und das Log aufzeichnen und hier posten. Wären sonst noch weitere Infos hilfreich?

**Comment by foxthefox** [comment]
naja, Iobroker version von admin und js eventuell.

**Comment by Heartblood76** [comment]
So, hier mal das Log und weitere Infos.

ioBroker NPM 7.0.15
Node.js 15.4.0
Admin 4.1.11
Fritzdect 1.1.3

[2020-12-19_log_iobroker.txt](https://github.com/foxthefox/ioBroker.fritzdect/files/5719289/2020-12-19_log_iobroker.txt)

Ich hatte zuerst nur die Versionen Installiert, welche ich direkt über ioBroker installieren kann. Dann traten die Fehler auf und ich habe Updates insbesondere von fritzdect gemacht. Habe die Version von GitHub genommen. Leider auch mit den selben Fehlern. Gleiches gilt entsprechend für Node.js. War zuerst auf der 12er Version mit Fehlern, mit der 15er Version ebenso Fehler.

**Comment by foxthefox** [comment]
Im adapter gibt es eine Nachführung des "mode" wenn über die Temperaturvorgabe geändert wird.
Diese Nachführung hatte ein ACK=false was wieder einen Befehl auslöst, höchstwahrscheinlich ist das die Ursache.

Habe ich in GitHub verbessert, wäre gut es nochmal zu testen.
Am besten Adapter deinstallieren und Fritzbox durchbooten und dann Adapter neu installieren.

**Comment by Heartblood76** [comment]
Leider habe ich immer noch den selben Fehler. Habe wie gewünscht den Adapter gestoppt, die Instanz gelöscht, den Adapter gelöscht, Fritzbox neu gestartet, Adapter über GitHub neu installiert und eine Instanz hinzugefügt. Kurz nach dem Start kamen leider wieder die selben Fehlermeldungen. Die Instanz ist allerdings dieses Mal auf gelb umgesprungen, blieb vorher immer grün.

Außer dem fritzdect adapter habe ich noch den tr-64 und den fb-checkpresence, beide laufen ohne Probleme. Kommen die sich ggf. in die Quere?

**Comment by Ilovegym66** [comment]
Ich habe auch alle drei Adapter gleichzeitig laufen, habe für jeden Adapter einen User angelegt.

**Comment by Heartblood76** [comment]
Ich benutze für fritzdect einen anderen Benutzer, damit ich im Log genauer in der Fritzbox analysieren kann "wer Probleme macht". Die beiden anderen Adapter benutzen den selben Benutzer und haben wie gesagt keine Probleme.

Was ich auch immer noch nicht verstehe, wieso werden die zwei DP "targettemp" ständig getriggert.

Hier ist das Blockly was ich geschrieben habe, es wird nur alle 15 Minuten geprüft. Oder habe ich was falsch gemacht?

![Screenshot_20201219_224521](https://user-images.githubusercontent.com/76169907/102700248-fe381200-424b-11eb-8838-ff28944a3ac4.png)

**Comment by Ilovegym66** [comment]
Du hast n Trigger im Trigger, damit meine ich das zweite ROTE Falls Objekt.. das muss ein BLAUES Falls Objekt... sein.. dann stimmts..!
So triggert das Rote dauernd deine Target Temp.. also das Script und der Adapter macht alles richtig :-)

**Comment by Heartblood76** [comment]
Oh man! Vielen Dank für den Hinweis. Jetzt läuft es einwandfrei.
