### ISSUE TITLE
Fritzdect API zu alt

### ISSUE THREAD

**Issue by julianraab** [foxthefox/ioBroker.fritzdect#97]
Hallo

Gerne würde ich einen Rollladenmotor über DECT steuern .. auslesen geht aber keine Funktion.
Lt. Hersteller wird hier noch der alte API benutzt 
FW: 07.21 der Fritzbox
![Unbenannt](https://user-images.githubusercontent.com/76208172/102607074-f8e1a700-4127-11eb-9de8-ab1fe105a505.jpg)

**Comment by foxthefox** [comment]
ich habe zwar schon die letzte API in Anwendung, aber Rolladen ist in der Spezifikation von AVM nur rudimentär erwähnt.
Darum meine Bitte.
Im admin des Adapters bitte auf den Button "Meine Geräte" klicken und den output mit bitte zukommen lassen.
Damit kann ich dann den Adapter erweitern.
Danke im Voraus.

**Comment by julianraab** [comment]
Hallo Fox,
leider bin ich halbblutiger Anfänger :-) Ich öffne die Instanz drücke auf Meine Geräte und sollte dann unter LOGS ein Screenshot machen habe ich das richtig verstanden?
Grüße

**Comment by foxthefox** [comment]
Das hilft weiter, super.
Noch eine Frage. Welche Bedienmöglichkeiten hat man in der FritzApp oder auf der Weboberfläche der Fritzbox?
- Anzeige 0-100%
- Vorgabe 0-100%?
- Befehl Auf/Stop/Zu?

**Comment by julianraab** [comment]
Hallo,

Bedienung auf ab und % Angabe siehe Screenshot
![Screenshot_1](https://user-images.githubusercontent.com/76208172/102685707-d2cd0d00-41e2-11eb-8915-8480c782329b.jpg)

**Comment by foxthefox** [comment]
sehr gut, also keine Vorgabe von % direkt! 
Prozent ist nur eine Anzeige, richtig?

**Comment by julianraab** [comment]
in der Fritzbox selber nein, in der APP kann man auch % fahren habe ich gerade getestet

**Comment by foxthefox** [comment]
OK, habe jetzt beides drin.
Version 1.1.4 kann man getestet werden

**Comment by julianraab** [comment]
leider komme ich nichtmehr rein 
Habe auch mal zum probieren Nutzer anmeldung ausgeschaltet 
![Screenshot_1](https://user-images.githubusercontent.com/76208172/102686204-46bce480-41e6-11eb-8fff-a2237bda0a4e.jpg)

**Comment by julianraab** [comment]
ich war kurz drin da die Werte sich aktualisiert haben bzw. ich des nun als blinds angezeigt bekomme .. nun taucht aber immer wieder die antwort auf invalid password *komisch*

**Comment by foxthefox** [comment]
unschön, aber das war halt kurz vor Frühstück mal reingehackt. Obwohl mit der Anmeldung eigentlich nichts passieren sollte.
Welche Version hat iobroker admin und js?

**Comment by julianraab** [comment]
admin ist 4.1.11
Node js ist 12.18.4

 du hättest natürlich erstmal frühstücken dürfen :-) ich habe keine Eile den Motor gibt es ja auch erst paar wochen.
vll hab auch ich irgendwo ein Fehler, hatte vorher schon anbundzu das Problem das sporadisches Login nicht möglich ist.

**Comment by foxthefox** [comment]
Also ich habs zwar unter node 10 am laufen, aber keine Probleme mit fritzbox login.
Kannst du bitte den adapter in den debug modus versetzen und neu starten?
Im Normalfall sollten dort viele Dinge zum erstellen der Objekte zu sehen sein, evtl. ist auch noch weiteres sichtbar.

Hast du Skripte am Laufen, die auf fritzdect zugreifen?
Wie schnell fragst du die fritzbox ab (die voreingestellten 5min)?

**Comment by julianraab** [comment]
hallo,

habe in den Einstellungen nichts geändert... habe über nacht den Motor weg gehabt und heute morgen gesehn das er sich versucht hatte einzuloggen.
Nun habe ich den Adapter neu gestartet und nach versuch 3 waren alle Objekte da und kann auch bedient werden 

alles sehr merkwürdig :-) 
Aber vielen Dank es funktioniert

**Comment by julianraab** [comment]
Hallo Hier mein Log, Adapter debugen weiß ich leider nicht wie es funktioniert.

Kein Skrit greift darauf ebenfalls die 5 min habe ich nicht umgestellt 
Gerne kann ich dir auch einen Teamviewer zum anschauen anbieten.
Bin leider noch nicht ganz fit in der Materie :-)

![Bild_2020-12-21_072615](https://user-images.githubusercontent.com/76208172/102746082-ce792f00-435d-11eb-9c11-e26451d8e8c2.png)

**Comment by julianraab** [comment]
habe es doch gefunden :-) 
![Bild_2020-12-21_074029](https://user-images.githubusercontent.com/76208172/102747049-cb7f3e00-435f-11eb-9ee0-c807e636349b.png)

**Comment by julianraab** [comment]
![Uploading Bild_2020-12-21_081725.png…]()

**Comment by foxthefox** [comment]
danke erstmal, ich muss scheinbar mal die js-controller 3.1.6 installieren

**Comment by foxthefox** [comment]
Was mir aufgefallen ist:

Ich habe bisher alles über den admin Zugang gemacht und dieser war im Heimnetz zugänglich, ohne Benutzerauswahl!

Werden eigene Benutzer für iobroker angelegt, dann brauchen diese nicht nur die Berechtigungen, sondern auch das Login über die Weboberfläche muß aktiviert sein.
Dazu sich natürlich bitte nicht aussperren, weil admin (mit allen Berechtigungen) ohne nochmal zusätzlich angelegt zu sein nicht angeboten wird!
ist die zweite Lasche neben dem Benutzer anlegen.
Also dies bitte mal prüfen und die Situation schildern wie es bei dir ist.

**Comment by foxthefox** [comment]
![userlogin](https://user-images.githubusercontent.com/16841643/102753462-9d9ff680-436b-11eb-825f-d80c6fc69e99.png)
![userpermissions](https://user-images.githubusercontent.com/16841643/102753468-a0025080-436b-11eb-9897-04579556323d.png)

**Comment by julianraab** [comment]
so wie gefordert aktiviert schon die ganze Zeit, Login über Weboberfläche funktioniert auch 

![Bild_2020-12-21_091701](https://user-images.githubusercontent.com/76208172/102754436-4864e480-436d-11eb-97e9-25d5c9677b5b.png)
![Unbenannt](https://user-images.githubusercontent.com/76208172/102754447-4bf86b80-436d-11eb-887c-69a78d35eb12.jpg)

**Comment by julianraab** [comment]
Es ist komisch manchmal bekommt er ja auch die Info bzw kann schalten .. zu 95% nicht ... einloggen war erst heute n8 irgendwann möglich lt. Log.
Wenn ich aber neu Starte geht es nicht

**Comment by foxthefox** [comment]
woher kommen denn die Befehle? Hast du den Moment abgepasst um sie zu schicken?
Läuft noch ein anderer Adapter, der mit der Fritzbox arbeitet z.B. tr-064?
steht vor den errors immer die debug Meldung "polling! fritzdect is alive"?
Die debug Meldung wird vor jedem Abholen des Status geschrieben (alle 5min).
So wie ich es verstehe, passiert das nur sporadisch und nicht alle 5min.
arbeitet iobroker über WLAN? Ändert sich da etwas während der Nacht?

**Comment by julianraab** [comment]
ich habe den TR64 abgeschaltet am Wochenende schon da ich gelesen hatte das es Probleme geben kann.
den Befehl habe ich Manuel im IObroker gegeben sprich 30% fahren und dann doch lieber 80% und da kommt die Meldung invaild Password
IObroker läuft auf dem NUC im LAN 
Bezüglich des Zugangs kann ich nichtz auf admin schalten dieser ist nicht in der Liste nur meine Benutzer.

Bei Befehl zu schnell senden gibt es nicht wirklich ein log ausser das falsche Password

Vor den Errors steht immer polling! fritzdect is alive

**Comment by julianraab** [comment]
so scheinbar geht es nun habe VPN rausgenommen und zugang aus dem Internet auch :-)

na nun schauen wir mal .. fals es neuigkeiten gibt melde ich mich.

**Comment by foxthefox** [comment]
die Abfrage ist nur zum aktualisieren von Werten, die entweder eingesammelt (Energieverbrauch) oder durch externer Schalthandlungen aktualisiert werden müssen.

Befehle gehen unabhängig davon und direkt.
Bei der Vorgabe vom Level gibt es 2 Werte! einmal level mit Wertebereich 0-255 und level percent 0-100%.
Die sollten eigentlich halbwegs exakt funktionieren.

**Comment by julianraab** [comment]
Ok wenn es nur zum Abfragen ist stimmt was nicht... nun nach Stunden und Bedienung über VIS Shutter Kontroll (was heute mittag funktionierte) kommt folgender LOG und geht wieder nicht ...

Ich verstehe es leider nicht ... wenn es nicht geht baue ich halt doch normale Motoren ein ... ich dachte nur es wäre einfacher ohne nochmals etwas zwischen rein zu bauen 
![Screenshot_1](https://user-images.githubusercontent.com/76208172/102808201-45471400-43c0-11eb-8efe-a5f6934431f2.jpg)

**Comment by foxthefox** [comment]
es ist schon komisch, daß 2 min nach dem letzten polling, die Fritzbox nicht mehr mag.

im adapter config hast du die IP Adresse der Fritzbox drin stehen, richtig?
Und die Fritzbox ist noch bei 7.21, richtig?
schonmal im log der Fritzbox geschaut was dort drin steht?

das mit der fritzbox und Rollläden muß klappen, mit der fritz APP gehts ja auch, oder?

durch irgendetwas scheint die Fritzbox spontan nicht zu mögen (update und Befehl benutzt den gleichen login Mechanismus).

wie oft hattest du die fritzbox schon durchgebootet?
hattest du den fritzdect Adapter schonmal komplett gelöscht und danach neu installiert?

PS. der admin war bei mir auch nicht bei den Benutzern dabei, aber den hatte ich dann nochmal angelegt. Vor dem Umschalten auf Login mit Benutzernamen hatte die Fritzbox mich immer direkt nach dem admin PW gefragt.
Es sollte nicht am login liegen, aber man weiß ja nie.

**Comment by julianraab** [comment]
im Adapter habe ich aktuell die IP habe es auch schon mit fritz.box probiert 
Fritzbox ist noch auf 07.21.
Fritzbox schon mehrfach neu gestartet ebenfalls IObroker Adapter wurde gelöscht und neu aufgespielt zwangsweise da wechsel von PI auf NUC 

APP geht dauerhaft 
ADMIN muss ich heute Mittag mal hinzufügen wieder
![Unbenannt](https://user-images.githubusercontent.com/76208172/102849201-f4aed580-4416-11eb-9d7f-b238763e473e.jpg)

**Comment by foxthefox** [comment]
was mir auffällt, es gibt unterschiedliche Anmeldeversuche von IPv4 und IPv6.
Die von IPv6 gehen immer schief. Beides scheint iobroker zu sein, oder die IPv6 benutzt auch den gleichen Anmeldenamen "dect".
Verwunderlich ist die unterschiedliche Nutzung der IP, so etwas hab ich beim Raps nicht im fritzbox log.
ich weiß ja nicht, inwieweit zwischendrin nochmal Befehle gegeben wurde, aber es sind teilweise ein paar mehr als die ca. 5min Intervalle.

**Comment by julianraab** [comment]
läuft alles auf einem NUC raspi ist ausgeschaltet ... habe nun in der Fritzbox mal die IPv6 ausgestellt da ich leider nicht weiß wie es unter Proxmox auszuschalten geht.
Dect wird ausschließlich im IObroker dür Fritzdect benutzt.

Kann natürlich den Raspi der noch konfiguriert ist mal dazu nutzen um den fritzadapter zu starten und am nuc ausstellen.

**Comment by julianraab** [comment]
so nach langem Suchen habe ich herausgefunden das auch meine Homematic steuerung darauf zugegriffen hatte (versuch) hatte da aber keine Logindaten hinterlegt habe das nun mal ausgeschaltet und beobachte den Log der Fritzbox

**Comment by foxthefox** [comment]
> so nach langem Suchen habe ich herausgefunden das auch meine Homematic steuerung darauf zugegriffen hatte (versuch) hatte da aber keine Logindaten hinterlegt habe das nun mal ausgeschaltet und beobachte den Log der Fritzbox

dann hoffe ich mal, das das die Ursache war. Die Fritzbox akzeptiert einige fehlgeschlagene Anmeldeversuche, dann blockiert sie aber mit immer mehr Zeit die Anfragen und man kommt nicht mehr durch.

**Comment by julianraab** [comment]
Also ... ich habe es nun beobachtet, nachdem ich die Homematic ausgenommen habe funktioniert alles bestens 

Vielen Dank dann kann ich das Produkt auch verbauen und evtl auch an die Kunden bringen.

Gutes neues Jahr noch

**Comment by foxthefox** [comment]
das freut mich, das es geht!
Falls möglich auch gleich mal die 2.0.0 testen :-)

**Comment by julianraab** [comment]
was hast du den gemacht? .. also Motor geht allerdings nun unter neuem Datenpunkt

**Comment by foxthefox** [comment]
habe komplett alles umgestellt, verwende nun die Datenpunkte die die Fritzbox liefert und nicht irgendwelche selbst ausgedachten. Das macht das update polling einfacher.
Bzgl. Rolladen hat sich eigentlich nichts geändert, außer daß evtl ein Datenbüunkt mit state und lastchgrtimestamp nun dabei ist.

und ja die Datenpunktbezeichnung ist nun immer DECT_xxxx.
Als ich den Adapter anfing gab es nur die Steckdose DECT200 und Comet (jetzt DECT3xx) das wird nun nicht mehr hineincodiert. Gerade mit den Dingen der HAN-FUN, die keine echte Bezechnung ala DECT2xx haben, ist das nicht mehr machbar.
