### ISSUE TITLE
DEC 500 Group not synchronized

### ISSUE THREAD

**Issue by vdi-cloud** [foxthefox/ioBroker.fritzdect#98]
Obviously groups which contain fritz dect 500 devices are getting not synched. Pls. find "Meine Gruppen" result below. In there, "Licht Kinderzimmer" and "Stehlampe" are representing the missing groups -

[{"synchronized":"0","identifier":"grp9CEFB6-3BDCFFC80","id":"901","functionbitmask":"233476","fwversion":"1.0","manufacturer":"AVM","present":"1","txbusy":"0","name":"Stehlampe","simpleonoff":{"state":"1"},"levelcontrol":{"level":"26","levelpercentage":"10"},"colorcontrol":{"supported_modes":"5","current_mode":"4","hue":"","saturation":"","temperature":"3000"},"groupinfo":{"masterdeviceid":"0","members":"2010,2011"}},{"synchronized":"0","identifier":"grp9CEFB6-3BB5C647F","id":"900","functionbitmask":"233476","fwversion":"1.0","manufacturer":"AVM","present":"1","txbusy":"0","name":"Licht Kinderzimmer","simpleonoff":{"state":"1"},"levelcontrol":{"level":"0","levelpercentage":"0"},"colorcontrol":{"supported_modes":"5","current_mode":"4","hue":"","saturation":"","temperature":"3000"},"groupinfo":{"masterdeviceid":"0","members":"2009,2012"}},{"synchronized":"1","identifier":"grp9CEFB6-3BB5C8228","id":"905","functionbitmask":"4160","fwversion":"1.0","manufacturer":"AVM","present":"1","txbusy":"0","name":"Heizung Bäder","hkr":{"tist":"","tsoll":"44","absenk":"40","komfort":"44","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","nextchange":{"endperiod":"1608498000","tchange":"40"},"summeractive":"0","holidayactive":"0"},"groupinfo":{"masterdeviceid":"0","members":"20,16"}},{"synchronized":"1","identifier":"grp9CEFB6-3BB5C5FBE","id":"904","functionbitmask":"4160","fwversion":"1.0","manufacturer":"AVM","present":"1","txbusy":"0","name":"Heizung Wohnzimmer","hkr":{"tist":"","tsoll":"42","absenk":"36","komfort":"42","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","nextchange":{"endperiod":"1608501600","tchange":"36"},"summeractive":"0","holidayactive":"0"},"groupinfo":{"masterdeviceid":"0","members":"24,25"}},{"synchronized":"1","identifier":"grp9CEFB6-3BB5C6313","id":"903","functionbitmask":"4160","fwversion":"1.0","manufacturer":"AVM","present":"1","txbusy":"0","name":"Heizung Kinderzimmer","hkr":{"tist":"","tsoll":"253","absenk":"38","komfort":"42","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","nextchange":{"endperiod":"1608490800","tchange":"38"},"summeractive":"0","holidayactive":"0"},"groupinfo":{"masterdeviceid":"0","members":"23,21"}},{"synchronized":"1","identifier":"grp9CEFB6-3BB5C6181","id":"902","functionbitmask":"4160","fwversion":"1.0","manufacturer":"AVM","present":"1","txbusy":"0","name":"Heizung Schlafzimmer","hkr":{"tist":"","tsoll":"42","absenk":"38","komfort":"42","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","nextchange":{"endperiod":"1608490800","tchange":"38"},"summeractive":"0","holidayactive":"0"},"groupinfo":{"masterdeviceid":"0","members":"18,19"}}]

**Comment by foxthefox** [comment]
I did not know that dect500 is also subject for grouping. Nice to know.
Thanks for the output, it is exact what I need.
It will probably take some time.

**Comment by perry94** [comment]
Guten Tag, (ich hoffe es geht auch auf Deutsch)
der Adapter müllt bei der neuen AVM DECT 500 das LOG voll. Die Lampe ist zwar angemeldet, lässt sich über AVM-Fritz-Telefone und auch über den ioBroker steuern ... aber zur Zeit ausgeschaltet. Das erzeugt ständige Eintragungen im LOG. Wäre schön, wenn das in einer größeren Zeitspanne passieren würde.  Herzlichen Dank für deine Bemühungen.
cu perry94

`
fritzdect.0 | 2020-12-29 11:55:08.343 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
-- | -- | -- | --
fritzdect.0 | 2020-12-29 11:54:08.345 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:53:08.356 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:52:08.340 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:51:08.354 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:50:08.344 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:49:08.348 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:48:08.348 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:47:08.346 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:46:08.348 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:45:08.340 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:44:08.343 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:43:08.344 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:42:08.347 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:41:08.349 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:40:08.341 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:39:08.338 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:38:08.328 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:37:08.339 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:36:08.335 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:35:08.342 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:34:08.326 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:33:08.332 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:32:08.321 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:31:08.335 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written
fritzdect.0 | 2020-12-29 11:30:08.330 | warn | (989) DECT500_130770009164-1 is not present, check the device connection, no values are written


`

**Comment by foxthefox** [comment]
das Abfrageintervall ist auf 1min gesetzt, und deswegen kommt auch alle Minute diese Meldung, daß die Lampe nicht erreichbar ist. Ich stelle es auf debug.
Dann gibt es keine Einträge solange der Adapter nicht im debug Modus läuft.

**Comment by foxthefox** [comment]
beide Dinge sollten jetzt gelöst sein:
- nicht sichtbare Geräte bekommen nur einen debug Eintrag
- Gruppen für Lampen sind auch erzeugt
Bitte die in GitHub vorhandene Version 2.0.0 testen

**Comment by vdi-cloud** [comment]
Dect500 Gruppe funktioniert. Es kommen auch keine Meldungen bei ausgeschalteter Lampe mehr. Debug Modus habe ich nicht getestet.
